const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');const read=n=>JSON.parse(fs.readFileSync(path.join(root,n),'utf8'));const write=(n,s)=>fs.writeFileSync(path.join(root,n),s);
const rows=read('records/position-measurements.json'), anchors=read('records/prop-anchors.json');
let qa=`# 워커 파일럿 2 검수표\n\n판정: 후보 제작 완료, 양산 관문 미통과. 머리 32셀의 중앙 추정값은 모두 2px 이내지만 오차 범위까지 보장하지 못하며, 팔·손의 픽셀 단위 동일성은 미확보다.\n\n## 측정 방법과 한계\n\n- 기준 셀: 마스터148×148, 최종74×74. 원본 첨부 시트를 4×2 구조 그대로 정규화했다. 원본 크기와 변환은 template-normalization.json에 있다. 셀별 새 포즈는 만들지 않았다.\n- 머리: 템플릿과 결과를 독립 육안 검수하고, 정면은 얼굴 중심·뒷면은 덮인 두개부 중심을 수동 지정했다. 표 수치는 최종 픽셀 환산 유클리드 거리다. 각 점 약 ±1 final px 불확실성이 있으며 경계 근처 결과를 확정 통과로 세지 않는다. 상세 좌표는 independent-visual-qa.json.\n- 발: 마스터 셀 y128~147 구역의 alpha>32 가중 중심 비교. 발 접점 실루엣 차이는 32셀 모두0이다. 템플릿 발 픽셀/alpha 보존의 결과다. 새 생성 자체가 보행을 정확히 만들었다는 증거가 아니다. 두 신발의 모든 RGB가 동일하다는 뜻도 아니다.\n- 여성 시트는 템플릿 alpha를 강제 보존했으므로 머리 alpha 무게중심0을 머리 정렬 통과 증거로 쓰지 않았다. 남성의 alpha proxy값은 제작 이력에만 남겼다.\n- 50% 겹치기: 확인1의 청록색은 템플릿 실루엣, 빨강/청록 십자는 각 머리 좌표. 확인2는 실제 그림의 템플릿/후보 비교다.\n\n## 32셀 위치 표\n\n|인물|방향|프레임|머리 차이 추정(px)|발 실루엣 차이(px)|머리 판정|\n|---|---|---:|---:|---:|---|\n`;
for(const r of rows)qa+=`|${r.id}|${r.direction}|${r.frame}|${r.headDistanceFinalPx.toFixed(2)}|${r.footSilhouetteDistanceFinalPx.toFixed(2)}|${r.thresholdVerdict==='near_threshold_not_certified'?'경계 오차 미확정':'육안 허용범위, 추정'}|\n`;
qa+=`\n## 방향 일관성·보행·의미 서명\n\nO=시각적으로 템플릿 유지, △=약함/정밀 미확인. 픽셀 동일성 O와 혼동하지 않는다.\n\n|인물|NE|SE|SW|NW|프레임0/1 다리·발|초상 의미 서명|남은 한계|\n|---|---|---|---|---|---|---|\n|P1|O|O|O|O|4/4 템플릿 유지|파랑+모피 깃+챙 모자 O|손/소매 다시 그려짐, 완전 픽셀 고정 미확보|\n|P4|O|O|O|O|4/4 템플릿 유지|빨강 hood+짧은 tunic O|원본 아래 다리 유지로 hose 색은 원본에 가까움|\n|P5|O|O|O|O|4/4 템플릿 유지|흰 coif+파랑+앞치마 O|얼룩은74px에서 약함, 손 내부 위치 미세차이|\n|P6|O|O|O|O|4/4 템플릿 유지|윔플/베일+회청 O|노년은 정면/확대에서만 읽힘; 뒤 신발 RGB 변경|\n\n실제 표본은 4시트×4방향=16방향쌍이다. 의뢰서의 ‘24방향쌍’은 산술상 맞지 않아 16쌍과32셀로 검사했다. 보행 유지16/16은 템플릿 대비 판단이며 새 보행 동작의 품질 승인이나 게임 애니메이션 시험이 아니다. 소지품은 최종 시트에서 제거한 상태다.\n\n## 교정과 잔여 차이\n\n- P6 앞치마 잔재와 여성의 옛 적갈색 옷자락: 원본 하단 전체 복원이 원인이었다. 실제 앞 신발 영역만 보호하도록 좁혀 제거했고 마지막 확인2에 반영했다. 머리 좌표에는 영향 없다.\n- P5 앞치마 뒤 끈, P6 정면 앞치마 제거: 입력 방향 쌍을 국소 이미지 편집해 교정했다. 원본/교정 프롬프트 보존.\n- 주머니 NE 초안에 앞면이 보였음: 뒤 오른쪽 면으로 다시 편집. 반려 원본과 기록 보존.\n- 소품 방향: 주머니 앞/뒤 면 구분 O. 자루·바구니는 대칭성이 커 앞/뒤 차이가 약함(△), 지팡이도 원통형이라 방향 판독성 △. 미러 변환은 사용하지 않았다. 고유 흠집의 3D 연속성은 보장하지 않는다.\n- 손잡이 기준점은 아래 표와 확인2의 빨강 십자로 표시했다. PNG에 십자를 굽지 않았다. 실제 손 위치 부착/깊이 정렬은 미시험이다.\n\n|소품|방향|기준점 x,y (32px)|\n|---|---|---|\n`;
for(const a of anchors)qa+=`|${a.kind}|${a.direction}|${a.anchor.join(', ')}|\n`;
qa+='\n## 양산 판단\n\n의상 부분 편집+정렬+보호 픽셀 합성이 자유 생성보다 템플릿의 발/보행을 유지한다. 그러나 모델 편집만으로 팔·손과 내부 머리를 픽셀 단위로 고정하는 것은 이번에도 증명되지 않았다. 75실루엣 양산 승인본으로 취급하지 않는다. 다음 제작법 판단에는 편집 마스크의 팔/머리 고정 또는 수작업 리터치가 필요하다. 게임 설치·성능·충돌·런타임 검증 없음.\n';write('SELF_QA.md',qa);
write('README.md',`# Astra 워커 파일럿 2 · candidate\n\n재스킨4시트 + 독립 소지품16PNG + 확인 그림2장 + assets.csv20행. 게임에 설치하지 않았다.\n\n**양산 관문 미통과:** 머리 위치 수동 추정 최대1.80px, 발 접점 실루엣 차이0px. 다만 머리 측정 불확실성과 팔·손의 미세한 재묘사 때문에 ‘32셀 모두 픽셀 단위 동일’은 확인하지 못했다. 자세한 수치/방향표는 [SELF_QA.md](SELF_QA.md).\n\n- [확인1: 템플릿50% 겹치기](proofs/01-template-overlay.png)\n- [확인2: 보행·소지품 기준점](proofs/02-gait-and-props.png)\n- [개별 파일 갤러리](index.html)\n- [20행 생성기록 CSV](assets.csv)\n\n## 규격과 제작\n\n시트296×148, 셀74×74, 열NE/SE/SW/NW, 행프레임0/1. 마스터592×296을 정확히50%로 축소했다. 소품은32×32투명PNG, 그림 부분은 종별14~28px높이.\n\n사람은 승인된 셀/시트를 입력한 이미지 편집만 사용했다. 남성은8셀 템플릿시트, 여성은방향별2셀을 함께 편집했다. 초상은옷/머리 참고다. 편집 원본을 템플릿에 등록하고 발·실루엣 보호합성을 했다. 생성된 위치 오차를 숨기지 않도록 sources 원본과 records 처리코드를 남겼다.\n\n소품은 의뢰서에 입력 템플릿이 없는 별도 제작품이다. 첫 방향을 프로젝트 아트와 맞춰 생성한 뒤 그 결과를 입력해 나머지 방향을 편집했다. 인물 자유 생성은 하지 않았다. 모델/seed값은 도구가 공개하지 않아 null이다.\n\n## 폴더\n\nassets/ 납품 후보20개 · masters/ 재스킨4개 · proofs/ 공식확인2장 · templates/ 정규화기준 · references/ 첨부원본 · sources/ 생성/교정원본 · records/ 전체프롬프트·변환·내부진단 · SHA256SUMS.txt 무결성. records의 QA보드는 내부확대검사이며 추가 납품확인그림이 아니다.\n\n원본은 덮어쓰지 않았으며 제품 코드/자산·브랜치에는 반영하지 않았다.\n`);
const files=[...Object.values({P1:'wk_reskin_P1_merchant_m-v1',P4:'wk_reskin_P4_labour_m-v1',P5:'wk_reskin_P5_labour_f-v1',P6:'wk_reskin_P6_widow_f-v1'}).map(n=>'assets/workers/'+n+'.png'),...anchors.map(a=>a.file)];write('index.html','<!doctype html><meta charset="utf-8"><title>Walker pilot2 candidates</title><style>body{font:16px sans-serif;background:#e9e7df;margin:24px}section{display:flex;flex-wrap:wrap;gap:20px}figure{margin:0;padding:12px;background:#ccc}img{image-rendering:auto}small{display:block}</style><h1>워커 파일럿 2 · 후보</h1><p>게임 미설치. 머리 최대1.8px 추정, 발 실루엣0px. 팔/손 픽셀 고정 및 머리 정밀 통과는 미확보.</p><p><a href="SELF_QA.md">검수표</a> · <a href="proofs/01-template-overlay.png">겹치기</a> · <a href="proofs/02-gait-and-props.png">보행</a></p><section>'+files.map(f=>`<figure><a href="${f}"><img src="${f}" width="${f.includes('workers')?592:96}"><small>${path.basename(f)}</small></a></figure>`).join('')+'</section>');
