const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {PNG}=require('/tmp/astra-wave4b-work-20260925/node_modules/pngjs');
const {createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');
const root=path.resolve(__dirname,'..'),topology=JSON.parse(fs.readFileSync(path.join(__dirname,'module-topology.json')));
const read=p=>PNG.sync.read(fs.readFileSync(p));const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
// Native painted-post landmarks, independently registered without mirrored artwork.
const transforms={'hurdle_gate-v1':[12.45,0,1.625,15,181.6,-121], 'hurdle_half-v1':[16.56,0,-3,11.54,100,352], 'hurdle_corner_e-v1':[10.69,0,.4609,10.328125,0,57.8125], 'hurdle_corner_s-v1':[11.3125,0,0,10.875,0,200], 'hurdle_corner_w-v1':[10.125,0,-.4453,10.078125,152,88.8]};
function bleed(im){const src=Buffer.from(im.data);let count=0;for(let y=0;y<im.height;y++)for(let x=0;x<im.width;x++){const k=(y*im.width+x)*4;if(src[k+3])continue;let best=-1,dist=10;for(let yy=Math.max(0,y-3);yy<=Math.min(im.height-1,y+3);yy++)for(let xx=Math.max(0,x-3);xx<=Math.min(im.width-1,x+3);xx++){const j=(yy*im.width+xx)*4,d=(xx-x)**2+(yy-y)**2;if(src[j+3]>32&&d<=9&&d<dist){best=j;dist=d;}}if(best>=0){src.copy(im.data,k,best,best+3);count++;}}return count;}
function pixel(src,x,y){x=Math.round(x);y=Math.round(y);let k=(y*src.width+x)*4;if(x>=0&&x<src.width&&y>=0&&y<src.height&&src.data[k+3]>64)return [...src.data.subarray(k,k+3)];for(let r=1;r<=150;r+=2)for(let a=0;a<24;a++){const xx=Math.round(x+r*Math.cos(a*Math.PI/12)),yy=Math.round(y+r*Math.sin(a*Math.PI/12));if(xx<0||yy<0||xx>=src.width||yy>=src.height)continue;k=(yy*src.width+xx)*4;if(src.data[k+3]>64)return [...src.data.subarray(k,k+3)];}throw Error(`No painted source near ${x},${y}`);}
async function main(){const records=[];for(const mod of topology.modules){if(!transforms[mod.id])continue;const file=path.join(root,'sources','fence__'+mod.id+'.png');if(!fs.existsSync(file))continue;const src=read(file),mask=read(path.join(root,'masks',mod.id+'-topology.png')),out=new PNG({width:mod.size[0],height:mod.size[1]}),t=transforms[mod.id];for(let y=0;y<out.height;y++)for(let x=0;x<out.width;x++){const k=(y*out.width+x)*4,alpha=mask.data[k];if(!alpha)continue;let rgb=[0,0,0];for(let sy=0;sy<4;sy++)for(let sx=0;sx<4;sx++){const xx=x+(sx+.5)/4,yy=y+(sy+.5)/4,p=pixel(src,t[0]*xx+t[1]*yy+t[4],t[2]*xx+t[3]*yy+t[5]);for(let c=0;c<3;c++)rgb[c]+=p[c]/16;}for(let c=0;c<3;c++)out.data[k+c]=Math.round(rgb[c]*[.81,.84,.88][c]);out.data[k+3]=alpha;}const mean=[0,0,0];let opaque=0;for(let k=0;k<out.data.length;k+=4)if(out.data[k+3]>200){opaque++;for(let ch=0;ch<3;ch++)mean[ch]+=out.data[k+ch];}const toneScale=mean.map((v,ch)=>[153,116,65][ch]/(v/opaque));for(let k=0;k<out.data.length;k+=4)if(out.data[k+3])for(let ch=0;ch<3;ch++)out.data[k+ch]=Math.min(245,Math.round(out.data[k+ch]*toneScale[ch]));const bleedPixels=bleed(out),target=path.join(root,'assets/fence',mod.id+'.png');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,PNG.sync.write(out));records.push({id:mod.id,source:path.relative(root,file),sourceSha256:sha(file),nativeSize:[src.width,src.height],size:mod.size,pivot:mod.pivot,ports:mod.ports,nativeSamplingAffine:t,onePassNativeToTarget:true,method:'4x4 footprint sampling of independently painted native image; exact approved topology alpha; nearest painted edge extrusion only where mask registration crosses source alpha; reference-average RGB normalization to existing straight/north timber; no mirrored art',referenceMeanRGB:[153,116,65],toneScale,transparentRGBDilation:3,bleedPixels,sha256:sha(target)});}fs.writeFileSync(path.join(__dirname,'process-modules.json'),JSON.stringify({assets:records},null,2)+'\n');
 const gate=await loadImage(path.join(root,'assets/fence/hurdle_gate-v1.png')),canvas=createCanvas(1120,750),c=canvas.getContext('2d');c.fillStyle='#eeeada';c.fillRect(0,0,1120,750);c.fillStyle='#303c24';c.font='20px sans-serif';c.fillText('Hurdle gate representative | 12 x 12 | zoom 0.6 (source x 0.3)',25,35);for(let row=0;row<12;row++)for(let col=0;col<12;col++){const x=280+(col-row)*19.2,y=90+(col+row)*9.6;c.beginPath();c.moveTo(x,y);c.lineTo(x+19.2,y+9.6);c.lineTo(x,y+19.2);c.lineTo(x-19.2,y+9.6);c.closePath();c.fillStyle=(row+col)%2?'#8d9868':'#879260';c.fill();if((row===3||row===8)&&col%3===1)c.drawImage(gate,x-19.2,y-13.2,38.4,19.2);}c.drawImage(gate,650,120,384,192);c.fillStyle='#303c24';c.fillText('3x pixel inspection (not gameplay scale)',640,340);fs.writeFileSync(path.join(__dirname,'module-representative-12x12.png'),canvas.toBuffer('image/png'));}
main();
