const fs=require('fs'),path=require('path'),sharp=require('/Users/rexxa/.npm/_npx/8b377f6eec906bc4/node_modules/sharp/lib/index.js');
const root=path.resolve(__dirname,'..');
const read=async p=>sharp(p).ensureAlpha().raw().toBuffer({resolveWithObject:true});
function over(dst,di,s,si){const a=s[si+3]/255,b=dst[di+3]/255,o=a+b*(1-a);for(let c=0;c<3;c++)dst[di+c]=o?Math.round((s[si+c]*a+dst[di+c]*b*(1-a))/o):0;dst[di+3]=Math.round(o*255);}
function strip(canvas,W,H,src,dir,px,py,from,length){const du=[.5,dir==='ne'?-.25:.25],dv=[dir==='ne'?.5:-.5,.25];const ox=px-du[0]*from-dv[0]*32,oy=py-du[1]*from-dv[1]*32,det=du[0]*dv[1]-du[1]*dv[0];for(let y=0;y<H;y++)for(let x=0;x<W;x++){const dx=x-ox,dy=y-oy;const u=(dx*dv[1]-dy*dv[0])/det,v=(dy*du[0]-dx*du[1])/det;if(u<from-8||u>=from+length+8||v<0||v>=64)continue;const ix=((Math.floor(u)%512)+512)%512,iy=Math.floor(v);over(canvas,(y*W+x)*4,src,(iy*512+ix)*4);}}
function sprite(canvas,W,H,src,info,left,top){for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const xx=x+left,yy=y+top;if(xx>=0&&xx<W&&yy>=0&&yy<H)over(canvas,(yy*W+xx)*4,src,(y*info.width+x)*4);}}
const sides={NW:[-32,-16,'nw',-128],NE:[32,-16,'ne',0],SW:[-32,16,'ne',-128],SE:[32,16,'nw',0]};
(async()=>{const metrics=JSON.parse(fs.readFileSync(__dirname+'/connections-metrics.json'));const panels=[];for(const m of metrics){const W=256,H=180;const canvas=Buffer.alloc(W*H*4);for(let i=0;i<canvas.length;i+=4){canvas[i]=126;canvas[i+1]=132;canvas[i+2]=89;canvas[i+3]=255;}for(const side of Object.keys(m.ports)){const [dx,dy,d,f]=sides[side];const p=await read(root+'/assets/paths/path_clear_'+d+'_'+m.season+'.png');const px=128+dx,py=90+dy;strip(canvas,W,H,p.data,d,px+(f<0?-64:0),py+(f<0?(d==='ne'?32:-32):0),f,128);}
const sp=await read(root+'/'+m.path);sprite(canvas,W,H,sp.data,sp.info,64,10);panels.push({input:await sharp(canvas,{raw:{width:W,height:H,channels:4}}).png().toBuffer(),left:(panels.length%4)*W,top:Math.floor(panels.length/4)*H});}
await sharp({create:{width:1024,height:360,channels:3,background:'#888866'}}).composite(panels).jpeg({quality:93}).toFile(root+'/proofs/connections-joined.jpg');
// A village-to-village collage using exact same connection routine and production assets.
const W=896,H=576,grass=await read('/Users/rexxa/orca/workspaces/feudal-lord-simulator/krill/public/assets/terrain/grass.png');const canvas=Buffer.alloc(W*H*4);for(let y=0;y<H;y++)for(let x=0;x<W;x++)for(let c=0;c<4;c++)canvas[(y*W+x)*4+c]=grass.data[((y%grass.info.height)*grass.info.width+x%grass.info.width)*4+c];const cx=440,cy=288;const m=metrics.find(m=>m.id==='path_clear_fork_ne_summer');for(const side of Object.keys(m.ports)){const [dx,dy,d,f]=sides[side];const src=await read(root+'/assets/paths/path_clear_'+d+'_summer.png');const neg=f<0;strip(canvas,W,H,src.data,d,cx+dx+(neg?-192:0),cy+dy+(neg?(d==='ne'?96:-96):0),neg?-384:0,384);}const sp=await read(root+'/'+m.path);sprite(canvas,W,H,sp.data,sp.info,cx-64,cy-80);
const housepaths=['house_l1-v2.png','house_l2-v2.png'];const houseBase='/Users/rexxa/orca/workspaces/feudal-lord-simulator/krill/public/assets/buildings/historical-houses/';const endpoints=[[cx-224,cy+112],[cx-224,cy-112],[cx+224,cy-112]];const ref=[];
for(let i=0;i<3;i++)for(let j=0;j<2;j++){const p=houseBase+housepaths[(i+j)%2];if(!fs.existsSync(p))continue;const b=await sharp(p).resize({width:96}).ensureAlpha().raw().toBuffer({resolveWithObject:true});sprite(canvas,W,H,b.data,b.info,endpoints[i][0]-45+j*68,endpoints[i][1]-b.info.height-10-j*20);ref.push(p);}
await sharp(canvas,{raw:{width:W,height:H,channels:4}}).jpeg({quality:90}).toFile(root+'/proofs/03-village-footpaths.jpg');fs.writeFileSync(__dirname+'/connection-proof-sources.json',JSON.stringify({sources:[...new Set(ref)],strip_mapping:'as CONNECTIONS.md; positive determinant; 8UVpx overlap; no reflection',runtime:false},null,2));})();
