const fs=require('fs'),path=require('path'),crypto=require('crypto'),{execFileSync}=require('child_process'),sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp'),{createCanvas,loadImage}=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');const R=path.resolve(__dirname,'..'),hash=b=>crypto.createHash('sha256').update(b).digest('hex');function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(d=>d.isDirectory()?walk(p+'/'+d.name):[p+'/'+d.name])}
(async()=>{const rows=['first','second','third'].flatMap(n=>{const x=JSON.parse(fs.readFileSync(R+'/records/'+n+'.json'));return Array.isArray(x)?x:x.assets;}).sort((a,b)=>a.id.localeCompare(b.id));if(rows.length!==5)throw Error('count');for(const r of rows){const p=R+'/'+r.file,m=await sharp(p).metadata();if(m.width!==960||m.height!==540)throw Error(r.file);Object.assign(r,{width:960,height:540,status:'candidate',sha256:hash(fs.readFileSync(p)),model_version:'not exposed',seed:'not exposed'});}fs.writeFileSync(R+'/records/manifest.json',JSON.stringify({status:'PASS',assets:rows},null,2));const c=createCanvas(1440,1215),g=c.getContext('2d');g.fillStyle='#746752';g.fillRect(0,0,1440,1215);for(let i=0;i<5;i++){g.drawImage(await loadImage(R+'/'+rows[i].file),(i%2)*720,Math.floor(i/2)*405,720,405);}g.fillStyle='#e7dbc4';g.font='25px sans-serif';g.fillText('Wave33 | Five interlude events',750,995);g.font='18px sans-serif';g.fillText('960 × 540 · candidate illustrations',750,1030);await sharp(c.toBuffer('image/png')).jpeg({quality:88,mozjpeg:true}).toFile(R+'/proofs/contact.jpg');
let html='<html lang="ko"><meta charset="utf-8"><title>Wave33</title><style>body{background:#5c5140;color:#eee;font:18px sans-serif}a{color:#eee}img{max-width:960px;width:100%}</style><h1>Wave33 막간 사건</h1>';for(const r of rows)html+='<h2>'+r.year+' '+r.title+'</h2><a href="'+r.file+'"><img src="'+r.file+'"></a>';fs.writeFileSync(R+'/gallery.html',html+'</html>');
const raw='/Users/rexxa/feudal-lord-analysis/astra-raw/wave33-20260929',inventory=[];for(const p of walk(R+'/native')){const b=fs.readFileSync(p),rel=path.relative(R,p),o=raw+'/'+rel;fs.mkdirSync(path.dirname(o),{recursive:true});fs.copyFileSync(p,o);inventory.push({file:rel,raw:o,bytes:b.length,sha256:hash(b)});}fs.writeFileSync(R+'/records/raw-inventory.json',JSON.stringify(inventory,null,2));const stage=fs.mkdtempSync('/tmp/astra-wave33-stage-'),dest=stage+'/astra-wave33',zip='/tmp/astra-wave33-candidates-20260929-lite.zip';fs.mkdirSync(dest);for(const d of ['assets','proofs','records','references','scripts'])fs.cpSync(R+'/'+d,dest+'/'+d,{recursive:true});for(const f of ['README.md','QA.md','PLAN.md','gallery.html'])fs.copyFileSync(R+'/'+f,dest+'/'+f);const files=walk(dest);fs.writeFileSync(dest+'/SHA256SUMS',files.map(p=>hash(fs.readFileSync(p))+'  '+path.relative(dest,p)).join('\n')+'\n');execFileSync('python3',['-c',`import pathlib,zipfile,hashlib
r=pathlib.Path(${JSON.stringify(dest)})
with zipfile.ZipFile(${JSON.stringify(zip)},'w',zipfile.ZIP_DEFLATED,compresslevel=9) as z:
 for p in sorted(r.rglob('*')):
  if p.is_file():z.write(p,str(p.relative_to(r.parent)))
with zipfile.ZipFile(${JSON.stringify(zip)}) as z:
 assert z.testzip() is None
 for line in z.read('astra-wave33/SHA256SUMS').decode().splitlines():
  h,n=line.split('  ',1);assert hashlib.sha256(z.read('astra-wave33/'+n)).hexdigest()==h
 assert len([n for n in z.namelist() if '/assets/' in n and n.endswith('.png')])==5
 print('5 PNG / CRC / allSHA PASS')`],{stdio:'inherit'});const b=fs.readFileSync(zip);console.log(JSON.stringify({zip,bytes:b.length,sha256:hash(b)}));})();
