const fs=require('fs'),path=require('path'),crypto=require('crypto'),{execFileSync}=require('child_process');const R=path.resolve(__dirname,'..'),raw='/Users/rexxa/feudal-lord-analysis/astra-raw/wave28-20260928',stage='/tmp/astra-wave28-package-stage',zip='/tmp/astra-wave28-candidates-20260928-lite.zip',dest=stage+'/astra-wave28-candidates';const hash=b=>crypto.createHash('sha256').update(b).digest('hex');function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(d=>d.isDirectory()?walk(p+'/'+d.name):[p+'/'+d.name])}
let qa=JSON.parse(fs.readFileSync(R+'/records/technical-qa.json'));if(qa.assets!==39||qa.failures.length)throw Error('technicalQAfailed');const assets=JSON.parse(fs.readFileSync(R+'/records/manifest.json')).assets,composition=JSON.parse(fs.readFileSync(R+'/records/composition-qa.json'));if(Object.keys(composition.seasons).length!==3)throw Error('Three seasons required');for(const v of Object.values(composition.seasons))if(v.outside_fraction>.15||v.changed_outside_overlay)throw Error('compositionQAfailed');fs.mkdirSync(raw,{recursive:true});let raws=[];for(const p of walk(R+'/native')){let rel=path.relative(R,p),out=raw+'/'+rel,b=fs.readFileSync(p);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,b);raws.push({source:rel,preserved:out,bytes:b.length,sha256:hash(b)})}fs.writeFileSync(R+'/records/raw-inventory.json',JSON.stringify(raws,null,2));for(const p of walk(R+'/native'))if(/\.(json|txt)$/.test(p)){const out=R+'/records/native-text/'+path.relative(R+'/native',p);fs.mkdirSync(path.dirname(out),{recursive:true});fs.copyFileSync(p,out);}
fs.writeFileSync(R+'/index.html','<!doctype html><meta charset="utf-8"><title>Wave28 후보</title><style>body{font:16px sans-serif;background:#6f7866;color:#fff8e7;margin:24px}a{color:#fff8e7}li{display:inline-block;width:530px;vertical-align:top;margin:12px}img{display:block;min-height:64px;object-fit:contain;object-position:bottom left;max-width:512px}</style><h1>Wave28 시골 풍경 후보39종</h1><p>게임 미설치 · <a href="proofs/01-outside-before-after.png">확인1: 전/후</a> · <a href="proofs/02-three-seasons.png">확인2: 사계절(봄은 여름 공유)</a></p>'+['summer','autumn','winter'].map(s=>'<h2>'+s+'</h2><ul>'+assets.filter(a=>a.season===s).map(a=>'<li><a href="'+a.file+'"><img src="'+a.file+'">'+a.id+'</a></li>').join('')+'</ul>').join(''));
fs.mkdirSync(dest,{recursive:true});for(const dir of['assets','proofs','references','records','scripts'])for(const p of walk(R+'/'+dir)){let rel=path.relative(R,p);if(dir==='records'&&(p.endsWith('.png')||p.endsWith('package-result.json')))continue;let out=dest+'/'+rel;fs.mkdirSync(path.dirname(out),{recursive:true});fs.copyFileSync(p,out)}for(const f of['README.md','QA.md','PLAN.md','index.html','generation-records.csv'])fs.copyFileSync(R+'/'+f,dest+'/'+f);let files=walk(dest).filter(p=>!p.endsWith('SHA256SUMS')).sort();fs.writeFileSync(dest+'/SHA256SUMS',files.map(p=>hash(fs.readFileSync(p))+'  '+path.relative(dest,p)).join('\n')+'\n');
execFileSync('python3',['-c',`import pathlib,zipfile,hashlib,csv,io
r=pathlib.Path(${JSON.stringify(dest)})
with zipfile.ZipFile(${JSON.stringify(zip)},'w',zipfile.ZIP_DEFLATED,compresslevel=9) as z:
 for p in sorted(r.rglob('*')):
  if p.is_file():z.write(p,str(p.relative_to(r.parent)))
with zipfile.ZipFile(${JSON.stringify(zip)}) as z:
 assert z.testzip() is None
 pre='astra-wave28-candidates/'
 for line in z.read(pre+'SHA256SUMS').decode().splitlines():
  h,n=line.split('  ',1);assert hashlib.sha256(z.read(pre+n)).hexdigest()==h,n
 rows=list(csv.DictReader(io.StringIO(z.read(pre+'generation-records.csv').decode('utf-8-sig'))))
 assert len(rows)==39 and len({x['id'] for x in rows})==39
 for row in rows:assert hashlib.sha256(z.read(pre+row['file'])).hexdigest()==row['sha256']
 assert len([n for n in z.namelist() if '/assets/' in n and n.endswith('.png')])==39
 assert len([n for n in z.namelist() if '/proofs/' in n and n.endswith('.png')])==2
 print('CRC + all manifest hashes +39 CSV records +39assets +2proofs PASS')`],{stdio:'inherit'});let b=fs.readFileSync(zip),result={zip,bytes:b.length,MiB:b.length/1048576,sha256:hash(b),assets:39,proofs:2,csv_rows:39,raw_files:raws.length,manifest_hashes:files.length,crc:'pass'};fs.writeFileSync(R+'/records/package-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
