const fs=require('fs'),path=require('path'),{createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');
const R=path.resolve(__dirname,'..'),layout=JSON.parse(fs.readFileSync(R+'/records/layout.json')),seasons=process.argv.includes('--summer-only')?['summer']:['summer','autumn','winter'];
function context(w,h){const c=createCanvas(w,h);return[c,c.getContext('2d')]}
function polygon(ctx){ctx.beginPath();layout.outside_polygon.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath()}
function text(ctx,s,x,y,size=20){ctx.fillStyle='#eadcc4';ctx.font=size+'px sans-serif';ctx.fillText(s,x,y)}
(async()=>{const source=await loadImage(R+'/'+layout.source),[base,bctx]=context(960,600);bctx.drawImage(source,0,0);const original=bctx.getImageData(0,0,960,600).data;const[mask,mctx]=context(960,600);mctx.fillStyle='#fff';polygon(mctx);mctx.fill();mctx.globalCompositeOperation='destination-out';for(const r of layout.exclude_rects)mctx.fillRect(...r);const md=mctx.getImageData(0,0,960,600).data;let area=0;for(let i=3;i<md.length;i+=4)if(md[i]===255)area++;
const manifest=JSON.parse(fs.readFileSync(R+'/records/manifest.json')).assets,qa={denominator:'Conservative visible outside-wall grass mask excluding woods, water, town, HUD',outside_pixels:area,limit:.15,seasons:{},placement_count:layout.placements.length,source_unchanged_outside_overlay:true},scenes={};
for(const season of seasons){const[overlay,ctx]=context(960,600);for(const p of layout.placements){const a=manifest.find(a=>a.id===p.id+'_'+season),img=await loadImage(R+'/'+a.file);ctx.save();if(p.w){ctx.transform(1,p.slope,0,1,p.x,p.y);ctx.drawImage(img,p.source_x||0,0,p.w/p.texture_scale,a.height,0,-a.pivot.y*p.texture_scale,p.w,a.height*p.texture_scale)}else{const pivot=a.pivot;ctx.drawImage(img,p.x-pivot.x*p.scale,p.y-pivot.y*p.scale,img.width*p.scale,img.height*p.scale)}ctx.restore()}const before=ctx.getImageData(0,0,960,600).data;let spill=0;for(let i=3;i<before.length;i+=4)if(before[i]&&md[i]!==255)spill++;ctx.globalCompositeOperation='destination-in';ctx.drawImage(mask,0,0);ctx.globalCompositeOperation='source-over';const od=ctx.getImageData(0,0,960,600).data;let count=0;for(let i=3;i<od.length;i+=4)if(od[i])count++;const ratio=count/area;if(ratio>.15)throw Error(season+' outside coverage too high '+ratio);const[scene,sctx]=context(960,600);sctx.drawImage(base,0,0);sctx.drawImage(overlay,0,0);const sd=sctx.getImageData(0,0,960,600).data;let changedOutside=0;for(let i=0;i<sd.length;i+=4)if(!od[i+3]&&(sd[i]!==original[i]||sd[i+1]!==original[i+1]||sd[i+2]!==original[i+2]))changedOutside++;if(changedOutside)throw Error('Source drift');qa.seasons[season]={covered_pixels:count,outside_fraction:ratio,whole_screen_fraction:count/(960*600),clipped_pixels:spill,changed_outside_overlay:changedOutside};fs.writeFileSync(R+'/records/scene-'+season+'.png',scene.toBuffer('image/png'));fs.writeFileSync(R+'/records/overlay-'+season+'.png',overlay.toBuffer('image/png'));scenes[season]=scene;}
const[proof1,c1]=context(1960,1120);c1.fillStyle='#302f28';c1.fillRect(0,0,1960,1120);text(c1,'Wave 28 · 원본 / 후보 합성 · 1.0',20,30);text(c1,'기존 화면',20,65);text(c1,'새 소품만 추가 · 성벽 밖 '+(qa.seasons.summer.outside_fraction*100).toFixed(2)+'% 덮음',1000,65);c1.drawImage(base,20,80);c1.drawImage(scenes.summer,1000,80);text(c1,'0.6 · 같은 그림의 축소 비교 (실제 게임 카메라 검증 아님)',20,715);c1.drawImage(base,20,735,576,360);c1.drawImage(scenes.summer,1000,735,576,360);fs.writeFileSync(R+'/proofs/01-outside-before-after.png',proof1.toBuffer('image/png'));
const[proof2,c2]=context(2920,690);c2.fillStyle='#302f28';c2.fillRect(0,0,2920,690);text(c2,'Wave 28 · 같은 배치의 여름 / 가을 / 겨울 · 배경은 원본 고정, 신규 소품만 계절 교체',20,30);for(const[si,s]of seasons.entries()){text(c2,({summer:'여름 (봄 공유)',autumn:'가을',winter:'겨울'})[s]+' · 성벽 밖 '+(qa.seasons[s].outside_fraction*100).toFixed(2)+'%',20+si*970,65);c2.drawImage(scenes[s],20+si*970,80)}if(seasons.length===3)fs.writeFileSync(R+'/proofs/02-three-seasons.png',proof2.toBuffer('image/png'));fs.writeFileSync(R+'/records/composition-qa.json',JSON.stringify(qa,null,2));console.log(JSON.stringify(qa));})().catch(e=>{console.error(e);process.exit(1)});
