const fs=require('fs'),crypto=require('crypto');
const {createCanvas,loadImage}=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const W='/tmp/astra-wave22-rework-work-20260927',D='/tmp/astra-wave22-rework-candidates-20260927',R='/tmp/astra-wave22-work-20260927/astra-wave22-reference-files',P='/Users/rexxa/orca/workspaces/feudal-lord-simulator/krill/public/assets';
const families=['chalk_down','heath','fen','coastal_grass','woodland_floor'],seasons=['summer','autumn','winter'],variants=['a','b'];
const decalFamily={chalk_down:'chalk_exposure',heath:'heath_patch',fen:'fen_pool',coastal_grass:'coastal_sand',woodland_floor:'woodland_litter'};
const cache=new Map(),used=new Set(),sceneRecords=[];
async function img(p){if(!cache.has(p)){if(!fs.existsSync(p))throw Error('Missing required source: '+p);cache.set(p,await loadImage(p));used.add(p)}return cache.get(p)}
function canvas(w,h){const c=createCanvas(w,h),g=c.getContext('2d');g.fillStyle='#e9e5da';g.fillRect(0,0,w,h);g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';return[c,g]}
function text(g,t,x,y,s=15){g.fillStyle='#333c35';g.font=`${s}px sans-serif`;g.fillText(t,x,y)}
function repeat(g,i,x,y,n,s,uvWidth=256,uvHeight=128){const c=createCanvas(uvWidth*n,uvHeight*n),q=c.getContext('2d');for(let a=0;a<n;a++)for(let b=0;b<n;b++)q.drawImage(i,a*uvWidth,b*uvHeight,uvWidth,uvHeight);g.drawImage(c,x,y,c.width*s,c.height*s)}
function fillPath(f,s,v){return D+`/terrain/${f}_${s}_${v}-v2.png`}
async function fillCheck(){const[c,g]=canvas(1760,10420),grass=await img(R+'/grass.png');text(g,'WAVE 22 REWORK / 01   Every fill: 4 x 4 repeats beside existing grass',24,32,23);text(g,'Left pair zoom 1.0 (0.5 source scale); right pair zoom 0.6 (0.3). Both use a 256 x 128 comparison UV.',24,62);text(g,'Grass uses its COMPLETE 256 x 256 source compressed to 256 x 128; this is a normalized repeat-density comparison, not engine output.',24,86,13);let row=0;for(const f of families)for(const s of seasons)for(const v of variants){const y=110+row++*342,i=await img(fillPath(f,s,v));text(g,`${f} / ${s} / ${v}`,24,y+18,19);text(g,'NEW / zoom 1.0',24,y+43);text(g,'EXISTING GRASS / zoom 1.0',554,y+43);text(g,'NEW / zoom 0.6',1084,y+43);text(g,'GRASS / zoom 0.6',1410,y+43);repeat(g,i,24,y+53,4,.5);repeat(g,grass,554,y+53,4,.5);repeat(g,i,1084,y+53,4,.3);repeat(g,grass,1410,y+53,4,.3)}fs.writeFileSync(D+'/checks/01-fill-repeats.png',c.toBuffer('image/png'));for(let k=0;k<5;k++){const crop=createCanvas(1760,2052),cg=crop.getContext('2d');cg.drawImage(c,0,110+k*2052,1760,2052,0,0,1760,2052);fs.writeFileSync(W+'/proofs-fill-'+families[k]+'.png',crop.toBuffer('image/png'))}}
function hash(s){let h=2166136261;for(const b of Buffer.from(s)){h^=b;h=Math.imul(h,16777619)}h^=h>>>16;h=Math.imul(h,0x85ebca6b);h^=h>>>13;h=Math.imul(h,0xc2b2ae35);h^=h>>>16;return h>>>0}
const SEED='wave22-rework-20260927-preview-158',VERSION='scatter-v1';
function h(f,x,y,tag){return hash(`${SEED}|${VERSION}|${f}|${x}|${y}|${tag}`)}
function point(x,y){return{x:384+.5*x-.5*y,y:100+.25*x+.25*y}}
function plane(g,fn){g.save();g.transform(.5,.25,-.5,.25,384,100);fn();g.restore()}
const dimensions=[[64,48],[96,64],[128,96]];
function candidate(f,cx,cy){const x=cx*160+80+(h(f,cx,cy,'jx')%97)-48,y=cy*160+80+(h(f,cx,cy,'jy')%97)-48,k=h(f,cx,cy,'variant')%3,[w,ht]=dimensions[k],p=point(x,y);return{cell:[cx,cy],x,y,variant:'abc'[k],asset:`decals/${decalFamily[f]}_${'abc'[k]}-v1.png`,priority:h(f,cx,cy,'priority'),active:h(f,cx,cy,'density')%100<82,rect:{x:p.x-w/2+8,y:p.y-ht+8,w:w-16,h:ht-16},anchor:{x:w/2,y:ht-8}}}
function overlap(a,b){return a.x<b.x+b.w+4&&a.x+a.w+4>b.x&&a.y<b.y+b.h+4&&a.y+a.h+4>b.y}
function allowed(c){return c.active&&Math.hypot(c.x-620,c.y-660)>110}
function placed(f,cx,cy){const c=candidate(f,cx,cy);if(!allowed(c))return null;for(let yy=cy-2;yy<=cy+2;yy++)for(let xx=cx-2;xx<=cx+2;xx++){if(xx===cx&&yy===cy)continue;const n=candidate(f,xx,yy);if(allowed(n)&&overlap(c.rect,n.rect)&&(n.priority<c.priority||(n.priority===c.priority&&(yy<cy||(yy===cy&&xx<cx)))))return null}return c}
function collect(f,cells){return cells.map(([x,y])=>placed(f,x,y)).filter(Boolean).sort((a,b)=>a.cell[1]-b.cell[1]||a.cell[0]-b.cell[0])}
function verifyPlacement(){const cells=[];for(let y=2;y<5;y++)for(let x=0;x<5;x++)cells.push([x,y]);const checks=[];for(const f of families){const a=collect(f,cells),b=collect(f,[...cells].reverse());if(JSON.stringify(a)!==JSON.stringify(b))throw Error('Order changed placements');const big=collect(f,[...cells,[-1,2],[5,2],[0,5]]).filter(c=>cells.some(p=>p[0]===c.cell[0]&&p[1]===c.cell[1]));if(JSON.stringify(a)!==JSON.stringify(big))throw Error('Added chunk changed placements');for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)if(overlap(a[i].rect,a[j].rect))throw Error('Decal bounds overlap');checks.push({family:f,count:a.length,visibleCount:a.filter(q=>q.x<735&&q.y<735).length,visibleVariants:[...new Set(a.filter(q=>q.x<735&&q.y<735).map(q=>q.variant))].sort(),replay:true,insertionInvariant:true,noDecalBoundsOverlap:true})}return checks}
const edge={chalk_down:'chalk',heath:'heath',fen:'fen',coastal_grass:'coastal'};
async function scene(f){const c=createCanvas(768,570),g=c.getContext('2d'),grass=await img(R+'/grass.png'),a=await img(fillPath(f,'summer','a')),b=await img(fillPath(f,'summer','b')),chunks=[];plane(g,()=>{for(let y=0;y<768;y+=256)for(let x=0;x<768;x+=256)g.drawImage(grass,x,y,256,256);g.save();g.beginPath();g.rect(0,290,768,478);g.clip();for(let y=256;y<768;y+=256)for(let x=0;x<768;x+=256){const v=h(f,x/256,y/256,'fill')%2?'b':'a';chunks.push({x:x/256,y:y/256,variant:v});g.drawImage(v==='a'?a:b,x,y,256,256)}g.restore()});if(edge[f]){const i=await img(D+`/boundary/${edge[f]}_edge_a-v1.png`);plane(g,()=>{g.save();g.beginPath();g.rect(0,0,768,768);g.clip();for(let x=0;x<768;x+=512)g.drawImage(i,x,258);g.restore()})}else{const i=await img(R+'/forest_fringe_a-v1.png');for(let x=80;x<700;x+=140){const p=point(x,300);g.drawImage(i,p.x-64,p.y-88)}}
const cells=[];for(let y=2;y<5;y++)for(let x=0;x<5;x++)cells.push([x,y]);const ps=collect(f,cells).filter(q=>q.x<735&&q.y<735);g.save();g.beginPath();for(const [index,xy] of [[0,[0,290]],[1,[768,290]],[2,[768,768]],[3,[0,768]]]){const p=point(...xy);if(index===0)g.moveTo(p.x,p.y);else g.lineTo(p.x,p.y)}g.closePath();g.clip();for(const d of ps){const i=await img(D+'/'+d.asset),p=point(d.x,d.y);g.drawImage(i,p.x-d.anchor.x,p.y-d.anchor.y)}g.restore();
const objects=[],house=await img(P+'/buildings/historical-houses/house_l1-v2.png'),r=house.width/1254,bb={x:137*r,y:187*r,w:1019*r,h:949*r},hp=point(280,200);objects.push({depth:hp.y,draw:()=>g.drawImage(house,bb.x,bb.y,bb.w,bb.h,hp.x-56.32,hp.y-bb.h/bb.w*112.64,112.64,bb.h/bb.w*112.64)});const anchorPath='/tmp/astra-wave15-work-20260926/foliage-runtime-anchors.json';used.add(anchorPath);const metas=JSON.parse(fs.readFileSync(anchorPath)).assets;for(const[xx,yy,key]of[[170,185,'tree_oak_small'],[595,220,'tree_birch'],[620,660,'tree_oak_large']]){const meta=metas.find(q=>q.key===key),i=await img(P+'/foliage/'+key+'.png'),p=point(xx,yy),s=meta.renderScale*2;objects.push({depth:p.y,draw:()=>g.drawImage(i,p.x-meta.anchor.x*s,p.y-meta.anchor.y*s,i.width*s,i.height*s)})}objects.sort((a,b)=>a.depth-b.depth).forEach(o=>o.draw());sceneRecords.push({family:f,seed:SEED,chunks,decals:ps,existingObjects:[{key:'house_l1-v2',world:[280,200]},{key:'tree_oak_small',world:[170,185]},{key:'tree_birch',world:[595,220]},{key:'tree_oak_large',world:[620,660]}]});return c}
async function sceneCheck(){const[c,g]=canvas(1180,1800);text(g,'WAVE 22 REWORK / 02   Quiet A/B fill + deterministic feature decals',24,32,23);text(g,'Identical house / trees / seed. No accepted props added: ground features come from the NEW scattered decals.',24,60,14);text(g,'zoom 1.0 / 64 x 32 px tile',24,91);text(g,'zoom 0.6 / 38.4 x 19.2 px tile',460,91);for(let n=0;n<5;n++){const y=110+n*333,s=await scene(families[n]);text(g,families[n].toUpperCase(),24,y+18,19);g.drawImage(s,24,y+32,384,285);g.drawImage(s,459,y+83,230.4,171);text(g,'A / B base fills',765,y+50);for(let k=0;k<2;k++){const i=await img(fillPath(families[n],'summer',variants[k]));g.drawImage(i,765+k*146,y+66,128,64)}text(g,'Feature decals: three sizes',765,y+163);for(let k=0;k<3;k++){const i=await img(D+`/decals/${decalFamily[families[n]]}_${'abc'[k]}-v1.png`);g.drawImage(i,775+k*120,y+185,i.width*.5,i.height*.5);text(g,`${'abc'[k]} / ${i.width} x ${i.height}`,765+k*120,y+260,12)}text(g,`Placed decals: ${sceneRecords[n].decals.length}; fixed coordinate hash`,765,y+293,13)}fs.writeFileSync(D+'/checks/02-archetype-scenes.png',c.toBuffer('image/png'))}
async function shoreCheck(){const[c,g]=canvas(1650,740),grass=await img(R+'/grass.png'),water=await img(R+'/water.png');text(g,'WAVE 22 REWORK / 03   Sand beach A v2 — irregular coast, X repeat',24,32,23);text(g,'Three repeats. Join markers stay outside art. Existing land / water underneath. Left zoom 1.0; right zoom 0.6.',24,62,14);const rows=[['sand_beach_a-v2',D+'/shore/sand_beach_a-v2.png'],['sand_beach_b-v1 (accepted)',D+'/shore/sand_beach_b-v1.png'],['existing shoreline_a-v1',R+'/shoreline_a-v1.png']];for(let n=0;n<rows.length;n++){const y=90+n*208,i=await img(rows[n][1]);text(g,rows[n][0],24,y+17,18);for(const[x,s]of[[24,.5],[865,.3]]){g.save();g.beginPath();g.rect(x,y+38,1536*s,130*s);g.clip();for(let a=0;a<1536;a+=256){g.drawImage(grass,x+a*s,y+38,256*s,65*s);g.drawImage(water,x+a*s,y+38+65*s,256*s,65*s)}for(let a=0;a<3;a++)g.drawImage(i,x+a*512*s,y+38+(65-i.height/2)*s,512*s,i.height*s);g.restore();for(let a=1;a<3;a++){g.strokeStyle='#a75435';g.beginPath();g.moveTo(x+a*512*s,y+30);g.lineTo(x+a*512*s,y+37);g.stroke()}text(g,`3 repeats / zoom ${s===.5?'1.0':'0.6'}`,x,y+38+130*s+22,13)}}fs.writeFileSync(D+'/checks/03-sand-beach-comparison.png',c.toBuffer('image/png'))}
(async()=>{fs.mkdirSync(D+'/checks',{recursive:true});const checks=verifyPlacement(),mode=process.argv[2]||'all';if(mode==='all'||mode==='fills')await fillCheck();if(mode==='all'||mode==='scenes')await sceneCheck();if(mode==='all'||mode==='shore')await shoreCheck();fs.writeFileSync(W+'/proofs-placement'+(mode==='all'?'':'-'+mode)+'.json',JSON.stringify({seed:SEED,algorithm:VERSION,checks,scenes:sceneRecords},null,2));fs.writeFileSync(W+'/proofs-provenance'+(mode==='all'?'':'-'+mode)+'.json',JSON.stringify({inputs:[...used].map(p=>({path:p,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')})),comparisonUV:{newSource:[256,128],grassSource:[256,256],displayUV:[256,128],grassTransform:'whole source compressed vertically, no crop'},sceneProjection:{a:.5,b:.25,c:-.5,d:.25,worldTile:128,fillUVWorldSquare:256},outputScales:{zoom1:.5,zoom06:.3},notes:'Mechanical offline proof. Runtime UV, chunk blending and placement integration not tested. Existing sprites retain documented runtime anchors. No generated substitutes for missing inputs.'},null,2));console.log(JSON.stringify({mode,checks,scenes:sceneRecords.map(s=>({family:s.family,decals:s.decals.length}))},null,2))})().catch(e=>{console.error(e);process.exit(1)});
