'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('/tmp/astra-wave39-work-20260930/node_modules/sharp');
const R=path.resolve(__dirname,'..'),K='/Users/rexxa/orca/workspaces/feudal-lord-simulator/krill-lme9',T='/Users/rexxa/fls-astra-world/assets-inbox/wave41/candidates-20261002/assets';
const shapes=JSON.parse(fs.readFileSync(path.join(__dirname,'path-shapes.json')));const entries=[];
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function gen(id){let j=JSON.parse(fs.readFileSync(path.join(__dirname,`gen-${id}.json`)));let dest=path.join(R,'raw',id+'.png');fs.copyFileSync(j.generated_path,dest);j.raw_sha256=sha(dest);j.reference_sha256=j.references.map(p=>({path:p,sha256:fs.existsSync(p)?sha(p):null}));fs.writeFileSync(path.join(__dirname,`gen-${id}.json`),JSON.stringify(j,null,2));return dest;}
async function bbox(p){const {data,info}=await sharp(p).ensureAlpha().raw().toBuffer({resolveWithObject:true});let x0=info.width,y0=info.height,x1=0,y1=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++)if(data[(y*info.width+x)*4+3]>20){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);}return{left:x0,top:y0,width:x1-x0+1,height:y1-y0+1};}
async function place(p,w,h,b){const crop=await bbox(p);let input=await sharp(p).extract(crop).resize(b.width,b.height,{fit:'fill'}).png().toBuffer();return sharp({create:{width:w,height:h,channels:4,background:'#00000000'}}).composite([{input,left:b.left,top:b.top}]).png().toBuffer();}
async function save(rel,buf,pivot,scale,extra={}){let p=path.join(R,'assets',rel);fs.mkdirSync(path.dirname(p),{recursive:true});await sharp(buf).png({compressionLevel:9}).toFile(p);let m=await sharp(p).metadata();entries.push({id:path.basename(rel,'.png'),file:rel,canvas:[m.width,m.height],pivot,worldScale:scale,flip:false,sha256:sha(p),...extra});}
async function main(){
let p=gen('rock'),base=await sharp(p).resize(512,512).removeAlpha().raw().toBuffer();let repair=await sharp(gen('rock_seamrepair')).resize(512,512).removeAlpha().raw().toBuffer();let out=Buffer.alloc(base.length);for(let y=0;y<512;y++)for(let x=0;x<512;x++){let ox=(x+256)%512,oy=(y+256)%512;let d=Math.min(Math.abs(ox-256),Math.abs(oy-256));let w=Math.max(0,Math.min(1,(44-d)/20));for(let c=0;c<3;c++)out[(y*512+x)*3+c]=Math.round(base[(y*512+x)*3+c]*(1-w)+repair[(oy*512+ox)*3+c]*w);}
// Pair edge samples smoothly; no wrapping reflection or duplicate quarter tiles.
for(let k=0;k<8;k++){let w=(8-k)/16;for(let n=0;n<512;n++)for(let c=0;c<3;c++){let a=(n*512+k)*3+c,b=(n*512+511-k)*3+c,aa=out[a],bb=out[b];out[a]=Math.round(aa*(1-w)+bb*w);out[b]=Math.round(bb*(1-w)+aa*w);}}
for(let k=0;k<8;k++){let w=(8-k)/16;for(let n=0;n<512;n++)for(let c=0;c<3;c++){let a=(k*512+n)*3+c,b=((511-k)*512+n)*3+c,aa=out[a],bb=out[b];out[a]=Math.round(aa*(1-w)+bb*w);out[b]=Math.round(bb*(1-w)+aa*w);}}
await save('terrain/rock.png',await sharp(out,{raw:{width:512,height:512,channels:3}}).png().toBuffer(),[0,0],1,{repeat:[512,512]});
p=gen('yard_rain_barrel');await save('yards/yard_rain_barrel.png',await place(p,128,64,{left:52,top:30,width:30,height:22}),[64,52],.5,{assemblyHeight:22,assemblyH:22*.5/17.6});
p=gen('yard_chicken_coop');const original=K+'/public/assets/wave27/yards/yard_chicken_coop.png';const ob=await bbox(original);const normalized=await place(p,128,64,ob);let a=await sharp(original).ensureAlpha().raw().toBuffer(),b=await sharp(normalized).ensureAlpha().raw().toBuffer();for(let y=0;y<64;y++)for(let x=0;x<128;x++){let inside=(x>=15&&x<=37&&y>=25&&y<=51)||(x>=77&&x<=104&&y>=33&&y<=57);if(inside)for(let c=0;c<4;c++)a[(y*128+x)*4+c]=b[(y*128+x)*4+c];}await save('yards/yard_chicken_coop.png',await sharp(a,{raw:{width:128,height:64,channels:4}}).png().toBuffer(),[64,52],.5,{editRegions:[[15,25,23,27],[77,33,28,25]],scope:'NAT5 coop hens; standalone flock excluded'});
const trees=[['apple_c','11',128],['apple_d','12',123],['pear_e','13',123],['plum_f','14',141]];
for(const [id,no,px]of trees){const original=path.join(T,`${no}-orchard_${id}-v1-wave41-v1.png`),ob=await bbox(original);const old=await sharp(original).ensureAlpha().raw().toBuffer();for(const season of ['spring','winter']){p=gen(`orchard_${id}_${season}`);let normalized=await place(p,256,256,ob);let b=await sharp(normalized).ensureAlpha().raw().toBuffer();for(let y=0;y<256;y++)for(let x=0;x<256;x++){let i=(y*256+x)*4;if(season==='spring')b[i+3]=Math.min(b[i+3],old[i+3]);if(y>=226){let w=Math.min(1,(y-226)/8);for(let c=0;c<4;c++)b[i+c]=Math.round(b[i+c]*(1-w)+old[i+c]*w);}}await save(`orchard/orchard_${id}_${season}-v1.png`,await sharp(b,{raw:{width:256,height:256,channels:4}}).png().toBuffer(),[px,246],43/256,{summerReference:original,summerSha256:sha(original)});}}
for(const [shape,ports] of Object.entries(shapes.shapes))for(const season of ['summer','winter']){let xs=[64,...ports.map(p=>shapes.ports[p][0])],ys=[80,...ports.map(p=>shapes.ports[p][1])];let b={left:Math.min(...xs)-6,top:Math.min(...ys)-5,width:Math.max(...xs)-Math.min(...xs)+12,height:Math.max(...ys)-Math.min(...ys)+10};p=gen(`path_clear_${shape}_${season}`);await save(`connections/path_clear_${shape}_${season}.png`,await place(p,128,128,b),[64,80],.5,{ports,portCoordinates:ports.map(p=>shapes.ports[p])});}
for(const material of ['stone','timber'])await save(`wall/gate_jamb_${material}.png`,await place(gen(`gate_jamb_${material}`),64,80,{left:10,top:10,width:44,height:60}),[32,70],.5,{bodyWorld:[22,30]});
fs.writeFileSync(path.join(R,'records/assets.json'),JSON.stringify(entries,null,2)+'\n');console.log(entries.length);
}main().catch(e=>{console.error(e);process.exitCode=1;});
