/* Offline candidate composites on preserved, real game captures. No game files changed. */
'use strict';
const fs=require('node:fs'); const path=require('node:path'); const crypto=require('node:crypto');
const sharp=require('/tmp/astra-wave39-work-20260930/node_modules/sharp');
const ROOT=path.resolve(__dirname,'..'); const A=path.join(ROOT,'assets'); const OUT=path.join(ROOT,'proofs');
const REPO='/Users/rexxa/orca/workspaces/feudal-lord-simulator/krill-lme9';
const records=[]; const missing=[]; const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const svg=(w,h,body)=>Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">${body}</svg>`);
const label=(w,text)=>svg(w,32,`<rect width="100%" height="100%" fill="#242820"/><text x="10" y="21" font-family="sans-serif" font-size="13" textLength="${Math.min(w-20,text.length*6.5)}" lengthAdjust="spacingAndGlyphs" fill="#f2ead8">${text.replaceAll('&','&amp;').replaceAll('<','&lt;')}</text>`);
async function source(rel,crop){const p=path.join(REPO,rel); records.push({source:p,sha256:sha(p),crop:crop??null});let im=sharp(p);if(crop)im=im.extract(crop);return im.png().toBuffer();}
async function asset(rel,scale,foot,pivot){const p=path.join(A,rel);if(!fs.existsSync(p)){missing.push(rel);return null;}const m=await sharp(p).metadata();const width=Math.max(1,Math.round(m.width*scale)),height=Math.max(1,Math.round(m.height*scale));records.push({candidate:rel,sha256:sha(p),canvas:[m.width,m.height],screenPixelsPerAssetPixel:scale,foot,pivot});return {input:await sharp(p).resize(width,height).png().toBuffer(),left:Math.round(foot[0]-pivot[0]*scale),top:Math.round(foot[1]-pivot[1]*scale)};}
async function board(name,panels,notes){for(const p of panels){const meta=await sharp(p.image).metadata();p.width=meta.width;p.height=meta.height;}const width=Math.max(...panels.map(p=>p.width));let y=0;const layers=[];for(const p of panels){layers.push({input:label(width,p.title),left:0,top:y});y+=32;layers.push({input:p.image,left:0,top:y});y+=p.height;}layers.push({input:label(width,'GAME_SCENE_COMPOSITE / OFFLINE CANDIDATES / original scene retained'),left:0,top:y});y+=32;await sharp({create:{width,height:y,channels:3,background:'#eee9da'}}).composite(layers).jpeg({quality:86,mozjpeg:true}).toFile(path.join(OUT,`scene-${name}.jpg`));records.push({proof:`scene-${name}.jpg`,notes});}
async function composed(base,layers){return sharp(base).composite(layers.filter(Boolean)).png().toBuffer();}
async function main(){fs.mkdirSync(OUT,{recursive:true});
const gate=await source('docs/verification/nat4/world/qa003-gate-z2.jpg');const gatePanels=[{image:gate,width:520,height:340,title:'QA003 original: game zoom 2; corner opening at tile (47,42)'}];
for(const material of ['stone','timber']){const layers=[];for(const foot of [[186,237],[258,210]])layers.push(await asset(`wall/gate_jamb_${material}.png`,1,foot,[32,70]));if(layers.some(Boolean))gatePanels.push({image:await composed(gate,layers),width:520,height:340,title:`${material}: candidate posts at opening edges; timber = material study on stone scene`});}
if(gatePanels.length>1)await board('gate',gatePanels,'Original zoom2 preserved. Candidate native .5world px/asset px multiplied by zoom2. Placement is manual, not occlusion/runtime verification. Manual foot anchors (186,237) and (258,210), same original 520x340 capture coordinates. Alpha bounds of the stipulated 44x60 bodies are x164..207/y177..236 and x236..279/y150..209. The central passage strip x210..234/y210..238 remains uncovered by either new post. Original wall/people are not erased. This is a placement study; depth ordering and actual walk collision are unverified.');
const field=await source('docs/verification/nat5/stages/gate-field-summer.jpg',{left:480,top:16,width:480,height:300});
const yardLayers=[await asset('yards/yard_rain_barrel.png',.35,[180,115],[64,52]),await asset('yards/yard_chicken_coop.png',.35,[205,135],[64,52])];
if(yardLayers.some(Boolean)){const original=await source('docs/verification/nat5/installs/barrel-city-z1.0-x3.jpg');await board('yard-scale',[{image:original,width:1040,height:300,title:'Original NAT5 evidence: zoom1 crop enlarged 3x; oversized old barrel remains visible'},{image:field,width:480,height:300,title:'Unchanged NAT5 summer field: effective screen scale .7 world px'},{image:await composed(field,yardLayers),width:480,height:300,title:'NEW barrel + coop on empty grass: .5 asset scale x .7 capture factor'}],'Objects added beside scenery; no original object erased. Field capture zoom1.4 reduced .5. New barrel body target16-23source px, hen6.34-9.86source px at fixed .5scale. Scene composites are not installed game captures.');}
for(const season of ['spring','winter']){const rel=`docs/verification/nat5/stages/gate-field-${season==='winter'?'winter':'summer'}.jpg`;const b=await source(rel,{left:480,top:16,width:480,height:300});const layers=[];for(const [i,id]of ['apple_c','apple_d','pear_e','plum_f'].entries())layers.push(await asset(`orchard/orchard_${id}_${season}-v1.png`,43/256*.7,[75+i*42,115],[id==='apple_c'?128:id==='plum_f'?141:123,246]));if(layers.some(Boolean))await board(`orchard-${season}`,[{image:b,width:480,height:300,title:`Original NAT5 ${season==='winter'?'winter':'summer'} ground; .7 screen px/world px`},{image:await composed(b,layers),width:480,height:300,title:`New ${season}: apple C / apple D / pear E / plum F; native prop scale1`}],'Spring candidate shown on actual summer-ground capture for neutral grass comparison; not a newly captured spring runtime. Same 256canvas and per-ID native anchor; rendered width43world px x .7.');}
for(const season of ['summer','winter']){const b=await source(`docs/verification/nat5/stages/gate-field-${season}.jpg`,{left:480,top:16,width:480,height:300});const dir=path.join(A,'connections');const names=fs.existsSync(dir)?fs.readdirSync(dir).filter(n=>n.endsWith(`_${season}.png`)).sort():[];const layers=[];for(const [i,name]of names.entries())layers.push(await asset(`connections/${name}`,.35,[65+(i%5)*41,88+Math.floor(i/5)*31],[64,80]));if(layers.length)await board(`paths-${season}`,[{image:b,width:480,height:300,title:'Original NAT5 field; existing path/ground pixels preserved'},{image:await composed(b,layers),width:480,height:300,title:`New ${season} joints, 128canvas at .5world scale x .7; ordered filename`}],{classification:'isolated-joint scene placement; separate topology proof required',order:names,effectiveGameZoom:.7});else missing.push(`connections/*_${season}.png`);}
// A local texture replacement study only: manually delimited interior rock patch, not a full runtime rerender.
const rockRel='terrain/rock.png';if(fs.existsSync(path.join(A,rockRel))){const b=await source('docs/verification/nat5/ground/river-rock-grass-before-after.jpg',{left:566,top:0,width:560,height:572});const translucent=await sharp(path.join(A,rockRel)).resize(512,512).removeAlpha().ensureAlpha(.6).png().toBuffer();const tex=await sharp({create:{width:512,height:512,channels:4,background:'#8A8071'}}).composite([{input:translucent}]).png().toBuffer();const mask=svg(512,512,'<path d="M0 170 L74 213 L137 246 L112 276 L100 319 L152 356 L219 386 L255 428 L339 450 L295 485 L232 508 L120 512 L0 512 Z" fill="white"/>');const softMask=await sharp(mask).blur(5).png().toBuffer();const patch=await sharp(tex).composite([{input:softMask,blend:'dest-in'}]).png().toBuffer();await board('rock',[{image:b,width:560,height:572,title:'Original NAT5 rock after install; scene pixels unchanged'},{image:await composed(b,[{input:patch,left:0,top:0}]),width:560,height:572,title:'Candidate .6 texture over #8A8071; feathered manual-mask interior study'}],'Deliberately labelled texture patch, not engine region rendering. Native texture compositing .6 over SEMANTIC_PALETTE stone #8A8071 reproduced; manual mask feather5px is proof-only. Candidate UV512px shown at 1:1 image-pixel study; capture resize factor not independently established. Use separate repetition proof for seam validation.');records.push({candidate:rockRel,sha256:sha(path.join(A,rockRel)),manualMask:true,notRuntime:true});}else missing.push(rockRel);
fs.writeFileSync(path.join(OUT,'scene-provenance.json'),JSON.stringify({status:'game_scene_composite',sourceRepo:REPO,sourceHead:'0091bcce79819c836214aad9326aedcf32cae277',missingCandidates:missing,records},null,2)+'\n');console.log(JSON.stringify({records:records.length,missing}));}
main().catch(e=>{console.error(e);process.exitCode=1;});
