const fs=require('fs'),path=require('path');
const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const {createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');
const base=path.resolve(__dirname,'..');
const defs=[['child_hoop',64,0.095,'굴렁쇠와 밀대'],['child_ball',64,0.039,'꿰맨 가죽 공'],['child_wooden_sword',64,0.10,'무딘 나무 장난감 칼'],['clothesline_a',128,0.145,'린넨·적갈색 튜닉 빨래줄'],['clothesline_b',128,0.145,'청회색 속옷·수건 빨래줄'],['doorstep_chair',96,0.063,'문 앞 낮은 목제 의자'],['doorstep_barrel',96,0.069,'문 앞 작은 참나무 통'],['well_bucket',64,0.062,'우물가 목제 물통']];
(async()=>{const prompts=JSON.parse(fs.readFileSync(path.join(base,'records/life-props-prompts.json'))),metadata=[];
const c=createCanvas(960,520),ctx=c.getContext('2d');ctx.fillStyle='#c9c4aa';ctx.fillRect(0,0,960,520);
for(let i=0;i<defs.length;i++){const [id,size,scale,desc]=defs[i],p=prompts.find(x=>x.id===id),raw=path.join(base,p.rawFile);const tr=await sharp(raw).trim().toBuffer();const fit=await sharp(tr).resize(size-8,size-8,{fit:'inside'}).toBuffer();const info=await sharp(fit).metadata(),left=Math.floor((size-info.width)/2),top=size-4-info.height;const file=`assets/life_props/${id}.png`;await sharp({create:{width:size,height:size,channels:4,background:'#00000000'}}).composite([{input:fit,left,top}]).png().toFile(path.join(base,file));
metadata.push({id:`life_props/${id}`,file,width:size,height:size,description:desc,role:'object',blendMode:'normal',opacityMax:1,frameLayout:null,pivot:{x:size/2,y:size-4},displayScale:scale,qa:{status:'candidate',native:'Target-size contact inspected; transparent isolated object, no people or ground slab.',world:'Cattle-scale world preview stays physically small; very small toy detail is not reliably identifiable at zoom 0.6.'},generationRecords:[{...p,tool:'image_gen.imagegen',model:null,seed:null}],processing:{method:'Trim transparent margins, proportional one-step Lanczos downsample, pad RGBA to square; no repaint.',contentBox:{left,top,width:info.width,height:info.height}}});const im=await loadImage(path.join(base,file)),x=i%4*240,y=Math.floor(i/4)*260;ctx.drawImage(im,x+(240-size)/2,y+25);ctx.fillStyle='#28231c';ctx.font='15px sans-serif';ctx.fillText(id,x+10,y+175);ctx.font='13px sans-serif';ctx.fillText(`${size}px · world scale ${scale}`,x+10,y+199);ctx.drawImage(im,x+30,y+220,size*scale,size*scale);ctx.drawImage(im,x+90,y+220,size*scale*.6,size*scale*.6);}
fs.writeFileSync(path.join(base,'records/metadata-life-props.json'),JSON.stringify(metadata,null,2));fs.writeFileSync(path.join(base,'records/life-props-contact.png'),c.toBuffer('image/png'));})();
