const fs=require('fs');const path=require('path');const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..');const inputs=JSON.parse(fs.readFileSync(path.join(root,'records/life-birds-inputs.json')));
const empty=(w,h)=>sharp({create:{width:w,height:h,channels:4,background:{r:0,g:0,b:0,alpha:0}}});
(async()=>{const rows=[];for(const[id,input]of Object.entries(inputs)){const rawFile=`raw/life_birds/${id}-generated.png`;fs.copyFileSync(input.source,path.join(root,rawFile));const src=path.join(root,rawFile);const m=await sharp(src).metadata();let cell=id==='sparrow_flight_sheet'?48:64,count=id.includes('flight')?4:1;let processing=[];
if(count===4){const cuts=id==='crow_flight_sheet'?[0,477,994,1452,1983]:[0,424,865,1265,1717];const top=id==='crow_flight_sheet'?100:250;const h=id==='crow_flight_sheet'?590:440;const comps=[];for(let i=0;i<4;i++){const w=cuts[i+1]-cuts[i];const offsets=id==='crow_flight_sheet'?[[-2,0],[-2,1],[1,1],[2,2]]:[[0,-1],[0,0],[0,1],[0,0]];const buf=await sharp(src).extract({left:cuts[i],top,width:w,height:h}).resize(cell-8,cell-8,{fit:'contain',background:{r:0,g:0,b:0,alpha:0}}).png().toBuffer();comps.push({input:buf,left:cell*i+4+offsets[i][0],top:4+offsets[i][1]});processing.push({frame:i,crop:[cuts[i],top,w,h],resize:[cell-8,cell-8],fit:'contain',offset:[4+offsets[i][0],4+offsets[i][1]],registration:'manual thorax center translation; four-pixel safety gutter'});}await empty(cell*4,cell).composite(comps).png().toFile(path.join(root,`assets/life_birds/${id}.png`));}
else{const b=await sharp(src).trim({threshold:5}).resize(52,52,{fit:'inside'}).png().toBuffer();const bm=await sharp(b).metadata();await empty(64,64).composite([{input:b,left:Math.round((64-bm.width)/2),top:58-bm.height}]).png().toFile(path.join(root,`assets/life_birds/${id}.png`));processing=[{trim:'alpha tight crop threshold5',resize:'fit inside52x52 preserving aspect',anchor:[32,58]}];}
const flight=count===4;const torsoEndpoints=id==='crow_flight_sheet'?[[26,36],[42,42]]:id==='sparrow_flight_sheet'?[[16,28],[28,32]]:id.endsWith('_a')?[[15,25],[42,44]]:[[43,47],[21,35]];if(flight)for(const p of torsoEndpoints){p[0]=p[0]*(cell-8)/cell+(id==='crow_flight_sheet'?2:4);p[1]=p[1]*(cell-8)/cell+(id==='crow_flight_sheet'?4:3);}const torsoPx=Math.hypot(torsoEndpoints[1][0]-torsoEndpoints[0][0],torsoEndpoints[1][1]-torsoEndpoints[0][1]);const ratio=id==='crow_flight_sheet'?0.20:id==='sparrow_flight_sheet'?0.085:0.16;const displayScale=31.30*0.24*ratio/torsoPx;
rows.push({id,file:`assets/life_birds/${id}.png`,width:cell*count,height:cell,description:id,role:'object',blendMode:'source-over',opacityMax:1,frameLayout:{columns:count,rows:1,cellWidth:cell,cellHeight:cell,count,order:flight?['wings_up','wings_level','wings_down','wings_return']:['perched'],direction:id.endsWith('_b')?'SE':'SW'},pivot:flight?[cell/2,Math.round(cell*0.6)]:[32,58],displayScale,bodyProportion:{reference:'references/cattle_pair-v1.png',cowTorsoEndpoints:[[56,49],[28,63]],cowTorsoPixels:31.30,cowScale:0.24,birdTorsoPixels:torsoPx,birdTorsoEndpoints:torsoEndpoints,torsoRatioToCow:ratio,renderedTorsoPixelsAtZoom1:31.30*0.24*ratio,measurement:'Manual shoulder-rump approximate segment; excludes beak/head/tail/wings'},qa:{status:'candidate',alpha:true,flightCycle:flight?'Four distinct wing phases; body/head visually consistent but not pixel-locked (wing cycle exempt from walking leg-only rule).':null,zoom06:'At cattle-proportional scale the torso is below 1px at zoom0.6; species is NOT reliably identifiable. Larger native-size inset needed for species QA. No artificial enlargement in world proof.'},generationRecords:[{prompt:input.prompt,rawFile,referenceImages:['references/goose_single-v1.png'],tool:'image_gen.imagegen',model:null,seed:null}],processing});}
fs.writeFileSync(path.join(root,'records/metadata-life-birds.json'),JSON.stringify(rows,null,2));
const comps=[];for(let i=0;i<rows.length;i++){const b=await sharp(path.join(root,rows[i].file)).resize({width:rows[i].width*3,kernel:'nearest'}).png().toBuffer();comps.push({input:b,left:20,top:20+i*210});}await sharp({create:{width:820,height:850,channels:4,background:'#c9bda4'}}).composite(comps).png().toFile(path.join(root,'records/life-birds-contact.png'));
console.log(rows.map(r=>({id:r.id,size:[r.width,r.height],scale:r.displayScale})));
})().catch(e=>{console.error(e);process.exit(1)});
