const fs=require('node:fs'), path=require('node:path');
const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..');
const record=n=>JSON.parse(fs.readFileSync(path.join(root,'raw/royal_pad',n+'-record.json')));
const specs=[['pad_a','A'],['pad_b','B'],['pad_x','X'],['pad_y','Y'],['pad_dpad','십자키'],['pad_shoulder','어깨 L/R'],['pad_trigger','트리거 L/R'],['pad_stick_press','스틱 누름'],['pad_menu','메뉴'],['pad_view','보기']];
async function main(){const rows=[];
 for(const [name,raw,description] of [['arms_royal_england_pre1340','arms_pre1340','1340년 전 잉글랜드 왕실: 붉은 바탕 금사자 셋 passant guardant'],['arms_royal_england_1340','arms_1340-v2','1340년형 잉글랜드·France ancien 4분할: 프랑스 백합 흩뿌림']]) {
   for(const size of [256,96]) {const file='assets/royal/'+name+'_'+size+'.png';await sharp(path.join(root,'raw/royal_pad',raw+'.png')).resize(size,size,{kernel:'lanczos3'}).png().toFile(path.join(root,file));rows.push({id:name+'_'+size,file,width:size,height:size,description,role:'object',blendMode:'source-over',opacityMax:1,frameLayout:{columns:1,rows:1,cellWidth:size,cellHeight:size},pivot:[size/2,size/2],displayScale:1,qa:{status:'pending-final-review',historicalSource:'records/royal-pad-history.md',era:name.includes('pre')?'1198–1339 representative':'1340 France ancien representative; not all subsequent personal arms',rights:'Historical royal arms specifically requested; not a claim of modern endorsement',limitations:'96px minor facial details simplify; heater type follows reference but generated alpha is not pixel-identical to mask'},generationRecords:raw.endsWith('v2')?[record('arms_1340'),record(raw)]:[record(raw)],processing:{operation:'one Lanczos3 downsample directly from generated original; preserve alpha',source:raw+'.png'}});}
 }
 for(const [id,description] of specs) {const src=path.join(root,'raw/royal_pad',id+'.png');if(!fs.existsSync(src)||!fs.existsSync(src.replace('.png','-record.json')))continue;const pair=id==='pad_shoulder'||id==='pad_trigger';for(const size of [48,32]){const file='assets/pad/'+id+'_'+size+'.png';const meta=await sharp(src).metadata(); const cells=[]; for(let k=0;k<(pair?2:1);k++){ let input=sharp(src); if(pair) input=input.extract({left:k*Math.floor(meta.width/2),top:0,width:Math.floor(meta.width/2),height:meta.height}); else if(meta.width>meta.height*1.3){const rgba=await sharp(src).ensureAlpha().raw().toBuffer();let bestStart=0,bestLen=0,runStart=0,runLen=0;for(let x=Math.floor(meta.width*0.3);x<Math.floor(meta.width*0.8);x++){let present=false;for(let y=0;y<meta.height;y++)if(rgba[(y*meta.width+x)*4+3]>8){present=true;break;}if(!present){if(runLen===0)runStart=x;runLen++;if(runLen>bestLen){bestStart=runStart;bestLen=runLen;}}else runLen=0;}if(bestLen<3)throw Error('Cannot isolate single glyph '+id);input=input.extract({left:0,top:0,width:bestStart+Math.floor(bestLen/2),height:meta.height});} const extracted=await input.png().toBuffer(); const trim=await sharp(extracted).trim().png().toBuffer(); const small=await sharp(trim).resize(Math.round(size*0.84),Math.round(size*0.84),{fit:'inside',kernel:'lanczos3'}).png().toBuffer({resolveWithObject:true}); cells.push({input:small.data,left:k*size+Math.floor((size-small.info.width)/2),top:Math.floor((size-small.info.height)/2)}); } await sharp({create:{width:size*(pair?2:1),height:size,channels:4,background:{r:0,g:0,b:0,alpha:0}}}).composite(cells).png().toFile(path.join(root,file));rows.push({id:id+'_'+size,file,width:size*(pair?2:1),height:size,description,role:'object',blendMode:'source-over',opacityMax:1,frameLayout:{columns:pair?2:1,rows:1,cellWidth:size,cellHeight:size,order:pair?['L','R']:[description]},pivot:[size/2,size/2],displayScale:1,qa:{status:'pending-final-review',rights:'Unbranded generic control notation; no brand-specific colors or logos'},generationRecords:[record(id)],processing:{operation:'Extract single large glyph if source includes unsolicited second size; trim transparent margin; one Lanczos3 downsample to 84% cell bounds preserving aspect; pairs independently centered in equal cells',source:id+'.png'}});}}
 fs.writeFileSync(path.join(root,'records/metadata-royal-pad.json'),JSON.stringify(rows,null,2));console.log(rows.length+' final PNGs');
}
main().catch(e=>{console.error(e);process.exit(1)});
