const fs=require('node:fs'),path=require('node:path');const {createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');const root=path.resolve(__dirname,'..');
async function main(){const original=await loadImage(path.join(root,'references/현재_평소화면.jpg'));const W=1280,H=800;const cache={};async function get(id){return cache[id]??=await loadImage(path.join(root,'assets/weather/'+id+'.png'));}const hud=[[0,0,382,56],[0,55,304,57],[1073,0,207,58],[0,740,290,60],[1120,730,160,70],[759,305,90,40]];
const panels=[],params=[];for(const state of ['clear','wet','dry','cold']){const c=createCanvas(W,H),ctx=c.getContext('2d');ctx.drawImage(original,0,0);const recipe=[];async function layer(id,alpha,blend,x,y,w,h,tiled=false){const im=await get(id);ctx.save();ctx.globalAlpha=alpha;ctx.globalCompositeOperation=blend; if(tiled){const tile=createCanvas(id.includes('sheet')?im.width/4:im.width,im.height);tile.getContext('2d').drawImage(im,0,0,tile.width,tile.height,0,0,tile.width,tile.height);ctx.fillStyle=ctx.createPattern(tile,'repeat');ctx.fillRect(x,y,w,h);}else ctx.drawImage(im,x,y,w,h);ctx.restore();recipe.push({id,alpha,blend,x,y,w,h,tiled});}
if(state==='clear'){await layer('cloud_shadow_a',.10,'multiply',100,120,580,440);}
if(state==='wet'){await layer('overcast_tint',.12,'multiply',0,0,W,H,true);await layer('drizzle_sheet',.08,'source-over',0,0,W,H,true);await layer('fog_bank_a',.10,'source-over',820,350,460,230);await layer('wet_ground_sheen',.04,'screen',365,480,470,210,true);}
if(state==='dry'){await layer('dry_dust_a',.18,'source-over',220,485,370,150);await layer('dry_dust_b',.16,'source-over',660,520,320,140);await layer('heat_cracked_ground',.20,'multiply',440,570,128,64);}
if(state==='cold'){await layer('frost_morning_tint',.10,'source-over',0,0,W,H,true);await layer('fog_bank_b',.16,'source-over',730,370,512,256);}
for(const [x,y,w,h]of hud)ctx.drawImage(original,x,y,w,h,x,y,w,h);const raw=ctx.getImageData(0,0,W,H).data;const base=createCanvas(W,H);base.getContext('2d').drawImage(original,0,0);const b=base.getContext('2d').getImageData(0,0,W,H).data;let hudDiff=0;for(const[x,y,w,h]of hud)for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)for(let k=0;k<4;k++)if(raw[(yy*W+xx)*4+k]!==b[(yy*W+xx)*4+k])hudDiff++;
const buf=c.toBuffer('image/png');fs.writeFileSync(path.join(root,'records/weather-'+state+'-1x.png'),buf);panels.push(await loadImage(buf));params.push({state,recipe,hudDifferingChannels:hudDiff});}
const sheet=createCanvas(2560,3440),s=sheet.getContext('2d');s.fillStyle='#e4dcc8';s.fillRect(0,0,sheet.width,sheet.height);s.fillStyle='#282a25';s.font='24px sans-serif';const labels=['맑음 / clear','젖은 여름 / wet','마른 여름 / dry','추운 날 / cold'];for(let row=0;row<4;row++){const y=row*860;s.fillStyle='#282a25';s.fillText(labels[row]+' — 1.0 offline',12,y+32);s.fillText(labels[row]+' — 0.6 offline',1292,y+32);s.drawImage(panels[row],0,y+50);s.drawImage(panels[row],1280+256,y+50+160,768,480);}fs.writeFileSync(path.join(root,'proofs/proof01-weather.png'),sheet.toBuffer('image/png'));
const tileIds=['overcast_tint','drizzle_sheet','storm_rain_sheet','wet_ground_sheen','frost_morning_tint'];const tc=createCanvas(2304,1500),t=tc.getContext('2d');t.fillStyle='#827f6d';t.fillRect(0,0,tc.width,tc.height);const edges=[];for(let i=0;i<tileIds.length;i++){const id=tileIds[i],im=await get(id),w=id.includes('sheet')?im.width/4:im.width,h=im.height;const x=(i%3)*768,y=Math.floor(i/3)*750;t.fillStyle='#eee';t.font='20px sans-serif';t.fillText(id,x+5,y+25);for(let yy=0;yy<3;yy++)for(let xx=0;xx<3;xx++)t.drawImage(im,0,0,w,h,x+xx*240,y+40+yy*220,240,220);const{data,info}=await sharp(path.join(root,'assets/weather/'+id+'.png')).extract({left:0,top:0,width:w,height:h}).ensureAlpha().raw().toBuffer({resolveWithObject:true});let max=0;for(let yy=0;yy<h;yy++)for(let k=0;k<4;k++)max=Math.max(max,Math.abs(data[(yy*w)*4+k]-data[(yy*w+w-1)*4+k]));for(let xx=0;xx<w;xx++)for(let k=0;k<4;k++)max=Math.max(max,Math.abs(data[xx*4+k]-data[((h-1)*w+xx)*4+k]));edges.push({id,opposingEdgeMaxDelta:max});}fs.writeFileSync(path.join(root,'records/weather-repeat-3x3.png'),tc.toBuffer('image/png'));fs.writeFileSync(path.join(root,'records/weather-proof-qa.json'),JSON.stringify({type:'offline compositing, same source screenshot; zoom0.6 is resampling not actual game camera',source:'references/현재_평소화면.jpg',hud,states:params,edges,combinedLayerAlphaCap:.38},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
