const fs=require('node:fs'),path=require('node:path');
const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const {createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');
const root=path.resolve(__dirname,'..');
const defs=[['overcast_tint',256,256,'multiply',.18,'fill'],['fog_bank_a',512,256,'normal',.20,'decal'],['fog_bank_b',512,256,'normal',.20,'decal'],['fog_bank_c',512,256,'normal',.20,'decal'],['drizzle_sheet',1024,256,'normal',.22,'fill'],['storm_rain_sheet',1024,256,'normal',.28,'fill'],['wet_ground_sheen',256,128,'screen',.16,'fill'],['puddle_ripple_sheet',256,32,'screen',.35,'decal'],['dry_dust_a',256,128,'normal',.18,'decal'],['dry_dust_b',256,128,'normal',.18,'decal'],['heat_cracked_ground',128,64,'multiply',.32,'decal'],['frost_morning_tint',256,256,'normal',.10,'fill'],['cloud_shadow_a',512,512,'multiply',.12,'decal'],['cloud_shadow_b',512,512,'multiply',.12,'decal']];
function seamless(data,w,h){const band=12;for(let y=0;y<h;y++)for(let d=0;d<band;d++)for(let c=0;c<4;c++){const a=(y*w+d)*4+c,b=(y*w+w-1-d)*4+c,mean=(data[a]+data[b])/2,t=(1-d/band)*.5;const av=data[a],bv=data[b];data[a]=Math.round(av+(mean-av)*t*2);data[b]=Math.round(bv+(mean-bv)*t*2);}for(let x=0;x<w;x++)for(let d=0;d<band;d++)for(let c=0;c<4;c++){const a=(d*w+x)*4+c,b=((h-1-d)*w+x)*4+c,mean=(data[a]+data[b])/2,t=(1-d/band);const av=data[a],bv=data[b];data[a]=Math.round(av+(mean-av)*t);data[b]=Math.round(bv+(mean-bv)*t);}return data;}
async function pngraw(buf,w,h){return sharp(buf,{raw:{width:w,height:h,channels:4}}).png().toBuffer();}
async function main(){const rows=[];const measurements=[];for(const[id,w,h,blend,cap,role]of defs){const src=path.join(root,'raw/weather',id+'.png');if(!fs.existsSync(src))throw Error('missing '+id);const meta=await sharp(src).metadata();let frames=[],out;let processing=[];
if(id==='drizzle_sheet'||id==='storm_rain_sheet'){for(let f=0;f<4;f++){const cw=Math.floor(meta.width/2),ch=Math.floor(meta.height/2);let data=await sharp(src).extract({left:(f%2)*cw,top:Math.floor(f/2)*ch,width:cw,height:ch}).resize(256,256).ensureAlpha().raw().toBuffer();frames.push(await pngraw(seamless(data,256,256),256,256));}out=await sharp({create:{width:w,height:h,channels:4,background:'#00000000'}}).composite(frames.map((input,i)=>({input,left:i*256,top:0}))).png().toBuffer();processing.push('Generated2x2 cells extracted, downsampled once to256square,12px XY edge seam blend percell, assembled4x1.');}
else if(id==='puddle_ripple_sheet'){const cw=Math.floor(meta.width/4);for(let f=0;f<4;f++)frames.push(await sharp(src).extract({left:f*cw,top:0,width:cw,height:meta.height}).resize(64,32).ensureAlpha().png().toBuffer());out=await sharp({create:{width:w,height:h,channels:4,background:'#00000000'}}).composite(frames.map((input,i)=>({input,left:i*64,top:0}))).png().toBuffer();processing.push('Four generated ripple frames horizontally extracted and downsampled once to64x32cells.');}
else{let pipeline=sharp(src);if(id.endsWith('_tint')){const size=Math.floor(Math.min(meta.width,meta.height)*.52);pipeline=pipeline.extract({left:Math.floor((meta.width-size)/2),top:Math.floor((meta.height-size)/2),width:size,height:size});processing.push('Central52percent crop removes generated edge falloff; quiet painted interior used for tint.');}let data=await pipeline.resize(w,h,{fit:'fill'}).ensureAlpha().raw().toBuffer();if(id.endsWith('_tint')){const mean=[0,0,0];for(let i=0;i<data.length;i+=4)for(let k=0;k<3;k++)mean[k]+=data[i+k]/(w*h);for(let i=0;i<data.length;i+=4)for(let k=0;k<3;k++)data[i+k]=Math.round(mean[k]+(data[i+k]-mean[k])*.25);processing.push('Quiet tint color normalization:retain25percent RGB variation around generated mean, suppress repeating broad exposure bands.');}if(role==='fill'){data=seamless(data,w,h);processing.push('12px opposite-edge blending repairs XY repeat; exact opposing edgeRGBA match.');}if(role==='decal'){for(let y=0;y<h;y++)for(let x=0;x<w;x++){const fade=Math.min(1,x/8,(w-1-x)/8,y/8,(h-1-y)/8);data[(y*w+x)*4+3]=Math.round(data[(y*w+x)*4+3]*fade);}processing.push('8px alpha edge feather prevents clipped transparent decal margins; no painted motif added.');}out=await pngraw(data,w,h);processing.push('Single downsample; actual generated alpha preserved.');}
const hygiene=await sharp(out).ensureAlpha().raw().toBuffer();let cleared=0;for(let i=0;i<hygiene.length;i+=4)if(hygiene[i+3]<=2){if(hygiene[i+3]>0)cleared++;hygiene[i]=hygiene[i+1]=hygiene[i+2]=hygiene[i+3]=0;}out=await pngraw(hygiene,w,h);processing.push('RGBA nearzero-alpha hygiene:alpha<=2/255 cleared, '+cleared+' nearinvisiblepixels; removes saturated hiddenRGB thumbnails, visiblepaintpreserved.');fs.writeFileSync(path.join(root,'assets/weather',id+'.png'),out);const raw=await sharp(out).raw().toBuffer();let alphaMin=255,alphaMax=0,alphaSum=0;for(let i=3;i<raw.length;i+=4){alphaMin=Math.min(alphaMin,raw[i]);alphaMax=Math.max(alphaMax,raw[i]);alphaSum+=raw[i];}measurements.push({id,width:w,height:h,alphaMin,alphaMax,meanAlpha:alphaSum/(w*h*255)});
rows.push({id:'weather/'+id,file:'assets/weather/'+id+'.png',width:w,height:h,description:id.replaceAll('_',' '),role,blendMode:blend,opacityMax:cap,frameLayout:id.includes('sheet')?{columns:4,rows:1,cellWidth:w/4,cellHeight:h,order:[0,1,2,3]}:null,pivot:role==='decal'?[w/2,h/2]:[0,0],displayScale:1,qa:{status:'offline_checked',combinedLayerCap:.38,scope:'Offline composite only; never apply to HUD. Same-pixel cumulative alpha <=0.38; use either drizzle or storm, not both.'},generationRecords:[{prompt:fs.readFileSync(path.join(root,'raw/weather',id+'.prompt.txt'),'utf8').trim(),rawFile:'raw/weather/'+id+'.png',referenceImages:[],tool:'image_gen.imagegen',model:null,seed:null}],processing});}
fs.writeFileSync(path.join(root,'records/metadata-weather.json'),JSON.stringify(rows,null,2));fs.writeFileSync(path.join(root,'records/weather-technical.json'),JSON.stringify(measurements,null,2));
const c=createCanvas(1536,1500),ctx=c.getContext('2d');ctx.fillStyle='#ddd6c5';ctx.fillRect(0,0,c.width,c.height);for(let i=0;i<defs.length;i++){const[id,w,h,,cap]=defs[i],im=await loadImage(path.join(root,'assets/weather',id+'.png'));const x=(i%3)*512,y=Math.floor(i/3)*300;ctx.fillStyle='#252723';ctx.fillRect(x,y+30,256,260);ctx.fillStyle='#ede8da';ctx.fillRect(x+256,y+30,256,260);ctx.fillStyle='#171915';ctx.font='16px sans-serif';ctx.fillText(id+' cap '+cap,x+5,y+23);const fw=id.includes('sheet')?w/4:w;ctx.drawImage(im,0,0,fw,h,x+5,y+40,246,Math.min(220,h/fw*246));ctx.drawImage(im,0,0,fw,h,x+261,y+40,246,Math.min(220,h/fw*246));}fs.writeFileSync(path.join(root,'records/weather-light-dark.png'),c.toBuffer('image/png'));
}
main().catch(e=>{console.error(e);process.exit(1)});
