const fs=require('fs'),path=require('path'),crypto=require('crypto');const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');const R=path.resolve(__dirname,'..'),expected=JSON.parse(fs.readFileSync(R+'/records/expected-assets.json')),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
async function main(){
const all=['main','reasons','patterns','zone','crisis','misc','reused'].flatMap(g=>JSON.parse(fs.readFileSync(R+'/records/metadata-'+g+'.json')));if(all.length!==41||new Set(all.map(a=>a.id)).size!==41)throw Error('count');const checks=[],rows=[];
for(const e of expected){const a=all.find(x=>x.id===e.id);if(!a||a.file!==e.file)throw Error('missing '+e.id);const m=await sharp(R+'/'+a.file).metadata();if(m.width!==e.width||m.height!==e.height||m.channels!==4)throw Error('RGBA/dimensions '+e.id);const {data,info}=await sharp(R+'/'+a.file).raw().toBuffer({resolveWithObject:true});let zero=0,positive=0,edge=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const al=data[(y*info.width+x)*4+3];if(al===0)zero++;else{positive++;if(x===0||y===0||x===info.width-1||y===info.height-1)edge++;}}if(!zero||!positive)throw Error('empty/opaque '+e.id);if(e.group!=='patterns'&&edge)throw Error('clippedicon '+e.id+' '+edge);if(e.group!=='reused'&&!a.generationRecords.length)throw Error('noprovenance');for(const rec of a.generationRecords){if(!rec.prompt||!fs.existsSync(R+'/'+rec.rawFile))throw Error('rawmissing '+e.id);const rm=await sharp(R+'/'+rec.rawFile).metadata();rec.sourceImageDimensions={width:rm.width,height:rm.height};}
checks.push({id:e.id,width:m.width,height:m.height,channels:4,transparentPixels:zero,visiblePixels:positive,visibleEdgePixels:edge,sha256:hash(R+'/'+e.file)});
rows.push({asset_id:e.id,status:e.group==='reused'?'reused reference crop':'candidate',file:e.file,width:e.width,height:e.height,group:e.group,description:a.sceneDescription,history_notes:typeof a.historyNotes==='string'?a.historyNotes:JSON.stringify(a.historyNotes),sha256:hash(R+'/'+e.file),generation_records:JSON.stringify(a.generationRecords),processing:JSON.stringify(a.processing),qa:JSON.stringify(a.qa)});
}
const refs=fs.readdirSync(R+'/references').map(file=>({file,sha256:hash(R+'/references/'+file)}));for(const r of JSON.parse(fs.readFileSync(R+'/records/reference-hashes.json')))if(hash(R+'/references/'+r.file)!==r.sha256)throw Error('refchanged '+r.file);fs.writeFileSync(R+'/records/reference-hashes.json',JSON.stringify(refs,null,2));
for(const a of expected.filter(x=>x.group==='reused')){const meta=all.find(x=>x.id===a.id),[left,top,width,height]=meta.processing.crop;const source=await sharp(R+'/'+meta.processing.source).extract({left,top,width,height}).raw().toBuffer(),actual=await sharp(R+'/'+a.file).raw().toBuffer();if(!source.equals(actual))throw Error('seasonpixelschanged');}
const gray=await sharp(R+'/proofs/03-placement-colour-grayscale.png').extract({left:0,top:748,width:1280,height:700}).removeAlpha().raw().toBuffer();let unequal=0;for(let i=0;i<gray.length;i+=3)if(gray[i]!==gray[i+1]||gray[i]!==gray[i+2])unequal++;if(unequal)throw Error('notgray');
const patternQA=[];for(const id of ['pattern_ok','pattern_blocked_hatch','pattern_blocked_cross','pattern_service_range_edge']){const e=expected.find(x=>x.id===id),{data,info}=await sharp(R+'/'+e.file).raw().toBuffer({resolveWithObject:true});let pairs=0,errors=0;const shift=id==='pattern_service_range_edge'?16:8;for(let y=0;y<info.height;y++)for(let x=0;x<info.width-shift;x++){const inside=(xx)=>id==='pattern_service_range_edge'||Math.abs((xx+.5-info.width/2)/(info.width/2))+Math.abs((y+.5-info.height/2)/(info.height/2))<.8;if(!inside(x)||!inside(x+shift))continue;const a=data[(y*info.width+x)*4+3],b=data[(y*info.width+x+shift)*4+3];pairs++;if(a!==b)errors++;}patternQA.push({id,alphaPeriodX:shift,pairs,errors});if(errors)throw Error('nonperiodicpattern '+id+' '+errors);}
const proofs=fs.readdirSync(R+'/proofs').filter(x=>x.endsWith('.png')).sort();if(proofs.length!==3)throw Error('proofcount '+proofs.length);if(fs.readdirSync(R+'/assets',{recursive:true}).filter(x=>x.endsWith('.png')).length!==41)throw Error('assetcount');
fs.writeFileSync(R+'/records/technical-qa.json',JSON.stringify({assets:41,new:37,reused:4,proofs:3,checks,seasonPixelsIdentical:true,grayscaleRgbUnequalPixels:unequal,patternQA},null,2));fs.writeFileSync(R+'/records/asset-rows.json',JSON.stringify(rows,null,2));
fs.writeFileSync(R+'/IMAGE_LINKS.md','# Wave18 이미지\n\n'+proofs.map(f=>`- [${f}](proofs/${f})`).join('\n')+'\n\n'+rows.map(a=>`- [${a.asset_id}](${a.file})`).join('\n')+'\n');
fs.writeFileSync(R+'/index.html',`<!doctype html><html lang="ko"><meta charset="utf-8"><title>Wave18 후보</title><style>body{background:#d7c9a9;color:#453627;font:16px sans-serif;margin:24px}a{color:#59412b}main{display:flex;flex-wrap:wrap}article{width:250px;padding:16px;border:1px solid #887255}img{max-width:288px;image-rendering:auto}p{overflow-wrap:anywhere}</style><h1>Wave18 최소 HUD 후보</h1><p>신규37 + 계절재사용4. 게임 미설치.</p><p>${proofs.map(f=>`<a href="proofs/${f}">${f}</a>`).join(' · ')}</p><p><a href="README.md">설명</a> · <a href="검수표.md">검수표</a> · <a href="assets.csv">CSV</a></p><main>${rows.map(a=>`<article><a href="${a.file}"><img src="${a.file}" alt="${a.asset_id}"></a><p><a href="${a.file}">${a.asset_id}</a><br>${a.width}×${a.height}</p></article>`).join('')}</main></html>`);
console.log('PASS 41RGBA/crops/provenance/alpha/3proofs/grayscale/periodic',patternQA);
}main().catch(e=>{console.error(e);process.exitCode=1});
