import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=name=>JSON.parse(fs.readFileSync(path.join(root,'provenance',name),'utf8'));
const eventMap={wedding:'wedding',baptism:'baptism',pilgrimage:'pilgrimage',fair:'fair','plague-cart':'plague','plague-marker-brazier':'plague',sandbags:'flood',revolt:'revolt',relief:'famine','relief-distribution':'famine','bucket-brigade':'fire',muster:'levy','levy-departure':'levy',judgment:'judgment','court-judgment':'judgment','fire-flicker':'fire'};
const placement={wedding:'교회 앞/다리 뒤 도로의 빈 접지; 다리 난간과 겹치지 않음',baptism:'교회 출입구 바깥 공터; 보행 출입구 유지',pilgrimage:'교회로 향하는 길의 쉼터; 횡단도로 비움',fair:'시장 밖 넓은 평지; 천막 실제 alpha 점유 전체 확보',plague:'집 출입문 앞 길가; 기존 집/판자와 충돌 금지',flood:'하천변/잠긴 밭의 육지 경계; 방재 작업 접근로 확보',revolt:'시장-장원 공터; 무기와 사람을 건물 뒤에 감추지 않음',famine:'교회 앞 배급 장소; 구휼 줄과 빈 좌판의 이유가 함께 보이게 배치',fire:'불난 집 앞 길가; 물동이 접근로 유지',levy:'성문/도로 갈림의 넓은 집결지; 장궁·짐마차 출발로 확보',judgment:'법정/장원 앞 공터; 문서 낭독자와 듣는 군중을 구분'};
function inspect(file){const b=fs.readFileSync(path.join(root,file));if(b.toString('hex',0,8)!=='89504e470d0a1a0a')throw Error('not PNG '+file);return {width:b.readUInt32BE(16),height:b.readUInt32BE(20),sha256:crypto.createHash('sha256').update(b).digest('hex')};}
function reusedEvent(n){if(/longbow|levy/.test(n))return 'levy';if(/market|stall|cattle|sheep/.test(n))return /quiet|empty/.test(n)?'famine|marketday':'marketday';if(/priest/.test(n))return 'funeral|baptism';if(/funeral|bier|grave/.test(n))return 'funeral|plague';if(/royal|scroll/.test(n))return 'royalenvoy';if(/hungry/.test(n))return 'famine';if(/burnt|smoke|fire/.test(n))return 'fire';if(/plague/.test(n))return 'plague';if(/flood/.test(n))return 'flood';if(/crowd/.test(n))return 'judgment|revolt';return /cloak/.test(n)?'compatible-winter-walkers':'wedding|levy';}
const cartGeometry={"id":"handcart","url":"assets/runtime-actors-v1/cart_hand-v4.png","width":1774,"height":887,"sha256":"8b9101a008254bce9878a9791ffc9be06e90adb819393b71926f61acc3bd359e","active":true,"frames":[{"direction":"NE","gaitFrame":0,"source":{"x":39,"y":226,"width":397,"height":374},"foot":{"x":207.5,"y":600},"handles":{"x":384,"y":251}},{"direction":"SE","gaitFrame":0,"source":{"x":481,"y":243,"width":380,"height":368},"foot":{"x":702.5,"y":611},"handles":{"x":801,"y":585}},{"direction":"SW","gaitFrame":0,"source":{"x":908,"y":249,"width":385,"height":362},"foot":{"x":1068,"y":611},"handles":{"x":967,"y":585}},{"direction":"NW","gaitFrame":0,"source":{"x":1338,"y":227,"width":399,"height":373},"foot":{"x":1555.5,"y":600},"handles":{"x":1384,"y":251}}]};
const assets=[];
for(const a of read('reused-manifest.json').assets){const n=path.basename(a.file);const meta=a.renderMetadata??{};let pivot=meta.pivot??null,anchorKind=meta.pivot?.overlay?'original-house-canvas-origin':'source-render-anchor',rule='원본 등록 기준점과 배율 유지; 새 계절 그림으로 세지 않음';let frames=a.frames??meta.frames??1;
 if(a.perFrameAnchors){pivot=null;anchorKind='per-frame-foot';rule='74px cell의 방향/걸음별 foot 및 figureHeight 사용; sheet전체를 한 인물로 축소하지 않음';}
 if(/cloak/.test(n)){pivot=null;anchorKind='template-registered-layer';rule='동일한 원본 인물 템플릿의 같은74px 셀에 합성; 독립 땅 배치 금지; priest/new group 부적합';frames={columns:4,rows:2,count:8,cellWidth:74,cellHeight:74};}
 if(/held_longbow|scroll_royal/.test(n)){anchorKind='hand-prop-anchor';rule='해당방향의 손좌표에 합성; 땅에 세우는 독립 그림 아님';}
 if(/market_(active|quiet)/.test(n)){pivot=null;anchorKind='facility-source-crop';rule='원본source rect(35,50,1213,1146) 전체시설로 배치; displayWidth108; 발중앙을 임의추정하지 않음';}
 if(/cart_hand/.test(n)){pivot=null;anchorKind='per-direction-cart-source';rule='runtimeActorManifest의 방향별 source crop/foot 사용. 인물74px셀계약과 다름';}
 if(/empty_stall/.test(n))pivot={x:48,y:94};
 if(/cattle|sheep/.test(n))pivot={x:64,y:84};
 if(/fresh_graves/.test(n))pivot={x:64,y:32};
 if(n==='fire_small.png')pivot={x:24,y:64};if(n==='fire_large.png')pivot={x:48,y:96};
 assets.push({id:n.replace('.png',''),file:a.file,event:reusedEvent(n),type:a.perFrameAnchors?'walker-sheet':/cloak/.test(n)?'template-cloak':/longbow|scroll/.test(n)?'held-prop':meta.pivot?.overlay?'house-canvas-overlay':/smoke/.test(n)?'animated-fx':/cart_hand/.test(n)?'cart-direction-sheet':'world-sprite',season:'all',newArt:false,frames,footPivot:pivot,anchorKind,perFrameAnchors:a.perFrameAnchors??null,measuredGroundAnchors:a.measuredGroundAnchors??null,compatibleTemplates:a.compatibleTemplates??null,placementRule:rule,source:a.path,sourceMetadataReference:'provenance/reused-manifest.json',cartGeometry:/cart_hand/.test(n)?cartGeometry:null,...inspect(a.file)});
}
for(const source of ['ceremony.json','crisis.json','response.json']){const data=read(source),rows=Array.isArray(data)?data:data.assets;for(const a of rows){const base=a.id??a.event;const event=eventMap[base]??a.event??base;const file=a.file;assets.push({id:a.assetId??path.basename(file,'.png'),file,event,type:a.kind??a.type??'static-whole-group',season:a.season,newArt:true,frames:a.frames??1,footPivot:a.footPivot??a.pivot,anchorKind:'group-ground-anchor',adultHeightPx:a.adultHeightPx??null,adultHeightMeasurement:a.adultHeightMeasurement??a.measurement??a.measurementStatus??'not supplied',placementRule:a.placementRule??placement[event]??'독립 접지; 인물과 건물 충돌 방지',sourceMetadataReference:'provenance/'+source,...inspect(file)});}}
const flame=read('flame-generation.json');assets.push({id:'fire-flicker-all',file:flame.output,event:'fire',type:'animated-flame-sheet',season:'all',newArt:true,frames:{count:4,columns:4,rows:1,width:64,height:96,timingMs:100,timingStatus:'proposed'},footPivot:flame.pivot,anchorKind:'per-frame-ground-anchor',adultHeightPx:null,placementRule:'동일한64×96셀의(32,88)을 땅에 고정. 4프레임만 잘라 반복; 집 전체에 늘여붙이지 않음',sourceMetadataReference:'provenance/flame-generation.json',...inspect(flame.output)});
if(assets.length!==56)throw Error(`Expected56 assets, got${assets.length}`);if(new Set(assets.map(a=>a.file)).size!==56)throw Error('Duplicate files');
const output={status:'candidate-not-installed',counts:{total:56,new:assets.filter(a=>a.newArt).length,reused:assets.filter(a=>!a.newArt).length},rule:'all-season files are single originals, not duplicate summer/winter claims; null pivot means use named binding/per-frame geometry, not guessed center',assets};
fs.writeFileSync(path.join(root,'assets/manifest.json'),JSON.stringify(output,null,2)+'\n');const columns=['id','file','event','type','season','newArt','frames','width','height','footPivot','anchorKind','adultHeightPx','adultHeightMeasurement','placementRule','sourceMetadataReference','sha256'];const csv=v=>'"'+String(v===null||v===undefined?'':typeof v==='object'?JSON.stringify(v):v).replaceAll('"','""')+'"';fs.writeFileSync(path.join(root,'assets/manifest.csv'),'\ufeff'+columns.map(csv).join(',')+'\n'+assets.map(a=>columns.map(c=>csv(a[c])).join(',')).join('\n')+'\n');console.log(output.counts);
