import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const read=async p=>JSON.parse(await fs.readFile(path.join(root,p),'utf8'));
const summaries=[];let md='# 독립 눈가림 판독\n\n**최종 16/28 = 57.1%, 목표80% 미달.** 전체 장면 첫 추측과 실제 픽셀 크롭 뒤 추측을 분리했다. 최종 회차는 두 지표가 모두16/28이지만 일부 문항의 정오가 서로 바뀌었다.\n\n사건명·파일명을 가린 장면을 서로 독립된 새 모델 검수자에게 배정했다. 매 회차 줌1.0 담당과0.6 담당 각1명, 각14문항. 사건별 두 줌을 모두 포함하며 각 검수자에게 여름7/겨울7을 배정했다. 같은 사건의 같은 계절 두 줌을 한 사람이 비교한 시험은 아니다. 허용된14개 분류명과 unknown을 제공하되 답 중복을 허용했고, 한 종류씩 나온다고 추론하지 말라고 지시했다. 목표 점수는 검수자에게 주지 않았다.\n\n전체 도시1600×1000을 먼저 보고, 그 뒤 확대하지 않은1:1 상세 크롭을 확인했다. 크롭 후 수치는 위치 찾기 부담을 줄인 보조 판독이다. 사람을 크게 그린 확대판으로 점수를 얻지 않았다. AI 검수자 소표본이며 실제 플레이어 사용성 통계가 아니다.\n\n| 회차 | 줌 | 첫 추측 | 상세 후 | 비고 |\n|---|---:|---:|---:|---|\n';
const detailed=[];
for(const [round,letters,keyfile] of [['initial',['A','B'],'provenance/BLIND_KEY.json'],['final',['C','D'],'provenance/BLIND_FINAL_KEY.json']]){
 const key=await read(keyfile);for(const letter of letters){const results=await read(`proofs/blind/${letter}/RESULTS.json`);let initial=0,final=0;for(const x of results){const k=key.find(y=>y.id===x.id);const scene=await fs.readFile(path.join(root,`proofs/blind/${letter}/${x.id}-scene.jpg`));const detail=await fs.readFile(path.join(root,`proofs/blind/${letter}/${x.id}-detail.png`));const row={...k,...x,round,initialCorrect:k.event===x.initialGuess,finalCorrect:k.event===x.finalGuess,sceneSha256:crypto.createHash('sha256').update(scene).digest('hex'),detailSha256:crypto.createHash('sha256').update(detail).digest('hex')};initial+=Number(row.initialCorrect);final+=Number(row.finalCorrect);detailed.push(row);}summaries.push({round,reviewer:letter,zoom:letter==='A'||letter==='C'?1:.6,trials:results.length,initialCorrect:initial,finalCorrect:final});md+=`| ${round}/${letter} | ${letter==='A'||letter==='C'?1:.6} | ${initial}/14 (${(initial/14*100).toFixed(1)}%) | ${final}/14 (${(final/14*100).toFixed(1)}%) | ${round==='final'?'최종 그림, 새 검수자':'수정 전, 이전 그림 보존'} |\n`;}}
md+='\n## 수정과 해석\n\n첫 상세 후16/28(57.1%)에서 마지막도16/28이다. 첫 전체 장면13/28(46.4%)에서 최종16/28(57.1%)로 달라졌지만, 검수자도 달라져 이를 수정의 인과 효과라고 단정할 수 없다. 장례·순례는 간격과 이동 문맥을 바꿨고, 구휼 줄과 징집 수레는 접지 문제를 고쳤다. 유리한 문항만 골라 재시험한 합산 점수가 아니라 매번14종 모두 시험했다.\n\n- 줌0.6에서 세례·혼인·장례의 작은 소품과 의례 구별이 약하다. 무리가 보이는 것과 무슨 사건인지 아는 것은 다르다.\n- 구휼 줄이 다른 대기/법정 무리로, 정기시 천막이 구휼 천막으로 혼동된다.\n- 실제 이동 방향·행렬 간격·배급 동작·조종 소리·목적지 반응은 추후 엔진 연결에서 필요하며 이번 정지 합성으로 검증되지 않았다.\n- SCENE_VERDICT의82/100은 명칭을 알고 본 미술·배치 정성 점수다. 맞힘률이 아니다.\n\n## 문항별 원자료\n\n| ID | 회차 | 정답 | 첫 추측 | 상세 후 | 정오 | 원본 장면 ID |\n|---|---|---|---|---|---|---|\n';
for(const x of detailed)md+=`| ${x.id} | ${x.round} | ${x.event} | ${x.initialGuess} | ${x.finalGuess} | ${x.finalCorrect?'맞음':'틀림'} | ${x.source} |\n`;
md+='\n정확한 검수 발언은 proofs/blind/*/RESULTS.json, 익명 제공 문항은 TRIALS.json, 해시는 proofs/blind/SCORES.json에 있다. 경량 ZIP의 중복 이미지 대응은 ARCHIVE_MAP.json으로 확인한다. 최초 전달 때는 익명 파일만 열도록 제한했으며, 정답 키는 채점 때 공개했다.\n';
await fs.writeFile(path.join(root,'BLIND.md'),md);await fs.writeFile(path.join(root,'proofs/blind/SCORES.json'),JSON.stringify({targetPercent:80,finalPercent:100*16/28,targetMet:false,summaries,trials:detailed},null,2));
console.log(JSON.stringify(summaries));
