const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');
const root='/tmp/astra-wave17-work-20260926',out=path.join(root,'delivery'),src=path.join(root,'supplemental-wave13-candidates/astra-wave13-candidates-v1');
const generated='/Users/rexxa/Library/Application Support/orca/codex-accounts/54be5844-95fd-4c46-925c-75327ccd186a/home/generated_images/01a0d8ee-8426-70b2-8089-eb3216379177/exec-1aa16dc4-caca-4bd7-b96e-c1473fe08d0b.png';
for(const d of ['assets/herd','assets/animal_walk','assets/cart','assets/prop','checks','records/convoy','reference'])fs.mkdirSync(path.join(out,d),{recursive:true});
const copies=[['assets/animal_walk/ox-v1.png',path.join(src,'assets/animal_walk/ox-v1.png')],['assets/cart/ox_cart_body-v1.png',path.join(src,'assets/cart/ox_cart_body-v1.png')],['assets/prop/refugee_child_sheet-v1.png','/tmp/astra-wave9-work-20260925/delivery/assets/prop/leaving_child_sheet-v1.png']];
const hashes=[];for(const [dest,from]of copies){fs.copyFileSync(from,path.join(out,dest));hashes.push({file:dest,source:from,sha256:crypto.createHash('sha256').update(fs.readFileSync(from)).digest('hex'),method:'byte-copy'});}
fs.copyFileSync(generated,path.join(out,'records/convoy/cargo-ai-source.png'));
fs.copyFileSync(path.join(root,'records/convoy-prompts.json'),path.join(out,'records/convoy/prompts.json'));
function bbox(image,x,y,w,h){const c=createCanvas(w,h),ctx=c.getContext('2d');ctx.drawImage(image,x,y,w,h,0,0,w,h);const d=ctx.getImageData(0,0,w,h).data;let l=w,t=h,r=-1,b=-1;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)if(d[(yy*w+xx)*4+3]>20){l=Math.min(l,xx);r=Math.max(r,xx);t=Math.min(t,yy);b=Math.max(b,yy);}return{x:x+l,y:y+t,w:r-l+1,h:b-t+1};}
(async()=>{const raw=await loadImage(generated),cargo=createCanvas(512,192),cx=cargo.getContext('2d'),regs=[];for(let row=0;row<2;row++)for(let col=0;col<4;col++){const b=bbox(raw,col*raw.width/4,row*raw.height/2,raw.width/4,raw.height/2),s=Math.min(55/b.w,([54,48,48,54][col])/b.h),w=Math.round(b.w*s),h=Math.round(b.h*s),localX=Math.round(([44,44,84,84][col])-w/2),localY=[58,52,52,58][col]-h;cx.drawImage(raw,b.x,b.y,b.w,b.h,col*128+localX,row*96+localY,w,h);regs.push({direction:['NE','SE','SW','NW'][col],frame:row,source:b,destination:[localX,localY,w,h],cell:[128,96],method:'uniform-scale AI cargo crop; original cart pixels unchanged'});}
cx.putImageData(cx.getImageData(0,0,512,96),0,96);
for(let col=0;col<4;col++)regs[col+4]={...regs[col],frame:1,method:'exact RGBA copy of same direction frame0; static cargo and flag'};
fs.writeFileSync(path.join(out,'assets/herd/wool_sack_convoy-v1.png'),cargo.toBuffer('image/png'));
const ox=await loadImage(path.join(out,'assets/animal_walk/ox-v1.png')),cart=await loadImage(path.join(out,'assets/cart/ox_cart_body-v1.png')),driver=await loadImage(path.join(root,'astra-wave17-reference-files/actor_civilian_man-v1.png'));
const anchors=JSON.parse(fs.readFileSync(path.join(src,'records/carts/layer-anchors.json'))).filter(x=>x.kind==='ox').map(({loadOrigin,loadFile,loadPixelScale,...a})=>({...a,newCargoOrigin:[0,0],newCargoFile:'assets/herd/wool_sack_convoy-v1.png',newCargoPixelScale:1,occlusion:'cart then animal then original near-shaft clipped polygon then cargo registered at local0,0; no additional historical load offset'}));
const proof=createCanvas(1200,660),p=proof.getContext('2d');p.fillStyle='#d8d3bd';p.fillRect(0,0,1200,660);p.fillStyle='#292922';p.font='20px sans-serif';p.fillText('WAVE17 CANDIDATE — separate cart / ox / driver / cargo, display scale 1.45x',22,28);
for(let row=0;row<2;row++)for(let col=0;col<4;col++){const anchor=anchors[col],tx=col*300+50,ty=row*300+145;p.save();p.translate(tx,ty);p.scale(1.45,1.45);p.drawImage(cart,col*128,row*96,128,96,0,0,128,96);p.drawImage(ox,col*96,row*74,96,74,...anchor.animalOrigin,96,74);p.save();p.beginPath();anchor.nearShaftPolygon.forEach((q,i)=>i?p.lineTo(...q):p.moveTo(...q));p.closePath();p.clip();p.drawImage(cart,col*128,row*96,128,96,0,0,128,96);p.restore();p.drawImage(cargo,col*128,row*96,128,96,0,0,128,96);const dp=[[-8,-26],[-12,37],[97,34],[114,-24]][col];p.drawImage(driver,col*driver.width/4,row*driver.height/2,driver.width/4,driver.height/2,...dp,44,44);p.restore();p.fillStyle='#292922';p.font='16px sans-serif';p.fillText(anchor.direction+' frame '+row,col*300+20,row*300+68);}
fs.writeFileSync(path.join(out,'checks/convoy-directions-phases.png'),proof.toBuffer('image/png'));
fs.writeFileSync(path.join(out,'records/convoy/assembly.json'),JSON.stringify({status:'candidate',directions:['NE','SE','SW','NW'],frames:2,cargoRegistration:regs,layerAnchors:anchors,driverSource:'astra-wave17-reference-files/actor_civilian_man-v1.png',driverCellDisplay:[44,44],driverOrigins:[[-8,-26],[-12,37],[97,34],[114,-24]],proofScale:1.45,proofNote:'Reference composition only. Original cart and ox preserved byte-for-byte; no claim of independent runtime animation validation. Original cart frames preserve Wave13 wheel changes; cargo frames are exact static copies.',copies:hashes},null,2));})();
