const fs=require('fs'),crypto=require('crypto');
const {createCanvas,loadImage}=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const dir=__dirname,out='/tmp/astra-wave39-candidates-20260930/assets';
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{let rows=[];let board=createCanvas(940,12*100+40),b=board.getContext('2d');b.fillStyle='#626553';b.fillRect(0,0,board.width,board.height);b.font='16px sans-serif';
for(const [n,j]of JSON.parse(fs.readFileSync(dir+'/jobs.json')).entries()){
const im=await loadImage(j.sourcePath),cv=createCanvas(im.width,im.height),c=cv.getContext('2d');c.drawImage(im,0,0);const d=c.getImageData(0,0,im.width,im.height).data;
let cols=[];for(let x=0;x<im.width;x++){let cnt=0;for(let y=0;y<im.height;y++)if(d[(y*im.width+x)*4+3]>32)cnt++;cols[x]=cnt>2;}
let runs=[];for(let x=0;x<cols.length;x++){if(!cols[x])continue;let a=x;while(x+1<cols.length&&cols[x+1])x++;if(x-a>8)runs.push([a,x]);}
if(runs.length!==6)throw Error(j.assetId+' runs '+JSON.stringify(runs));
let boxes=runs.map(([a,z])=>{let y0=im.height,y1=0;for(let x=a;x<=z;x++)for(let y=0;y<im.height;y++)if(d[(y*im.width+x)*4+3]>16){y0=Math.min(y0,y);y1=Math.max(y1,y);}return {x:a-2,y:y0-2,w:z-a+5,h:y1-y0+5};});
let scale=10/Math.max(...boxes.flatMap(q=>[q.w,q.h]));let dest=createCanvas(96,16),ctx=dest.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';
for(let f=0;f<6;f++){let q=boxes[f];ctx.drawImage(im,q.x,q.y,q.w,q.h,f*16+8-q.w*scale/2,8-q.h*scale/2,q.w*scale,q.h*scale);}
let file=out+'/'+j.assetId+'.png';fs.mkdirSync(require('path').dirname(file),{recursive:true});fs.writeFileSync(file,dest.toBuffer('image/png'));
let frameHashes=[],bounds=[];for(let f=0;f<6;f++){let raw=ctx.getImageData(f*16,0,16,16).data;frameHashes.push(crypto.createHash('sha256').update(raw).digest('hex'));let x0=16,y0=16,x1=-1,y1=-1;for(let y=0;y<16;y++)for(let x=0;x<16;x++)if(raw[(y*16+x)*4+3]>8){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}bounds.push([x0,y0,x1,y1]);}
let refs=['falling_leaves_sheet-v1.png','Wave28_계절.jpg'].map(name=>{let path='/tmp/astra-wave39-work-20260930/astra-wave39-reference-files/'+name;return{filename:name,path,sha256:hash(path)}});
rows.push({...j,outputPath:file,outputHash:hash(file),sourceHash:hash(j.sourcePath),references:refs,tool:'native image_gen.imagegen',model:'not exposed by tool',generationDate:'2026-09-30',width:96,height:16,frameWidth:16,frameHeight:16,frames:6,frameCount:6,pivot:[8,8],recommendedAlpha:0.9,recommendedSpeed:14,worldPixelsPerSecond:14,windTilt:20,lifetime:4,depth:'tree canopy emitter to world ground; depth sorted at particle world position',lifecycle:'emit within matching tree crown, flutter 6 frames at 8fps loop, descend 14 world-px/s, stop at ground; deposited leaf rendered separately',status:'candidate',candidateCount:1,selectionReason:'Six distinct width-changing flutter views with species-shaped broadside frames and low-saturation seasonal tones',manualEdits:'Mechanical alpha-bound six-run extraction; one common uniform scale across six frames; centered each bounding box on (8,8); packed horizontal 96x16 RGBA. No recoloring or drawn replacement art.',normalization:{sourceDimensions:[im.width,im.height],sourceBoxes:boxes,uniformScale:scale},validation:{distinctFrames:new Set(frameHashes).size,frameHashes,alphaBounds:bounds},visualCaveat:'At zoom0.6 each leaf is only about6px; species lobes are clearest in broadside frames and on enlarged QA, not all edge-on frames.'});
b.fillStyle='#eee9d9';b.fillText(j.assetId,10,n*100+23);b.imageSmoothingEnabled=false;b.drawImage(dest,300,n*100+10,576,96);b.imageSmoothingEnabled=true;b.drawImage(dest,10,n*100+45);}
fs.writeFileSync(dir+'/manifest.json',JSON.stringify(rows,null,2));fs.writeFileSync(dir+'/qa-contact.png',board.toBuffer('image/png'));console.log(JSON.stringify(rows.map(r=>({id:r.assetId,distinct:r.validation.distinctFrames,bounds:r.validation.alphaBounds}))));})();
