// LM-R2 (estates area): the lord screen's 영지 words — the portfolio cards, the oversight, the attention, the audit, the
// season summaries. Engine enums are keyed here (the estates' holders, pieces and kinds are module-private in
// src/content/historyCopy.ko.ts; switch to its tables once they are exported: docs/requests/engine-lmr2-seen-and-reads.md).
import type { EstateKind, PossessionLoss, RightPieceKind } from "../../../engine/estates.types";
import type { EstatePetition, OversightMode, StewardDisposition } from "../../../engine/stewardship.types";

export const ESTATES_COPY = {
  region: "영지 포트폴리오",
  heading: "당신의 이름 아래",
  intro: "직할과 위임을 나누고, 권원과 점유를 따로 살핍니다.",
  shut: "아직 영지의 장부가 없습니다",
  homeName: (house: string) => `${house} 가문의 본영`,
  /** The portfolio's top line. */
  totals: { estates: "보유 영지", value: "연간 가치", attention: "직접 주의력", audit: "다음 감사" },
  estateCount: (count: number) => `${count}곳`,
  attentionLine: (load: number, capacity: number) => `${load} / ${capacity}`,
  untilAudit: (days: number) => `감사까지 ${days}일`,
  noAudit: "감사할 영지 없음",
  cardsLabel: "영지 카드",
  cardChoose: (name: string) => `${name} 영지 살피기`,
  kinds: { manor: "장원", market_town: "시장 마을", mill_estate: "방앗간 영지", fishery: "어장 영지" } satisfies Record<EstateKind, string>,
  standing: { direct: "직할", delegated: "위임", neighbour: "이웃 영지" } as const,
  homeStanding: "본영 · 직할",
  manors: (count: number) => `장원 ${count}곳`,
  annualValue: "연간 가치",
  title: "권원",
  possessor: "점유",
  lifeTenant: "종신 보유",
  remainder: "잔여권",
  burdens: "부담",
  burdensLine: (debt: string, rent: string, repairs: string) => `빚 ${debt} · 지대 부담 ${rent} · 수리 ${repairs}`,
  noBurdens: "부담 없음",
  pieces: "권리 조각",
  pieceKinds: { land_rent: "토지 지대", manor_court: "장원 법정", mill: "방앗간 사용료", market: "시장 좌판세", tolls: "통행세", fishery: "어업권",
    advowson: "성직자 추천권", hunting: "사냥권" } satisfies Record<RightPieceKind, string>,
  pieceHolders: (title: string, possessor: string) => title === possessor ? title : `${title} / ${possessor}`,
  losses: { suspended: "상위 영주가 맡아 둠", seized: "빼앗김", forced: "힘으로 빼앗김", held_against_judgment: "판결에도 버팀" } satisfies Record<PossessionLoss, string>,
  scope: (permille: number) => `판결 범위 ${Math.round(permille / 10)}%`,
  grantsHeading: (count: number) => `특허 이양 ${count}건`,
  titlePossessor: "권원 / 점유",
  grantLine: (piece: string, holder: string, year: number) => `${piece} → ${holder} (${year}년부터)`,
  grantNoPiece: "권리",
  claims: "걸린 청구",
  claimsCount: (count: number) => count === 0 ? "없음" : `${count}건`,
  /** The holders (historyCopy's HOLDER_KO words, with the faction and house names where the game has them). */
  holders: { lord: "영주", overlord: "상위 영주", crown: "국왕", merchants: "상인들", townsfolk: "주민들", bishop: "주교", commons: "평민" } as Readonly<Record<string, string>>,
  lordHolder: (house: string) => `영주(${house} 가문)`,
  personHolder: "옛 가문의 친족",
  estateHolder: "이웃 영주",
  houseHolder: (name: string) => `${name} 가문`,
  integrated: "점유를 얻어 영주의 땅이 됨",
  /** Oversight (SW-2, SW-3). */
  oversightHeading: "관리",
  modes: { direct: "직접 관리", steward: "청지기에게 위임" } satisfies Record<OversightMode, string>,
  modeChoose: (mode: string) => `관리 방식: ${mode}`,
  receiver: "수납인",
  steward: "청지기",
  stewardNone: "맡은 사람 없음",
  candidates: "청지기 후보",
  candidateLine: (ability: number, loyalty: number) => `관리 ${ability} · 충성 ${loyalty}`,
  dispositions: { merchant: "상인 친화", peasant: "농민 친화", greedy: "제 잇속" } satisfies Record<StewardDisposition, string>,
  connection: (name: string) => `연줄: ${name}`,
  noConnection: "연줄 없음",
  connections: { merchant_house_1: "상인 가문", commons: "평민", overlord: "상위 영주", bishop: "주교" } as Readonly<Record<string, string>>,
  keeperName: (office: string, name: string) => `${office} ${name}`,
  appoint: "청지기로 세우기",
  appointReceiver: "수납인으로 세우기",
  appointLabel: (name: string, estate: string, office: string) => `${name}을(를) ${estate} 영지의 ${office}(으)로 세우기`,
  /** SW-1 attention. */
  attentionHeading: "주의력",
  attentionBar: (load: number, capacity: number) => `직접 돌보는 영지 ${load} / 한도 ${capacity}`,
  overloaded: "주의력 초과: 직할 영지의 청원이 한 철 늦고 장부가 더 틀립니다",
  attentionReasons: { base: "기본", heir: "다 자란 상속자", age: "나이 또는 후견", visit: "감사 방문 뒤 한 해" } as const,
  reasonValue: (value: number) => `${value > 0 ? "+" : "−"}${Math.abs(value)}`,
  /** SW-5 exception rules. */
  rulesHeading: "영주에게 올릴 일",
  rulesIntro: "청지기는 이 조건에 맞는 청원을 영주에게 가져옵니다.",
  ruleAmount: (money: string) => `${money} 이상 드는 일`,
  ruleAmountOff: "금액으로는 올리지 않음",
  ruleAmountLess: "기준 금액 낮추기",
  ruleAmountMore: "기준 금액 높이기",
  ruleAmountToggle: "금액 기준",
  minus: "−",
  plus: "+",
  ruleRights: "권리가 바뀌는 일",
  ruleMarriage: "혼인에 관한 일",
  ruleRecurring: "전에 답한 종류도 다시",
  /** SW-6 audit. */
  auditHeading: "미가엘 축일 감사",
  auditModes: { accounts: "장부 감사", visit: "현지 방문" } as const,
  auditModeChoose: (mode: string) => `감사 방식: ${mode}`,
  visitCost: "현지 방문은 한 해 동안 주의력을 1 줄입니다",
  lastAudit: "지난 감사",
  noAuditYet: "아직 감사 없음",
  auditStatus: { clean: "깨끗함", pending: "감사 대기", punished: "처벌함", replaced: "갈아치움", tolerated: "눈감아 줌" } as const,
  auditLine: (year: number, mode: string, status: string) => `${year}년 ${mode} · ${status}`,
  auditFound: (kept: string, errors: string) => `찾은 빼돌림 ${kept} · 드러난 오류 ${errors}`,
  auditPending: "감사 대기",
  auditPendingLine: (steward: string, kept: string, days: number) => `${steward}의 장부에서 ${kept}을 찾았습니다 · 답할 날 ${days}일 남음`,
  /** SW-7 the season summaries. */
  summaryHeading: "철 요약",
  summaryNone: "아직 지난 철이 없습니다",
  seasons: ["봄", "여름", "가을", "겨울"] as readonly string[],
  summarySeason: (year: number, season: string) => `${year}년 ${season}`,
  summaryCols: { season: "철", mode: "관리", reported: "장부상 수입", rates: "지대·시장세", goodwill: "농민·상인 마음", petitions: "청원" },
  summaryHidden: "빼돌린 몫과 장부 오류는 감사에서 드러납니다.",
  rates: (rent: number, dues: number) => `${Math.round(rent / 10)}% · ${Math.round(dues / 10)}%`,
  goodwill: (tenants: number, merchants: number) => `${tenants} · ${merchants}`,
  summaryOverloaded: "주의력 초과",
  summaryPetitions: (count: number) => `청원 ${count}`,
  /** SW-4 petitions (answered on the lead's decision cards). */
  petitionsHeading: "영주에게 온 영지 청원",
  petitionsNone: "기다리는 청원 없음",
  petitionKinds: { rent_relief: "지대 감면", market_dues: "시장세", repair: "수리", common_dispute: "공유지 다툼", charter_request: "특허 요청",
    marriage_licence: "혼인 허가", boundary_dispute: "경계 다툼", mill_suit: "방앗간 의무", heriot: "상속세", merchet: "혼인세", ale_fines: "에일 벌금",
    road_bridge: "길과 다리", stall_dispute: "좌판 다툼", wardship: "후견", common_pasture: "공유 목초지", newcomer: "새 정착민", pannage: "돼지 방목",
    chancel_repair: "성단소 수리" } satisfies Record<EstatePetition["kind"], string>,
  petitionLine: (estate: string, kind: string, money: string, days: number) => `${estate} · ${kind} · ${money} · ${days}일 남음`,
  /** The estate cards' office icons (the receiver of a direct estate, the steward of a delegated one). */
  offices: { receiver: "수납인", steward: "청지기" } as const,
} as const;
