import sharp from '/Users/rexxa/.npm/_npx/8b377f6eec906bc4/node_modules/sharp/lib/index.js';
import fs from 'node:fs/promises';import crypto from 'node:crypto';
const W='/tmp/astra-wave20-snow-v4',D=W+'/delivery',P='/tmp/astra-wave20-rework-20260927/delivery';
const g=JSON.parse(await fs.readFile('/tmp/astra-wave20-work-20260926/records/geometry-contract.json')).houses;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const rows=[];
for(const era of [1350,1400])for(const l of [2,3,4]){const name=`roof_snow_l${l}_${era}-v4.png`,src=W+`/${era}/${name}`,b=await fs.readFile(src);await fs.writeFile(D+'/assets/overlays/'+name,b);const m=await sharp(b).metadata();if(m.width!==g[l].canvas[0]||m.height!==g[l].canvas[1])throw Error('Canvas mismatch '+name);rows.push({id:name.slice(0,-4),file:'assets/overlays/'+name,status:'candidate',level:l,era,variants:'a;b',width:m.width,height:m.height,pivot_x:g[l].runtimeDerivedNativeAnchor[0],pivot_y:g[l].runtimeDerivedNativeAnchor[1],native_to_world_scale:g[l].nativeToWorldScale,offset_x:0,offset_y:0,overlay_scale:1,sha256:sha(b)});}
const labels=['1300 reference','1350 a','1350 b','1400 a','1400 b'];
for(const zoom of [1,.6]){const width=760,height=455,comps=[];let txt=`<text x="18" y="28" font-size="19">WAVE 20 WINTER | game zoom ${zoom.toFixed(1)}</text><text x="18" y="48" font-size="11">100% display: native asset scale approx. ${(zoom*.5).toFixed(2)} | identical pivots and house PNGs</text>`;
for(let c=0;c<5;c++)txt+=`<text x="${40+145*c}" y="80" font-size="12">${labels[c]}</text>`;
for(const l of [2,3,4]){const ground=186+(l-2)*117;txt+=`<text x="12" y="${ground-20}" font-size="12">L${l}</text>`;for(let c=0;c<5;c++){const era=c===0?1300:c<3?1350:1400,v=c===1||c===3?'a':'b',h=c===0?P+`/references/houses/house_l${l}-v2.png`:P+`/assets/houses/house_l${l}_${era}_${v}-v2.png`,o=c===0?P+`/references/overlays/roof_snow_l${l}-v2.png`:D+`/assets/overlays/roof_snow_l${l}_${era}-v4.png`;const hb=await fs.readFile(h),ob=await fs.readFile(o);await fs.writeFile(D+'/references/'+h.split('/').at(-1),hb);if(c===0)await fs.writeFile(D+'/references/'+o.split('/').at(-1),ob);const scale=g[l].nativeToWorldScale*zoom,size=Math.round(g[l].canvas[0]*scale),base=await sharp(hb).composite([{input:ob}]).png().toBuffer();comps.push({input:await sharp(base).resize(size,size).png().toBuffer(),left:Math.round(90+c*145-g[l].runtimeDerivedNativeAnchor[0]*scale),top:Math.round(ground-g[l].runtimeDerivedNativeAnchor[1]*scale)});}}
const svg=Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><g fill="#f2f2ec" font-family="Arial,sans-serif">${txt}</g></svg>`);await sharp({create:{width,height,channels:4,background:'#747e79'}}).composite([{input:svg},...comps]).png().toFile(D+`/proofs/winter_three_eras_zoom_${zoom===1?'10':'06'}.png`);}
const keys=Object.keys(rows[0]),cell=v=>'"'+String(v??'').replaceAll('"','""')+'"';await fs.writeFile(D+'/assets.csv','\ufeff'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n')+'\r\n');
await fs.writeFile(D+'/qa/asset-metadata.json',JSON.stringify(rows,null,2));console.log('six assets, two winter proof sheets, CSV written');
