import sharp from '/Users/rexxa/.npm/_npx/8b377f6eec906bc4/node_modules/sharp/lib/index.js';import fs from 'node:fs/promises';import crypto from 'node:crypto';
const W='/tmp/astra-wave20-snow-v4',D=W+'/delivery',P='/tmp/astra-wave20-rework-20260927/delivery',hash=async p=>crypto.createHash('sha256').update(await fs.readFile(p)).digest('hex');
const checks=[],check=(name,pass,detail)=>{checks.push({name,pass,detail});};
const rows=JSON.parse(await fs.readFile(D+'/qa/asset-metadata.json'));
check('exactly six snow overlays',rows.length===6);
for(const r of rows){const p=D+'/'+r.file,{data,info}=await sharp(p).ensureAlpha().raw().toBuffer({resolveWithObject:true});check(r.id+' dimensions',info.width===r.width&&info.height===r.height);let border=0,nonzero=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const a=data[(y*info.width+x)*4+3];if(a)nonzero++;if((!x||!y||x===info.width-1||y===info.height-1)&&a)border++;}check(r.id+' transparent margins',border===0,{border,nonzero});check(r.id+' SHA',await hash(p)===r.sha256);for(const v of ['a','b']){const f=`house_l${r.level}_${r.era}_${v}-v2.png`;check(f+' unchanged reference',await hash(D+'/references/'+f)===await hash(P+'/assets/houses/'+f));}}
for(const folder of ['houses','overlays'])for(const f of await fs.readdir(P+'/assets/'+folder)){if(folder==='overlays'&&!f.startsWith('boarded'))continue;const p=P+'/assets/'+folder+'/'+f;const expected=(await fs.readFile(P+'/SHA256SUMS.txt','utf8')).split('\n').find(line=>line.slice(66)==='assets/'+folder+'/'+f)?.slice(0,64);check('preserved_source/'+folder+'/'+f,await hash(p)===expected,{sha256:await hash(p)});}
for(const zoom of ['10','06']){const m=await sharp(D+`/proofs/winter_three_eras_zoom_${zoom}.png`).metadata();check('proof '+zoom,m.width===760&&m.height===455);}
const failed=checks.filter(x=>!x.pass),report={checks,passed:checks.length-failed.length,failed};await fs.writeFile(D+'/qa/validation.json',JSON.stringify(report,null,2));console.log({passed:report.passed,failed});if(failed.length)process.exitCode=1;
