const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const {createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');
const base=path.resolve(__dirname,'..'),dir=path.join(base,'assets/heraldry');
const raw=async f=>(await sharp(f).ensureAlpha().raw().toBuffer());
let seed=140926;function rng(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const shields=['heater','rounded','knightly'],parts=['per_pale','per_fess','per_bend','per_bend_sinister','per_chevron','quarterly','per_saltire','per_pale_indented','barry','paly'];
const colors=[[115,39,36],[33,66,97],[39,79,59],[70,47,79],[38,40,42]],metals=[[224,186,90],[234,229,207]];
(async()=>{let chargeDir=process.argv[2];if(!chargeDir)throw Error('charge dir required');let charges=fs.readdirSync(chargeDir).filter(x=>x.endsWith('.png')).sort();if(charges.length!==12)throw Error('Expected12charges');
fs.mkdirSync(path.join(__dirname,'heraldry-composites'),{recursive:true});const order=shuffle(Array.from({length:24},(_,i)=>i)),manifest=[],pngs=[];let seamMax=0,outsideAlphaPixels=0,neutralFringePixels=0;
const texture=await raw(path.join(dir,'shield_surface_texture.png')),chiefMask=await raw(path.join(dir,'ordinary_chief.png'));
for(let n=0;n<24;n++){let v=order[n],sk=shields[v%3],pk=parts[(v*7)%10];let s=await raw(path.join(dir,`shield_${sk}.png`)),p=await raw(path.join(dir,`partition_${pk}.png`));let charge=await sharp(path.join(chargeDir,charges[v%12])).resize(116,116,{fit:'contain'}).extend({left:70,right:70,top:77,bottom:63,background:{r:0,g:0,b:0,alpha:0}}).ensureAlpha().raw().toBuffer();let c1=colors[v%5],c2=colors[(v+2)%5],metal=metals[Math.floor(v/3)%2],chief=v%4===0;let out=Buffer.alloc(256*256*4);
for(let i=0;i<out.length;i+=4){let a=s[i+3]/255,fill=a*s[i]/255,outline=a-fill,m=p[i+3]/255;let ca=charge[i+3]/255;let y=Math.floor(i/4/256);let chiefCoverage=chief?chiefMask[i+3]/255:0;let partitionColor=c1.map((c,k)=>c*(1-m)+c2[k]*m);let surface=partitionColor.map((c,k)=>c*(1-ca)+metal[k]*ca);if(chiefCoverage)surface=surface.map((c,k)=>c*(1-chiefCoverage)+metal[k]*chiefCoverage);let ta=texture[i+3]/255;surface=surface.map(c=>c*(1-ta)+texture[i]*ta);
for(let k=0;k<3;k++)out[i+k]=a?Math.round((surface[k]*fill+18*outline)/a):0;out[i+3]=s[i+3];seamMax=Math.max(seamMax,Math.abs(fill*m+fill*(1-m)-fill));if(!a&&out[i+3])outsideAlphaPixels++;if(a>0&&fill===0&&out[i]>18)neutralFringePixels++;}
let buf=await sharp(out,{raw:{width:256,height:256,channels:4}}).png().toBuffer();pngs.push(buf);fs.writeFileSync(path.join(__dirname,'heraldry-composites',`${String(n+1).padStart(2,'0')}.png`),buf);manifest.push({index:n+1,shield:sk,partition:pk,charge:charges[v%12],fieldColors:[c1,c2],chargeMetal:metal,ordinary:chief?'chief':null,sha256:crypto.createHash('sha256').update(buf).digest('hex')});}
fs.writeFileSync(path.join(__dirname,'ui-lord-heraldry.png'),pngs[0]);const canvas=createCanvas(1728,1880),ctx=canvas.getContext('2d');ctx.fillStyle='#e6dcc5';ctx.fillRect(0,0,1728,1880);ctx.fillStyle='#30281e';ctx.font='bold 28px sans-serif';ctx.fillText('HERALDRY 24  /  256px + 96px  /  seed 140926',24,40);ctx.font='17px sans-serif';ctx.fillText('Invented combinations · dark color fields / metal charges · no historical arms reference',24,69);
for(let n=0;n<24;n++){let x=24+(n%6)*284,y=96+Math.floor(n/6)*442;ctx.fillStyle=n%2?'#292b2a':'#faf5e9';ctx.fillRect(x,y,272,416);let im=await loadImage(pngs[n]);ctx.drawImage(im,x+8,y+8);ctx.drawImage(im,x+16,y+282,96,96);ctx.fillStyle=n%2?'#efe4cd':'#34291b';ctx.font='16px sans-serif';ctx.fillText(String(n+1).padStart(2,'0'),x+126,y+320);ctx.font='12px sans-serif';ctx.fillText(manifest[n].partition,x+118,y+344);}
fs.writeFileSync(path.join(base,'proofs/01-heraldry-combinations.png'),canvas.toBuffer('image/png'));fs.writeFileSync(path.join(__dirname,'heraldry-combinations.json'),JSON.stringify({seed:140926,count:24,uniqueHashes:new Set(manifest.map(m=>m.sha256)).size,combinations:manifest},null,2));fs.writeFileSync(path.join(__dirname,'heraldry-qa.json'),JSON.stringify({coverageSeamMaxError:seamMax,outsideAlphaPixels,neutralFringePixels,uniqueCombos:new Set(manifest.map(m=>m.sha256)).size,tinctureRule:'two color-class field partitions, metal-class charges; optional metal chief separated spatially from charge',historical:'No real family source used. Invented seeded combinations, not exhaustive collision audit of all historic arms.',texture:'Generated transparent scuff layer, grayscale and opacity0.13',visual:{status:'pass',distinct:'24/24 at256 and96',seams:'No visible seams or bright halos at256',detail:'Eagle feathers/wheat grain reduce at96 but silhouettes remain distinct',ordinaryMatrix:'8ordinary by3shields checked'}},null,2));console.log('proofready');})();
