// Generated by scripts/installEndings.py — the campaign's six ending paintings (INSTALL-33, INBOX-2s): one per
// LegacyEndingId (a missing ending fails the type check), shipped as the received 1920 × 1080 JPEGs
// (scripts/keyartDerivatives.ts, format jpeg-received); `source` is the received file in assets-inbox.
import type { LegacyEndingId } from "../content/legacyConfig";

export type EndingImage = Readonly<{ url: string; width: number; height: number; assetId: string; source: string }>;

export const ENDING_IMAGES = {
  free_borough: {"url": "assets/endings/campaign_ending_self_governing_city-v1.jpg", "width": 1920, "height": 1080, "assetId": "campaign_ending_self_governing_city-v1", "source": "assets-inbox/endings-manors/candidates-20260930/assets/endings/campaign_ending_self_governing_city-v1.jpg"},
  house_remembered: {"url": "assets/endings/campaign_ending_remembered_lineage-v1.jpg", "width": 1920, "height": 1080, "assetId": "campaign_ending_remembered_lineage-v1", "source": "assets-inbox/endings-manors/candidates-20260930/assets/endings/campaign_ending_remembered_lineage-v1.jpg"},
  merchants_chantry: {"url": "assets/endings/campaign_ending_merchants_chantry-v1.jpg", "width": 1920, "height": 1080, "assetId": "campaign_ending_merchants_chantry-v1", "source": "assets-inbox/endings-manors/candidates-20260930/assets/endings/campaign_ending_merchants_chantry-v1.jpg"},
  house_seat: {"url": "assets/endings/campaign_ending_family_city-v1.jpg", "width": 1920, "height": 1080, "assetId": "campaign_ending_family_city-v1", "source": "assets-inbox/endings-manors/candidates-20260930/assets/endings/campaign_ending_family_city-v1.jpg"},
  lords_town: {"url": "assets/endings/campaign_ending_lords_city-v1.jpg", "width": 1920, "height": 1080, "assetId": "campaign_ending_lords_city-v1", "source": "assets-inbox/endings-manors/candidates-20260930/assets/endings/campaign_ending_lords_city-v1.jpg"},
  pilgrim_town: {"url": "assets/endings/campaign_ending_pilgrims_city-v1.jpg", "width": 1920, "height": 1080, "assetId": "campaign_ending_pilgrims_city-v1", "source": "assets-inbox/endings-manors/candidates-20260930/assets/endings/campaign_ending_pilgrims_city-v1.jpg"},
} as const satisfies Readonly<Record<LegacyEndingId, EndingImage>>;
