// Generated by scripts/installUiArt.py from assets-inbox/ui-p0 (UX-2). Do not edit by hand.
// Frames: 9-slice insets in source pixels (sourceScale 2 = drawn at half size, 1:1 on a DPR 2 screen).
// Icon sheets: 96 px cells in `cells` order; `sizes` holds the per-cell Lanczos copies (1x / 2x per CSS size).
export const UI_ART_MANIFEST = {
 "cursors": {
  "cursor_inspect": {
   "hotspot": [
    4,
    3
   ],
   "x1": {
    "url": "assets/ui-p0/cursors/cursor_inspect-32.png"
   },
   "x2": {
    "url": "assets/ui-p0/cursor_inspect.png"
   }
  },
  "cursor_place_invalid": {
   "hotspot": [
    3,
    3
   ],
   "x1": {
    "url": "assets/ui-p0/cursors/cursor_place_invalid-32.png"
   },
   "x2": {
    "url": "assets/ui-p0/cursor_place_invalid.png"
   }
  },
  "cursor_place_valid": {
   "hotspot": [
    3,
    4
   ],
   "x1": {
    "url": "assets/ui-p0/cursors/cursor_place_valid-32.png"
   },
   "x2": {
    "url": "assets/ui-p0/cursor_place_valid.png"
   }
  },
  "cursor_road_draw": {
   "hotspot": [
    3,
    4
   ],
   "x1": {
    "url": "assets/ui-p0/cursors/cursor_road_draw-32.png"
   },
   "x2": {
    "url": "assets/ui-p0/cursor_road_draw.png"
   }
  },
  "cursor_select": {
   "hotspot": [
    4,
    3
   ],
   "x1": {
    "url": "assets/ui-p0/cursors/cursor_select-32.png"
   },
   "x2": {
    "url": "assets/ui-p0/cursor_select.png"
   }
  },
  "cursor_zone_brush": {
   "hotspot": [
    4,
    3
   ],
   "x1": {
    "url": "assets/ui-p0/cursors/cursor_zone_brush-32.png"
   },
   "x2": {
    "url": "assets/ui-p0/cursor_zone_brush.png"
   }
  }
 },
 "frames": {
  "banner_unlock": {
   "height": 128,
   "slice": {
    "bottom": 48,
    "left": 48,
    "right": 48,
    "top": 48
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/banner_unlock.png",
   "width": 800
  },
  "button_icon_square_base": {
   "height": 72,
   "slice": {
    "bottom": 10,
    "left": 10,
    "right": 10,
    "top": 10
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/button_icon_square_base.png",
   "width": 72
  },
  "button_primary_base": {
   "height": 72,
   "slice": {
    "bottom": 12,
    "left": 12,
    "right": 12,
    "top": 12
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/button_primary_base.png",
   "width": 128
  },
  "button_secondary_base": {
   "height": 72,
   "slice": {
    "bottom": 12,
    "left": 12,
    "right": 12,
    "top": 12
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/button_secondary_base.png",
   "width": 128
  },
  "chip_condition_base": {
   "height": 48,
   "slice": {
    "bottom": 8,
    "left": 8,
    "right": 8,
    "top": 8
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/chip_condition_base.png",
   "width": 144
  },
  "frame_advisor_normal": {
   "height": 192,
   "slice": {
    "bottom": 24,
    "left": 24,
    "right": 24,
    "top": 24
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_advisor_normal.png",
   "width": 256
  },
  "frame_advisor_warn": {
   "height": 192,
   "slice": {
    "bottom": 24,
    "left": 24,
    "right": 24,
    "top": 24
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_advisor_warn.png",
   "width": 256
  },
  "frame_hud_strip_bottom": {
   "height": 256,
   "slice": {
    "bottom": 24,
    "left": 24,
    "right": 24,
    "top": 24
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_hud_strip_bottom.png",
   "width": 256
  },
  "frame_hud_strip_top": {
   "height": 256,
   "slice": {
    "bottom": 24,
    "left": 24,
    "right": 24,
    "top": 24
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_hud_strip_top.png",
   "width": 256
  },
  "frame_modal": {
   "height": 256,
   "slice": {
    "bottom": 32,
    "left": 32,
    "right": 32,
    "top": 32
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_modal.png",
   "width": 256
  },
  "frame_objective_complete": {
   "height": 256,
   "slice": {
    "bottom": 32,
    "left": 32,
    "right": 32,
    "top": 32
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_objective_complete.png",
   "width": 256
  },
  "frame_objective_normal": {
   "height": 256,
   "slice": {
    "bottom": 32,
    "left": 32,
    "right": 32,
    "top": 32
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_objective_normal.png",
   "width": 256
  },
  "frame_objective_warn": {
   "height": 256,
   "slice": {
    "bottom": 32,
    "left": 32,
    "right": 32,
    "top": 32
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_objective_warn.png",
   "width": 256
  },
  "frame_panel_dark": {
   "height": 192,
   "slice": {
    "bottom": 24,
    "left": 24,
    "right": 24,
    "top": 24
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_panel_dark.png",
   "width": 192
  },
  "frame_panel_light": {
   "height": 192,
   "slice": {
    "bottom": 32,
    "left": 32,
    "right": 32,
    "top": 32
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_panel_light.png",
   "width": 192
  },
  "frame_tooltip": {
   "height": 128,
   "slice": {
    "bottom": 12,
    "left": 12,
    "right": 12,
    "top": 12
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/frame_tooltip.png",
   "width": 128
  },
  "tab_build_base": {
   "height": 72,
   "slice": {
    "bottom": 12,
    "left": 12,
    "right": 12,
    "top": 12
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/tab_build_base.png",
   "width": 144
  },
  "toast_small": {
   "height": 96,
   "slice": {
    "bottom": 24,
    "left": 24,
    "right": 24,
    "top": 24
   },
   "sourceScale": 2,
   "url": "assets/ui-p0/toast_small.png",
   "width": 640
  }
 },
 "iconSheets": {
  "icon_alert_priority_sheet": {
   "cells": [
    "warn",
    "urgent",
    "info"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/icon_alert_priority_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/icon_alert_priority_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/icon_alert_priority_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/icon_alert_priority_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/icon_alert_priority_sheet.png"
    }
   }
  },
  "icon_build_category_sheet": {
   "cells": [
    "living",
    "paths",
    "trade",
    "storage",
    "public",
    "defense"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/icon_build_category_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/icon_build_category_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/icon_build_category_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/icon_build_category_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/icon_build_category_sheet.png"
    }
   }
  },
  "icon_cause_family_sheet": {
   "cells": [
    "water",
    "food",
    "access",
    "labour",
    "storage",
    "safety",
    "rights"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/icon_cause_family_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/icon_cause_family_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/icon_cause_family_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/icon_cause_family_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/icon_cause_family_sheet.png"
    }
   }
  },
  "icon_first_session_buildings_sheet": {
   "cells": [
    "hut",
    "well",
    "road",
    "field",
    "barn",
    "windmill",
    "granary",
    "warehouse",
    "chapel",
    "market",
    "burgage",
    "palisade"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/icon_first_session_buildings_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/icon_first_session_buildings_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/icon_first_session_buildings_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/icon_first_session_buildings_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/icon_first_session_buildings_sheet.png"
    }
   }
  },
  "icon_layer_mode_sheet": {
   "cells": [
    "direct",
    "zone",
    "direction"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/icon_layer_mode_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/icon_layer_mode_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/icon_layer_mode_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/icon_layer_mode_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/icon_layer_mode_sheet.png"
    }
   }
  },
  "icon_lock_new_sheet": {
   "cells": [
    "locked",
    "new",
    "help"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/icon_lock_new_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/icon_lock_new_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/icon_lock_new_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/icon_lock_new_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/icon_lock_new_sheet.png"
    }
   }
  },
  "icon_objective_action_sheet": {
   "cells": [
    "open",
    "look",
    "log",
    "up"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/icon_objective_action_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/icon_objective_action_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/icon_objective_action_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/icon_objective_action_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/icon_objective_action_sheet.png"
    }
   }
  },
  "icon_prediction_sheet": {
   "cells": [
    "pending",
    "ok",
    "warn",
    "block"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/icon_prediction_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/icon_prediction_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/icon_prediction_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/icon_prediction_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/icon_prediction_sheet.png"
    }
   }
  },
  "icon_resource_sheet": {
   "cells": [
    "population",
    "bread",
    "timber",
    "stone",
    "coin",
    "spring",
    "summer",
    "autumn",
    "winter"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/icon_resource_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/icon_resource_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/icon_resource_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/icon_resource_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/icon_resource_sheet.png"
    }
   }
  },
  "icon_time_sheet": {
   "cells": [
    "pause",
    "play",
    "fast",
    "fastest"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/icon_time_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/icon_time_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/icon_time_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/icon_time_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/icon_time_sheet.png"
    }
   }
  },
  "warning_map_marker_sheet": {
   "cells": [
    "warn",
    "urgent"
   ],
   "sizes": {
    "24": {
     "url": "assets/ui-p0/icons/warning_map_marker_sheet-24.png"
    },
    "32": {
     "url": "assets/ui-p0/icons/warning_map_marker_sheet-32.png"
    },
    "48": {
     "url": "assets/ui-p0/icons/warning_map_marker_sheet-48.png"
    },
    "64": {
     "url": "assets/ui-p0/icons/warning_map_marker_sheet-64.png"
    },
    "96": {
     "url": "assets/ui-p0/warning_map_marker_sheet.png"
    }
   }
  }
 },
 "portraits": {
  "advisor_portrait_frame": {
   "x1": {
    "url": "assets/ui-p0/portraits/advisor_portrait_frame-96.png"
   },
   "x2": {
    "url": "assets/ui-p0/advisor_portrait_frame.png"
   }
  },
  "advisor_steward_portrait_concern": {
   "x1": {
    "url": "assets/ui-p0/portraits/advisor_steward_portrait_concern-96.png"
   },
   "x2": {
    "url": "assets/ui-p0/advisor_steward_portrait_concern.png"
   }
  },
  "advisor_steward_portrait_neutral": {
   "x1": {
    "url": "assets/ui-p0/portraits/advisor_steward_portrait_neutral-96.png"
   },
   "x2": {
    "url": "assets/ui-p0/advisor_steward_portrait_neutral.png"
   }
  },
  "advisor_steward_portrait_success": {
   "x1": {
    "url": "assets/ui-p0/portraits/advisor_steward_portrait_success-96.png"
   },
   "x2": {
    "url": "assets/ui-p0/advisor_steward_portrait_success.png"
   }
  }
 },
 "textures": {
  "divider_manuscript_dark": {
   "height": 16,
   "url": "assets/ui-p0/divider_manuscript_dark.png",
   "width": 128
  },
  "divider_manuscript_light": {
   "height": 16,
   "url": "assets/ui-p0/divider_manuscript_light.png",
   "width": 128
  },
  "texture_vellum_dark": {
   "height": 256,
   "url": "assets/ui-p0/texture_vellum_dark.png",
   "width": 256
  },
  "texture_vellum_light": {
   "height": 256,
   "url": "assets/ui-p0/texture_vellum_light.png",
   "width": 256
  }
 }
} as const;
