// Player-facing copy of the walker diagnosis model (carter and distributor cards).
export const WALKER_DIAGNOSIS_COPY = {
  carterRole: "운반꾼",
  distributorRole: "배급꾼",
  destinationUnavailable: "목적지를 이용할 수 없음",
  manualCancel: "수동 취소",
  roadRemoved: "도로가 끊김",
  sourceUnavailable: "출발지 재고를 이용할 수 없음",
  north: "북",
  south: "남",
  west: "서",
  east: "동",
  samePosition: "같은 위치",
  directionSide: (direction: string) => `${direction}쪽`,
  /** INSTALL-23: a building site the carter heads to, by the building's name and where it lies from the carter. */
  site: (name: string) => `${name} 공사장`,
  sitePlace: (name: string, direction: string, distance: number) => `${name} 공사장 · ${direction} ${distance}칸`,
  siteGone: "공사장",
  noCargo: "화물 없음",
  deliveryCancelled: "배송 취소",
  delivering: "배송 중",
  goingToCollect: "수령하러 이동 중",
  returningToSource: "출발지로 귀환 중",
  homeGranary: "소속 곡창",
  roadRound: "도로 순회",
  returningToGranary: "곡창으로 귀환 중",
  distributing: "주택 배급 순회 중",
} as const;
