// Generated by scripts/installWave44.py — the Wave 44 home-petition illustrations (LM-R1): one 960 × 540 picture per
// FIX-14 home petition kind that matches one to one, and `by_precedent` for the steward's answer by precedent; shipped
// as the received JPEGs (scripts/keyartDerivatives.ts, format jpeg-received); `source` is the received file in assets-inbox.
export const WAVE44_IMAGES = {
  boundary_dispute: {"url": "assets/wave44/01_boundary_dispute.jpg", "width": 960, "height": 540, "assetId": "01_boundary_dispute", "title": "경계 다툼", "source": "assets-inbox/wave44/candidates-20261002/assets/01_boundary_dispute.jpg"},
  mill_suit: {"url": "assets/wave44/02_suit_of_mill.jpg", "width": 960, "height": 540, "assetId": "02_suit_of_mill", "title": "방앗간 강제", "source": "assets-inbox/wave44/candidates-20261002/assets/02_suit_of_mill.jpg"},
  heriot: {"url": "assets/wave44/03_heriot.jpg", "width": 960, "height": 540, "assetId": "03_heriot", "title": "상속세", "source": "assets-inbox/wave44/candidates-20261002/assets/03_heriot.jpg"},
  merchet: {"url": "assets/wave44/04_merchet.jpg", "width": 960, "height": 540, "assetId": "04_merchet", "title": "혼인세", "source": "assets-inbox/wave44/candidates-20261002/assets/04_merchet.jpg"},
  ale_fines: {"url": "assets/wave44/05_ale_assize.jpg", "width": 960, "height": 540, "assetId": "05_ale_assize", "title": "에일 검정", "source": "assets-inbox/wave44/candidates-20261002/assets/05_ale_assize.jpg"},
  road_bridge: {"url": "assets/wave44/06_bridge_repair.jpg", "width": 960, "height": 540, "assetId": "06_bridge_repair", "title": "길·다리 수리 분담", "source": "assets-inbox/wave44/candidates-20261002/assets/06_bridge_repair.jpg"},
  stall_dispute: {"url": "assets/wave44/07_market_stall_dispute.jpg", "width": 960, "height": 540, "assetId": "07_market_stall_dispute", "title": "시장 좌판 다툼", "source": "assets-inbox/wave44/candidates-20261002/assets/07_market_stall_dispute.jpg"},
  wardship: {"url": "assets/wave44/08_minor_wardship.jpg", "width": 960, "height": 540, "assetId": "08_minor_wardship", "title": "미성년 상속자 후견", "source": "assets-inbox/wave44/candidates-20261002/assets/08_minor_wardship.jpg"},
  common_pasture: {"url": "assets/wave44/09_common_pasture.jpg", "width": 960, "height": 540, "assetId": "09_common_pasture", "title": "공유지 방목", "source": "assets-inbox/wave44/candidates-20261002/assets/09_common_pasture.jpg"},
  newcomer: {"url": "assets/wave44/10_migrant_settlement.jpg", "width": 960, "height": 540, "assetId": "10_migrant_settlement", "title": "이주민 정착 허가", "source": "assets-inbox/wave44/candidates-20261002/assets/10_migrant_settlement.jpg"},
  by_precedent: {"url": "assets/wave44/13_by_precedent.jpg", "width": 960, "height": 540, "assetId": "13_by_precedent", "title": "선례대로 처리", "source": "assets-inbox/wave44/candidates-20261002/assets/13_by_precedent.jpg"},
} as const;
