// Generated by scripts/installWave33.py — Wave 33 interlude illustrations (UI-10): chapter 5's five 1384–1400
// interlude events, one per LegacyInterludeId (`interlude_<id>`), loaded as build-time JPEG derivatives
// (scripts/keyartDerivatives.ts); `source` is the received PNG in assets-inbox.
export const WAVE33_IMAGES = {
  interlude_staple: {"url": "assets/wave33/interlude/interlude_staple.jpg", "width": 960, "height": 540, "year": 1391, "source": "assets-inbox/wave33/candidates-20260929/assets/1391-wool-staple.png"},
  interlude_guild_dispute: {"url": "assets/wave33/interlude/interlude_guild_dispute.jpg", "width": 960, "height": 540, "year": 1394, "source": "assets-inbox/wave33/candidates-20260929/assets/1394-guild-dispute.png"},
  interlude_market_fire: {"url": "assets/wave33/interlude/interlude_market_fire.jpg", "width": 960, "height": 540, "year": 1394, "source": "assets-inbox/wave33/candidates-20260929/assets/1394-market-fire.png"},
  interlude_church_rebuilding: {"url": "assets/wave33/interlude/interlude_church_rebuilding.jpg", "width": 960, "height": 540, "year": 1396, "source": "assets-inbox/wave33/candidates-20260929/assets/1396-church-extension.png"},
  interlude_deposition: {"url": "assets/wave33/interlude/interlude_deposition.jpg", "width": 960, "height": 540, "year": 1399, "source": "assets-inbox/wave33/candidates-20260929/assets/1399-henry-iv-news.png"},
} as const;
