// Generated by scripts/installWave21.py — Wave 21 chapter 3 illustrations (UI-8): decision cards,
// event illustrations, chronicle scenes and the chapter-3 end page, loaded as build-time JPEG
// derivatives (scripts/keyartDerivatives.ts); `source` is the received PNG in assets-inbox.
export const WAVE21_IMAGES = {
  ch3_decision_wages: {"url": "assets/wave21/ch3_records/ch3_decision_wages.jpg", "width": 640, "height": 480, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_records/ch3_decision_wages.png"},
  ch3_decision_land_redistribution: {"url": "assets/wave21/ch3_records/ch3_decision_land_redistribution.jpg", "width": 640, "height": 480, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_records/ch3_decision_land_redistribution.png"},
  ch3_decision_vacant_priest: {"url": "assets/wave21/ch3_records/ch3_decision_vacant_priest.jpg", "width": 640, "height": 480, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_records/ch3_decision_vacant_priest.png"},
  ch3_decision_cash_rent: {"url": "assets/wave21/ch3_records/ch3_decision_cash_rent.jpg", "width": 640, "height": 480, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_records/ch3_decision_cash_rent.png"},
  ch3_chronicle_first_death: {"url": "assets/wave21/ch3_records/ch3_chronicle_first_death.jpg", "width": 384, "height": 384, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_records/ch3_chronicle_first_death.png"},
  ch3_chronicle_churchyard: {"url": "assets/wave21/ch3_records/ch3_chronicle_churchyard.jpg", "width": 384, "height": 384, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_records/ch3_chronicle_churchyard.png"},
  ch3_chronicle_abandoned_fields: {"url": "assets/wave21/ch3_records/ch3_chronicle_abandoned_fields.jpg", "width": 384, "height": 384, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_records/ch3_chronicle_abandoned_fields.png"},
  ch3_chronicle_ordinance: {"url": "assets/wave21/ch3_records/ch3_chronicle_ordinance.jpg", "width": 384, "height": 384, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_records/ch3_chronicle_ordinance.png"},
  ch3_chronicle_resettlement: {"url": "assets/wave21/ch3_records/ch3_chronicle_resettlement.jpg", "width": 384, "height": 384, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_records/ch3_chronicle_resettlement.png"},
  ch3_chronicle_spring_recovery: {"url": "assets/wave21/ch3_records/ch3_chronicle_spring_recovery.jpg", "width": 384, "height": 384, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_records/ch3_chronicle_spring_recovery.png"},
  ch3_event_harbour_fever: {"url": "assets/wave21/ch3_events/ch3_event_harbour_fever.jpg", "width": 960, "height": 540, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_events/ch3_event_harbour_fever.png"},
  ch3_event_priest_death: {"url": "assets/wave21/ch3_events/ch3_event_priest_death.jpg", "width": 960, "height": 540, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_events/ch3_event_priest_death.png"},
  ch3_event_new_graves: {"url": "assets/wave21/ch3_events/ch3_event_new_graves.jpg", "width": 960, "height": 540, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_events/ch3_event_new_graves.png"},
  ch3_event_empty_streets: {"url": "assets/wave21/ch3_events/ch3_event_empty_streets.jpg", "width": 960, "height": 540, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_events/ch3_event_empty_streets.png"},
  ch3_event_abandoned_fields: {"url": "assets/wave21/ch3_events/ch3_event_abandoned_fields.jpg", "width": 960, "height": 540, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_events/ch3_event_abandoned_fields.png"},
  ch3_event_wage_demand: {"url": "assets/wave21/ch3_events/ch3_event_wage_demand.jpg", "width": 960, "height": 540, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_events/ch3_event_wage_demand.png"},
  ch3_event_ordinance_reading: {"url": "assets/wave21/ch3_events/ch3_event_ordinance_reading.jpg", "width": 960, "height": 540, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_events/ch3_event_ordinance_reading.png"},
  ch3_event_resettlement: {"url": "assets/wave21/ch3_events/ch3_event_resettlement.jpg", "width": 960, "height": 540, "source": "assets-inbox/wave21/candidates-v1/assets/ch3_events/ch3_event_resettlement.png"},
  ch3_ending: {"url": "assets/wave21/ch3_events/ch3_ending.jpg", "width": 1920, "height": 1080, "source": "assets-inbox/wave21/rework-20260927/assets/ch3_events/ch3_ending.png"},
} as const;
