// Generated by scripts/installWave25.py — Wave 25 family tree parts (UI-7): url, size and, for 9-slice parts, the insets.
export const WAVE25_IMAGES = {
  tree_collapse: {"url": "assets/wave25/tree/tree_collapse.png", "width": 32, "height": 32},
  tree_expand: {"url": "assets/wave25/tree/tree_expand.png", "width": 32, "height": 32},
  tree_generation_label: {"url": "assets/wave25/tree/tree_generation_label.png", "width": 120, "height": 32, "nineSlice": {"left": 10, "top": 8, "right": 10, "bottom": 8}},
  tree_line_corner_bl: {"url": "assets/wave25/tree/tree_line_corner_bl.png", "width": 16, "height": 16},
  tree_line_corner_br: {"url": "assets/wave25/tree/tree_line_corner_br.png", "width": 16, "height": 16},
  tree_line_corner_tl: {"url": "assets/wave25/tree/tree_line_corner_tl.png", "width": 16, "height": 16},
  tree_line_corner_tr: {"url": "assets/wave25/tree/tree_line_corner_tr.png", "width": 16, "height": 16},
  tree_line_h: {"url": "assets/wave25/tree/tree_line_h.png", "width": 64, "height": 8},
  tree_line_junction_t: {"url": "assets/wave25/tree/tree_line_junction_t.png", "width": 16, "height": 16},
  tree_line_v: {"url": "assets/wave25/tree/tree_line_v.png", "width": 8, "height": 64},
  tree_lineage_banner: {"url": "assets/wave25/tree/tree_lineage_banner.png", "width": 320, "height": 72, "nineSlice": {"left": 24, "top": 10, "right": 24, "bottom": 10}},
  tree_marriage_link: {"url": "assets/wave25/tree/tree_marriage_link.png", "width": 48, "height": 16},
  tree_node_frame: {"url": "assets/wave25/tree/tree_node_frame.png", "width": 176, "height": 216, "nineSlice": {"left": 12, "top": 12, "right": 12, "bottom": 12}},
  tree_node_frame_deceased: {"url": "assets/wave25/tree/tree_node_frame_deceased.png", "width": 176, "height": 216, "nineSlice": {"left": 20, "top": 20, "right": 20, "bottom": 20}},
  tree_node_frame_selected: {"url": "assets/wave25/tree/tree_node_frame_selected.png", "width": 176, "height": 216, "nineSlice": {"left": 12, "top": 12, "right": 12, "bottom": 12}},
  tree_outside_spouse_marker: {"url": "assets/wave25/tree/tree_outside_spouse_marker.png", "width": 24, "height": 24},
} as const;

export type Wave25ImageId = keyof typeof WAVE25_IMAGES;
