// Generated by scripts/installWave31.py — Wave 31 chapter opening paintings (1920 × 1080): the chronicle's
// chapter start and the chapter's opening screen (runtime JPEG 70 copies in public/assets/wave31);
// `source` is the received JPEG in assets-inbox.
export const WAVE31_IMAGES = {
  chapter3_intro: {"url": "assets/wave31/chapters/chapter3_intro.jpg", "width": 1920, "height": 1080, "chapter": 3, "source": "assets-inbox/wave31/candidates-20260929/assets/illustrations/chapter3_intro-v1.jpg"},
  chapter4_intro: {"url": "assets/wave31/chapters/chapter4_intro.jpg", "width": 1920, "height": 1080, "chapter": 4, "source": "assets-inbox/wave31/candidates-20260929/assets/illustrations/chapter4_intro-v1.jpg"},
  chapter5_intro: {"url": "assets/wave31/chapters/chapter5_intro.jpg", "width": 1920, "height": 1080, "chapter": 5, "source": "assets-inbox/wave31/candidates-20260929/assets/illustrations/chapter5_intro-v1.jpg"},
} as const;
