// Generated by scripts/installChronicleArt.py — Wave 17 chronicle illustrations (CHRON-1), loaded as build-time web
// derivatives (scripts/keyartDerivatives.ts); `source` is the received PNG in assets-inbox.
export const WAVE17_IMAGES = {
  stonewall_start: {"url": "assets/wave17/chronicle/stonewall_start.jpg", "width": 384, "height": 384, "source": "assets-inbox/wave17/candidates-20260926/assets/illustration/chronicle/stonewall_start.png"},
  stonewall_complete: {"url": "assets/wave17/chronicle/stonewall_complete.jpg", "width": 384, "height": 384, "source": "assets-inbox/wave17/candidates-20260926/assets/illustration/chronicle/stonewall_complete.png"},
} as const;
