const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {createCanvas,loadImage}=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const W='/tmp/astra-wave34-stage3-regions-work-20260929',O='/tmp/astra-wave34-stage3-regions-candidates-20260929',OLD='/tmp/astra-wave34-candidates-20260929',P='/Users/rexxa/orca/workspaces/feudal-lord-simulator/krill/public/assets',A='/Users/rexxa/orca/workspaces/feudal-lord-simulator/krill/assets-inbox/wave22/rework-20260927/assets';
const inputs=[],cache=new Map();async function image(p){if(!cache.has(p)){const im=await loadImage(p);cache.set(p,im);inputs.push({path:p,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});}return cache.get(p)}
function iso(u,v){return[(u+v)*64,(v-u)*32]};function text(c,t,x,y,s=16){c.fillStyle='#343c35';c.font=`${s}px sans-serif`;c.fillText(t,x,y)}function diamond(c,n){const h=n/2,pts=[iso(-h,-h),iso(h,-h),iso(h,h),iso(-h,h)];c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();return pts}
async function ground(c,p,n){c.save();diamond(c,n);c.clip();c.transform(1,-.5,1,.5,0,0);c.fillStyle=c.createPattern(await image(p),'repeat');c.fillRect(-1500,-1500,3000,3000);c.restore()}
function sprite(c,im,u,v,mirror=false){const p=iso(u,v);c.save();c.translate(...p);if(mirror)c.scale(-1,1);c.drawImage(im,-im.width/2,-im.height/2);c.restore()}
async function panel(n,season,stage){const a=createCanvas(680,400),c=a.getContext('2d');c.translate(340,195);const h=n/2,m=(n-1)/2,fill=stage===3?(season==='summer'?P+'/terrain/grass.png':P+'/wave15/terrain/grass_winter_fill-v1.png'):A+'/terrain/fen_'+season+'_a-v2.png';await ground(c,fill,n);
const pools=[[-.3,-.28],[.26,-.2],[.04,.02],[-.22,.3],[.28,.24]],count=[5,3,0,0][stage];for(let i=0;i<count;i++){const im=await image(A+'/decals/fen_pool_'+(i%2?'b':'c')+'-v1.png'),[x,y]=iso(pools[i][0]*n,pools[i][1]*n),s=stage===1?.7:1;c.drawImage(im,x-im.width*s/2,y-im.height*s/2,im.width*s,im.height*s)}
let overlays=0,region=null;const ditchOffsets=n===5?[-1,1]:[-.5,.5];
if(stage===0){const im=await image(OLD+'/drain/drain_stage1_staked_'+season+'-v1.png');for(let u=-m;u<=m;u++)for(let v=-m;v<=m;v++){if(Math.abs(u)!==m&&Math.abs(v)!==m)continue;sprite(c,im,u,v,Math.abs(u)===m&&Math.abs(v)!==m);overlays++}}
if(stage===1){const im=await image(OLD+'/drain/drain_stage2_ditched_'+season+'-v1.png');for(const u of ditchOffsets)for(let v=-m;v<=m;v++){sprite(c,im,u,v,true);overlays++}}
if(stage===2){region=O+'/drain/drain_stage3_drying_'+season+'_'+n+'x'+n+'-v3.png';const im=await image(region);if(im.width!==n*128||im.height!==n*64)throw Error('Wrong region dimensions: '+region);c.drawImage(im,-im.width/2,-im.height/2);overlays=1}
if(stage===3){const im=await image(OLD+'/drain/drain_done_edge_'+season+'-v1.png'),corners=diamond(c,n);for(let i=0;i<4;i++){const p=corners[i],q=corners[(i+1)%4],dx=q[0]-p[0],dy=q[1]-p[1],len=Math.hypot(dx,dy);c.save();c.transform(dx/im.width,dy/im.width,-dy/len*.6,dx/len*.6,...p);c.drawImage(im,0,-im.height/2);c.restore()}}
const props=stage===0?[['drain_earth_cart',-.32*n,.32*n],['drain_soil_heap',-.16*n,.4*n]]:stage===1?[['drain_sluice',ditchOffsets[1],m]]:stage===3?[['drain_plank_bridge',h,0]]:[];for(const [name,u,v]of props){const im=await image(OLD+'/props/'+name+'-v1.png'),[x,y]=iso(u,v);c.drawImage(im,x-im.width/2,y-im.height+8+(name==='drain_plank_bridge'?24:0))}
return{canvas:a,record:{n,season,stage:stage+1,fill,region,overlayCount:overlays,pondCount:count,ditchOffsets,stage2Transform:stage===1?"horizontal flip per sprite; constant u channels / +0.5 slope":null,stage3Placement:stage===2?'one whole-region drawImage at 1:1 source pixels':null}}}
(async()=>{fs.mkdirSync(O+'/checks',{recursive:true});const out=createCanvas(1500,1870),c=out.getContext('2d');c.fillStyle='#e9e7dc';c.fillRect(0,0,out.width,out.height);text(c,'WAVE 34 / stage 3 v3: whole-region drainage overlays',24,34,24);text(c,'Offline reconstruction; not a game screenshot. One non-repeating stage-3 image per entire region.',24,61,15);const records=[];let row=0;for(const n of[5,3])for(const season of['summer','winter']){const y=105+row*430;text(c,n+' x '+n+' / '+season.toUpperCase()+' / zoom 1.0',24,y,19);for(let stage=0;stage<4;stage++){const x=20+stage*365,{canvas,record}=await panel(n,season,stage);records.push(record);text(c,['1 / staked','2 / ditched','3 / whole-region drying','4 / grass + perimeter ditch'][stage],x,y+28,16);c.drawImage(canvas,x,y+36,340,200);text(c,'0.6',x,y+257,14);c.drawImage(canvas,x+68,y+264,204,120)}row++}text(c,'Tile = 64 x 32 px at zoom 1.0. Region overlays are placed once, without tiling, recolouring, masking or feature removal.',24,1840,14);const file='checks/01-region-drainage-sequence.png';fs.writeFileSync(O+'/'+file,out.toBuffer('image/png'));fs.writeFileSync(W+'/proofs-provenance.json',JSON.stringify({inputs,records,file,sha256:crypto.createHash('sha256').update(fs.readFileSync(O+'/'+file)).digest('hex')},null,2));console.log(file)})().catch(e=>{console.error(e);process.exit(1)});
