// NAT-2 QA tool: the QA info overlay's labels (settings → developer, key `). Values are the game's own numbers.
export const QA_OVERLAY_COPY = {
  region: "QA 정보",
  tick: "틱",
  calendar: "연도·계절",
  speed: "속도",
  speedValue: (speed: number) => speed === 0 ? "멈춤" : `${speed}배속`,
  zoom: "줌",
  pan: "카메라 이동",
  center: "화면 중심 월드",
  centerTile: "화면 중심 칸",
  click: "마지막 클릭 칸",
  none: "없음",
  selection: "선택",
  state: "상태",
  way: "가는 길",
  cancelled: "멈춘 까닭",
  point: (x: number, y: number) => `(${x}, ${y})`,
  tile: (tx: number, ty: number) => `(${tx}, ${ty})`,
  walker: (role: string, id: string, name: string | null) => `${role} ${name ?? "이름 없음"} · ${id}`,
  walkerState: (status: string, line: string | null) => line === null ? status : `${status} · ${line}`,
  walkerLeft: (distance: number, eta: number) => `남은 길 ${distance.toFixed(1)}칸 · 도착까지 ${eta}틱`,
  building: (name: string, id: string, tx: number, ty: number) => `${name} · ${id} · 칸 (${tx}, ${ty})`,
  site: (id: string) => `공사장 · ${id}`,
  wall: (id: string) => `성벽 구간 · ${id}`,
  gone: (id: string) => `사라짐 · ${id}`,
  copy: "복사",
  copyLabel: "QA 정보를 글로 복사",
  copied: "복사함",
  close: "QA 정보 닫기",
  closeMark: "×",
} as const;
