const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const p=path.resolve(__dirname,'..'),exp=JSON.parse(fs.readFileSync(p+'/records/expected-assets.json'));
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const records=fs.readdirSync(p+'/records').filter(f=>/^metadata-.*\.json$/.test(f)).flatMap(f=>{const j=JSON.parse(fs.readFileSync(p+'/records/'+f));return Array.isArray(j)?j:j.assets||j.records||[];});
const rows=[],checks=[];for(const a of exp){const f=p+'/'+a.file,buf=fs.readFileSync(f),m=await sharp(buf).metadata();if(m.width!==a.width||m.height!==a.height||m.channels!==4)throw Error('dimensions/alpha '+a.id+JSON.stringify(m));const {data,info}=await sharp(buf).raw().toBuffer({resolveWithObject:true});let clear=0,visible=0;for(let n=3;n<data.length;n+=4){if(data[n]===0)clear++;else visible++;}if(!visible)throw Error('empty '+a.id);let r=records.find(r=>r.id===a.id||r.asset_id===a.id);if(!r)throw Error('missing metadata '+a.id);let gr=r.generationRecords||r.generation_records||[];if(!Array.isArray(gr))gr=[gr];if(!gr.length)throw Error('missing provenance '+a.id);for(const g of gr){if(!g.prompt)throw Error('missing prompt '+a.id);const raw=g.rawFile||g.raw_file;if(raw){const rp=path.isAbsolute(raw)?raw:path.join(p,raw);if(!fs.existsSync(rp))throw Error('raw missing '+rp);const mm=await sharp(rp).metadata();g.sourceImageDimensions={width:mm.width,height:mm.height};}}
const sha=hash(buf);checks.push({id:a.id,width:m.width,height:m.height,channels:m.channels,clearPixels:clear,visiblePixels:visible,sha256:sha});rows.push({asset_id:a.id,status:'candidate',file:a.file,width:a.width,height:a.height,group:a.group,description:r.description||'',history_notes:'Project reference art. Candidate only; no runtime installation.',sha256:sha,generation_records:JSON.stringify(gr),processing:JSON.stringify(r.processing||r.postProcessing||''),qa:JSON.stringify({...(r.qa||{}),nineSlice:r.nineSlice||null})});}
fs.writeFileSync(p+'/records/asset-rows.json',JSON.stringify(rows,null,2));fs.writeFileSync(p+'/records/technical-qa.json',JSON.stringify({assetCount:checks.length,checks},null,2));
const ref=fs.readdirSync(p+'/references').filter(f=>fs.statSync(p+'/references/'+f).isFile()).map(f=>({file:'references/'+f,sha256:hash(fs.readFileSync(p+'/references/'+f))}));fs.writeFileSync(p+'/records/reference-hashes.json',JSON.stringify(ref,null,2));
const proofs=['01-chronicle-cards.png','02-biography-faction.png','03-ledger-scenes.png'];
fs.writeFileSync(p+'/IMAGE_LINKS.md','# Wave19 개별 이미지\n\n'+proofs.map(f=>`- [${f}](${p}/proofs/${f})`).join('\n')+'\n\n'+exp.map(a=>`- [${a.id}](${p}/${a.file})`).join('\n'));
fs.writeFileSync(p+'/index.html','<!doctype html><html lang="ko"><meta charset="utf-8"><title>Wave19 candidates</title><style>body{background:#e1d4ad;color:#392b20;font:16px sans-serif;margin:28px}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}article{border:1px solid #85734f;padding:14px;overflow:auto}img{max-width:100%;object-fit:contain}article img{height:180px}a{color:#574424}</style><h1>Wave19 후보 53장</h1><p>오프라인 아트 검사. 게임 미설치. <a href="README.md">설명</a> · <a href="검수표.md">검수표</a></p>'+proofs.map(f=>`<p><a href="proofs/${f}"><img src="proofs/${f}" alt="${f}"></a></p>`).join('')+'<section>'+exp.map(a=>`<article><a href="${a.file}"><img src="${a.file}" alt="${a.id}"><p>${a.id}</p></a>${a.width}×${a.height}</article>`).join('')+'</section></html>');console.log('PASS asset metadata',checks.length);})();
