const fs = require('fs');
const path = require('path');
const sharp = require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const base = path.resolve(__dirname, '..');
const source = JSON.parse(fs.readFileSync(path.join(base,'records/pages-source.json')));
const dims = {frame_biography:[640,800],frame_faction_page:[640,800],biography_life_line:[32,256],biography_life_dot:[96,96],biography_life_end:[96,96],relation_scale_pin:[96,96],relation_scale_track:[256,24],frame_snapshot_map_320:[320,320]};
const desc = {frame_biography:'인물 전기: 초상·문장·표식·생애 연표·관계 빈 칸',frame_faction_page:'세력: 수장·문장·관계 척도·요구와 약속·연표 빈 칸',biography_life_line:'생애 연표 세로 선',biography_life_dot:'생애 연표 원형 점',biography_life_end:'생애 연표 마름모 끝 표식',relation_scale_track:'우호·중립·적대 척도 바탕',relation_scale_pin:'관계 척도 삼각 핀',frame_snapshot_map_320:'그때 지도 틀 320',frame_snapshot_map_160:'그때 지도 틀 160'};
const slices={frame_biography:{left:325,right:45,top:580,bottom:200},frame_faction_page:{left:340,right:170,top:340,bottom:450},frame_snapshot_map_320:{left:45,right:45,top:50,bottom:45},frame_snapshot_map_160:{left:23,right:23,top:25,bottom:23}};
async function bounds(file){const {data,info}=await sharp(file).ensureAlpha().raw().toBuffer({resolveWithObject:true}); let x0=info.width,y0=info.height,x1=0,y1=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++)if(data[(y*info.width+x)*4+3]>16){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}return{left:Math.max(0,x0-2),top:Math.max(0,y0-2),width:Math.min(info.width-1,x1+2)-Math.max(0,x0-2)+1,height:Math.min(info.height-1,y1+2)-Math.max(0,y0-2)+1};}
(async()=>{const rows=[];for(const s of source){const [width,height]=dims[s.id];const rawFile='raw/pages/'+s.id+'-v1.png';fs.copyFileSync(s.src,path.join(base,rawFile));const crop=await bounds(s.src);let pipe=sharp(s.src).extract(crop);let processing;
if(s.id==='frame_biography'||s.id==='frame_faction_page'){const inner=await pipe.resize(width-4,height-4,{fit:'fill'}).ensureAlpha().png().toBuffer();pipe=sharp(inner).extend({top:2,bottom:2,left:2,right:2,background:'#00000000'});processing='Alpha bounds crop, resize to 636x796, transparent 2px exterior padding; no painted-content alterations.';}
else if(s.id==='relation_scale_track'){const inner=await pipe.resize(252,20,{fit:'fill'}).png().toBuffer();pipe=sharp(inner).extend({top:2,bottom:2,left:2,right:2,background:'#00000000'});processing='Alpha bounds crop; channel normalized to 252x20, 2px transparent padding.';}
else {const margin=s.id==='biography_life_line'?4:6;pipe=pipe.resize(width-margin*2,height-margin*2,{fit:'contain',background:'#00000000'});const inner=await pipe.png().toBuffer();pipe=sharp(inner).extend({top:margin,bottom:margin,left:margin,right:margin,background:'#00000000'});processing='Alpha bounds crop; proportional contain resize, transparent padding, generated alpha preserved.';}
const file='assets/pages/'+s.id+'.png';await pipe.ensureAlpha().png().toFile(path.join(base,file));rows.push({id:s.id,file,width,height,description:desc[s.id],generationRecords:[{prompt:s.prompt,rawFile,referenceImages:s.refs.map(f=>'references/'+f),tool:'image_gen.imagegen',model:null,seed:null}],processing,crop,qa:{status:'candidate',text:'No letters or numbers observed',alpha:'RGBA generated transparency preserved'},nineSlice:slices[s.id]?{...slices[s.id],minimumSize:[width,height],restriction:'Expand only. Insets preserve complete portrait/emblem and fixed internal compartments; native layout coordinates remain authoritative. No arbitrary uniform page scaling.'}:null});}
const small='assets/pages/frame_snapshot_map_160.png';await sharp(path.join(base,'assets/pages/frame_snapshot_map_320.png')).resize(160,160).png().toFile(path.join(base,small));const parent=rows.find(r=>r.id==='frame_snapshot_map_320');rows.push({...parent,id:'frame_snapshot_map_160',file:small,width:160,height:160,description:desc.frame_snapshot_map_160,processing:'Intentional 1/2 scale variant of frame_snapshot_map_320; no additional generation.',nineSlice:{...slices.frame_snapshot_map_160,minimumSize:[160,160],restriction:'Expand only; transparent map hole retained.'}});
fs.writeFileSync(path.join(base,'records/metadata-pages.json'),JSON.stringify(rows,null,2));console.log(rows.length+' pages exported');})();
