require 'json'
r=__dir__;head=File.read(File.expand_path('../office-context/build.rb',r));prefix=head.split('specs=[',2).first
specs=[
 ['legacy.staple','weaversAtStaple',{'present'=>'양모 지정 무역 제도의 중단이 기록될 때, 도시에는 직조공 작업장이 있었다.','absent'=>'양모 지정 무역 제도의 중단이 기록될 때, 도시에는 직조공 작업장이 없었다.'},'src/engine/legacy.ts:270-304; src/content/buildingCatalog.ts:127-128','At actual staple emission count existing after.buildings kind weaver_house, not constructionSites, not current read-time buildings. Positive count -> present; zero -> absent. Valid complete building list required. Do not infer actual sales, profit, household occupation or historical causation; price effect is game balance only.'],
 ['legacy.guild_dispute','guildHeadAtDispute',{'identified'=>'수장이 기록된 길드와 상인이 직물 판매 권리를 두고 다투는 안건이 올랐다.','unidentified'=>'길드 수장이 특정되지 않은 가운데 직물 판매 권리의 다툼이 기록되었다.'},'src/engine/legacy.ts:279-295; src/engine/reorganisation.types.ts:6-11','Require event guild_dispute and after.reorganisation.guild exists. Snapshot guild.headId: nonempty string -> identified, null -> unidentified; missing/empty/malformed unknown. No inferred death, vacancy cause, weakness, or outcome. Names resolved only at reading if future formatter adds ID slot.'],
 ['legacy.market_fire','repairPaymentAtFire',{'full'=>'장터 화재 수리비로 정해진 금액이 모두 금고에서 나갔다.','partial'=>'장터 화재 수리비 가운데 일부만 금고에서 나갔다.','zero'=>'장터 화재 수리비가 기록되었으나 금고에서 나간 돈은 없었다.'},'src/engine/legacy.ts:73-78,290-298; src/content/legacyConfig.ts:109','Capture return moved from exact post construction call sourceRef claim market_fire/detail repair. Compare positive configured marketFireRepair with -moved: equal full, positive smaller partial, zero zero. Safe integer bounds and exact call correlation required; aggregate tick treasury delta is insufficient. Do not infer burned building IDs, casualty extent, completion, debt, or unpaid remainder obligation.'],
 ['legacy.church_rebuilding','treasuryAtNaveRequest',{'covers_cost'=>'교회 증축 청원이 올랐다. 당시 금고에는 정해진 증축비를 감당할 돈이 있었다.','below_cost'=>'교회 증축 청원이 올랐다. 당시 금고의 돈은 정해진 증축비에 미치지 못했다.'},'src/engine/legacy.ts:290-295,196-201; src/content/legacyConfig.ts:110-111','At the exact addPetition church_rebuilding point read treasuryBalance and configured churchRebuildingCost; finite nonnegative safe coin and positive safe cost required. coin>=cost covers_cost else below_cost. Capture operation-local state to avoid later same-tick effects. Not an approval, future affordability, reserved fund, physical church audit, or payment.'],
 ['legacy.nave_rebuilt','navePaymentAtRecord',{'full'=>'회중석 증축이 기록되었고, 정해진 비용이 모두 금고에서 나갔다.','partial'=>'회중석 증축이 기록되었으나, 정해진 비용 중 일부만 금고에서 나갔다.','zero'=>'회중석 증축이 기록되었으나, 금고에서 나간 비용은 없었다.'},'src/engine/legacy.ts:73-78,196-201; src/engine/history.ts:767','Capture exact accept answer post church_rebuilding source claim church_rebuilding/detail nave and false->true naveRebuilt. -moved==cost -> full; 0<-moved<cost -> partial; moved0 -> zero. Validate safe integers, record binding. Flag is set immediately even if payment is partial/zero. No construction site, physical nave completion, labour, or remaining debt inferred.'],
 ['legacy.deposition','crownResetAtDeposition',{'toward_closer'=>'왕위 교체에 따른 조정은 왕실과의 관계를 가까워지는 쪽으로 움직였다.','toward_distant'=>'왕위 교체에 따른 조정은 왕실과의 관계를 멀어지는 쪽으로 움직였다.','unchanged'=>'왕위 교체가 기록되었으나, 그에 따른 왕실 관계 조정분은 없었다.'},'src/engine/factions.ts:423-431; src/content/legacyConfig.ts:112-113','At factionChanges deposition branch capture exact Math.round((start-crown.relation)*depositionPermille/1000) before delta filtering, with crown present and finite valid relation/start. Positive -> toward_closer, negative -> toward_distant, zero -> unchanged. Capture local contribution, not total after-minus-before relation if other causes share tick. No inference of player loyalty, dynastic cause, reward or punishment.']
]
tail=head.split("fields=specs.map",2).last.split("sources=",2).first
script=prefix+'specs='+specs.inspect+"\nfields=specs.map"+tail
script=script.gsub('office-context-v1','legacy-town-context-v1').gsub('.r06office.','.r06town.').gsub('r06office','r06town').gsub('minItems:8,maxItems:8','minItems:15,maxItems:15')
script+=<<~'CODE'
sources={'src/engine/legacy.ts'=>[[73,78],[196,201],[270,304]],'src/engine/history.ts'=>[[760,767]],'src/engine/factions.ts'=>[[423,431]],'src/content/legacyConfig.ts'=>[[101,113]],'src/content/buildingCatalog.ts'=>[[127,128]],'src/engine/reorganisation.types.ts'=>[[6,11]],'src/content/historyCopy.ko.ts'=>[[201,206]],'src/engine/historyNames.ts'=>[[15,20],[43,54]],'docs/design/glossary.md'=>[[11,21],[45,72],[189,192]]}.map{|path,spans|body=File.read(repo+'/'+path);{path:path,sha256:Digest::SHA256.hexdigest(body),spans:spans.map{|a,b|{start:a,end:b,text:body.lines[(a-1)...b].join}}}};write.call('SOURCE_EVIDENCE.json',sources)
holds=adds.select{|a|%w[legacy.market_fire legacy.nave_rebuilt].include?(a[:template])}.map{|a|{variantId:a[:variant][:id],status:'HOLD_COMPOSED_FACT_LINE_REVIEW',reason:a[:template]=='legacy.market_fire' ? 'Original cost is configured repair cost, not actual posted payment; no building fire operation in this event. Review configured versus paid and avoid physical damage claims.' : 'Original fact line claims new nave stood; producer only sets flag immediately after bounded cash post, without physical construction. Review paid/flag versus completed building language.',engineModified:false}}
write.call('ADOPTION_LIMITS.json',{allVariantsRequireVerifiedCapture:true,compositionHolds:holds,globalLimit:'Scheduled interlude and balance effects are game events, not additional historical source evidence. No fire scope, built nave or sales results were measured.',runtimeInstalled:false})
write.call('NOT_AUTHORED.json',{assigned:6,authored:6,notAuthored:[],fixedEventLimits:['Fire has no variable burn footprint in advanceInterlude; no extent variants authored.','Nave has no construction timing in answerLegacyPetition; no construction-stage variants authored.','Staple price multiplier is fixed; no arbitrary magnitude or profit variants authored.','Deposition historical headline is fixed; variants describe only source-proven game relation contribution.']})
write.call('BASELINE_REF.json',{path:'../../chronicle/variants.ko.json',sha256:Digest::SHA256.file(round+'/chronicle/variants.ko.json').hexdigest,modified:false})
CODE
File.write(r+'/build.rb',script)
