require 'json'
r=__dir__;source=File.read(File.expand_path('../office-context/build.rb',r));prefix=source.split('specs=[',2).first
specs=[
 ['person.came_of_age','parentsAtAdulthood',{'co_resident'=>'기록된 부모와 한 가구에서 지내던 아이가 성장의 고비를 맞았다.','not_co_resident'=>'기록된 부모와 함께 살지 않는 가구에서 아이가 성장의 고비를 맞았다.'},'src/engine/history.ts:392-406; src/engine/persons.types.ts:48-72; src/engine/persons.ts:85-87,233-237','At age-threshold emission bind subject person ID before/after, preserve birthYear, require before age<14 and after age>=14 at event years. Both motherId and fatherId must be distinct nonempty IDs and each resolve exactly once across after.persons.people and after.persons.past with explicit alive and nonempty householdId. Subject must belong to current people, alive=true, leftYear absent. A co-resident parent must belong to current people AND alive=true AND leftYear absent AND householdId equal subject; only then co_resident. A living parent in past, or any parent with leftYear, never qualifies even when historical householdId is equal. If both parents resolve but neither qualifies -> not_co_resident. Unknown/missing parent IDs -> unknown, never absent. No orphanhood, death cause, care quality or work start inferred; current ages/parents never backfill.'],
 ['milestone.stone_town','wallCompletionAtMilestone',{'all_complete'=>'석벽 사업 단계가 기록될 때, 성벽 구간들은 모두 완성 상태였다.','partly_complete'=>'석벽 사업 단계가 기록될 때, 완성된 성벽 구간과 미완성 구간이 함께 있었다.','none_complete'=>'석벽 사업 단계가 기록될 때, 아직 완성 상태인 성벽 구간은 없었다.'},'src/engine/history.ts:451-466; src/engine/era.ts:108-140; src/engine/engine.types.ts:32-43','At emitted milestone require era stone_town and nonempty after.palisade.segments with unique IDs and explicit boolean completed. All true/all false/mixed determine enum. Describe segment completed only, not replacementConstructionSiteId completion or material. Null/empty/inconsistent array unknown. No timber/stone material guess, no wall ring fully sealed inference.'],
 ['plague.priest_died','worshipBuildingsAtVacancy',{'present'=>'교회나 예배당이 있는 도시에 사제직 공석이 기록되었다.','absent'=>'교회와 예배당이 없는 도시에 사제직 공석이 기록되었다.'},'src/engine/plague.ts:511-522; src/engine/history.ts:649-651; src/content/buildingCatalog.ts:94,113','Require curacy newly present, vacantSince matches operation tick, match old template record. Count existing after.buildings whose kind church or chapel; positive present else absent. Complete valid building list required; construction sites excluded. This is building presence, never actual priest death/cause/worship cessation. No current-world backfill.'],
 ['ledger.l4','archivedL4Direction',{'increased'=>'보존된 집계에서 도시 대가옥 수가 늘었다.','decreased'=>'보존된 집계에서 도시 대가옥 수가 줄었다.','unchanged'=>'보존된 집계에서 도시 대가옥 수는 그대로였다.'},'src/content/historyCopy.ko.ts:336; src/engine/history.ts:468-491','For a real archived history record whose template is ledger.l4, validate original params.from and params.to as finite nonnegative safe integers. Compare to/from for increased/decreased/unchanged. Bind immutable record and campaign; do not calculate counts from present houses, infer period, cause, or producer identity. Real archive presence not established by this proposal; current checked save contains zero such records.']
]
tail=source.split('fields=specs.map',2).last.split('sources=',2).first
script=prefix+'specs='+specs.inspect+"\nfields=specs.map"+tail
script=script.gsub('office-context-v1','fixed-context-second-pass-v1').gsub('r06office','r06fixed').gsub('minItems:8,maxItems:8','minItems:10,maxItems:10')
script=script.sub("write.call('PROPOSAL.json',proposal)","fields.find{|f|f[:id]=='archivedL4Direction'}[:provenance]='immutable_record_params';write.call('PROPOSAL.json',proposal)")
script=script.gsub('obj(common.merge({template:{const:t}',"obj(common.merge({captureKind:{const:t=='ledger.l4' ? 'immutable_record_params' : 'emission_snapshot'},template:{const:t}")
script=script.sub("captureKind:'emission_snapshot',status:'known'","captureKind:t=='ledger.l4' ? 'immutable_record_params' : 'emission_snapshot',status:'known'")
script=script.sub("fixtures<<{id:a[:variant][:id]+'.known'", "identity[:params]=q[:value]=='increased' ? {from:0,to:1} : q[:value]=='decreased' ? {from:2,to:1} : {from:2,to:2} if t=='ledger.l4'\n fixtures<<{id:a[:variant][:id]+'.known'")
script+=<<~'CODE'
sources={'src/engine/persons.ts'=>[[85,87],[233,237]],'src/engine/history.ts'=>[[392,410],[451,466],[468,491],[649,651]],'src/engine/era.ts'=>[[108,140]],'src/engine/engine.types.ts'=>[[32,43]],'src/engine/persons.types.ts'=>[[48,72]],'src/engine/plague.ts'=>[[511,522]],'src/content/buildingCatalog.ts'=>[[94,95],[113,114]],'src/content/historyCopy.ko.ts'=>[[159,159],[328,328],[336,336],[356,356]],'src/engine/historyNames.ts'=>[[15,20],[43,54]],'docs/design/glossary.md'=>[[11,21],[189,192]]}.map{|path,spans|body=File.read(repo+'/'+path);{path:path,sha256:Digest::SHA256.hexdigest(body),spans:spans.map{|a,b|{start:a,end:b,text:body.lines[(a-1)...b].join}}}};write.call('SOURCE_EVIDENCE.json',sources)
write.call('ADOPTION_LIMITS.json',{allVariantsRequireVerifiedCapture:true,compositionHolds:adds.reject{|a|a[:template]=='ledger.l4'}.map{|a|{variantId:a[:variant][:id],status:'HOLD_BASELINE_FACT_LINE_REVIEW',reason:case a[:template];when 'person.came_of_age';'Baseline says started helping work, but producer checks age threshold only. Review combined output; no work assignment verified.';when 'milestone.stone_town';'Baseline stone city does not establish wall material or completion; review combined display with neutral stage wording.';else;'Baseline asserts priest died of plague, but producer only creates curacy vacancy. Neutral factline patch is separate and not presumed applied.';end,engineModified:false}},archiveCandidateLimit:'ledger.l4 has no emitter found in current searched source; one actual archive checked has zero records. Proposals are for validated original from/to only, no runtime reachability claim.',runtimeInstalled:false})
write.call('BASELINE_REF.json',{path:'../../chronicle/variants.ko.json',sha256:Digest::SHA256.file(round+'/chronicle/variants.ko.json').hexdigest,modified:false})
CODE
File.write(r+'/build.rb',script)
