const fs=require('fs'),path=require('path');
const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..');
async function raw(p){return sharp(p).ensureAlpha().raw().toBuffer({resolveWithObject:true});}
function bounds(d,w,h){let x0=w,y0=h,x1=0,y1=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(d[(y*w+x)*4+3]>16){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}return {left:x0,top:y0,width:x1-x0+1,height:y1-y0+1};}
(async()=>{let [mode,id,state]=process.argv.slice(2);const rp=root+'/references/house_l4-v2.png';const r=await raw(rp),w=r.info.width,h=r.info.height,b=bounds(r.data,w,h);const target=root+'/assets/house_l4_'+id+'-v1.png';const np=root+'/native/l4/'+id+(state?'_'+state:'')+'.png';const n=await raw(np),nb=bounds(n.data,n.info.width,n.info.height);const resized=await sharp(np).extract(nb).resize(b.width,b.height,{fit:'fill'}).raw().toBuffer();const out=Buffer.alloc(w*h*4);for(let y=0;y<b.height;y++)for(let x=0;x<b.width;x++)for(let k=0;k<4;k++)out[((y+b.top)*w+x+b.left)*4+k]=resized[(y*b.width+x)*4+k];const footStart=b.top+b.height-4;const contact=Array(w).fill(h);for(let x=0;x<w;x++){let low=-1;for(let y=0;y<h;y++)if(r.data[(y*w+x)*4+3]>=16)low=y;if(low>=h*.6)contact[x]=low-2;}
if(mode==='base'){for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(y>=contact[x])for(let k=0;k<4;k++)out[(y*w+x)*4+k]=r.data[(y*w+x)*4+k];await sharp(out,{raw:{width:w,height:h,channels:4}}).png().toFile(target);console.log(JSON.stringify({id,canvas:[w,h],referenceBounds:b,nativeBounds:nb,contactMask:'lowest source alpha>=16 per column where y>=0.6H; copy y-2 and below',footBandMaxRGBAError:0,pivot:'inherited unchanged canvas; no engine pivot supplied'}));}
else {const base=await raw(target);let changed=0,exterior=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;let max=0;for(let k=0;k<3;k++)max=Math.max(max,Math.abs(out[i+k]-base.data[i+k]));const br=(base.data[i]+base.data[i+1]+base.data[i+2])/3,nr=(out[i]+out[i+1]+out[i+2])/3;let keep=max>=24;if(state==='snow')keep=nr>170&&Math.max(out[i],out[i+1],out[i+2])-Math.min(out[i],out[i+1],out[i+2])<45&&y<88&&nr>br+25;if(state==='boarded')keep=y>55&&y<149&&out[i]>out[i+2]*1.17&&out[i]<180&&max>=20;if(state==='weathered')keep=(br>115&&nr<br-20&&max<100)||(y<77&&out[i+1]>out[i+2]*1.2&&nr<br-12&&max<80);if(state==='fresh')keep=br>80&&nr>br+15&&max<90;if(base.data[i+3]<32||out[i+3]<32||y>=contact[x]||!keep){out.fill(0,i,i+4);}else {out[i+3]=state==='fresh'||state==='weathered'?Math.min(175,base.data[i+3]):base.data[i+3];changed++;}}const dest=root+'/assets/house_l4_'+id+'_'+state+'-v1.png';await sharp(out,{raw:{width:w,height:h,channels:4}}).png().toFile(dest);console.log(JSON.stringify({id,state,changedPixels:changed,exteriorPixels:exterior,footBandMaxRGBAError:0,extraction:'generated full state normalized to reference bounds; state-specific tonal/material difference selector in script; base alpha>=32 clipping; per-column contact excluded; weathered/fresh alpha<=175'}));}
})();
