const fs=require('fs'),path=require('path');const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');const{createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');
const R=path.resolve(__dirname,'..'),A=R+'/assets';const ref=n=>R+'/references/house_l'+n+(n===0?'-v3.png':'-v2.png');
function board(w,h){let c=createCanvas(w,h),g=c.getContext('2d');g.fillStyle='#6f7866';g.fillRect(0,0,w,h);return[c,g]}
function text(g,s,x,y,size=16){g.font=size+'px sans-serif';g.fillStyle='#fff8e7';g.textAlign='left';g.fillText(s,x,y)}
async function asset(g,p,x,y,w,h){if(!fs.existsSync(p))return;let im=await loadImage(p);g.drawImage(im,x,y,w??im.width,h??im.height)}
(async()=>{let[c,g]=board(1250,1080);text(g,'Wave26 · 등급별 기존1 + 변형4 / 후보·게임 미설치',25,32,23);let heads=['기존 원본','c','d','e','f'];heads.forEach((s,i)=>text(g,s,90+i*235,68));for(let n=0;n<5;n++){text(g,'L'+n,12,180+n*195,20);for(let i=0;i<5;i++){let p=i===0?ref(n):A+'/house_l'+n+'_'+heads[i]+'-v1.png';let m=await sharp(ref(n)).metadata();await asset(g,p,65+i*235+(170-m.width)/2,78+n*195+(170-m.height),m.width,m.height);}}fs.writeFileSync(R+'/proofs/01-level-variants.png',c.toBuffer('image/png'));
let layout=JSON.parse(fs.readFileSync(R+'/records/city-layout.json'));let source=await sharp(R+'/'+layout.source).ensureAlpha().raw().toBuffer();let clean=await sharp(R+'/native/city-cleanplate.png').resize(960,600,{fit:'fill'}).ensureAlpha().raw().toBuffer();let[m,mg]=board(960,600);mg.clearRect(0,0,960,600);mg.fillStyle='white';for(const s of layout.sites){mg.beginPath();let pts=[[.00,.33],[.20,0],[.88,.22],[1,.43],[.95,.50],[.95,.93],[.54,1],[.05,.76],[.05,.42]];pts.forEach(([u,v],i)=>i?mg.lineTo(s.x+u*s.w,s.y+v*s.h):mg.moveTo(s.x+u*s.w,s.y+v*s.h));mg.closePath();mg.fill();}const mask=mg.getImageData(0,0,960,600).data;let mixed=Buffer.from(source),count=0;for(let i=0;i<960*600;i++){if(mask[i*4+3]){count++;let a=mask[i*4+3]/255;for(let k=0;k<3;k++)mixed[i*4+k]=Math.round(source[i*4+k]*(1-a)+clean[i*4+k]*a)}}let mixedPNG=await sharp(mixed,{raw:{width:960,height:600,channels:4}}).png().toBuffer();let town=createCanvas(960,600),tg=town.getContext('2d');tg.drawImage(await loadImage(mixedPNG),0,0);let assignments=[];for(const s of [...layout.sites].sort((a,b)=>(a.y+a.h)-(b.y+b.h))){let p=A+'/house_l'+s.level+'_'+s.variant+'-v1.png';if(!fs.existsSync(p))continue;const raw=await sharp(p).ensureAlpha().raw().toBuffer({resolveWithObject:true});let x0=raw.info.width,y0=raw.info.height,x1=0,y1=0;for(let y=0;y<raw.info.height;y++)for(let x=0;x<raw.info.width;x++)if(raw.data[(y*raw.info.width+x)*4+3]>=16){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y)}const scale=Math.min(s.w*.88/(x1-x0+1),s.h*.94/(y1-y0+1));const dx=s.x+s.w/2-(x0+x1+1)/2*scale,dy=s.y+s.h-(y1+1)*scale;tg.drawImage(await loadImage(p),dx,dy,raw.info.width*scale,raw.info.height*scale);assignments.push({file:path.basename(p),...s,uniform_scale:scale,draw_xy:[dx,dy]})}
// Preserve original HUD above rebuilt residential layer.
const orig=await loadImage(R+'/'+layout.source);for(const[x,y,w,h]of[[0,0,326,45],[260,57,249,49],[805,0,155,86],[0,554,193,46],[697,517,263,83]])tg.drawImage(orig,x,y,w,h,x,y,w,h);
let[p,pg]=board(1960,1100);text(pg,'같은 캡처 구성 · 기존 / 변형 오프라인 합성 (실제 게임 적용 아님)',20,30,24);text(pg,'첨부 원본 · 1.0',20,62);text(pg,'동일 주택 위치 교체 · 1.0',1000,62);pg.drawImage(orig,20,76);pg.drawImage(town,1000,76);text(pg,'0.6',212,709);text(pg,'0.6',1192,709);pg.drawImage(orig,212,725,576,360);pg.drawImage(town,1192,725,576,360);fs.writeFileSync(R+'/proofs/02-city-repetition.png',p.toBuffer('image/png'));fs.writeFileSync(R+'/records/city-composite-qa.json',JSON.stringify({source_dimensions:[960,600],sites:assignments.length,assignments,mask_pixels:count,source_pixels_outside_mask:'preserved before overlaying new house sprites',proof:'offline approximate screenshot reconstruction; visually inferred levels, not saved game state; no background changes outside house masks except new sprite silhouette'},null,2));
let[z,zg]=board(2040,1410);text(zg,'상태 합성 · 기본 / 낡음 / 새것 / 눈 / 빈집 · 각 그룹 동일 캔버스·접지',20,32,23);for(let n=0;n<5;n++)for(let i=0;i<4;i++){let v='cdef'[i],x=20+i*505,y=65+n*265;let base=A+'/house_l'+n+'_'+v+'-v1.png';text(zg,'L'+n+' · '+v,x,y);let states=['','weathered','fresh','snow','boarded'];for(let j=0;j<5;j++){let p=states[j]?A+'/house_l'+n+'_'+v+'_'+states[j]+'-v1.png':null;let sz=96;await asset(zg,base,x+j*98,y+20,sz,sz);if(p)await asset(zg,p,x+j*98,y+20,sz,sz);text(zg,['기본','낡음','새것','눈','빈집'][j],x+j*98,y+140,13);if(p&&fs.existsSync(p)){await asset(zg,p,x+j*98,y+155,72,72)}}}fs.writeFileSync(R+'/proofs/03-state-overlays.png',z.toBuffer('image/png'));console.log('proofs3 written');})();
