const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('/Users/rexxa/.npm/_npx/8b377f6eec906bc4/node_modules/sharp/lib/index.js');
const root=path.resolve(__dirname,'..'); const sources=require('./raw-sources.json'),specs=require('./generation-specs.json');
const sizes=[[128,96],[128,96],[256,128],[512,64],[128,96],[256,192]];
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{const manifest=[],records=[];for(let i=0;i<6;i++){const s=sources[i], [w,h]=sizes[i],raw=path.join(root,'raw',s.id+'.png');fs.copyFileSync(s.source,raw);let img=sharp(raw);let meta=await img.metadata();let input=await img.ensureAlpha().raw().toBuffer({resolveWithObject:true});let minY=input.info.height,maxY=0;for(let y=0;y<input.info.height;y++)for(let x=0;x<input.info.width;x++)if(input.data[(y*input.info.width+x)*4+3]>10){minY=Math.min(minY,y);maxY=Math.max(maxY,y);}if(i===3)img=img.extract({left:0,top:Math.max(0,minY-8),width:meta.width,height:Math.min(meta.height,maxY-minY+17)});let {data,info}=await img.resize(w,h,{fit:'contain',background:{r:0,g:0,b:0,alpha:0}}).ensureAlpha().raw().toBuffer({resolveWithObject:true});if(i===3){const n=16;for(let y=0;y<h;y++)for(let k=0;k<n;k++)for(let c=0;c<4;c++){const a=(y*w+k)*4+c,b=(y*w+w-1-k)*4+c,avg=(data[a]+data[b])/2,t=(n-k)/n;data[a]=Math.round(data[a]*(1-t)+avg*t);data[b]=Math.round(data[b]*(1-t)+avg*t);}}
let hidden=0;for(let p=0;p<data.length;p+=4)if(data[p+3]===0){data[p]=data[p+1]=data[p+2]=0;}
const file='assets/'+s.id+'.png';await sharp(data,{raw:{width:w,height:h,channels:4}}).png({compressionLevel:9}).toFile(path.join(root,file));let seam=0;if(i===3)for(let y=0;y<h;y++)for(let c=0;c<4;c++)seam=Math.max(seam,Math.abs(data[(y*w)*4+c]-data[(y*w+w-1)*4+c]));
manifest.push({id:s.id,file,width:w,height:h,pivot:{x:w/2,y:i===3?h-4:Math.round(h*.87)},summer_reference:null,winter_reference:null,status:'candidate',tile:i===3?'X':'none',suggested_world_width:[28,28,128,256,9,72][i],note:'신규 봄 전용 소품. 다른 계절 대응 원본 없음. 여름·겨울 기준 장면에서는 부재. 캔버스 픽셀과 월드 크기는 별개.'});
records.push({id:s.id,status:'candidate',tool:'builtin image_gen.imagegen',model:null,seed:null,prompt:specs[i].prompt,raw_file:'raw/'+s.id+'.png',raw_sha256:hash(raw),source_generated_path:s.source,raw_width:meta.width,raw_height:meta.height,references:specs[i].refs.map(p=>({source:p,file:'references/'+path.basename(p),sha256:hash(p)})),file,sha256:hash(path.join(root,file)),postprocessing:i===3?'Alpha-bbox vertical crop; Lanczos contain resize; symmetric premultiplication-free 16px border equalization; zero RGB at alpha=0':'Lanczos contain resize preserving aspect and alpha; zero RGB at alpha=0',width:w,height:h,alpha_zero_rgb_nonzero:hidden,x_seam_max_diff:i===3?seam:null});}
fs.writeFileSync(path.join(root,'manifest.json'),JSON.stringify(manifest,null,2));fs.writeFileSync(path.join(root,'records/provenance.json'),JSON.stringify(records,null,2));
for(const [name,bg] of [['bright','#e6dfc7'],['dark','#252b28']]){const comps=[];for(let i=0;i<6;i++){const m=manifest[i],x=(i%2)*550+15,y=Math.floor(i/2)*235+25;comps.push({input:path.join(root,m.file),left:x,top:y});}await sharp({create:{width:1100,height:705,channels:3,background:bg}}).composite(comps).jpeg({quality:92}).toFile(path.join(root,'proofs/actual-size-'+name+'.jpg'));}
const hedge=await sharp(path.join(root,manifest[3].file)).toBuffer();await sharp({create:{width:1536,height:64,channels:4,background:'#ddd8c0'}}).composite([0,512,1024].map(left=>({input:hedge,left,top:0}))).png().toFile(path.join(root,'proofs/hawthorn-repeat-3x.png'));
await sharp(path.join(root,'proofs/actual-size-bright.jpg')).resize(2200,1410,{kernel:'nearest'}).jpeg({quality:94}).toFile(path.join(root,'proofs/detail-2x.jpg'));
console.log(JSON.stringify(records.map(r=>({id:r.id,w:r.width,h:r.height,seam:r.x_seam_max_diff})),null,2));})();
