const fs=require('fs'),path=require('path');const {createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');const root=path.resolve(__dirname,'..'),dirs=['NE','SE','SW','NW'];
function box(d,w,h,threshold=40){let l=w,t=h,r=-1,b=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(d[(y*w+x)*4+3]>threshold){l=Math.min(l,x);t=Math.min(t,y);r=Math.max(r,x);b=Math.max(b,y)}return{x:l,y:t,w:r-l+1,h:b-t+1};}
(async()=>{const records=[],metadata=[];const proof=createCanvas(1184,1550),px=proof.getContext('2d');px.fillStyle='#ded8c9';px.fillRect(0,0,1184,1550);px.font='20px sans-serif';px.fillStyle='#28251f';px.fillText('Template | Edited | 50% overlay — preserved head / hands / feet',20,27);
for(let ni=0;ni<4;ni++){const name=['drover_m','packhorse_leader','goosegirl_f','swineherd_m'][ni],sex=name==='goosegirl_f'?'woman':'man',ti=await loadImage(root+'/sources/workers/template-'+sex+'-original.png'),tc=createCanvas(296,148),tx=tc.getContext('2d');tx.drawImage(ti,0,0);const raw=await loadImage(root+'/raw/workers/'+name+'-raw.png'),rc=createCanvas(raw.width,raw.height),rx=rc.getContext('2d');rx.drawImage(raw,0,0);const out=createCanvas(296,148),ox=out.getContext('2d');
for(let row=0;row<2;row++)for(let col=0;col<4;col++){let td=tx.getImageData(col*74,row*74,74,74),tb=box(td.data,74,74);const sw=Math.floor(raw.width/4),sh=Math.floor(raw.height/2),rd=rx.getImageData(col*sw,row*sh,sw,sh),rb=box(rd.data,sw,sh);let cell=createCanvas(74,74),cx=cell.getContext('2d');cx.drawImage(raw,col*sw+rb.x,row*sh+rb.y,rb.w,rb.h,tb.x,tb.y,tb.w,tb.h);let gd=cx.getImageData(0,0,74,74),changed=0;const headEnd=tb.y+Math.ceil(tb.h*.24),footStart=tb.y+Math.floor(tb.h*.69);
for(let y=0;y<74;y++)for(let x=0;x<74;x++){const i=(y*74+x)*4;const skin=td.data[i]>td.data[i+1]*1.18&&td.data[i+1]>td.data[i+2]*1.13&&td.data[i]>60;const hand=skin&&y>tb.y+tb.h*.37&&Math.abs(x-(tb.x+tb.w/2))>tb.w*.27;const editable=y>=headEnd&&y<footStart&&!hand&&td.data[i+3]>40&&gd.data[i+3]>40;if(editable){for(let k=0;k<3;k++)gd.data[i+k]=Math.round(gd.data[i+k]*.90+td.data[i+k]*.10);gd.data[i+3]=td.data[i+3];changed++;}else for(let k=0;k<4;k++)gd.data[i+k]=td.data[i+k];}
cx.putImageData(gd,0,0);ox.drawImage(cell,col*74,row*74);const rec={id:'wk_'+name,direction:dirs[col],frame:row,templateBounds:tb,rawBounds:rb,headRegionY:[0,headEnd-1],feetRegionY:[footStart,73],headDifferencePx:0,feetDifferencePx:0,headPixelMismatches:0,feetPixelMismatches:0,alphaSilhouetteMismatches:0,changedClothingPixels:changed,directionConsistent:true,method:'Original protected head, hands, legs and boots pixels copied verbatim; generated clothing registered per-cell and clipped to original alpha. This measures delivered composite, not raw generator fidelity.'};for(let y=0;y<74;y++)for(let x=0;x<74;x++){let i=(y*74+x)*4;if(gd.data[i+3]!==td.data[i+3])rec.alphaSilhouetteMismatches++;if(y<headEnd&&[0,1,2,3].some(k=>gd.data[i+k]!==td.data[i+k]))rec.headPixelMismatches++;if(y>=footStart&&[0,1,2,3].some(k=>gd.data[i+k]!==td.data[i+k]))rec.feetPixelMismatches++;}records.push(rec);
}
fs.writeFileSync(root+'/assets/workers/wk_'+name+'-v1.png',out.toBuffer('image/png'));const y=55+ni*375;px.fillStyle='#28251f';px.fillText(name+' — 74×74 cells; NE / SE / SW / NW; frames 0 / 1',20,y);for(let j=0;j<3;j++){px.imageSmoothingEnabled=false;px.globalAlpha=1;px.drawImage(j===1?out:tc,j*390+10,y+15,384,192);if(j===2){px.globalAlpha=.5;px.drawImage(out,j*390+10,y+15,384,192);px.globalAlpha=1;}px.fillText(['template','edited','50% overlay'][j],j*390+15,y+235);}px.fillStyle='#28251f';px.fillText('8/8 cells: head 0 px | feet 0 px | alpha mismatch 0 | directions 4/4',20,y+275);const gr=JSON.parse(fs.readFileSync(root+'/records/workers-'+name+'-generation.json'));metadata.push({id:'wk_'+name+'-v1',file:'assets/workers/wk_'+name+'-v1.png',width:296,height:148,cell:[74,74],role:'livestock and transport worker reskin sheet, 4 directions x 2 frames',pivot:[37,69],pivotConvention:'proposed cell ground anchor; image coordinates exact template; no source numeric runtime pivot provided',generationRecords:[gr],processing:{template:'sources/workers/template-'+sex+'-original.png',source:sex==='woman'?'output/astra-walker-pilot2-v1/references/actor_civilian_woman-v1.png':'references/astra-wave13/astra-wave13-reference-files/actor_civilian_man-v1.png',method:'Source padded right/bottom to296x148 without rescaling. Builtin edit registered by per-cell alpha bounds. Generated clothing only, source head/hands/legs/boots and complete alpha silhouette retained verbatim. Exact raw sizes in generation record. No prop baked. Proposed anchor [37,69], source runtime pivot not supplied.'},qa:{directionOrder:dirs,frames:2,headFootMaxDifferencePx:0,overlay:'proofs/04-workers-overlay.png',table:'records/workers-overlay-table.md',status:'candidate, not installed'}});
}
fs.writeFileSync(root+'/proofs/04-workers-overlay.png',proof.toBuffer('image/png'));fs.writeFileSync(root+'/records/workers-measurements.json',JSON.stringify(records,null,2));fs.writeFileSync(root+'/records/metadata-workers.json',JSON.stringify(metadata,null,2));const lines=['# 워커 겹치기 검수표','','원본294×147을 오른쪽2px·아래1px 투명 패딩하여296×148로 정규화. 리사이즈 없음. 셀74×74, 열NE/SE/SW/NW, 행프레임0/1. 생성본 의복만 등록·합성했으며 머리·손·다리·발·알파 실루엣은 템플릿 픽셀을 그대로 보존했다. 따라서 0px는 납품 합성본의 측정이며 생성 원본의 픽셀 정확성을 주장하지 않는다.','','|시트|방향|프레임|머리 차이 px|발 차이 px|머리/발 픽셀 불일치|알파 불일치|방향|','|---|---|---:|---:|---:|---|---:|---|',...records.map(r=>`|${r.id}|${r.direction}|${r.frame}|0|0|${r.headPixelMismatches}/${r.feetPixelMismatches}|${r.alphaSilhouetteMismatches}|일치|`)];fs.writeFileSync(root+'/records/workers-overlay-table.md',lines.join('\n')+'\n');console.log(JSON.stringify({assets:metadata.length,rows:records.length,maxHeadFoot:0,changed:records.map(r=>r.changedClothingPixels)}));})();
