const fs=require('fs'),path=require('path'),crypto=require('crypto'),sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),csv=x=>'"'+String(x??'').replaceAll('"','""')+'"';
const ko={baker:'빵집',smith:'대장간',weaver:'직조',dyer:'염색',tanner:'무두장이',ale:'에일',miller:'방앗간 일꾼',carpenter:'목수',merchant:'상인',shepherd:'목동',fisher:'어부',inn:'여관'};
async function main(){const records=['trades-a','trades-b','trades-c','conditions'].flatMap(n=>{let a=JSON.parse(fs.readFileSync(path.join(root,'records',n+'.json')));return Array.isArray(a)?a:a.assets;});if(records.length!==32)throw Error('record count '+records.length);
let rows=[['asset_id','category','trade_or_condition','variant','width','height','foot_x','foot_y','foot_method','foot_uncertainty_px','lighting','flipped','status','sha256','record','postprocess']];const checks=[];
for(const a of records){const id=a.id,f=path.join(root,'assets',id+'.png'),{data,info}=await sharp(f).ensureAlpha().raw().toBuffer({resolveWithObject:true});let n=0,edge=0,leak=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const j=(y*info.width+x)*4;if(data[j+3]>0){n++;if(x===0||y===0||x===info.width-1||y===info.height-1)edge++;}else if(data[j]||data[j+1]||data[j+2])leak++;}
const category=id.startsWith('trade_')?'trade':'condition',name=category==='trade'?ko[id.split('_')[1]]:({prosperous:'넉넉함',ordinary:'보통',strained:'빠듯함',newcomer:'새 입주'}[id.split('_')[1]]),width=info.width,height=info.height;
if(!(width>=64&&width<=128&&height>=64&&height<=96))throw Error('size '+id);
if(!Number.isFinite(a.foot_x)||!Number.isFinite(a.foot_y))throw Error('foot missing '+id);
checks.push({id,width,height,nonzero_alpha:n,canvas_edge_alpha:edge,transparent_rgb_nonzero:leak,foot_in_canvas:a.foot_x>=0&&a.foot_x<width&&a.foot_y>=0&&a.foot_y<height});
rows.push([id,category,name,(/_[ab]$/.test(id)?id.slice(-1):'single'),width,height,a.foot_x,a.foot_y,a.foot_method,a.foot_uncertainty_px,'upper-left requested; visual review',false,'candidate',sha(fs.readFileSync(f)),category==='condition'?'records/conditions.json':a.record_file||'records/trades-'+(['baker','smith','weaver','dyer'].includes(id.split('_')[1])?'a':['tanner','ale','miller','carpenter'].includes(id.split('_')[1])?'b':'c')+'.json',typeof a.postprocess==='object'?JSON.stringify(a.postprocess):a.postprocess]);}
fs.writeFileSync(path.join(root,'assets.csv'),rows.map(r=>r.map(csv).join(',')).join('\n')+'\n');fs.writeFileSync(path.join(root,'qa/structural-checks.json'),JSON.stringify({count:32,checks},null,2));
const imgs=['proofs/01-city-context.jpg','proofs/02-blind-trades.jpg','proofs/03-zoom-06.jpg','qa/all-assets.jpg',...records.map(a=>'assets/'+a.id+'.png')];fs.writeFileSync(path.join(root,'INDEX.md'),'# Wave37 개별 이미지\n\n'+imgs.map(f=>`- [${f}](${f})`).join('\n')+'\n');fs.writeFileSync(path.join(root,'index.html'),'<!doctype html><meta charset="utf-8"><title>Wave37 후보</title><style>body{font:16px sans-serif;background:#e8ddc4;color:#30291f}figure{display:inline-block;width:240px;vertical-align:top}img{max-width:230px;max-height:200px}a{color:#513a1d}</style><h1>Wave37 집 앞 직업·형편 표지</h1><p>후보 · 게임 미설치 · <a href="REPORT.md">보고서</a> · <a href="assets.csv">CSV</a></p>'+imgs.map(f=>`<figure><a href="${f}"><img loading="lazy" src="${f}"><figcaption>${f}</figcaption></a></figure>`).join(''));
console.log(JSON.stringify({count:records.length,edge_touch:checks.filter(c=>c.canvas_edge_alpha).map(c=>c.id),foot_invalid:checks.filter(c=>!c.foot_in_canvas).map(c=>c.id)}));}
main().catch(e=>{console.error(e);process.exit(1)});
