const fs=require('fs'),path=require('path'),crypto=require('crypto'),sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..'),bg='#78836d',trades=['baker','smith','weaver','dyer','tanner','ale','miller','carpenter','merchant','shepherd','fisher','inn'];
const text=(s,w=240)=>Buffer.from(`<svg width="${w}" height="24"><text x="5" y="17" fill="#fcf7e8" font-family="sans-serif" font-size="13">${s}</text></svg>`);
let seed=20260930;function rng(){seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;}
async function tile(id,z=1){const base=await sharp(path.join(root,'references/house-l2.png')).ensureAlpha().raw().toBuffer({resolveWithObject:true}),m=await sharp(path.join(root,'assets',id+'.png')).metadata(),pw=Math.round(m.width*.45),ph=Math.round(m.height*.45),prop=await sharp(path.join(root,'assets',id+'.png')).resize(pw,ph).png().toBuffer();
 // Both entire rectangles are disjoint, providing stronger separation than alpha overlap alone.
 const layers=[{input:path.join(root,'references/house-l2.png'),left:22,top:5},{input:prop,left:162,top:143-ph}];
 const im=await sharp({create:{width:235,height:175,channels:3,background:bg}}).composite(layers).png().toBuffer();return sharp(im).resize(Math.round(235*z),Math.round(175*z)).png().toBuffer();}
async function main(){let order=[...trades];for(let i=11;i>0;i--){let j=Math.floor(rng()*(i+1));[order[i],order[j]]=[order[j],order[i]];}
const keys=[],layers=[],small=[];fs.mkdirSync(path.join(root,'blind'),{recursive:true});
for(let i=0;i<12;i++){const id='trade_'+order[i]+'_a',num=String(i+1).padStart(2,'0'),im=await tile(id),imSmall=await tile(id,.6);fs.writeFileSync(path.join(root,'blind',num+'.png'),im);keys.push({slot:num,trade:order[i],asset:id,zoom:1,native_sprite_scale:.45});layers.push({input:im,left:i%4*250,top:Math.floor(i/4)*200+24},{input:text(num),left:i%4*250,top:Math.floor(i/4)*200});small.push({input:imSmall,left:i%4*160,top:Math.floor(i/4)*130+24},{input:text(num,150),left:i%4*160,top:Math.floor(i/4)*130});}
await sharp({create:{width:1000,height:600,channels:3,background:bg}}).composite(layers).jpeg({quality:96}).toFile(path.join(root,'proofs/02-blind-trades.jpg'));
await sharp({create:{width:640,height:390,channels:3,background:bg}}).composite(small).jpeg({quality:96}).toFile(path.join(root,'proofs/03-zoom-06.jpg'));
const smallIds=[...order.map(t=>'trade_'+t+'_a'),...order.map(t=>'trade_'+t+'_b'),...fs.readdirSync(path.join(root,'assets')).filter(f=>f.startsWith('condition_')).sort().map(f=>f.replace('.png',''))],smallAll=[];for(let i=0;i<smallIds.length;i++){smallAll.push({input:await tile(smallIds[i],.6),left:i%6*160,top:Math.floor(i/6)*130+24},{input:text(String(i+1).padStart(2,'0'),150),left:i%6*160,top:Math.floor(i/6)*130});}await sharp({create:{width:960,height:Math.ceil(smallIds.length/6)*130,channels:3,background:bg}}).composite(smallAll).jpeg({quality:96}).toFile(path.join(root,'proofs/03-zoom-06.jpg'));fs.writeFileSync(path.join(root,'records/zoom06-map.json'),JSON.stringify(smallIds.map((id,i)=>({slot:i+1,id})),null,2));
fs.writeFileSync(path.join(root,'records/blind-key.json'),JSON.stringify({shuffle_seed:20260930,house:'same reference house for all',choices:keys},null,2));
const all=fs.readdirSync(path.join(root,'assets')).filter(f=>f.endsWith('.png')).sort(),contact=[];for(let i=0;i<all.length;i++){const b=await sharp(path.join(root,'assets',all[i])).resize(128,96,{fit:'contain',background:'#78836d'}).png().toBuffer();contact.push({input:b,left:i%4*250+40,top:Math.floor(i/4)*135+24},{input:text(all[i].replace('.png',''),245),left:i%4*250,top:Math.floor(i/4)*135});}await sharp({create:{width:1000,height:Math.ceil(all.length/4)*135,channels:3,background:bg}}).composite(contact).jpeg({quality:96}).toFile(path.join(root,'qa/all-assets.jpg'));
// Supplied screenshot remains unchanged except these freestanding overlays.
const placements=[['trade_inn_a',862,249],['trade_baker_a',729,250]],city=[];
for(const[id,x,y]of placements){const p=path.join(root,'assets',id+'.png'),m=await sharp(p).metadata(),w=Math.round(m.width*.24),h=Math.round(m.height*.24);city.push({input:await sharp(p).resize(w,h).toBuffer(),left:x,top:y-h});}
const cityBuffer=await sharp(path.join(root,'references/reference-1.jpg')).composite(city).png().toBuffer(); await sharp(cityBuffer).jpeg({quality:96}).toFile(path.join(root,'qa/city-full.jpg'));const cityBoard=[{input:cityBuffer,left:0,top:0}]; for(const [n,left,top,x] of [['A',680,180,20],['B',790,190,620]]){cityBoard.push({input:await sharp(cityBuffer).extract({left,top,width:210,height:140}).resize(504,336).toBuffer(),left:x,top:785},{input:text('Offline crop '+n+' 2.4x',540),left:x,top:755});}await sharp({create:{width:1200,height:1130,channels:3,background:bg}}).composite(cityBoard).jpeg({quality:95}).toFile(path.join(root,'proofs/01-city-context.jpg'));
fs.writeFileSync(path.join(root,'records/proof-placements.json'),JSON.stringify({status:'offline candidate composite; no installation',zoom1_sprite_scale:.45,city_reported_zoom:1.4,city_pixel_sprite_scale:.24,city_placements:placements,blind_house_rect:[22,5,137,137],blind_prop_left:162,minimum_rect_gap_px:3,mirror:false,note:'City contact evaluated visually. Engine pivots and world renderer scale not supplied; chosen fixed proof scale disclosed. City supplied image is rescaled: local house width about60px vs reference114px yields .45*(60/114) approximately .24; not multiplied by nominal zoom again.'},null,2));
console.log('proofs generated; blind frozen');}
main().catch(e=>{console.error(e);process.exit(1)});
