// Generated by scripts/registerVariantOverlays.py: per-variant registration of the house condition overlays.
// variant point = scale * base point + (dx, dy), in the base painting's authored pixels.
export const BUILDING_VARIANT_OVERLAY_REGISTRATION = [
  {
    "url": "assets/buildings/variants-wave2/house_l0_garden-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l0-v3.png",
    "scale": 0.89,
    "dx": 24.6,
    "dy": 122.9,
    "roofIou": 0.714
  },
  {
    "url": "assets/buildings/variants-wave2/house_l0_pen-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l0-v3.png",
    "scale": 0.75,
    "dx": 57.4,
    "dy": 204.9,
    "roofIou": 0.789
  },
  {
    "url": "assets/buildings/variants-wave2/house_l1_artisan-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l1-v2.png",
    "scale": 0.95,
    "dx": 45.1,
    "dy": 54.1,
    "roofIou": 0.91
  },
  {
    "url": "assets/buildings/variants-wave2/house_l1_garden-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l1-v2.png",
    "scale": 0.77,
    "dx": 45.1,
    "dy": 198.5,
    "roofIou": 0.789
  },
  {
    "url": "assets/buildings/variants-wave2/house_l2_brewer-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l2-v2.png",
    "scale": 0.84,
    "dx": 27.5,
    "dy": 173.9,
    "roofIou": 0.821
  },
  {
    "url": "assets/buildings/variants-wave2/house_l2_garden-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l2-v2.png",
    "scale": 0.86,
    "dx": -9.2,
    "dy": 137.3,
    "roofIou": 0.772
  },
  {
    "url": "assets/buildings/variants-wave2/house_l2_weaver-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l2-v2.png",
    "scale": 0.85,
    "dx": 18.3,
    "dy": 73.2,
    "roofIou": 0.79
  },
  {
    "url": "assets/buildings/variants-wave2/house_l3_clothier-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l3-v2.png",
    "scale": 0.85,
    "dx": 44.2,
    "dy": 132.5,
    "roofIou": 0.705
  },
  {
    "url": "assets/buildings/variants-wave2/house_l3_shop-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l3-v2.png",
    "scale": 0.92,
    "dx": 79.5,
    "dy": 97.1,
    "roofIou": 0.637
  },
  {
    "url": "assets/buildings/variants-wave2/house_l3_storage-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l3-v2.png",
    "scale": 0.85,
    "dx": 17.7,
    "dy": 141.3,
    "roofIou": 0.712
  },
  {
    "url": "assets/buildings/variants-wave2/house_l4_courtyard-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l4-v2.png",
    "scale": 0.93,
    "dx": 93.5,
    "dy": 54.5,
    "roofIou": 0.689
  },
  {
    "url": "assets/buildings/variants-wave2/house_l4_inn-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l4-v2.png",
    "scale": 0.93,
    "dx": 0.0,
    "dy": 124.6,
    "roofIou": 0.692
  },
  {
    "url": "assets/buildings/variants-wave2/house_l4_wing-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_l4-v2.png",
    "scale": 0.96,
    "dx": 0.0,
    "dy": 38.9,
    "roofIou": 0.771
  },
  {
    "url": "assets/buildings/variants-wave2/house_pair_l3_horizontal_courtyard-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_pair_l3_horizontal-v2.png",
    "scale": 0.85,
    "dx": 20.1,
    "dy": 134.2,
    "roofIou": 0.387
  },
  {
    "url": "assets/buildings/variants-wave2/house_pair_l3_vertical_workshop-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_pair_l3_vertical-v2.png",
    "scale": 1.01,
    "dx": 20.6,
    "dy": 13.7,
    "roofIou": 0.481
  },
  {
    "url": "assets/buildings/variants-wave2/house_pair_l4_horizontal_hall-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_pair_l4_horizontal-v2.png",
    "scale": 0.9,
    "dx": 30.7,
    "dy": 178.3,
    "roofIou": 0.439
  },
  {
    "url": "assets/buildings/variants-wave2/house_pair_l4_vertical_court-v1.png",
    "baseUrl": "assets/buildings/historical-houses/house_pair_l4_vertical-v2.png",
    "scale": 0.92,
    "dx": 20.4,
    "dy": 75.0,
    "roofIou": 0.581
  }
] as const;
