// Generated by scripts/buildBuildingSpriteFit.ts — alpha (>= 128) bounds of the fitted building sprites, meta px.
export const BUILDING_SPRITE_ALPHA = {
  well: { width: 72, height: 80, alpha: { x: 13, y: 3, width: 47, height: 62 } }, // /assets/buildings/well.png
  logging_camp: { width: 96, height: 104, alpha: { x: 5, y: 7, width: 87, height: 82 } }, // /assets/buildings/logging_camp.png
  storehouse: { width: 160, height: 136, alpha: { x: 11, y: 5, width: 139, height: 116 } }, // /assets/buildings/storehouse.png
  barn: { width: 160, height: 144, alpha: { x: 31, y: 3, width: 99, height: 126 } }, // /assets/buildings/barn.png
  farmstead: { width: 160, height: 136, alpha: { x: 13, y: 14, width: 134, height: 111 } }, // assets/buildings/farmstead/farmstead_a-v1.png
} as const;
