// Player-facing copy of the selection diagnostic card (house, walker, construction site, facility).
export const DIAGNOSTIC_CARD_COPY = {
  houseSummary: (level: number, residents: number, capacity: number, footprint: string) =>
    `생활 등급 ${level} · 주민 ${residents}명 / 정원 ${capacity}명 · ${footprint}칸`,
  builtStageTerm: '건축 단계',
  builtStage: (stage: number, condition: string) => `${stage}단계 · ${condition}`,
  waterTerm: '물',
  breadTerm: '빵',
  populationTerm: '인구',
  developmentSummary: '주택 발전 조건',
  protectionTerm: '성벽',
  marketTerm: '시장',
  churchTerm: '교회',
  stoneHouseTerm: '도시 대가옥',
  mergeHeading: '인접 주택 합필',
  demolishWarning: (residents: number) => `철거하면 주민 ${residents}명이 떠납니다. 자재와 보관 식량은 반환되지 않습니다.`,
  demolishHouse: '주택 철거',
  cargoTerm: '화물',
  sourceTerm: '출발',
  sourcePositionTerm: '출발 위치',
  sourcePosition: (direction: string, distance: number) => `${direction} ${distance}칸`,
  destinationTerm: '목적',
  statusTerm: '상태',
  remainingTerm: '남은 길',
  remaining: (tiles: number, eta: string) => `${tiles}칸 · ${eta}`,
  passedTerm: '통과',
  passed: (houses: number) => `지난 집 ${houses}`,
  roundTerm: '순회',
  travelled: (tiles: number) => `이동 ${tiles}칸`,
  cancellationTerm: '취소',
  abandonConstruction: '공사 포기',
  abandonConstructionUnavailable: '공사 포기 불가',
  houseType: (level: number) => `주택 · 생활 등급 ${level}`,
  houseLabel: (name: string) => `${name} 원인 진단`,
  houseArt: (footprint: string) => `${footprint} 주택`,
  facilityType: '도시 시설',
  facilityLabel: (name: string) => `${name} 시설 진단`,
  walkerType: '주민 · 이동과 운송',
  walkerLabel: (role: string) => `${role} 임무 진단`,
  walkerArt: '이동',
  siteType: '건설 현장',
  siteLabel: (name: string) => `${name} 건설 진단`,
  siteArt: '공사',
  close: '상세 정보 닫기',
  topLevel: '최고 단계',
  nextLevel: (level: number) => `L${level}`,
  keepRisk: '유지 위험',
  firstBlocker: '첫 방해',
  noneAwaitingPromotion: '없음 · 승급 대기',
  none: '없음',
  causeSummary: (next: string, blockerHeading: string, blocker: string) => `다음: ${next} / ${blockerHeading}: ${blocker}`,
  holdRemaining: (level: number, minutes: number, seconds: string) => `L${level}까지 조건 유지 ${minutes}:${seconds} 남음`,
  operationsHeading: '운영과 재고',
} as const;
