// Generated by scripts/installManorHouse.py — the manor house (LM-R1 RUN-01, src/render/manorHouseArt.ts): Wave 12 manor
// A / B, their activity overlays and the empty manors (A, B v2) on one 416 x 328 canvas; pivot = Astra's front ground contact.
export const MANOR_HOUSE_IMAGES = {
  "manor_a": {"url": "assets/wave12/bld/manor_house_a-v1.png", "width": 416, "height": 328, "pivot": {"x": 249, "y": 319}},
  "manor_b": {"url": "assets/wave12/bld/manor_house_b-v1.png", "width": 416, "height": 328, "pivot": {"x": 251, "y": 319}},
  "manor_a_active": {"url": "assets/wave12/active/manor_house_a-active-v1.png", "width": 416, "height": 328, "pivot": {"x": 249, "y": 319}},
  "manor_b_active": {"url": "assets/wave12/active/manor_house_b-active-v1.png", "width": 416, "height": 328, "pivot": {"x": 251, "y": 319}},
  "manor_a_empty": {"url": "assets/endings-manors/manors/manor_house_a_empty-v1.png", "width": 416, "height": 328, "pivot": {"x": 249, "y": 319}},
  "manor_b_empty": {"url": "assets/endings-manors/manors/manor_house_b_empty-v2.png", "width": 416, "height": 328, "pivot": {"x": 251, "y": 319}},
} as const;

export type ManorHouseKey = keyof typeof MANOR_HOUSE_IMAGES;
