// Generated by scripts/roofSmokeAnchors.py (rule in its header). Do not edit by hand.
// Ridge point of each house art as a fraction of its alpha bounds (fx from the left, fy from the top).
export const ROOF_SMOKE_ANCHORS: Readonly<Record<string, { readonly fx: number; readonly fy: number }>> = {
 "assets/buildings/historical-houses/house_l0-v3.png": {
  "fx": 0.3451,
  "fy": 0.0
 },
 "assets/buildings/historical-houses/house_l1-v2.png": {
  "fx": 0.2611,
  "fy": 0.0
 },
 "assets/buildings/historical-houses/house_l2-v2.png": {
  "fx": 0.2389,
  "fy": 0.0
 },
 "assets/buildings/historical-houses/house_l3-v2.png": {
  "fx": 0.2434,
  "fy": 0.0
 },
 "assets/buildings/historical-houses/house_l4-v2.png": {
  "fx": 0.2061,
  "fy": 0.0068
 },
 "assets/buildings/historical-houses/house_pair_l2_horizontal-v4.png": {
  "fx": 0.1686,
  "fy": 0.0
 },
 "assets/buildings/historical-houses/house_pair_l2_vertical-v2.png": {
  "fx": 0.1735,
  "fy": 0.0
 },
 "assets/buildings/historical-houses/house_pair_l3_horizontal-v2.png": {
  "fx": 0.1627,
  "fy": 0.0
 },
 "assets/buildings/historical-houses/house_pair_l3_vertical-v2.png": {
  "fx": 0.2012,
  "fy": 0.0
 },
 "assets/buildings/historical-houses/house_pair_l4_horizontal-v2.png": {
  "fx": 0.1775,
  "fy": 0.0051
 },
 "assets/buildings/historical-houses/house_pair_l4_vertical-v2.png": {
  "fx": 0.1509,
  "fy": 0.0
 },
 "assets/buildings/variants-wave2/house_l0_garden-v1.png": {
  "fx": 0.323,
  "fy": 0.0745
 },
 "assets/buildings/variants-wave2/house_l0_pen-v1.png": {
  "fx": 0.3186,
  "fy": 0.117
 },
 "assets/buildings/variants-wave2/house_l1_artisan-v1.png": {
  "fx": 0.292,
  "fy": 0.0286
 },
 "assets/buildings/variants-wave2/house_l1_garden-v1.png": {
  "fx": 0.2212,
  "fy": 0.1524
 },
 "assets/buildings/variants-wave2/house_l1_tile-v1.png": {
  "fx": 0.2655,
  "fy": 0.0
 },
 "assets/buildings/variants-wave2/house_l2_brewer-v1.png": {
  "fx": 0.2389,
  "fy": 0.096
 },
 "assets/buildings/variants-wave2/house_l2_garden-v1.png": {
  "fx": 0.2389,
  "fy": 0.088
 },
 "assets/buildings/variants-wave2/house_l2_weaver-v1.png": {
  "fx": 0.2257,
  "fy": 0.008
 },
 "assets/buildings/variants-wave2/house_l3_clothier-v1.png": {
  "fx": 0.2345,
  "fy": 0.0992
 },
 "assets/buildings/variants-wave2/house_l3_shop-v1.png": {
  "fx": 0.3009,
  "fy": 0.0763
 },
 "assets/buildings/variants-wave2/house_l3_storage-v1.png": {
  "fx": 0.2168,
  "fy": 0.1145
 },
 "assets/buildings/variants-wave2/house_l4_courtyard-v1.png": {
  "fx": 0.2851,
  "fy": 0.0342
 },
 "assets/buildings/variants-wave2/house_l4_inn-v1.png": {
  "fx": 0.1974,
  "fy": 0.0959
 },
 "assets/buildings/variants-wave2/house_l4_wing-v1.png": {
  "fx": 0.2193,
  "fy": 0.0068
 },
 "assets/buildings/variants-wave2/house_pair_l3_horizontal_courtyard-v1.png": {
  "fx": 0.1509,
  "fy": 0.1258
 },
 "assets/buildings/variants-wave2/house_pair_l3_vertical_workshop-v1.png": {
  "fx": 0.2219,
  "fy": 0.0
 },
 "assets/buildings/variants-wave2/house_pair_l4_horizontal_hall-v1.png": {
  "fx": 0.1657,
  "fy": 0.1385
 },
 "assets/buildings/variants-wave2/house_pair_l4_vertical_court-v1.png": {
  "fx": 0.1686,
  "fy": 0.0364
 }
};
