// Generated by scripts/installStorehouseSnow.py — the storehouse snow layers (NAT-5 RUN-02): one per body variant
// (a = the base storehouse.png, b, c = the Wave 2 variants), each on its body's 160 x 136 canvas at offset (0, 0).
export const STOREHOUSE_SNOW_IMAGES = {
  a: {"url": "assets/buildings/storehouse-snow/storehouse_a_snow.png", "width": 160, "height": 136, "pivot": {"x": 0, "y": 0}, "body": "assets/buildings/storehouse.png"},
  b: {"url": "assets/buildings/storehouse-snow/storehouse_b_snow.png", "width": 160, "height": 136, "pivot": {"x": 0, "y": 0}, "body": "assets/buildings/variants-wave2/storehouse_b-v1.png"},
  c: {"url": "assets/buildings/storehouse-snow/storehouse_c_snow.png", "width": 160, "height": 136, "pivot": {"x": 0, "y": 0}, "body": "assets/buildings/variants-wave2/storehouse_c-v1.png"},
} as const;

export type StorehouseSnowKey = keyof typeof STOREHOUSE_SNOW_IMAGES;
