// Generated by scripts/generateTownLandscapeManifest.mjs.
export const townLandscapeManifest = [
  {
    "id": "vegetable",
    "url": "/assets/phase16-landscape/vegetable.png",
    "width": 144,
    "height": 59,
    "displayWidth": 48,
    "groundAnchor": {
      "x": 0.5,
      "y": 0.5
    }
  },
  {
    "id": "orchard",
    "url": "/assets/phase16-landscape/orchard.png",
    "width": 113,
    "height": 80,
    "displayWidth": 40,
    "groundAnchor": {
      "x": 0.5,
      "y": 0.93
    }
  },
  {
    "id": "pasture",
    "url": "/assets/phase16-landscape/pasture.png",
    "width": 106,
    "height": 60,
    "displayWidth": 40,
    "groundAnchor": {
      "x": 0.5,
      "y": 0.65
    }
  }
] as const;
