// Generated by scripts/installWave34.py — Wave 34's fords and drainage works (LAND-UI): url, folder, stage, season, repeat
// (none: one picture; x: a strip repeating along x; grid: 128 x 64 isometric tiles; region: one sheet drawn once over its
// region), size and pivot of each picture.
export const WAVE34_WORKS = {
  drain_done_edge_summer: {"url": "assets/wave34/drain/drain_done_edge_summer.png", "folder": "drain", "stage": "done", "season": "summer", "repeat": "x", "width": 512, "height": 64, "pivot": {"x": 256, "y": 32}},
  drain_done_edge_winter: {"url": "assets/wave34/drain/drain_done_edge_winter.png", "folder": "drain", "stage": "done", "season": "winter", "repeat": "x", "width": 512, "height": 64, "pivot": {"x": 256, "y": 32}},
  drain_earth_cart: {"url": "assets/wave34/props/drain_earth_cart.png", "folder": "props", "stage": "none", "season": "all", "repeat": "none", "width": 128, "height": 96, "pivot": {"x": 64, "y": 88}},
  drain_plank_bridge: {"url": "assets/wave34/props/drain_plank_bridge.png", "folder": "props", "stage": "none", "season": "all", "repeat": "none", "width": 128, "height": 64, "pivot": {"x": 64, "y": 56}},
  drain_sluice: {"url": "assets/wave34/props/drain_sluice.png", "folder": "props", "stage": "none", "season": "all", "repeat": "none", "width": 128, "height": 96, "pivot": {"x": 64, "y": 88}},
  drain_soil_heap: {"url": "assets/wave34/props/drain_soil_heap.png", "folder": "props", "stage": "none", "season": "all", "repeat": "none", "width": 96, "height": 64, "pivot": {"x": 48, "y": 56}},
  drain_stage1_staked_summer: {"url": "assets/wave34/drain/drain_stage1_staked_summer.png", "folder": "drain", "stage": "1_staked", "season": "summer", "repeat": "grid", "width": 128, "height": 64, "pivot": {"x": 64, "y": 32}},
  drain_stage1_staked_winter: {"url": "assets/wave34/drain/drain_stage1_staked_winter.png", "folder": "drain", "stage": "1_staked", "season": "winter", "repeat": "grid", "width": 128, "height": 64, "pivot": {"x": 64, "y": 32}},
  drain_stage2_ditched_summer: {"url": "assets/wave34/drain/drain_stage2_ditched_summer.png", "folder": "drain", "stage": "2_ditched", "season": "summer", "repeat": "grid", "width": 128, "height": 64, "pivot": {"x": 64, "y": 32}},
  drain_stage2_ditched_winter: {"url": "assets/wave34/drain/drain_stage2_ditched_winter.png", "folder": "drain", "stage": "2_ditched", "season": "winter", "repeat": "grid", "width": 128, "height": 64, "pivot": {"x": 64, "y": 32}},
  drain_stage3_drying_summer_3x3: {"url": "assets/wave34/drain/drain_stage3_drying_summer_3x3.png", "folder": "drain", "stage": "3", "season": "summer", "repeat": "region", "width": 384, "height": 192, "pivot": {"x": 192, "y": 96}},
  drain_stage3_drying_summer_5x5: {"url": "assets/wave34/drain/drain_stage3_drying_summer_5x5.png", "folder": "drain", "stage": "3", "season": "summer", "repeat": "region", "width": 640, "height": 320, "pivot": {"x": 320, "y": 160}},
  drain_stage3_drying_winter_3x3: {"url": "assets/wave34/drain/drain_stage3_drying_winter_3x3.png", "folder": "drain", "stage": "3", "season": "winter", "repeat": "region", "width": 384, "height": 192, "pivot": {"x": 192, "y": 96}},
  drain_stage3_drying_winter_5x5: {"url": "assets/wave34/drain/drain_stage3_drying_winter_5x5.png", "folder": "drain", "stage": "3", "season": "winter", "repeat": "region", "width": 640, "height": 320, "pivot": {"x": 320, "y": 160}},
  ford_splash_a: {"url": "assets/wave34/props/ford_splash_a.png", "folder": "props", "stage": "none", "season": "all", "repeat": "none", "width": 96, "height": 64, "pivot": {"x": 48, "y": 56}},
  ford_splash_b: {"url": "assets/wave34/props/ford_splash_b.png", "folder": "props", "stage": "none", "season": "all", "repeat": "none", "width": 96, "height": 64, "pivot": {"x": 48, "y": 56}},
  ford_w2_ne_summer: {"url": "assets/wave34/ford/ford_w2_ne_summer.png", "folder": "ford", "stage": "none", "season": "summer", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w2_ne_winter: {"url": "assets/wave34/ford/ford_w2_ne_winter.png", "folder": "ford", "stage": "none", "season": "winter", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w2_nw_summer: {"url": "assets/wave34/ford/ford_w2_nw_summer.png", "folder": "ford", "stage": "none", "season": "summer", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w2_nw_winter: {"url": "assets/wave34/ford/ford_w2_nw_winter.png", "folder": "ford", "stage": "none", "season": "winter", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w3_ne_summer: {"url": "assets/wave34/ford/ford_w3_ne_summer.png", "folder": "ford", "stage": "none", "season": "summer", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w3_ne_winter: {"url": "assets/wave34/ford/ford_w3_ne_winter.png", "folder": "ford", "stage": "none", "season": "winter", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w3_nw_summer: {"url": "assets/wave34/ford/ford_w3_nw_summer.png", "folder": "ford", "stage": "none", "season": "summer", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w3_nw_winter: {"url": "assets/wave34/ford/ford_w3_nw_winter.png", "folder": "ford", "stage": "none", "season": "winter", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w4_ne_summer: {"url": "assets/wave34/ford/ford_w4_ne_summer.png", "folder": "ford", "stage": "none", "season": "summer", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w4_ne_winter: {"url": "assets/wave34/ford/ford_w4_ne_winter.png", "folder": "ford", "stage": "none", "season": "winter", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w4_nw_summer: {"url": "assets/wave34/ford/ford_w4_nw_summer.png", "folder": "ford", "stage": "none", "season": "summer", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  ford_w4_nw_winter: {"url": "assets/wave34/ford/ford_w4_nw_winter.png", "folder": "ford", "stage": "none", "season": "winter", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
} as const;

export type Wave34WorksKey = keyof typeof WAVE34_WORKS;
