// Generated by scripts/installWave17World.py — Wave 17 world sprites (UI-6) and the Wave 12 quay under the burning
// quay (UI-6b): url, size, ground pivot (Astra's registration, source px), cell and, for the smoke sheet, its
// frames; footprint in tiles; zoom1Scale = world px per source px (game_zoom_1_source_scale).
export const WAVE17_WORLD_IMAGES = {
  beacon_idle: {"url": "assets/wave17/world/beacon_idle-v1.png", "width": 128, "height": 160, "pivot": {"x": 64, "y": 151}, "cell": {"width": 128, "height": 160}, "footprint": {"width": 1, "height": 1}, "zoom1Scale": 0.5},
  beacon_lit: {"url": "assets/wave17/world/beacon_lit-v1.png", "width": 128, "height": 160, "pivot": {"x": 64, "y": 151}, "cell": {"width": 128, "height": 160}, "footprint": {"width": 1, "height": 1}, "zoom1Scale": 0.5},
  quay: {"url": "assets/wave12/world/quay-v1.png", "width": 256, "height": 128, "pivot": {"x": 68, "y": 119}, "cell": {"width": 256, "height": 128}, "footprint": {"width": 2, "height": 2}, "zoom1Scale": 0.5},
  raid_burning_quay: {"url": "assets/wave17/world/raid_burning_quay-v1.png", "width": 256, "height": 128, "pivot": {"x": 68, "y": 119}, "cell": {"width": 256, "height": 128}, "footprint": {"width": 2, "height": 2}, "zoom1Scale": 0.5},
  raid_smoke_column_sheet: {"url": "assets/wave17/world/raid_smoke_column_sheet-v1.png", "width": 512, "height": 192, "pivot": {"x": 64, "y": 186}, "cell": {"width": 128, "height": 192}, "frames": {"width": 128, "height": 192, "count": 4}, "footprint": {"width": 1, "height": 1}, "zoom1Scale": 0.5},
} as const;
