// Generated by scripts/installWave12Guildhall.py — Wave 12 guildhall world prop (UI-9):
// body painting and active overlay; chapter 4 (chapterArt.ts CHAPTER_ART).
// pivot: Astra's ground registration (SW front-left corner of the 3×2 building).
export const WAVE12_GUILDHALL_IMAGES = {
  guildhall_body: {"url": "assets/wave12/bld/guildhall-v1.png", "width": 352, "height": 300, "pivot": {"x": 107, "y": 291}},
  guildhall_active: {"url": "assets/wave12/bld/guildhall-active-v1.png", "width": 352, "height": 300, "pivot": {"x": 107, "y": 291}},
} as const;
