// Generated by scripts/installWave41.py — the Wave 41 additions (NAT-4): the forest edge strip (WAVE41_GROUND, x: repeating
// along x; top the meadow, bottom the woodland floor) and the width-1 fords (WAVE41_FORDS, one picture each): url, folder,
// season, repeat, size and pivot of each picture.
export const WAVE41_GROUND = {
  "boundary/woodland_grass_edge_summer": {"url": "assets/wave41/boundary/woodland_grass_edge_summer.png", "folder": "boundary", "season": "summer", "repeat": "x", "width": 512, "height": 64, "pivot": {"x": 256, "y": 32}},
  "boundary/woodland_grass_edge_winter": {"url": "assets/wave41/boundary/woodland_grass_edge_winter.png", "folder": "boundary", "season": "winter", "repeat": "x", "width": 512, "height": 64, "pivot": {"x": 256, "y": 32}},
} as const;

export type Wave41GroundKey = keyof typeof WAVE41_GROUND;

export const WAVE41_FORDS = {
  "ford_w1_ne_summer": {"url": "assets/wave41/ford/ford_w1_ne_summer.png", "folder": "ford", "season": "summer", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  "ford_w1_ne_winter": {"url": "assets/wave41/ford/ford_w1_ne_winter.png", "folder": "ford", "season": "winter", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  "ford_w1_nw_summer": {"url": "assets/wave41/ford/ford_w1_nw_summer.png", "folder": "ford", "season": "summer", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
  "ford_w1_nw_winter": {"url": "assets/wave41/ford/ford_w1_nw_winter.png", "folder": "ford", "season": "winter", "repeat": "none", "width": 512, "height": 256, "pivot": {"x": 256, "y": 128}},
} as const;

export type Wave41FordKey = keyof typeof WAVE41_FORDS;
