// Generated by scripts/installWave29.py — Wave 29 water motion sheets (INSTALL-29), from the batch's records/assets.csv: url,
// frame size and count (one row, left to right, no margins), fps (0: static), loop, repeat axes, recommended alpha (the
// ripples' low alpha is baked in the PNG: only this is applied), anchor and placement offset (null: none given).
export const WAVE29_WATER = {
  current_arrows_ne_sheet: {"url": "assets/wave29/water/current_arrows_ne_sheet.png", "frameWidth": 128, "frameHeight": 64, "frames": 6, "fps": 6, "loop": true, "repeatX": true, "repeatY": true, "alpha": 1, "anchorX": 64, "anchorY": 32, "offsetX": null, "offsetY": null},
  current_arrows_nw_sheet: {"url": "assets/wave29/water/current_arrows_nw_sheet.png", "frameWidth": 128, "frameHeight": 64, "frames": 6, "fps": 6, "loop": true, "repeatX": true, "repeatY": true, "alpha": 1, "anchorX": 64, "anchorY": 32, "offsetX": null, "offsetY": null},
  current_arrows_se_sheet: {"url": "assets/wave29/water/current_arrows_se_sheet.png", "frameWidth": 128, "frameHeight": 64, "frames": 6, "fps": 6, "loop": true, "repeatX": true, "repeatY": true, "alpha": 1, "anchorX": 64, "anchorY": 32, "offsetX": null, "offsetY": null},
  current_arrows_sw_sheet: {"url": "assets/wave29/water/current_arrows_sw_sheet.png", "frameWidth": 128, "frameHeight": 64, "frames": 6, "fps": 6, "loop": true, "repeatX": true, "repeatY": true, "alpha": 1, "anchorX": 64, "anchorY": 32, "offsetX": null, "offsetY": null},
  fish_ring: {"url": "assets/wave29/water/fish_ring.png", "frameWidth": 48, "frameHeight": 24, "frames": 6, "fps": 6, "loop": true, "repeatX": false, "repeatY": false, "alpha": 0.45, "anchorX": 24, "anchorY": 12, "offsetX": null, "offsetY": null},
  ice_edge: {"url": "assets/wave29/water/ice_edge.png", "frameWidth": 512, "frameHeight": 32, "frames": 1, "fps": 0, "loop": true, "repeatX": true, "repeatY": false, "alpha": 0.8, "anchorX": 0, "anchorY": 16, "offsetX": 0, "offsetY": 27},
  mill_race_sheet: {"url": "assets/wave29/water/mill_race_sheet.png", "frameWidth": 128, "frameHeight": 64, "frames": 6, "fps": 8, "loop": true, "repeatX": true, "repeatY": true, "alpha": 1, "anchorX": 64, "anchorY": 32, "offsetX": null, "offsetY": null},
  reeds_sway_a_sheet: {"url": "assets/wave29/water/reeds_sway_a_sheet.png", "frameWidth": 96, "frameHeight": 96, "frames": 4, "fps": 4, "loop": true, "repeatX": false, "repeatY": false, "alpha": 1, "anchorX": 57.05168820341809, "anchorY": 87, "offsetX": null, "offsetY": null},
  reeds_sway_b_sheet: {"url": "assets/wave29/water/reeds_sway_b_sheet.png", "frameWidth": 96, "frameHeight": 96, "frames": 4, "fps": 4, "loop": true, "repeatX": false, "repeatY": false, "alpha": 1, "anchorX": 43.542258134963966, "anchorY": 87, "offsetX": null, "offsetY": null},
  reeds_sway_c_sheet: {"url": "assets/wave29/water/reeds_sway_c_sheet.png", "frameWidth": 96, "frameHeight": 96, "frames": 4, "fps": 4, "loop": true, "repeatX": false, "repeatY": false, "alpha": 1, "anchorX": 50.73512035010941, "anchorY": 87, "offsetX": null, "offsetY": null},
  ripple_shallow_sheet: {"url": "assets/wave29/water/ripple_shallow_sheet.png", "frameWidth": 256, "frameHeight": 128, "frames": 8, "fps": 4, "loop": true, "repeatX": true, "repeatY": true, "alpha": 1, "anchorX": 128, "anchorY": 64, "offsetX": null, "offsetY": null},
  ripple_sheet: {"url": "assets/wave29/water/ripple_sheet.png", "frameWidth": 256, "frameHeight": 128, "frames": 8, "fps": 4, "loop": true, "repeatX": true, "repeatY": true, "alpha": 1, "anchorX": 128, "anchorY": 64, "offsetX": null, "offsetY": null},
  shore_foam_sheet: {"url": "assets/wave29/water/shore_foam_sheet.png", "frameWidth": 512, "frameHeight": 32, "frames": 6, "fps": 4, "loop": true, "repeatX": true, "repeatY": false, "alpha": 0.65, "anchorX": 0, "anchorY": 16, "offsetX": 0, "offsetY": 27},
  sparkle: {"url": "assets/wave29/water/sparkle.png", "frameWidth": 32, "frameHeight": 32, "frames": 6, "fps": 6, "loop": true, "repeatX": false, "repeatY": false, "alpha": 0.4, "anchorX": 16, "anchorY": 16, "offsetX": null, "offsetY": null},
} as const;

export type Wave29WaterKey = keyof typeof WAVE29_WATER;
