// Generated by scripts/installWave17Collector.py — Wave 17's lord's tax collector (UI-9b): url, size, the pivot (cell
// centre, the feet's median row), the sheet's cells (columns NE SE SW NW, rows the gait frames) with each cell's
// foot from records/frame_pivots.csv, and the figure height (median opaque cell height, alpha > 32).
export const WAVE17_WALKER_IMAGES = {
  wk_tax_collector: {"url": "assets/wave17/walker/wk_tax_collector-v1.png", "width": 296, "height": 148, "pivot": {"x": 37, "y": 68}, "frames": {"width": 74, "height": 74, "count": 4, "rows": 2}, "directions": ["NE", "SE", "SW", "NW"], "feet": {"NE": [{"x": 32.06, "y": 68.0}, {"x": 31.0, "y": 68.0}], "SE": [{"x": 44.89, "y": 69.0}, {"x": 46.47, "y": 69.0}], "SW": [{"x": 26.56, "y": 70.0}, {"x": 26.53, "y": 69.0}], "NW": [{"x": 40.29, "y": 68.0}, {"x": 43.6, "y": 68.0}]}, "figureHeight": 68},
} as const;
