const fs=require('fs'),p=require('path'),sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');const b=p.resolve(__dirname,'..');
const commonTraits={hair:'dark brown',faceShape:'long oval overall',brow:'straight low brows'};
const t={
101:['male',25,'short neat wavy hair','gray green','broad shoulders','one mole high on left cheek','married'],
102:['female',25,'smooth hair covered in adulthood','brown','slender shoulders','light freckles across nose','married'],
201:['male',24,'short straight cropped hair','gray blue','heavy broad build','one mole beside right mouth corner','married'],
202:['male',22,'long ear length loose curls','hazel','slim narrow build','many freckles across nose and cheeks','unmarried'],
203:['female',24,'long smooth single braid under adult veil','gray green','slender long neck','small mole below left eye','married'],
204:['female',22,'short full curly bob when unmarried','warm brown','rounder broad shoulders','dense nose freckles','unmarried'],
205:['female',23,'covered chestnut wavy hair','blue','broad shoulders','tiny mole above right eyebrow','married'],
206:['male',26,'short sandy blond straight hair','brown','stocky shoulders','healed pale mark on right cheek','married'],
301:['male',22,'short dark brown tight curls','blue gray','narrow shoulders','one mole beside right mouth corner','unmarried'],
302:['female',20,'long dark brown straight loose braid','green','broad shoulders','few freckles on cheeks','unmarried'],
303:['male',22,'ear length dark brown straight hair','brown','wide shoulders','small mole below left eye','unmarried'],
304:['female',20,'short dark brown loose waves','gray green','slim shoulders','many freckles on nose','unmarried']};
if(process.argv[2]==='init'){fs.writeFileSync(p.join(b,'records/L3-traits.json'),JSON.stringify({family:commonTraits,identities:t},null,2));process.exit();}
(async()=>{let j=JSON.parse(fs.readFileSync(process.argv[2])),n=Number(j.identity.split('_')[1]),v=t[n],stage=j.stage,id=j.identity+'_'+stage,age=stage==='young'?v[1]:stage==='mature'?v[1]+20:stage==='old'?70:stage==='child'?([201,203,301,303].includes(n)?8:6):([201,203,301,303].includes(n)?.9:.5);let maritalStatus=['baby','child'].includes(stage)?'not applicable':stage==='mature'&&[202,204].includes(n)?'married':v[6];let parents=n>=301?(n<=302?['L3_201','L3_205']:['L3_206','L3_203']):n>=201&&n<=204?['L3_101','L3_102']:[null,null];let file='assets/L3/'+id+'.png',rawFile='raw/L3/'+id+'.png';fs.copyFileSync(j.source,p.join(b,rawFile));await sharp(j.source).resize(256,256,{fit:'contain'}).png().toFile(p.join(b,file));let f=p.join(b,'records/L3.json'),rows=fs.existsSync(f)?JSON.parse(fs.readFileSync(f)):[];if(rows.some(x=>x.id===id))throw Error('exists');rows.push({id,file,identity:j.identity,lineage:'L3',generation:Math.floor(n/100),stage,age,sex:v[0],maritalStatus,clothing:stage==='baby'?'linen bonnet and swaddling':'gentry fine wool and modest fur collar; married adult women head covered',fatherIdentity:parents[0],motherIdentity:parents[1],commonTraits:[205,206].includes(n)?{hair:n===205?'chestnut':'sandy blond',faceShape:n===205?'round':'broad square',brow:n===205?'arched':'bushy'}:commonTraits,differenceMarkers:{hair:v[2],eyes:v[3],build:v[4],personalMark:v[5],age},generationRecords:[{prompt:j.prompt,rawFile,referenceImages:j.refs,referenceHashes:Object.fromEntries(j.refs.map(r=>[r,require('crypto').createHash('sha256').update(fs.readFileSync(r)).digest('hex')])),tool:'image_gen.imagegen',model:null,seed:null}],processing:'Sharp contain resize 256x256 only; no face modification',qa:{status:'candidate',visualObservation:j.qa||'Pending final independent QA',runtime:'not installed'}});fs.writeFileSync(f,JSON.stringify(rows,null,2));console.log(id);})();
