'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const sharp=require('/tmp/astra-wave4b-work-20260925/node_modules/sharp');
const {createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');
const base=path.resolve(__dirname,'..'),previous=path.resolve(base,'../astra-lineage-pilot2-v1');
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
(async()=>{const items=JSON.parse(fs.readFileSync(path.join(base,'records/pilot2-baby-inputs.json'),'utf8'));const rows=[];
for(const dir of ['assets/pilot2-baby','raw/pilot2-baby','references/pilot2-baby'])fs.mkdirSync(path.join(base,dir),{recursive:true});
const board=createCanvas(840,1848),ctx=board.getContext('2d');ctx.fillStyle='#e8e6e0';ctx.fillRect(0,0,840,1848);ctx.fillStyle='#222';ctx.font='18px sans-serif';ctx.fillText('Actual child reference',12,24);ctx.fillText('Previous baby',290,24);ctx.fillText('Infant correction v2',570,24);
for(const [index,item]of items.entries()){
 const child=path.join(previous,'assets',item.lane,`${item.id}_child.png`),old=path.join(previous,'assets',item.lane,`${item.id}_baby.png`),id=`${item.id}_baby-v2`,file=`assets/pilot2-baby/${id}.png`,rawFile=`raw/pilot2-baby/${id}.png`;
 const childHash=sha(child),oldHash=sha(old);const attemptFile=`raw/pilot2-baby/${id}-attempt1.png`;fs.copyFileSync(item.source,path.join(base,attemptFile));fs.copyFileSync(item.retrySource,path.join(base,rawFile));if(item.targetSource){fs.copyFileSync(item.retrySource,path.join(base,`raw/pilot2-baby/${id}-attempt2.png`));fs.copyFileSync(item.targetSource,path.join(base,rawFile));}fs.copyFileSync(child,path.join(base,`references/pilot2-baby/${item.id}_child.png`));fs.copyFileSync(old,path.join(base,`references/pilot2-baby/${item.id}_baby-before.png`));
 await sharp(path.join(base,rawFile)).resize(256,256,{fit:'contain'}).png().toFile(path.join(base,file));
 const female=!['L2_201','L2_202'].includes(item.id),eyes=item.id==='L2_201'?'blue':item.id==='L2_204'?'brown':item.id==='L1_204'||item.id==='L2_202'?'hazel brown':'green';
 rows.push({id,file,identity:item.id,lineage:item.id.slice(0,2),generation:2,stage:'baby',age:0.5,sex:female?'female':'male',maritalStatus:'notApplicable',clothing:'Cream linen swaddling and linen infant bonnet; '+item.cloth,fatherIdentity:null,motherIdentity:null,commonTraits:{hair:'auburn family range',faceShape:item.id==='L1_204'||item.id==='L2_201'||item.id==='L2_204'?'round':'oval',feature:'soft low eyebrow family tendency'},differenceMarkers:{age:0.5,eyes,hair:item.traits,wrap:item.cloth},childIdentityReference:{file:child,sha256:childHash,packagedFile:`references/pilot2-baby/${item.id}_child.png`,role:'Primary personal identity reference'},previousBaby:{file:old,sha256:oldHash,packagedFile:`references/pilot2-baby/${item.id}_baby-before.png`,role:'Comparison only, not generator input'},generationRecords:[{prompt:item.prompt,rawFile:attemptFile,referenceImages:[child],referenceRoles:['Primary identity from matching pilot2 child portrait'],referenceSHA256:[childHash],tool:'image_gen.imagegen',model:null,seed:null,selection:'rejected-age-too-old'},{prompt:item.retryPrompt,rawFile,referenceImages:[child,path.join(previous,'assets/brothers/L2_202_baby.png')],referenceRoles:['Primary matching child personal identity','Infant anatomy and swaddling only; identity not copied'],referenceSHA256:[childHash,sha(path.join(previous,'assets/brothers/L2_202_baby.png'))],tool:'image_gen.imagegen',model:null,seed:null,selection:'candidate-final'}],processing:'Sharp contain resize to 256x256 only. No facial retouch; original pilot2 unchanged.',qa:{status:'candidate',visualObservation:'Awaiting independent age/identity review; target real infant in swaddling and bonnet.',runtime:'not installed'},sha256:sha(path.join(base,file))});
 if(item.targetSource){const row=rows[rows.length-1],targetRef=path.join(base,`references/pilot2-baby/${item.id}_baby-v2-before-targeted.png`);row.generationRecords[1].rawFile=`raw/pilot2-baby/${id}-attempt2.png`;row.generationRecords[1].selection='rejected-sibling-too-similar';row.generationRecords.push({prompt:item.targetPrompt,rawFile,referenceImages:[child,targetRef],referenceRoles:['Own child primary identity','Own prior infant age/proportions edit target'],referenceSHA256:[childHash,sha(targetRef)],tool:'image_gen.imagegen',model:null,seed:null,selection:'candidate-final'});row.differenceMarkers.expression='Open mouth delighted infant expression';row.differenceMarkers.face='Round wide face, broad cheeks, fuller lower lip';row.differenceMarkers.hair='Short auburn curl tufts at bonnet edge';}
 const y=42+index*300;ctx.drawImage(await loadImage(child),12,y,256,256);ctx.drawImage(await loadImage(old),290,y,256,256);ctx.drawImage(await loadImage(path.join(base,file)),568,y,256,256);ctx.fillStyle='#222';ctx.font='18px sans-serif';ctx.fillText(item.id,12,y+280);if(sha(child)!==childHash||sha(old)!==oldHash)throw Error('Original changed');
}
fs.writeFileSync(path.join(base,'records/pilot2-baby.json'),JSON.stringify(rows,null,2)+'\n');fs.writeFileSync(path.join(base,'records/pilot2-baby-comparison.png'),board.toBuffer('image/png'));console.log(JSON.stringify({count:rows.length,status:'Candidate 6, original references preserved'}));})();
