const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..');
(async()=>{let names=fs.readdirSync(root+'/assets').filter(x=>x.endsWith('.png')).sort();assert.equal(names.length,16);let items=[];let data={};for(const f of names){let b=fs.readFileSync(root+'/assets/'+f),m=await sharp(b).metadata(),raw=await sharp(b).ensureAlpha().raw().toBuffer();let id=f.slice(0,-4),dims=id.startsWith('tree_node_frame')?[176,216]:id.includes('corner')||id.includes('junction')?[16,16]:({tree_line_h:[64,8],tree_line_v:[8,64],tree_marriage_link:[48,16],tree_lineage_banner:[320,72],tree_generation_label:[120,32],tree_expand:[32,32],tree_collapse:[32,32],tree_outside_spouse_marker:[24,24]})[id];assert.deepEqual([m.width,m.height],dims);assert.equal(m.hasAlpha,true);let alphas=Array.from({length:m.width*m.height},(_,i)=>raw[i*4+3]);let inset=id.startsWith('tree_node_frame')?(id.endsWith('deceased')?[20,20,20,20]:[12,12,12,12]):id==='tree_lineage_banner'?[24,10,24,10]:id==='tree_generation_label'?[10,8,10,8]:null;items.push({id,file:'assets/'+f,width:m.width,height:m.height,rgba:true,transparent_pixels:alphas.filter(x=>x===0).length,alpha_min:Math.min(...alphas),nine_slice_ltrb:inset,status:'candidate',sha256:crypto.createHash('sha256').update(b).digest('hex')});data[id]={b:raw,w:m.width,h:m.height};}
function px(id,x,y){let d=data[id];return Array.from(d.b.subarray((y*d.w+x)*4,(y*d.w+x)*4+4))}
let seams=[];for(let y=0;y<8;y++)assert.deepEqual(px('tree_line_h',0,y),px('tree_line_h',63,y));for(let x=0;x<8;x++)assert.deepEqual(px('tree_line_v',x,0),px('tree_line_v',x,63));seams.push('h left/right and v top/bottom identical, mismatch0');
for(const [id,ports]of Object.entries({tl:['r','b'],tr:['l','b'],bl:['r','t'],br:['l','t'],junction_t:['l','r','b']})){let n='tree_line_'+(id==='junction_t'?id:'corner_'+id);for(const port of ports)for(let i=0;i<8;i++){let actual=port==='l'?px(n,0,i+4):port==='r'?px(n,15,i+4):port==='t'?px(n,i+4,0):px(n,i+4,15);assert.deepEqual(actual,px('tree_line_h',0,i));}seams.push(n+' all declared ports mismatch0');}
const proof=await sharp(root+'/proofs/01-lineage-1280x800.png').metadata();assert.deepEqual([proof.width,proof.height],[1280,800]);
fs.writeFileSync(root+'/records/asset-manifest.json',JSON.stringify({assets:items,portrait_slot:{center_x:88,top:18,diameter:96,baked:false},tile_ports:{center:8,width:8,corner_naming:'top-left joins right+down; top-right left+down; bottom-left right+up; bottom-right left+up',junction_t:'left+right+down'},proof:{width:1280,height:800,portraits:12,deceased:1,selected:1,collapsed:1,synthetic:true}},null,2));
fs.writeFileSync(root+'/records/technical-qa.json',JSON.stringify({asset_count:16,dimension_checks:'16/16',rgba_checks:'16/16',seams,proof_dimensions:'1280x800',limits:['Opaque parchment-centered rectangular node frames have no fully transparent pixels in selected/deceased variants.','Runtime interaction not tested.','Spouse portraits are source JPEG crops upscaled65 to96 pixels.']},null,2));console.log(JSON.stringify({assets:16,checks:seams.length+34}));})();
