const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const sharp=require('/Users/rexxa/.npm/_npx/8b377f6eec906bc4/node_modules/sharp/lib/index.js');
const root=path.resolve(__dirname,'..');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
async function bounds(input){const {data,info}=await sharp(input).ensureAlpha().raw().toBuffer({resolveWithObject:true});let l=info.width,t=info.height,r=-1,b=-1;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++)if(data[(y*info.width+x)*4+3]>8){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}return{left:l,top:t,width:r-l+1,height:b-t+1};}
(async()=>{const records=JSON.parse(fs.readFileSync(__dirname+'/regrowth-generations.json')),metrics=[];
for(const r of records){const raw=root+'/raw/regrowth/'+r.id+'.png';fs.copyFileSync(r.generated_path,raw);r.inputHashes=r.inputs.map(file=>({file,sha256:sha(file)}));r.generatedSha256=sha(raw);
const crop=await bounds(raw),w=80,h=r.id.includes('1to3')?30:56;const sprite=await sharp(raw).extract(crop).resize(w,h,{fit:'fill'}).png().toBuffer();
const dest=root+'/assets/regrowth/'+r.id+'.png';await sharp({create:{width:128,height:192,channels:4,background:'#00000000'}}).composite([{input:sprite,left:24,top:172-h}]).png({compressionLevel:9}).toFile(dest);
const {data}=await sharp(dest).raw().toBuffer({resolveWithObject:true});let min=255,max=0,edge=0;for(let y=0;y<192;y++)for(let x=0;x<128;x++){const a=data[(y*128+x)*4+3];min=Math.min(min,a);max=Math.max(max,a);if(x===0||x===127||y===0||y===191)edge=Math.max(edge,a);}r.outputSha256=sha(dest);metrics.push({id:r.id,file:'assets/regrowth/'+r.id+'.png',width:128,height:192,pivot:[64,172],visibleBounds:await bounds(dest),alphaMin:min,alphaMax:max,edgeAlpha:edge,sha256:r.outputSha256,transform:{crop,resize:[w,h],placement:[24,172-h],flipX:false},status:'candidate'});}
fs.writeFileSync(__dirname+'/regrowth-generations.json',JSON.stringify(records,null,2));fs.writeFileSync(__dirname+'/regrowth-metrics.json',JSON.stringify(metrics,null,2));
const grassPath='/Users/rexxa/orca/workspaces/feudal-lord-simulator/krill/public/assets/terrain/grass.png';const grass=await sharp(grassPath).resize(640,260,{fit:'fill'}).flatten({background:'#828b56'}).png().toBuffer();
for(const [name,bg]of[['light','#ded9be'],['dark','#23352c'],['grass',grass]]){const layers=[];for(let i=0;i<records.length;i++){const file=root+'/assets/regrowth/'+records[i].id+'.png';layers.push({input:await sharp(file).extract({left:0,top:110,width:128,height:82}).png().toBuffer(),left:i*160+16,top:30});layers.push({input:await sharp(file).extract({left:0,top:110,width:128,height:82}).resize(77,49).png().toBuffer(),left:i*160+41,top:160});}const base=typeof bg==='string'?sharp({create:{width:640,height:260,channels:4,background:bg}}):sharp(bg);await base.composite(layers).png().toFile(root+'/proofs/regrowth-'+name+'-native-060.png');}
console.log(JSON.stringify({count:metrics.length,metrics}));})();
