import fs from 'node:fs/promises';
import {Workbook} from '@oai/artifact-tool';
const base='/Users/rexxa/github/feudal-lord-simulator/output/astra-lineage-prod2-v1';
const rows=JSON.parse(await fs.readFile(base+'/records/asset-rows.json','utf8'));
if(rows.length!==114)throw Error('Expected114');
const headers=Object.keys(rows[0]);
if(headers.length!==20)throw Error('Expected20columns');
const values=[headers,...rows.map(r=>headers.map(k=>r[k]??''))];
const book=Workbook.create(),sheet=book.worksheets.add('Portraits');
sheet.getRange('A1:T115').values=values;
book.recalculate();
const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';
const csv=sheet.getRange('A1:T115').values.map(r=>r.map(quote).join(',')).join('\r\n')+'\r\n';
const reopened=await Workbook.fromCSV(csv,{sheetName:'Check'});
const back=reopened.worksheets.getItem('Check').getRange('A1:T115').values;
for(let i=0;i<115;i++)for(let j=0;j<20;j++)if(String(values[i][j])!==String(back[i][j]))throw Error(`Roundtrip ${i}:${j}`);
for(const row of back.slice(1))for(const col of [13,14,15,16,17,18])JSON.parse(row[col]);
await fs.writeFile(base+'/assets.csv','\uFEFF'+csv);
await fs.writeFile(base+'/records/csv-validation.json',JSON.stringify({status:'PASS',rows:114,columns:20,allCellsRoundtrip:true,jsonFieldsParsed:true,authoring:'artifact-tool'},null,2));
console.log('PASS CSV114 rows20columns exact roundtrip');
