require 'json';require 'digest'
r='/tmp/astra-steward-r08-20261004/records/storage-flow-executed';b='/Users/rexxa/fls-astra-steward/output/steward-storage-flow-r08';repo='/Users/rexxa/fls-astra-steward'
def j(p);JSON.parse(File.read(p));end
counts={};[[r+'/SHA256SUMS',r],[b+'/SHA256SUMS',b],[b+'/SOURCE_SHA256SUMS',repo]].each{|m,root|ls=File.readlines(m);ls.each{|l|h,p=l.strip.split(/\s+/,2);raise p unless Digest::SHA256.file(root+'/'+p).hexdigest==h};counts[m]=ls.size}
[['source','SOURCE_SHA256SUMS'],['artifact','SHA256SUMS']].each{|kind,m|expected=File.readlines(b+'/'+m).map{|l|l.strip.split(/\s+/,2)[1]}.sort;%w[before after].each{|phase|ls=File.readlines(r+"/run-evidence/#{kind}-#{phase}.log").map(&:strip);raise 'pins' unless ls.all?{|x|x.end_with?(': OK')}&&ls.map{|x|x.delete_suffix(': OK')}.sort==expected}}
p=r+'/result';s=j(p+'/summary.json');base=j(p+'/baseline.json');t=File.readlines(p+'/timeline.jsonl').map{|l|JSON.parse(l)};d=File.readlines(p+'/diagnostics.jsonl').map{|l|JSON.parse(l)}
raise 'contiguous' unless t.size==3841&&t.each_with_index.all?{|v,i|v['step']==i&&v['toTick']==200000+i&&v['fromTick']==200000+[0,i-1].max};raise 'wallticks' unless t.drop(1).each_cons(2).all?{|a,z|z['wallTick']==a['wallTick']+1}
prev=base['projection'];progress=[];stock=[];first=nil;count={dispatch:0,removed:0,phaseChanges:0,ambiguousDeltas:0};t.drop(1).each do |x|
 v=x['target'];first||=x['toTick'] if v!=prev['target'];progress<<{tick:x['toTick'],from:prev['target']['productionProgress'],to:v['productionProgress'],inventory:v['inventory']} if prev['target']['productionProgress']!=v['productionProgress'];stock<<{tick:x['toTick'],inventory:v['inventory'],reserved:v['reserved'],progress:v['productionProgress']} if v['inventory']!=prev['target']['inventory']||v['reserved']!=prev['target']['reserved'];count[:dispatch]+=x['delta']['births'].size;count[:removed]+=x['delta']['removed'].size;count[:phaseChanges]+=x['delta']['phases'].size;count[:ambiguousDeltas]+=1 unless x['delta']['changedBuildings'].empty?;prev=x
end
raise 'summary counts' unless progress.size==70&&first==200394&&count.all?{|k,v|s['transitions'][k.to_s]==v};raise 'diagnostic changed' unless d.all?{|x|x['unchanged']&&x['mainStateShaBefore']==x['mainStateShaAfter']}
snaps=s['saved'].map do |meta|
 raw=File.binread(p+'/'+meta['label']+'.fls.json');raise 'fileSHA' unless Digest::SHA256.hexdigest(raw)==meta['fileSha256'];state=JSON.parse(raw)['state'];compact=raw[(raw.index(',"state":')+9)...-1];raise 'stateSHA' unless Digest::SHA256.hexdigest(compact)==meta['stateSha256'];raise 'tick' unless state['tick']==meta['tick'];target=state['buildings'].find{|v|v['id']=='construction-site-000050'};row=t.find{|v|v['toTick']==meta['tick']};raise 'target saved vs trace' unless row['target'].all?{|k,v|%w[capacity].include?(k)||(k=='operationPaused'||k=='upkeepUnpaid' ? (target[k]||false)==v : k=='stuckSinceTick' ? target[k]==v : target[k]==v)}
 {label:meta['label'],tick:state['tick'],file_sha256:meta['fileSha256'],state_sha256:meta['stateSha256'],topology_fields:%w[width height roadRevision tiles buildings palisade river wallConstructionReserve].to_h{|k|[k,{present:state.key?(k),type:state[k].class.name}]}}
end
result={verdict:'PASS_BOUNDED_TRANSIENT_PRODUCTION_RECOVERY',manifest_counts:counts,trace_rows:t.size,public_steps:3840,first_target_change:first,progress_changes:progress.size,completion_resets:progress.select{|x|x[:to]==0},progress_first:progress.first,progress_last:progress.last,stock_changes:stock,diagnostic_rows:d.size,diagnostic_operations:d.group_by{|x|x['operation']}.transform_values(&:size),diagnostics_all_hash_unchanged:true,topology_changed_rows:t.count{|x|x['topologyChanged']},all_tick_end_stores_committed_full:t.drop(1).all?{|x|x['stores'].all?{|y|y['space']==0}},snapshots:snaps,transitions:count,endpoint_target:t.last['target'],official_exit:File.read(r+'/runner-exit-code').strip,official_timing:File.read(r+'/runner-timing.env'),scope_correction:j(r+'/PARENT_CHECK.json').slice('scope','scopeId','recordCorrection'),limits:s['limitations']}
File.write(__dir__+'/REVIEW.json',JSON.pretty_generate(result)+"\n");puts JSON.pretty_generate(result.reject{|k,v|[:stock_changes,:snapshots,:limits].include?(k)})
