import fs from 'node:fs/promises';import path from 'node:path';import sharp from '/Users/rexxa/.npm/_npx/8b377f6eec906bc4/node_modules/sharp/lib/index.js';import crypto from'node:crypto';
const W='/tmp/astra-wave17-work-20260926',D=W+'/delivery',rows=JSON.parse(await fs.readFile(W+'/catalog.json'));let checks=[];function check(name,ok,detail){checks.push({name,pass:Boolean(ok),detail});if(!ok)throw Error(name+': '+detail);}
check('candidate_count',rows.length===57,rows.length);check('illustration_count',rows.filter(r=>r.file.includes('/illustration/')).length===22,22);let all=[];
for(const r of rows){let meta=await sharp(D+'/'+r.file).metadata(),buf=await fs.readFile(D+'/'+r.file);check('sha:'+r.asset_id,crypto.createHash('sha256').update(buf).digest('hex')===r.sha256,'Current final pixels match CSV');check('dims:'+r.asset_id,meta.width===r.width&&meta.height===r.height,[meta.width,meta.height]);check('prompt:'+r.asset_id,Boolean(r.full_prompt),'Complete prompt or explicit reuse record');if(r.file.includes('/illustration/')){let wh=r.file.includes('/event/')?[960,540]:r.file.includes('/decision/')?[640,480]:r.file.includes('/chronicle/')?[384,384]:[1920,1080];check('illustration_spec:'+r.asset_id,meta.width===wh[0]&&meta.height===wh[1],wh);}else check('rgba:'+r.asset_id,meta.hasAlpha&&r.alpha_nonzero_pixels>0&&r.alpha_nonzero_pixels<r.width*r.height,'Nonempty true alpha');all.push(r.file);}
let pfiles=(await fs.readdir(D+'/proofs')).filter(f=>f.endsWith('.png'));check('proof_count',pfiles.length===3,pfiles);for(const p of pfiles){await sharp(D+'/proofs/'+p).stats();}
const pairs=[['wk_levy_archer-v1','P4'],['wk_levy_billman-v1','P4'],['wk_raider-v1','P4'],['wk_royal_purveyor-v1','P1'],['wk_tax_collector-v1','P1'],['wk_refugee_family-v1','P5']];for(const[n,t]of pairs){const a=await sharp(D+'/assets/wk/'+n+'.png').ensureAlpha().raw().toBuffer(),b=await sharp(D+'/reference/templates/'+t+'.png').ensureAlpha().raw().toBuffer();let diff=0;for(let i=3;i<a.length;i+=4)if(a[i]!==b[i])diff++;check('worker_exact_alpha:'+n,diff===0,diff);}
const cargo=await sharp(D+'/assets/herd/wool_sack_convoy-v1.png').ensureAlpha().raw().toBuffer();check('cargo_f0_f1',cargo.subarray(0,512*96*4).equals(cargo.subarray(512*96*4)),true);
let idle=await sharp(D+'/assets/bld/beacon_idle-v1.png').ensureAlpha().raw().toBuffer(),lit=await sharp(D+'/assets/bld/beacon_lit-v1.png').ensureAlpha().raw().toBuffer();check('beacon_base_preserved_below56',idle.subarray(56*128*4).equals(lit.subarray(56*128*4)),true);
let qa=JSON.parse(await fs.readFile(W+'/records/independent-qa-verdict.json'));let result={status:'PASS',candidate_pngs:57,proof_pngs:3,assertions:checks.length,checks,visual_qa:qa,scope:'Offline candidate assets only; no game installation or runtime validation.'};await fs.writeFile(D+'/records/final-validation.json',JSON.stringify(result,null,2));console.log(JSON.stringify({status:result.status,assets:57,proofs:3,assertions:checks.length}));
