import sharp from '/Users/rexxa/.npm/_npx/8b377f6eec906bc4/node_modules/sharp/lib/index.js';
import fs from 'node:fs/promises';
const W='/tmp/astra-wave17-work-20260926';
const specs=[['wk_levy_archer-v1','P4'],['wk_levy_billman-v1','P4'],['wk_royal_purveyor-v1','P1'],['wk_tax_collector-v1','P1'],['wk_raider-v1','P4'],['wk_refugee_family-v1','P5']];
const px=async f=>{const {data,info}=await sharp(f).ensureAlpha().raw().toBuffer({resolveWithObject:true});return {data,w:info.width,h:info.height}};
function bb(p,x,y,w,h,t=20){let l=x+w,r=-1,a=y+h,b=-1;for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)if(p.data[(yy*p.w+xx)*4+3]>t){l=Math.min(l,xx);r=Math.max(r,xx);a=Math.min(a,yy);b=Math.max(b,yy)};if(r<0)throw Error('No alpha in cell');return{left:l,top:a,width:r-l+1,height:b-a+1}}
const dirs=['NE','SE','SW','NW'];let csv='asset,direction,frame,template,foot_dx_px,foot_dy_px,head_dx_px,head_dy_px,alpha_difference_pixels,protected_foot_rgb_difference_pixels,clothing_changed_pixels,verdict\n',meta=[];
await fs.mkdir(W+'/delivery/assets/wk',{recursive:true});
for(const [id,t]of specs){const rec=JSON.parse(await fs.readFile(W+'/records/'+id+'.json','utf8')),template=W+'/workerrefs/'+t+'.png',s=await px(template),g=await px(rec.source),o=Buffer.from(s.data);let total=0;
for(let row=0;row<2;row++)for(let col=0;col<4;col++){const sx=col*74,sy=row*74,b=bb(s,sx,sy,74,74),gx=Math.round(col*g.w/4),gy=Math.round(row*g.h/2),gb=bb(g,gx,gy,Math.round((col+1)*g.w/4)-gx,Math.round((row+1)*g.h/2)-gy),tex=await sharp(rec.source).extract(gb).resize(b.width,b.height,{fit:'fill'}).ensureAlpha().raw().toBuffer();let changed=0;
for(let y=b.top;y<b.top+b.height-10;y++)for(let x=b.left;x<b.left+b.width;x++){const i=(y*s.w+x)*4,j=((y-b.top)*b.width+x-b.left)*4;if(s.data[i+3]<20||tex[j+3]<100)continue;const helmet=id==='wk_levy_billman-v1'&&y<b.top+9;if(y<b.top+16&&!helmet)continue;const lum=(s.data[i]+s.data[i+1]+s.data[i+2])/3,glum=(tex[j]+tex[j+1]+tex[j+2])/3;if(glum<8)continue;for(let c=0;c<3;c++)o[i+c]=Math.max(0,Math.min(255,tex[j+c]*(.8+.2*lum/glum)));if(o[i]!==s.data[i]||o[i+1]!==s.data[i+1]||o[i+2]!==s.data[i+2])changed++;}
let alphaDiff=0,feetDiff=0;for(let y=sy;y<sy+74;y++)for(let x=sx;x<sx+74;x++){const i=(y*s.w+x)*4;if(o[i+3]!==s.data[i+3])alphaDiff++;if(y>=b.top+b.height-10&&o[i+3]&&(o[i]!==s.data[i]||o[i+1]!==s.data[i+1]||o[i+2]!==s.data[i+2]))feetDiff++;}const ob=bb({data:o,w:s.w,h:s.h},sx,sy,74,74);if(alphaDiff||feetDiff||ob.top!==b.top)throw Error('Contract fail '+id);total+=changed;csv+=`${id},${dirs[col]},${row},templates/${t}.png,0,0,0,0,${alphaDiff},${feetDiff},${changed},PASS\n`;}
await sharp(o,{raw:{width:s.w,height:s.h,channels:4}}).png().toFile(W+'/delivery/assets/wk/'+id+'.png');rec.registration_template=template;rec.processing='Generated clothing RGB registered per cell to exact approved Pilot2 template alpha. Entire silhouette unchanged. Bottom 10px figure feet RGB byte-preserved. Original face/head top16px retained except billman top9px ironcap recolor; head alpha unchanged.';rec.clothing_changed_pixels=total;await fs.writeFile(W+'/records/'+id+'.json',JSON.stringify(rec,null,2));meta.push({id,template,source:rec.source,changed:total});}
await fs.writeFile(W+'/delivery/worker-overlap.csv',csv);await fs.writeFile(W+'/records/worker-registration.json',JSON.stringify(meta,null,2));
const panels=[];for(let k=0;k<specs.length;k++){const[id,t]=specs[k];for(const[j,file]of [W+'/workerrefs/'+t+'.png',W+'/delivery/assets/wk/'+id+'.png'].entries())panels.push({input:await sharp(file).resize(592,296,{kernel:'nearest'}).png().toBuffer(),left:j*610,top:k*320+22});panels.push({input:Buffer.from(`<svg width="1200" height="22"><text x="8" y="17" fill="#eee" font-size="15">${id} | template / candidate | foot 0px · head 0px · alpha exact</text></svg>`),left:0,top:k*320});}
await sharp({create:{width:1220,height:1920,channels:4,background:'#6b7162'}}).composite(panels).png().toFile(W+'/worker-contact.png');console.log(JSON.stringify(meta));
