import sharp from '/Users/rexxa/.npm/_npx/8b377f6eec906bc4/node_modules/sharp/lib/index.js';
import fs from 'node:fs/promises';
import {px,box,write,svg,label} from '/tmp/astra-wave12-work-20260926/build.mjs';
export const W='/tmp/astra-wave17-work-20260926',D=W+'/delivery';
const names=['beacon_idle','muster_field','royal_warehouse','raid_burning_quay','raid_smoke_column_sheet','stone_wall_repair_scaffold','trampled_field'];
export async function build(){let all=[];for(const id of names){let f=W+'/records/world-'+id+(id==='stone_wall_repair_scaffold'?'-v2':'')+'.json',a=JSON.parse(await fs.readFile(f));let p=await px(a.source);const structural=!/smoke|burning|trampled/.test(id);if(structural)for(let i=3;i<p.data.length;i+=4)p.data[i]=p.data[i]>=240?255:0;let b;
if(id==='raid_burning_quay'){let cps=[];for(let c=0;c<3;c++){let left=Math.round(p.w*[.30,.46,.64][c]),right=Math.round(p.w*[.46,.64,.85][c]);let crop=await sharp(p.data,{raw:{width:p.w,height:p.h,channels:4}}).extract({left,top:0,width:right-left,height:p.h}).raw().toBuffer({resolveWithObject:true});let sub={data:crop.data,w:crop.info.width,h:crop.info.height};let bb=box(sub,20),tw=[32,38,39][c],th=[41,48,31][c];let input=await sharp(sub.data,{raw:{width:sub.w,height:sub.h,channels:4}}).extract(bb).resize(tw,th,{fit:'fill'}).png().toBuffer();cps.push({input,left:[55,109,175][c],top:[38,8,3][c]});}b=await sharp({create:{width:a.w,height:a.h,channels:4,background:'#00000000'}}).composite(cps).raw().toBuffer();a.registration='Independent fire clusters registered to quay cargo surface. Canvas256x128, origin0,0 identical to original quay.';
}else if(id==='raid_smoke_column_sheet'){let cps=[];for(let c=0;c<4;c++){const left=Math.round(c*p.w/4),right=Math.round((c+1)*p.w/4);let crop=await sharp(p.data,{raw:{width:p.w,height:p.h,channels:4}}).extract({left,top:0,width:right-left,height:p.h}).raw().toBuffer({resolveWithObject:true});let sub={data:crop.data,w:crop.info.width,h:crop.info.height},bb=box(sub,8);let input=await sharp(sub.data,{raw:{width:sub.w,height:sub.h,channels:4}}).extract(bb).resize(108,180,{fit:'fill'}).png().toBuffer();cps.push({input,left:c*128+10,top:6});}b=await sharp({create:{width:a.w,height:a.h,channels:4,background:'#00000000'}}).composite(cps).raw().toBuffer();a.registration='4x1; cell128x192; common ground pivot64,186. Individual diffusion normalized to same envelope.';
}else if(id==='stone_wall_repair_scaffold'){b=await sharp(p.data,{raw:{width:p.w,height:p.h,channels:4}}).extract(box(p,8)).resize(a.w,a.h,{fit:'fill'}).raw().toBuffer();a.registration='Straight512x128 wall strip per Wave4 stone_face_a. Strip endpoints not declared seamless; overlap scaffold join at installation.';
}else{const bb=box(p,8);const mw=a.w-(id==='trampled_field'?0:16),mh=a.h-(id==='beacon_idle'?52:16);const s=Math.min(mw/bb.width,mh/bb.height),tw=Math.round(bb.width*s),th=Math.round(bb.height*s);const input=await sharp(p.data,{raw:{width:p.w,height:p.h,channels:4}}).extract(bb).resize(tw,th).png().toBuffer();const x=Math.floor((a.w-tw)/2),y=a.h-(id==='trampled_field'?0:8)-th;b=await sharp({create:{width:a.w,height:a.h,channels:4,background:'#00000000'}}).composite([{input,left:x,top:y}]).raw().toBuffer();a.registration=`Single uniform downsample alpha crop; placement${x},${y},${tw},${th}`;}
a.file='assets/'+a.folder+'/'+a.id+'-v1.png';await write({data:b,w:a.w,h:a.h},D+'/'+a.file);all.push(a);}await fs.writeFile(W+'/world-registered.json',JSON.stringify(all,null,2));return all;}
export async function contact(){let records=JSON.parse(await fs.readFile(W+'/world-registered.json'));let cps=[],txt='';for(let i=0;i<records.length;i++){const a=records[i],x=(i%3)*530,y=Math.floor(i/3)*310;let input=await sharp(D+'/'+a.file).png().toBuffer();cps.push({input,left:x+Math.round((530-a.w)/2),top:y+Math.max(10,265-a.h)});txt+=label(x+12,y+291,a.id+' '+a.w+'x'+a.h,14);}const h=Math.ceil(records.length/3)*310;cps.push({input:svg(1590,h,txt),left:0,top:0});await sharp({create:{width:1590,height:h,channels:4,background:'#b4b39d'}}).composite(cps).png().toFile(W+'/world-contact.png');}
if(process.argv.includes('--build')){await build();await contact();}
