require 'json';require 'digest'
d=__dir__;repo='/Users/rexxa/fls-astra-steward';head='5fb1aebfe735592c1424c947e88388d4ffe21742'
rows=[]
add=lambda{|template,field,contract,branches|rows<<{template:template,field:field,values:branches.map(&:first),captureContract:contract,variants:branches.map{|value,headline|{id:template+'.r06wp.'+value,when:{field:'context.'+field,op:'eq',value:value},headline:headline,retainFactLine:true,requiredSlots:[]}}}}
ring='At the existing history emission edge, inspect after.palisade.segments. no_ring iff null/empty; unfinished iff nonempty and any completed false; complete iff nonempty and every completed true. Do not infer stone material, safety, or garrison. Store enum at emission, not current ring at reading.'
add.call('war.messenger','ringAtMessenger',ring,[['no_ring','둘레 방벽이 없는 도시에 국왕의 전령이 전쟁 소식을 가져왔다.'],['unfinished','둘레 방벽 공사가 끝나지 않은 때에 국왕의 전령이 왔다.'],['complete','둘레 방벽이 완성된 도시에 국왕의 전령이 전쟁 소식을 가져왔다.']])
add.call('war.beacon','ringAtBeacon',ring,[['no_ring','해안의 봉화가 올랐지만 도시에는 둘레 방벽이 없었다.'],['unfinished','해안의 봉화가 오를 때에도 둘레 방벽은 아직 미완성이었다.'],['complete','둘레 방벽이 완성된 때에 해안의 봉화가 올랐다.']])
add.call('war.licence','granaryWheatAtLicence','At undefined -> defined licenceSeasonsLeft emission, inspect after buildings kind=granary, sum nonnegative safe integer inventory.wheat (missing property means engine inventory zero). no_stock iff sum=0 including no granary; stocked iff sum>0. Invalid input unknown. This is inventory at history emission, not a transaction-stage stock and not proof any purchase or income occurred.',[['no_stock','왕실 조달 면허를 받았으나 그때 곡물창고에 든 밀은 없었다.'],['stocked','곡물창고에 밀이 남아 있는 때에 왕실 조달 면허를 받았다.']])
add.call('plague.rumour','arrivalAlongsideRumour','Only on rumourTick undefined -> defined. no_arrival iff after.plague.first undefined; arrival_recorded iff first exists and arrivalTick equals after.tick. Other old/future/inconsistent state unknown. No claim about real-world knowledge timing or prevention.',[['no_arrival','항구의 열병 소문이 먼저 들어왔고, 도시의 역병 도착은 아직 기록되지 않았다.'],['arrival_recorded','항구의 열병 소문과 도시의 역병 도착이 같은 때에 기록되었다.']])
add.call('plague.arrived','priorRumourAtArrival','Only first undefined -> defined. prior_rumour iff before.plague.rumourTick exists and is strictly less than first.arrivalTick=after.tick. no_prior_rumour iff before.plague.rumourTick undefined. Same/future/inconsistent tick unknown. Absence means no prior in-game rumour record, not ignorance or lack of preparation.',[['prior_rumour','앞서 열병 소문이 들어온 뒤, 역병이 도시에 도착했다.'],['no_prior_rumour','앞선 열병 소문 기록 없이 역병의 도시 도착이 기록되었다.']])
add.call('plague.second','curacyAtSecondArrival','Only second undefined -> defined AND first.endTick defined <= after.tick. after.curacy must exist. filled iff filledTick defined <= after.tick; vacant iff filledTick absent or > after.tick. Malformed dates unknown. This classifies appointment state only, not presence of a church building or named living priest. Same-tick curacy transitions use after and imply no ordering within tick.',[['filled','사제 자리를 채운 상태에서 두 번째 역병이 도착했다.'],['vacant','사제 자리가 빈 상태에서 두 번째 역병이 도착했다.']])
p={version:'war-plague-context-v1',status:'PROPOSED_UNINSTALLED',sourceHead:head,captureKind:'emission_snapshot',fallback:'Unknown, missing, malformed, wrong event binding or unverified capture -> original fact line only; do not backfill current state.',templates:rows}
write=lambda{|f,v|File.write(d+'/'+f,JSON.pretty_generate(v)+"\n")};write.call('PROPOSAL.json',p)
base={'type'=>'object','required'=>%w[status recordId recordTick template sourceHead captureKind referenceVerified fields],'additionalProperties'=>false,'properties'=>{'status'=>{'enum'=>%w[known unknown]},'recordId'=>{'type'=>'string','minLength'=>1},'recordTick'=>{'type'=>'integer','minimum'=>0},'template'=>{'enum'=>rows.map{|r|r[:template]}},'sourceHead'=>{'const'=>head},'captureKind'=>{'const'=>'emission_snapshot'},'referenceVerified'=>{'type'=>'boolean'},'fields'=>{'type'=>'object'}}}
base['anyOf']=rows.map{|r|{'properties'=>{'status'=>{'const'=>'known'},'template'=>{'const'=>r[:template]},'referenceVerified'=>{'const'=>true},'fields'=>{'type'=>'object','required'=>[r[:field]],'additionalProperties'=>false,'properties'=>{r[:field]=>{'enum'=>r[:values]}}}}}}+[{'properties'=>{'status'=>{'const'=>'unknown'},'fields'=>{'const'=>{}}}}];write.call('CONTEXT.schema.json',base)
# Freeze the reviewed field/domain/template contract, not merely an open array.
ps={'type'=>'object','required'=>p.keys.map(&:to_s),'additionalProperties'=>false,'properties'=>p.reject{|k,v|k==:templates}.transform_keys(&:to_s).transform_values{|v|{'const'=>v}}};ps['properties']['templates']={'type'=>'array','minItems'=>6,'maxItems'=>6,'uniqueItems'=>true,'items'=>{'anyOf'=>rows.map{|r|{'type'=>'object','required'=>r.keys.map(&:to_s),'additionalProperties'=>false,'properties'=>r.reject{|k,v|k==:variants}.transform_keys(&:to_s).transform_values{|v|{'const'=>v}}.merge('variants'=>{'type'=>'array','minItems'=>r[:variants].size,'maxItems'=>r[:variants].size,'uniqueItems'=>true,'items'=>{'anyOf'=>r[:variants].map{|v|{'type'=>'object','required'=>v.keys.map(&:to_s),'additionalProperties'=>false,'properties'=>v.transform_keys(&:to_s).transform_values{|x|{'const'=>x}}}}}})}}}};write.call('PROPOSAL.schema.json',ps)
fixtures=rows.flat_map{|r|r[:variants].map{|v|{id:v[:id],template:r[:template],recordId:'h-probe',recordTick:1000,context:{status:'known',recordId:'h-probe',recordTick:1000,template:r[:template],sourceHead:head,captureKind:'emission_snapshot',referenceVerified:true,fields:{r[:field]=>v[:when][:value]}},expected:v[:id]}}};write.call('FIXTURES.json',fixtures)
source={'src/engine/history.ts'=>[[608,632],[642,682]],'src/engine/war.ts'=>[[146,155],[380,385],[443,461],[500,535]],'src/engine/plague.ts'=>[[499,534],[544,559]],'src/content/historyCopy.ko.ts'=>[[155,169],[208,214]],'src/engine/historyNames.ts'=>[[15,22],[43,54]]};write.call('SOURCE_EVIDENCE.json',source.map{|path,spans|text=File.read(repo+'/'+path);{path:path,sha256:Digest::SHA256.hexdigest(text),spans:spans.map{|a,b|{start:a,end:b,text:text.lines[(a-1)..(b-1)].join}}}})
write.call('NOT_AUTHORED.json',{template:'plague.priest_died',status:'NOT_AUTHORED_FIXED_FACT_AND_BASELINE_RISK',reason:'Producer tests curacy created, not a named-person death transition. Arrival sets vacantSince and adds priest petition regardless of whether a church building or tracked priest exists. Existing fact line asserts priest death and church emptied. Do not author population/death-size variants on this marker; neutral vacancy baseline review needed. Engine unchanged.'})
