const fs=require('fs'),path=require('path'),sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..'),prior=path.resolve(root,'../astra-lineage-pilot-v1');
const commonTraits={hair:'chestnut auburn',faceShape:'broad oval overall outline',feature:'gently arched eyebrows'};
const people={L2_203:{ages:{baby:2,child:9,young:24,mature:44},markers:['three years older than sister','long straight chestnut hair in single braid','clear green eyes','slender long neck and narrow shoulders','dense freckles across nose and cheeks','noticeably wide mouth'],clothing:'muted sage fine wool merchant dress, linen neckline'},L2_204:{ages:{baby:0.5,child:6,young:21,mature:41},markers:['three years younger than sister','short loose curly chestnut bob','dark brown eyes','plump cheeks and stockier shoulders','small dark birthmark immediately below anatomical LEFT eye (viewer right)','small compact mouth'],clothing:'dusty russet fine wool merchant dress, linen neckline'}};
function job(identity,stage){const p=people[identity]; const refs=[path.join(prior,'assets/lineage2/L2_101_mature.png'),path.join(prior,'assets/lineage2/L2_102_mature.png')];if(stage!=='young')refs.unshift(path.join(root,'assets/sisters/'+identity+'_young.png'));const prompt='Single square head and upper torso painterly historical game portrait, soft muted taupe background, naturalistic hand-painted gouache/oil, subtle brushwork, upper-left light. Match project references. No text, no frame, no symbols. '+(stage==='young'?'Images 1 and 2 are the actual father and mother. Create their daughter as a strongly individual NEW person. Family resemblance restricted to chestnut auburn hair, broad oval overall face outline, gently arched eyebrows. DO NOT copy either parent nose or jaw. Invent individual nose and chin. ':'Image 1 is THIS EXACT PERSON young adult, images 2 and 3 are actual father and mother. Age-transform image 1 preserving personal face identity and distinctive markers; do not substitute sibling or parent. ')+'Female '+identity+', exact age '+p.ages[stage]+'. Individual markers: '+p.markers.join('; ')+'. '+(stage==='child'?'CLEARLY a '+p.ages[stage]+' year old prepubescent child, NOT 12-14, little child proportions, shorter lower face, large childhood cranium, child-sized shoulders, no adolescent chest or adult makeup. ':stage==='baby'?'Clearly a face-visible '+(identity==='L2_203'?'two year old toddler with short early hair not long braid; freckles subtle early signs':'six month old baby with fine short curls, birthmark retained')+', infant proportions and natural face, linen infant clothes. ':stage==='mature'?'Clearly middle-aged with age-appropriate subtle eye wrinkles and nasolabial folds, same distinctive person. ':'Young adult; avoid generic identical pretty face. ')+ 'Southern England 1300-1450. '+(stage==='baby'?'Plain linen baby garment. ':p.clothing+'. ')+'No veil, no coif, no head covering: unmarried girl/woman with hair fully visible. No jewelry, modern clothes, props or family-wide color coding. Preserve strong individual facial distinction independent of hairstyle.';
return {id:identity+'_'+stage,identity,lineage:'L2',generation:2,stage,age:p.ages[stage],sex:'female',fatherIdentity:'L2_101',motherIdentity:'L2_102',commonTraits,differenceMarkers:p.markers,clothing:p.clothing,prompt,referenceImages:refs,file:'assets/sisters/'+identity+'_'+stage+'.png'};}
const jobs=Object.keys(people).flatMap(i=>['young','child','baby','mature'].map(s=>job(i,s)));
async function main(){if(process.argv[2]==='jobs')console.log(JSON.stringify(jobs));if(process.argv[2]==='save'){const q=JSON.parse(Buffer.from(process.argv[3],'base64').toString()),j=jobs.find(x=>x.id===q.id),raw='raw/sisters/'+j.id+'.png';fs.copyFileSync(q.source,path.join(root,raw));const m=await sharp(q.source).metadata();await sharp(q.source).resize(256,256,{fit:'contain',background:'#827565'}).png().toFile(path.join(root,j.file));const rp=path.join(root,'records/sisters.json'),rows=fs.existsSync(rp)?JSON.parse(fs.readFileSync(rp)):[];rows.push({...j,width:256,height:256,generationRecords:[{prompt:j.prompt,referenceImages:j.referenceImages,rawFile:raw,tool:'image_gen.imagegen',model:null,seed:null,originalWidth:m.width,originalHeight:m.height}],processing:'Sharp contain resize only; no face painting',qa:{status:'pending'}});fs.writeFileSync(rp,JSON.stringify(rows,null,2));console.log(j.file);}}
main();
async function revise(){if(process.argv[2]!=='revise')return;const q=JSON.parse(Buffer.from(process.argv[3],'base64').toString()),rp=path.join(root,'records/sisters.json'),rows=JSON.parse(fs.readFileSync(rp)),j=rows.find(x=>x.id===q.id);const raw='raw/sisters/'+j.id+'-v2.png';fs.copyFileSync(q.source,path.join(root,raw));const m=await sharp(q.source).metadata();await sharp(q.source).resize(256,256,{fit:'contain',background:'#827565'}).png().toFile(path.join(root,j.file));j.generationRecords.push({prompt:q.prompt,referenceImages:q.refs,rawFile:raw,tool:'image_gen.imagegen',model:null,seed:null,originalWidth:m.width,originalHeight:m.height});j.qa={status:'age correction visually reviewed',reason:'First output read older than requested; child anatomy unlocked from adult portrait'};fs.writeFileSync(rp,JSON.stringify(rows,null,2));console.log(j.file);}revise();
