const fs=require('fs'),path=require('path'),crypto=require('crypto');
const{loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');
const r=path.resolve(__dirname,'..'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{const rows=['frames','icons','portraits'].flatMap(f=>JSON.parse(fs.readFileSync(path.join(r,'records',f+'.json'))));if(rows.length!==43)throw Error('Expected43 got'+rows.length);const out=[];
for(const a of rows){const p=path.join(r,a.file),im=await loadImage(p);if(im.width!==a.width||im.height!==a.height)throw Error('Dimensions'+a.id);if(!JSON.stringify(a.generationRecords).includes('prompt'))throw Error('Missingprompt'+a.id);out.push({asset_id:a.id,status:'candidate',file:a.file,width:im.width,height:im.height,role:a.role,sha256:sha(p),generation_records:JSON.stringify(a.generationRecords),processing:JSON.stringify(a.processing??{}),slice_or_cells:JSON.stringify(a.nineSlice??{cellSize:a.cellSize,cellOrder:a.cellOrder}),hotspot:JSON.stringify(a.hotspot??null),qa:JSON.stringify(a.qa??{})});}
fs.writeFileSync(path.join(r,'records/asset-rows.json'),JSON.stringify(out,null,2));
let html='<!doctype html><meta charset="utf-8"><title>UI P0 C candidates</title><style>body{background:#e1d1ae;color:#332d25;font:16px sans-serif;margin:24px}section{display:flex;flex-wrap:wrap;gap:16px}figure{width:340px;margin:0;padding:14px;background:#c3b595}img{max-width:100%;max-height:220px;object-fit:contain}small{display:block}a{color:#332d25}</style><h1>UI P0 C안 · 43개 후보 PNG</h1><p>A23 + B11시트(57셀) + C6 + D3 / 게임 미설치</p><p><a href="README.md">설명</a> · <a href="assets.csv">CSV43행</a></p><p><a href="proofs/01-hud-desktop-tablet.png">HUD 두 화면 합성</a> · <a href="proofs/02-icons-24px.png">전체 24px</a> · <a href="proofs/03-objective-advisor.png">상태·표정</a></p><section>';
for(const a of out)html+=`<figure><a href="${a.file}"><img src="${a.file}"><small>${a.asset_id}</small></a><small>${a.width}×${a.height}</small></figure>`;fs.writeFileSync(path.join(r,'index.html'),html+'</section>');
fs.writeFileSync(path.join(r,'records/package-validation.json'),JSON.stringify({assets:43,iconCells:57,expectedCsvRows:43,proofs:fs.readdirSync(path.join(r,'proofs')).filter(p=>p.endsWith('.png')).length,dimensionsMatch:true,generationRecordsPresent:true,gameInstalled:false,hashes:out.map(a=>({id:a.asset_id,sha:a.sha256}))},null,2));console.log('43assets validated, gallery/rows generated');})();
