const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('/Users/rexxa/.npm/_npx/8b377f6eec906bc4/node_modules/sharp/lib/index.js');
const L='/tmp/astra-wave29-work/lanes/ripples',W=256,H=128,N=8;
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const mod=(a,n)=>(a%n+n)%n;
function seamless(buf){
 let b=Buffer.from(buf);
 for(let y=0;y<H;y++)for(let i=0;i<16;i++)for(let c=0;c<4;c++){let a=(y*W+i)*4+c,z=(y*W+W-1-i)*4+c,q=.5*(1-i/16),v=b[a],u=b[z];b[a]=Math.round(v*(1-q)+u*q);b[z]=Math.round(u*(1-q)+v*q);}
 for(let x=0;x<W;x++)for(let i=0;i<12;i++)for(let c=0;c<4;c++){let a=(i*W+x)*4+c,z=((H-1-i)*W+x)*4+c,q=.5*(1-i/12),v=b[a],u=b[z];b[a]=Math.round(v*(1-q)+u*q);b[z]=Math.round(u*(1-q)+v*q);}
 return b;
}
function sample(b,x,y,c){x=mod(x,W-1);y=mod(y,H-1);let x0=Math.floor(x),y0=Math.floor(y),xf=x-x0,yf=y-y0;return b[(y0*W+x0)*4+c]*(1-xf)*(1-yf)+b[(y0*W+(x0+1)%(W-1))*4+c]*xf*(1-yf)+b[(((y0+1)%(H-1))*W+x0)*4+c]*(1-xf)*yf+b[(((y0+1)%(H-1))*W+(x0+1)%(W-1))*4+c]*xf*yf;}
function frame(b,t){const o=Buffer.alloc(W*H*4),a=2*Math.PI*t;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const xx=x%(W-1),yy=y%(H-1),u=xx+4*Math.cos(a)+1.2*Math.sin(a+2*Math.PI*yy/(H-1)),v=yy+2*Math.sin(a);let i=(y*W+x)*4;let alpha=Math.round(Math.min(63,sample(b,u,v,3)*63/255*(.84+.16*Math.cos(a+2*Math.PI*xx/(W-1)+2*Math.PI*yy/(H-1)))));o[i+3]=alpha;if(alpha)for(let c=0;c<3;c++)o[i+c]=Math.round(sample(b,u,v,c));}return o;}
function diff(a,b){let s=0;for(let i=0;i<a.length;i+=4){for(let c=0;c<3;c++)s+=Math.abs(a[i+c]*a[i+3]/255-b[i+c]*b[i+3]/255);s+=Math.abs(a[i+3]-b[i+3]);}return s/a.length;}
(async()=>{const configs=JSON.parse(fs.readFileSync(L+'/records/sources.json'));let index=[],qa=[];for(const cfg of configs){let raw=await sharp(cfg.source).resize(W,H,{fit:'fill'}).ensureAlpha().raw().toBuffer();if(cfg.id==='ripple_shallow_sheet'){const warped=Buffer.alloc(raw.length);for(let y=0;y<H;y++)for(let x=0;x<W;x++)for(let c=0;c<4;c++)warped[(y*W+x)*4+c]=Math.round(sample(raw,x+15*Math.sin(y*.093)+7*Math.cos(x*.061+y*.027),y+9*Math.sin(x*.078)+5*Math.cos(y*.12),c));raw=warped;}let base=seamless(raw);const frames=[];for(let k=0;k<N;k++){let b=frame(base,k/N);frames.push(b);await sharp(b,{raw:{width:W,height:H,channels:4}}).png().toFile(L+'/frames/'+cfg.id+'_'+k+'.png');}let file='assets/'+cfg.id+'-v1.png';await sharp({create:{width:W*N,height:H,channels:4,background:'#00000000'}}).composite(frames.map((b,k)=>({input:b,raw:{width:W,height:H,channels:4},left:k*W,top:0}))).png().toFile(L+'/'+file);const steps=frames.map((f,k)=>diff(f,frames[(k+1)%N]));const endpoint=diff(frame(base,0),frame(base,1));let edge=0;for(const b of frames){for(let y=0;y<H;y++)for(let c=0;c<4;c++)edge=Math.max(edge,Math.abs(b[(y*W)*4+c]-b[(y*W+W-1)*4+c]));for(let x=0;x<W;x++)for(let c=0;c<4;c++)edge=Math.max(edge,Math.abs(b[x*4+c]-b[((H-1)*W+x)*4+c]));}
 const tiles=[];for(let y=0;y<4;y++)for(let x=0;x<4;x++)tiles.push({input:frames[0],raw:{width:W,height:H,channels:4},left:x*W,top:y*H});await sharp({create:{width:W*4,height:H*4,channels:4,background:'#517983'}}).composite(tiles).png().toFile(L+'/records/'+cfg.id+'_4x4.png');
 const gifFrames=frames.map(f=>{const b=Buffer.from(f);for(let i=0;i<b.length;i+=4){const a=b[i+3]/255;[81,121,131].forEach((v,c)=>b[i+c]=Math.round(b[i+c]*a+v*(1-a)));b[i+3]=255;}return b;});await sharp(Buffer.concat(gifFrames),{raw:{width:W,height:H*N,channels:4,pageHeight:H}}).gif({loop:0,delay:Array(N).fill(250)}).toFile(L+'/records/'+cfg.id+'.gif');
 index.push({id:cfg.id,file,frame_width:W,frame_height:H,frame_count:N,sheet_width:W*N,sheet_height:H,layout:'horizontal',fps:4,loop:true,repeat_x:true,repeat_y:true,alpha_baked_max:63,recommended_alpha:1,blend:'source-over',anchor_x:128,anchor_y:64,notes:'Painted transparent water accents. Alpha strength baked; do not multiply by 0.25 again.',prompt:cfg.prompt,generation_source:cfg.source,source_sha256:sha(cfg.source),sha256:sha(L+'/'+file),processing:'Resize coherent generated base to256x128; shallow base receives nonuniform smooth spatial warp to break straight lattice; symmetrical16pxX/12pxY edgecrossfade; periodic bilinear sampling on255x127 domain; cyclic4pxX/2pxY drift with1.2px shear; continuous0.68..1 alpha modulation; bakedmax63; zeroRGBwhenalpha0.',preview_frame:0});qa.push({id:cfg.id,edge_max_RGBA_difference:edge,analytical_t0_t1_difference:endpoint,temporal_steps_premultiplied_mean:steps,wrap_ratio:steps[7]/Math.max(...steps.slice(0,7)),alpha_max:Math.max(...frames[0].filter((_,i)=>i%4===3))});}
fs.writeFileSync(L+'/index.json',JSON.stringify(index,null,2));fs.writeFileSync(L+'/records/qa.json',JSON.stringify(qa,null,2));console.log(JSON.stringify(qa));})();
