require 'json';require 'digest'
r=__dir__;repo='/Users/rexxa/fls-astra-steward';round=File.dirname(File.dirname(r));head='5fb1aebfe735592c1424c947e88388d4ffe21742'
write=lambda{|n,x|File.write(r+'/'+n,JSON.pretty_generate(x)+"\n")}
templates=[]
add=lambda do |name,field,contract,lines|
 t='legacy.'+name
 templates<<{template:t,field:field,values:lines.keys,captureContract:contract,variants:lines.map{|key,text|{id:t+'.r06gov.'+key,when:{field:'context.'+field,op:'eq',value:key},headline:text,retainFactLine:true,requiredSlots:[]}}}
end
add.call('royal_tax_envoy','townMarketTollsAtEnvoy','At steps.royal_tax_envoy absent->present: inspect after.politics.rights, unique id=market_tolls. held iff holder=townsfolk; not_held iff no such id or unique other holder. Missing politics/rights, duplicates, invalid holder unknown. Only this political right, not all market income/estate pieces.',{'held'=>'도시가 시장 좌판세를 거둘 권리를 지닌 때에 국왕의 과세 사절이 왔다.','not_held'=>'도시가 시장 좌판세를 거둘 권리를 지니지 않은 때에 국왕의 과세 사절이 왔다.'})
add.call('royal_subsidy','cashAfterSubsidy','At legacy.royalSubsidy positive increase; use treasuryBalance(after), safe integer >=0; zero iff0 else remaining. record.params.amount must equal positive delta. This is after-emission cash, not attribution of every same-tick payment. Do not include charter confirmation fee, which posts ledger but does not increment royalSubsidy.',{'zero'=>'국왕에게 보조세를 낸 때, 금고에 남은 돈은 없었다.','remaining'=>'국왕에게 보조세를 낸 뒤에도 금고에 돈이 남아 있었다.'})
add.call('city_seal','heirChoiceBeforeSeal','At steps.city_seal absent->present: after.legacy.heir.tick <= after.tick and unique matching saved candidates by personId. son iff kind eldest_son+relation son; daughter_husband iff kind daughter_husband+relation husband; collateral iff kind nephew+relation nephew or kinsman. Missing/mismatched candidate unknown. Describes recorded choice, not current living head or rights inheritance proof.',{'son'=>'아들을 후계자로 정한 뒤, 도시는 제 인장을 새겼다.','daughter_husband'=>'딸의 남편을 후계자로 정한 뒤, 도시는 제 인장을 새겼다.','collateral'=>'다른 친족을 후계자로 정한 뒤, 도시는 제 인장을 새겼다.'})
add.call('charter_sealed','mayorSelectionAtSeal','At borough_autonomy answer absent->accept: record.params.mayorId must equal after.legacy.mayorId or empty on explicit null. same iff nonempty candidateId=mayorId; replacement iff both nonempty unequal; unnamed iff mayorId explicitly null. Undefined/malformed/inconsistent unknown. No lookup of alive or reason for replacement. Names only through historyNames at reading.',{'same'=>'당초 후보를 첫 도시의 시장으로 올리며 자치 특허에 인장을 찍었다.','replacement'=>'당초 후보와 다른 이를 첫 도시의 시장으로 올리며 자치 특허에 인장을 찍었다.','unnamed'=>'첫 도시의 시장 이름을 기록하지 않은 채 자치 특허에 인장을 찍었다.'})
add.call('family_departed','priorSubsidyAtDeparture','Only family_departure step absent->present AND family=departed AND borough_autonomy=accept. after.legacy.royalSubsidy safe integer>=0: paid iff>0, no_record iff0. Payment accumulator records royal tax response only; no_record does not mean no payments to Crown. Preserve original house params, not current lordship name lookup.',{'paid'=>'과세 사절이 요구한 보조세를 낸 가문이 영주관을 떠나 시골 장원으로 갔다.','no_record'=>'과세 사절의 요구에 따른 납부 기록 없이 가문은 영주관을 떠나 시골 장원으로 갔다.'})
add.call('family_stayed','priorSubsidyAtStay','Only family_departure step absent->present AND family=stayed AND borough_autonomy answer is known nonaccept response. after.legacy.royalSubsidy safe integer>=0: paid iff>0, no_record iff0. Does not infer loyalty/refusal motive. Confirmation ledger charges are not this accumulator.',{'paid'=>'과세 사절이 요구한 보조세를 낸 가문은 영주관에 그대로 남았다.','no_record'=>'과세 사절의 요구에 따른 납부 기록 없이 가문은 영주관에 남았다.'})
p={version:'legacy-government-context-v1',status:'PROPOSED_UNINSTALLED',sourceHead:head,baselineSha256:Digest::SHA256.file(round+'/chronicle/variants.ko.json').hexdigest,captureKind:'emission_snapshot',fallback:'unknown or invalid context => original fact line only; capture provenance must be independently validated, not trusted from a flag',templates:templates}
write.call('PROPOSAL.json',p)
write.call('PROPOSAL.schema.json',{'type'=>'object','const'=>JSON.parse(JSON.generate(p))})
record={'type'=>'object','required'=>%w[id tick template],'additionalProperties'=>false,'properties'=>{'id'=>{'type'=>'string','minLength'=>1,'pattern'=>'^\\S+$'},'tick'=>{'type'=>'integer','minimum'=>0},'template'=>{'enum'=>templates.map{|t|t[:template]}}}}
write.call('RECORD.schema.json',record)
cs={'type'=>'object','required'=>%w[status recordId recordTick template sourceHead captureKind referenceVerified fields],'additionalProperties'=>false,'properties'=>{'status'=>{'enum'=>%w[known unknown]},'recordId'=>{'type'=>'string','minLength'=>1,'pattern'=>'^\\S+$'},'recordTick'=>{'type'=>'integer','minimum'=>0},'template'=>{'enum'=>templates.map{|t|t[:template]}},'sourceHead'=>{'const'=>head},'captureKind'=>{'const'=>'emission_snapshot'},'referenceVerified'=>{'type'=>'boolean'},'fields'=>{'type'=>'object'}},'anyOf'=>[]}
templates.each{|t|cs['anyOf']<<{'properties'=>{'status'=>{'const'=>'known'},'template'=>{'const'=>t[:template]},'referenceVerified'=>{'const'=>true},'fields'=>{'type'=>'object','required'=>[t[:field]],'additionalProperties'=>false,'properties'=>{t[:field]=>{'enum'=>t[:values]}}}}}}
cs['anyOf']<<{'properties'=>{'status'=>{'const'=>'unknown'},'referenceVerified'=>{'const'=>false},'fields'=>{'type'=>'object','additionalProperties'=>false}}}
write.call('CONTEXT.schema.json',cs)
fixtures=templates.flat_map{|t|t[:variants].map{|v|{id:v[:id],record:{id:'fixture-'+v[:id],tick:440000,template:t[:template]},context:{status:'known',recordId:'fixture-'+v[:id],recordTick:440000,template:t[:template],sourceHead:head,captureKind:'emission_snapshot',referenceVerified:true,fields:{t[:field]=>v[:when][:value]}},expected:v[:id]}}}
write.call('FIXTURES.json',fixtures)
spans={'src/engine/history.ts'=>[[729,760]],'src/engine/legacy.ts'=>[[72,81],[146,191],[249,253],[490,501]],'src/engine/legacy.types.ts'=>[[7,26],[48,69]],'src/content/historyCopy.ko.ts'=>[[186,197]],'src/content/reorganisationConfig.ts'=>[[19,24]],'src/content/legacyConfig.ts'=>[[10,27],[50,53]],'src/ui/lordshipCopy.ko.ts'=>[[6,11]],'src/engine/persons.ts'=>[[655,678]],'src/engine/historyNames.ts'=>[[1,18],[43,54]],'docs/design/glossary.md'=>[[23,35],[67,84],[191,191]]}
write.call('SOURCE_EVIDENCE.json',spans.map{|path,rs|s=File.read(repo+'/'+path);{path:path,sha256:Digest::SHA256.hexdigest(s),spans:rs.map{|a,b|{start:a,end:b,text:s.lines[(a-1)..(b-1)].join}}}})
code=File.read(File.dirname(r)+'/war-plague-context/validate.rb');File.write(r+'/schema_validator.rb',code[0...code.index('d=__dir__;read=')])
f=r+'/schema_validator.rb';s=File.read(f);s=s.sub('!Regexp.new(schema[\'pattern\']).match?(value)', '!(schema[\'pattern\'] == \'^\\\\S+$\' ? /\\A\\S+\\z/.match?(value) : Regexp.new(schema[\'pattern\']).match?(value))');File.write(f,s)
