require 'json';require 'digest';require 'fileutils'
d=__dir__;repo='/Users/rexxa/fls-astra-steward';head='5fb1aebfe735592c1424c947e88388d4ffe21742';write=lambda{|f,v|File.write(d+'/'+f,JSON.pretty_generate(v)+"\n")};fields=[];adds=[]
add=lambda do |t,id,source,rule,branches|
 fields<<{id:id,values:branches.map(&:first),templates:[t],capture:source,producer:'src/engine/history.ts:689-720',currentRecordStorage:'Context absent from existing record; snapshot proposed.',currentOtherStorage:'Mutable reorganisation/person state; never read current state to reconstruct a historical condition.',immutableReconstruction:'Unknown for older records unless exact immutable event-time capture verified; no nearest-record or present-person inference.',provenance:'emission_snapshot',captureRule:rule}
 branches.each{|v,line|adds<<{template:t,variant:{id:t+'.r06rg.'+v,priority:20,when:[{field:'context.'+id,op:'eq',value:v}],headline:line,requiredSlots:[],retainFactLine:true}}}
end
add.call('reorg.wage_competition','departuresAtWageOpening','src/engine/reorganisation.ts:417-424','Only wageCompetitionTick undefined->defined at after.tick. Compare before/after wageLeavers counters, safe nonnegative integers (undefined before reorganisation means source default0 only when creation proved). delta0 -> none_recorded; delta>0 -> departure_recorded. Counter captures this wage mechanism, not all town departures; no claim poorest person chose destination.',[['none_recorded','이웃 장원의 임금 경쟁이 시작됐지만, 그 첫 시점의 임금 경쟁 이주 기록은 없었다.'],['departure_recorded','이웃 장원의 임금 경쟁이 시작된 때에, 이 경쟁으로 떠난 가구도 기록되었다.']])
add.call('reorg.guild_founded','headAtGuildFoundation','src/engine/reorganisation.ts:214-220,238-240','Only guild undefined->defined. after.guild.headId null -> unassigned; nonempty ID -> assigned only if exact selected ID exists uniquely in event-time persons.people. Current head at reading does not qualify. No class/occupation/blood relation inference; null proves no recorded appointee, not permanent headless guild.',[['assigned','대표를 정하며 직인 길드가 섰다.'],['unassigned','대표가 아직 지정되지 않은 채 직인 길드가 섰다.']])
add.call('reorg.weavers_left','guildAnswerAtDeparture','src/engine/reorganisation.ts:189-211,469-476','Only actual weaverLeavers increase. Capture after.answers.guild_charter exact refuse or expired. Do not derive occupation from nearest weaver_house sorting; count is cumulative and not this departure delta. Existing factual line calls all departing households weavers and gives a destination not modeled by leave; block composition until neutral fact reviewed.',[['refused','길드 설립 청원을 거절한 뒤, 이주한 가구가 기록되었다.'],['expired','길드 설립 청원이 답 없이 기한을 넘긴 뒤, 이주한 가구가 기록되었다.']])
add.call('reorg.overlord_warning','guildAtWarning','src/engine/reorganisation.ts:438-446','Only warningTick undefined->defined. after.guild exists foundedTick<=after.tick -> founded; absent -> not_founded. Invalid/future tick unknown. Condition documents coexistence only, not guild as sole warning cause; warning requires petition and influence threshold.',[['founded','직인 길드가 선 도시에 상위 영주의 경고가 전해졌다.'],['not_founded','직인 길드가 아직 서지 않은 때에 상위 영주의 경고가 전해졌다.']])
add.call('reorg.autonomy_request','autonomyRouteAtRequest','src/engine/reorganisation.ts:305-308,478-480','Capture actual autonomyDue branch at first autonomyTick. rebellion.outcome=chased with rebellion.tick<after.tick -> chased; else answers.guild_charter=accept -> guild_accepted; else -> guild_not_accepted. Require valid state and emission guard. Ordered first match; no cause inference beyond stored prior answer/event, no internal deadline historical story.',[['chased','인두세 징수원을 쫓아낸 일이 있은 뒤, 도시가 자치 특허를 요구했다.'],['guild_accepted','길드 설립을 받아들인 도시에 자치 특허 청원이 올라왔다.'],['guild_not_accepted','길드 설립을 받아들이지 않은 상태에서 도시가 자치 특허를 요구했다.']])
FileUtils.cp(File.dirname(d)+'/event-context-wave2-revised/baseline647.ko.json',d+'/baseline647.ko.json')
p={formatVersion:'event-context-proposal-v1',status:'DRAFT_UNINSTALLED_AUTHOR_ONLY',baselineSha256:Digest::SHA256.file(d+'/baseline647.ko.json').hexdigest,sourceHead:head,canonicalModified:false,engineChangesRequiredForUse:true,engineIntegrationRequiredToCompleteUserDraftTask:false,fields:fields,additions:adds,fallback:{rule:'unknown/missing/malformed/context provenance mismatch -> existing baseline only; never guess',legacyDefault:'Do not backfill inferred historical relationships or causes into old records.',nameRule:'Only IDs in snapshots; resolve names through existing historyParams(record,state) at reading time.'}};write.call('PROPOSAL.json',p);write.call('FIELD_CONTRACTS.json',fields)
# Exact frozen proposal schema; any editorial change requires schema/review change.
s={'type'=>'object','required'=>p.keys.map(&:to_s),'additionalProperties'=>false,'properties'=>p.reject{|k,v|[:fields,:additions].include?(k)}.transform_keys(&:to_s).transform_values{|v|{'const'=>v}}}
[:fields,:additions].each{|k|s['properties'][k.to_s]={'type'=>'array','minItems'=>p[k].size,'maxItems'=>p[k].size,'uniqueItems'=>true,'items'=>{'enum'=>p[k]}}};write.call('PROPOSAL.schema.json',s)
c={'type'=>'object','required'=>%w[status recordId recordTick template sourceHead captureKind referenceVerified fields],'additionalProperties'=>false,'properties'=>{'status'=>{'enum'=>%w[known unknown]},'recordId'=>{'type'=>'string','minLength'=>1},'recordTick'=>{'type'=>'integer','minimum'=>0},'template'=>{'enum'=>fields.flat_map{|f|f[:templates]}},'sourceHead'=>{'const'=>head},'captureKind'=>{'const'=>'emission_snapshot'},'referenceVerified'=>{'type'=>'boolean'},'fields'=>{'type'=>'object'}}}
c['anyOf']=fields.map{|f|{'properties'=>{'status'=>{'const'=>'known'},'template'=>{'const'=>f[:templates][0]},'referenceVerified'=>{'const'=>true},'fields'=>{'type'=>'object','required'=>[f[:id]],'additionalProperties'=>false,'properties'=>{f[:id]=>{'enum'=>f[:values]}}}}}}+[{'properties'=>{'status'=>{'const'=>'unknown'},'fields'=>{'const'=>{}}}}];write.call('CONTEXT.schema.json',c)
fixtures=adds.map{|a|v=a[:variant];field=v[:when][0][:field].sub('context.','');{id:v[:id],template:a[:template],recordId:'h-test',recordTick:1000,context:{status:'known',recordId:'h-test',recordTick:1000,template:a[:template],sourceHead:head,captureKind:'emission_snapshot',referenceVerified:true,fields:{field=>v[:when][0][:value]}},expected:v[:id]}};write.call('FIXTURES.json',fixtures)
blocks=adds.select{|a|a[:template]=='reorg.weavers_left'}.map{|a|{variantId:a[:variant][:id],status:'BLOCK_FACT_LINE_OCCUPATION_DESTINATION',reason:'leave selects households by proximity, without proving weaver occupation or modeled destination. Review neutral factual line; do not alter engine here.'}};write.call('ADOPTION_LIMITS.json',{status:'all_context_candidates_uninstalled',allVariantsRequireProvenanceAdapter:true,blocks:blocks});write.call('NOT_AUTHORED.json',[])
source={'src/engine/reorganisation.ts'=>[[189,220],[230,246],[305,308],[417,446],[469,480]],'src/engine/history.ts'=>[[689,720]],'src/content/historyCopy.ko.ts'=>[[171,181]],'src/engine/historyNames.ts'=>[[15,22],[43,54]]};write.call('SOURCE_EVIDENCE.json',source.map{|path,spans|text=File.read(repo+'/'+path);{path:path,sha256:Digest::SHA256.hexdigest(text),spans:spans.map{|a,b|{start:a,end:b,text:text.lines[(a-1)..(b-1)].join}}}})
