require 'json';require 'digest';require 'set'
R8='/tmp/astra-steward-r08-20261004';R7='/tmp/astra-steward-r07-20261004';REPO='/Users/rexxa/fls-astra-steward';OUT=__dir__
def j(p);JSON.parse(File.read(p));end
def sha(p);Digest::SHA256.file(p).hexdigest;end
def out(n,x);File.write(OUT+'/'+n,JSON.pretty_generate(x)+"\n");end
def objs(x);x.is_a?(Hash) ? [x]+x.values.flat_map{|v|objs(v)} : x.is_a?(Array) ? x.flat_map{|v|objs(v)} : [];end
inherit=j(R8+'/records/CUMULATIVE_D_E_INHERITANCE.json'); inheritance=inherit['rows'].map{|x|{path:x['path'],sha256:x['sha256'],r08Matches:sha(R8+'/'+x['path'])==x['sha256'],r07Matches:sha(R7+'/'+x['path'])==x['sha256']}};raise 'inheritance' unless inheritance.size==132 && inheritance.all?{|x|x[:r08Matches]&&x[:r07Matches]}
e=j(R8+'/content/events.json');r=j(R8+'/content/registry.json')['entries'];ans=j(R8+'/content/ASTRA_ANSWERS_R05.json')['answers'];a=j(R8+'/chronicle/variants.ko.json');cat=j(R8+'/chronicle/CONTEXT_DRAFTS.catalog.json');c=cat['entries'];age=j(R8+'/records/age-context-copy-proposal/ADDITIONS.json')['additions']
issues=[]
e.each{|x|%w[id category period years sender title body choices recurrence illustration history integration contentClass].each{|k|issues << [x['id'],k] if x[k].nil?||x[k].respond_to?(:empty?)&&x[k].empty?};%w[land population rights relations season state].each{|k|issues<<[x['id'],'conditions.'+k] unless x['conditions'][k]};%w[sourceIds basis inference limits sources].each{|k|issues<<[x['id'],'history.'+k] unless x['history'][k]};raise 'choice count' unless (2..4).include?(x['choices'].size);raise 'choiceids' unless x['choices'].map{|z|z['id']}==r.find{|z|z['id']==x['id']}['choices'].map{|z|z['id']}}
raise 'D fields' unless issues.empty? && e.size==200 && ans.size==24 && ans.map{|x|x['id']}.uniq.size==24
h=a['historyTemplates'];l=a['ledgerCategories'];hs=File.read(REPO+'/src/content/historyCopy.ko.ts').split('export const HISTORY_TEMPLATES:')[1].scan(/^  "([^"]+)":/).flatten;ls=File.read(REPO+'/src/ledger/ledger.types.ts').split('export const LEDGER_CATEGORIES = [')[1].split('] as const')[0].lines.reject{|x|x.lstrip.start_with?('//')}.join.scan(/"([^"]+)"/).flatten
raise 'source set' unless h.map{|x|x['template']}.sort==hs.sort && l.map{|x|x['category']}.sort==ls.sort
sourcecheck=c.map{|x|p=R7+'/'+x['sourcePath'];ok=sha(p)==x['sourceSha256']&&objs(j(p)).include?(x['sourceEntry']);raise 'catalog' unless ok;{id:x['id'],sourcePath:x['sourcePath'],shaMatchesR07:ok,sourcePresentR08:File.file?(R8+'/'+x['sourcePath']),reviewPresentR08:File.directory?(R8+'/'+x['reviewPath'])}}
ids=h.flat_map{|x|x['variants'].map{|v|v['id']}}+l.flat_map{|x|x['variants'].map{|v|v['id']}}+c.map{|x|x['id']}+age.flat_map{|x|x['variants'].map{|v|v['id']}};raise 'duplicate ids' unless ids.size==882&&ids.uniq.size==882
slots=h.flat_map{|x|x['variants']}.select{|v|v['headline'].scan(/\{([^}]+)\}/).flatten.uniq.sort!=(v['requiredSlots']||[]).sort};raise 'slots' unless slots.empty?
coverage=h.map{|x|{template:x['template'],canonical:x['variants'].size,context:c.count{|v|v['template']==x['template']},age:age.select{|v|v['template']==x['template']}.sum{|v|v['variants'].size},distinctCanonicalConditionalText:x['variants'].reject{|v|v['when'].nil?||v['when'].empty?}.map{|v|v['headline']}.uniq.size}};single=coverage.select{|x|x[:canonical]==1};raise 'single uncovered' unless single.all?{|x|x[:context]>0||x[:age]>0}
holds=j(R8+'/chronicle/R06_CONTEXT_FACTLINE_HOLDS.json');blocks=j(R8+'/chronicle/R05D_INSTALL_BLOCKS.json');out('COVERAGE.json',{history:coverage,ledger:l.map{|x|{category:x['category'],canonical:x['variants'].size,context:c.count{|v|v['category']==x['category']}}},catalogSources:sourcecheck,astra:ans.map{|x|{id:x['id'],status:x['status'],evidence:x['evidence'],r08Present:File.exist?(File.expand_path(x['evidence'],R8+'/content')),r07Present:File.exist?(File.expand_path(x['evidence'],R7+'/content'))}}})
oldsrc=j(R7+'/records/e-final-draft-audit/SOURCE_EVIDENCE.json');srccheck=oldsrc.map{|x|p=REPO+'/'+x['path'];{path:x['path'],sha256:sha(p),matchesPrior:sha(p)==x['sha256']}};raise 'source drift' unless srccheck.all?{|x|x[:matchesPrior]}
extra=%w[src/content/historyCopy.ko.ts src/ledger/ledger.types.ts src/engine/personsApi.ts src/engine/history.ts src/ui/chronicle/chronicleScreenModel.ts];extra.each{|p|srccheck<<{path:p,sha256:sha(REPO+'/'+p)}};out('SOURCE_PINS.json',srccheck.uniq{|x|x[:path]});out('INHERITANCE_CHECK.json',inheritance)
out('RESULT.json',{status:'AUTHORED_SCOPE_COVERED_CURRENT_EVIDENCE_PRESENT',sourceHead:`git -C #{REPO} rev-parse HEAD`.strip,inheritanceFiles:132,eventDrafts:200,astraAnswers:24,choices:e.sum{|x|x['choices'].size},commands:r.sum{|x|x['choices'].sum{|v|v['commands'].size}},blockedEvents:e.count{|x|x.dig('integration','mode')=='blocked_unsupported_effect'},allChoicesUnsupported:r.count{|x|x['choices'].all?{|v|v['commands'].empty?}},sidecarEnabled:r.count{|x|x['enabledInEngine']},historyTypes:hs.size,ledgerCategories:ls.size,canonicalVariants:h.sum{|x|x['variants'].size}+l.sum{|x|x['variants'].size},separateContext:c.size,contextHistory:c.count{|x|x['template']},contextLedger:c.count{|x|x['category']},ageDrafts:age.sum{|x|x['variants'].size},uniqueIds:ids.uniq.size,singleCanonicalTypes:single.size,singleTypesWithSupplement:single.count{|x|x[:context]>0||x[:age]>0},factlineCompositionHolds:holds['holds'].size,canonicalSlotIssues:slots.size,missingTypeKeys:[],confirmedNewAuthoringGaps:[],fullCombinationCoverage:false,semanticReview:'prior independent reviews inherited with exact source/input equality; current keysets, slots, IDs and source linkage freshly checked',engineExecuted:false,installed:false})
puts File.read(OUT+'/RESULT.json')
