const fs=require('fs');const path=require('path');const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..');const record=path.join(root,'records/metadata-lineage2.json');
const keys=['hair','skin','eyes','faceShape','nose','jaw','brow'];
const people={};
function person(id,sex,traits,clothing,parents,mix){const p={identity:id,lineage:'L2',generation:id[3]==='1'?1:id[3]==='3'?3:2,sex,traits:Object.fromEntries(keys.map((k,i)=>[k,traits[i]])),clothing,fatherIdentity:parents?.[0]??null,motherIdentity:parents?.[1]??null,inheritance:{}};if(parents)keys.forEach((k,i)=>{const from=parents[mix[i]];p.traits[k]=people[from].traits[k];p.inheritance[k]={from,value:p.traits[k]};});people[id]=p;}
person('L2_101','male',['copper auburn','light warm peach','small hazel eyes with relaxed narrow lids','broad round cheeks','broad short nose with rounded tip','soft broad rounded jaw','low straight brow'],'muted indigo wool gown, modest fur collar and soft cap');
person('L2_102','female',['chestnut auburn','light rosy beige','gray-green eyes with alert almond lids','long oval face','narrow straight nose','angular tapering jaw','high subtly arched brow'],'muted wine wool gown and linen veil');
person('L2_2S1','female',['dark brown','medium warm olive','deep brown wide-set eyes','short heart-shaped face','short gently upturned nose','small pointed chin','thick gently arched brows'],'muted ochre wool gown with plain cream linen coif');
person('L2_2S2','male',['dark ash blond','light neutral beige','clear blue deep-set eyes','long rectangular face','long mildly convex nose','square firm jaw','heavy straight brows'],'muted moss green wool tunic and simple brown shoulder mantle');
const mixes=[[0,1,1,0,0,1,1],[1,0,0,1,1,0,0],[0,0,1,1,0,0,1],[1,1,0,0,1,1,0]];
['male','male','female','female'].forEach((s,i)=>person('L2_20'+(i+1),s,[],['dusty teal merchant wool tunic','clay brown merchant wool gown','muted sage wool dress with linen neckline','dusty russet wool dress with linen coif'][i],['L2_101','L2_102'],mixes[i]));
['male','female','male','female'].forEach((s,i)=>person('L2_30'+(i+1),s,[],['dusty plum wool tunic','ochre gray wool dress','slate blue wool tunic','muted terracotta wool dress'][i],i<2?['L2_201','L2_2S1']:['L2_2S2','L2_203'],mixes[i]));
const base='Use case: historical-scene. Single square game portrait, one person only, head and upper torso, 256x256 final target. Match supplied project portrait painterly naturalistic gouache/oil style, muted solid taupe background, soft upper-left light, subtle brushwork. Southern England 1300-1450 merchant clothing, no modern elements, no text, no frame, no coat of arms or badge, no held props. Class conveyed only by clothes, never skin or facial character. '; 
function job(id,stage){const p=people[id],age={baby:1,child:8,young:22,mature:45,old:70}[stage];let refs=[],prompt=base;
if(id==='L2_101'||id==='L2_102'){refs=['references/'+(id==='L2_101'?'I043':'I047')+'_mature.png'];prompt+='Reference image 1 is the exact existing founder identity. Preserve that specific person, facial geometry, distinctive nose, cheeks, eyes and hairline. '+(stage==='old'?'Age this same person to 70, natural wrinkles, graying hair; no identity replacement. ':'Paint this same person age 45, preserve age and identity. ');}
else if(p.fatherIdentity){refs=['assets/lineage2/'+p.fatherIdentity+'_'+(p.fatherIdentity.includes('10')?'mature':'young')+'.png','assets/lineage2/'+p.motherIdentity+'_'+(p.motherIdentity.includes('10')?'mature':'young')+'.png'];if(stage==='young')prompt+='Reference 1 is the actual father and reference 2 the actual mother. Create their NEW '+p.sex+' child, not a clone of either parent. ';else{refs.push('assets/lineage2/'+id+'_young.png');prompt+='Reference 1 actual father; reference 2 actual mother; reference 3 THIS SAME PERSON as a young adult. Transform reference 3 to the requested age preserving identity and family resemblance. ';}prompt+='Exact artistic trait inheritance contract: '+keys.map(k=>k+' from '+p.inheritance[k].from+': '+p.traits[k]).join('; ')+'. ';}
else{refs=['references/I043_mature.png','references/I047_mature.png'];prompt+='References are STYLE ONLY. Create an original unrelated external spouse with a clearly different NEW face, not either reference person. ';}
prompt+='Subject '+id+', '+p.sex+', age '+age+'. Traits: '+keys.map(k=>k+': '+p.traits[k]).join('; ')+'. Clothing: '+(stage==='baby'?'age appropriate plain linen swaddle in '+(id.endsWith('1')?'dusty teal':id.endsWith('2')?'warm cream':id.endsWith('3')?'soft sage':'faded rose')+', full face unobscured':p.clothing)+'. '+(stage==='baby'?'Clearly a one-year-old baby, very short fine infant hair, soft rounded baby face, natural infant proportions, no adult facial hair or adult costume. ':stage==='child'?'Clearly an eight-year-old child, natural child proportions and soft age-appropriate features, no facial hair or adult face. ':'')+'Keep eyes visible, distinct individual face; siblings differ through the specified trait mix. No family-wide clothing color code.';
return {...p,id:id+'_'+stage,file:'assets/lineage2/'+id+'_'+stage+'.png',stage,age,width:256,height:256,prompt,referenceImages:refs};}
const jobs=[];['L2_101','L2_102'].forEach(id=>['mature','old'].forEach(s=>jobs.push(job(id,s))));['L2_2S1','L2_2S2'].forEach(id=>jobs.push(job(id,'young')));['L2_201','L2_202','L2_203','L2_204'].forEach(id=>['young','baby','child','mature'].forEach(s=>jobs.push(job(id,s))));['L2_301','L2_302','L2_303','L2_304'].forEach(id=>['young','baby','child'].forEach(s=>jobs.push(job(id,s))));
async function main(){if(process.argv[2]==='init'){fs.writeFileSync(path.join(root,'records/traits-lineage2.json'),JSON.stringify({status:'contract recorded before generation',interpretation:'Artistic explicit parent-trait assignment, not biological determinism',people,jobs},null,2));if(!fs.existsSync(record))fs.writeFileSync(record,'[]');console.log(JSON.stringify(jobs));}else if(process.argv[2]==='save'){const {id,source}=JSON.parse(Buffer.from(process.argv[3],'base64').toString());const j=jobs.find(x=>x.id===id);const raw='raw/lineage2/'+id+'.png';fs.copyFileSync(source,path.join(root,raw));const m=await sharp(source).metadata();await sharp(source).resize(256,256,{fit:'contain',background:'#777166'}).png().toFile(path.join(root,j.file));const rows=JSON.parse(fs.readFileSync(record));rows.push({...j,generationRecords:[{prompt:j.prompt,rawFile:raw,referenceImages:j.referenceImages,tool:'image_gen.imagegen',model:null,seed:null,originalWidth:m.width,originalHeight:m.height}],processing:'Sharp aspect-preserving contain resize to 256 square; no face painting or geometric warping',qa:{status:'pending visual review',limitations:'Fine eye colors and infant nose/jaw inheritance may be visually ambiguous at 256px.'}});fs.writeFileSync(record,JSON.stringify(rows,null,2));console.log(j.file);} }
main().catch(e=>{console.error(e);process.exitCode=1;});
