const fs=require('fs'),path=require('path');const {createCanvas,loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');const root=path.resolve(__dirname,'..'),exp=JSON.parse(fs.readFileSync(root+'/records/expected-assets.json'));const cache=new Map();async function im(f){if(!cache.has(f))cache.set(f,await loadImage(root+'/'+f));return cache.get(f);}function panel(g,image,x,y,w,h,p){const xs=[0,p,image.width-p,image.width],ys=[0,p,image.height-p,image.height],dx=[x,x+p,x+w-p,x+w],dy=[y,y+p,y+h-p,y+h];for(let j=0;j<3;j++)for(let i=0;i<3;i++)g.drawImage(image,xs[i],ys[j],xs[i+1]-xs[i],ys[j+1]-ys[j],dx[i],dy[j],dx[i+1]-dx[i],dy[j+1]-dy[j]);}
(async()=>{const evt=await im('references/frame_objective_normal.png'),mod=await im('references/frame_modal.png'),page=await im('references/frame_chronicle_page.png'),layout=[];
for(const ch of [3,4,5]){const c=createCanvas(1488,ch===5?2120:1660),g=c.getContext('2d');g.fillStyle='#a59c88';g.fillRect(0,0,c.width,c.height);const events=exp.filter(a=>a.chapter===ch&&a.id.includes('_event_')),decisions=exp.filter(a=>a.chapter===ch&&a.id.includes('_decision_')),chronicles=exp.filter(a=>a.chapter===ch&&a.id.includes('_chronicle_'));
for(let i=0;i<events.length;i++){let x=32+i%4*360,y=32+Math.floor(i/4)*240;panel(g,evt,x,y,344,220,12);g.drawImage(await im(events[i].file),x+12,y+16,320,180);}
for(let i=0;i<decisions.length;i++){let x=32+i*360,y=548;panel(g,mod,x,y,344,300,18);g.drawImage(await im(decisions[i].file),x+12,y+20,320,240);}
for(let i=0;i<chronicles.length;i++){let x=32+i*240,y=898;panel(g,page,x,y,224,256,16);g.drawImage(await im(chronicles[i].file),x+12,y+28,200,200);}
if(ch!==5){const end=exp.find(a=>a.id===`ch${ch}_ending`);g.drawImage(await im(end.file),384,1220,720,405);}else{for(let i=0;i<3;i++){const end=exp.find(a=>a.id===`ch${i+3}_ending`);g.drawImage(await im(end.file),32+i*488,1220,464,261);}g.drawImage(await im(exp.find(a=>a.id==='ch5_campaign_ending').file),264,1532,960,540);}
const file=`proofs/0${ch-2}-chapter${ch}.png`;fs.writeFileSync(root+'/'+file,c.toBuffer('image/png'));layout.push({chapter:ch,file,size:[c.width,c.height],captions:'none',events:{order:events.map(a=>a.id),imageDisplay:[320,180],layout:'4x2'},decisions:{order:decisions.map(a=>a.id),imageDisplay:[320,240],layout:'4x1'},chronicles:{order:chronicles.map(a=>a.id),imageDisplay:[200,200],layout:'6x1'},endings:ch===5?['ch3_ending','ch4_ending','ch5_ending','ch5_campaign_ending']:[`ch${ch}_ending`]});}
fs.writeFileSync(root+'/records/proof-layout.json',JSON.stringify(layout,null,2));console.log('3 uncaptioned chapter proof atlases rendered');})();
