const fs=require('fs');
const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const base=require('path').resolve(__dirname,'..');
async function bounds(input){ const {data,info}=await sharp(input).ensureAlpha().raw().toBuffer({resolveWithObject:true});let l=info.width,t=info.height,r=-1,b=-1;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++)if(data[(y*info.width+x)*4+3]>3){l=Math.min(l,x);t=Math.min(t,y);r=Math.max(r,x);b=Math.max(b,y);}return {left:l,top:t,width:r-l+1,height:b-t+1}; }
(async()=>{
const items=['effects-work.json','effects-more.json','effects-construction-work.json'].flatMap(f=>JSON.parse(fs.readFileSync(__dirname+'/'+f)));
const records=[];
for(const a of items){const construction=a.id.startsWith('roof_frame');const family=construction?'construction':'fx';const rawFile='sources/effects/'+a.id+'-raw.png';fs.copyFileSync(a.raw,base+'/'+rawFile);const file='assets/'+family+'/'+a.id+'-v1.png';const meta=await sharp(a.raw).metadata();let parts=[];let sizes=[];
if(a.frames){for(let i=0;i<4;i++){const left=Math.round(meta.width*i/4),right=Math.round(meta.width*(i+1)/4);const part=await sharp(a.raw).extract({left,top:0,width:right-left,height:meta.height}).png().toBuffer();const box=await bounds(part);parts.push(await sharp(part).extract(box).png().toBuffer());sizes.push(box);}const fw=a.w/4;const maxW=Math.max(...sizes.map(s=>s.width)),maxH=Math.max(...sizes.map(s=>s.height));const scale=Math.min((fw-10)/maxW,(a.h-10)/maxH);const layers=[];for(let i=0;i<4;i++){const w=Math.max(1,Math.round(sizes[i].width*scale)),h=Math.max(1,Math.round(sizes[i].height*scale));layers.push({input:await sharp(parts[i]).resize(w,h).toBuffer(),left:i*fw+Math.round((fw-w)/2),top:a.h-4-h});}await sharp({create:{width:a.w,height:a.h,channels:4,background:'#0000'}}).composite(layers).png().toFile(base+'/'+file);
}else{const box=await bounds(a.raw);const resized=await sharp(a.raw).extract(box).resize(a.w-12,a.h-12,{fit:'inside'}).toBuffer();const m=await sharp(resized).metadata();await sharp({create:{width:a.w,height:a.h,channels:4,background:'#0000'}}).composite([{input:resized,left:Math.round((a.w-m.width)/2),top:a.h-6-m.height}]).png().toFile(base+'/'+file);}
const {data,info}=await sharp(base+'/'+file).raw().toBuffer({resolveWithObject:true});let zero=0,semi=0,edge=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const v=data[(y*info.width+x)*4+3];if(v===0)zero++;if(v>0&&v<255)semi++;if((y===0||y===info.height-1||x===0||x===info.width-1||a.frames&&(x%(a.w/4)===0||x%(a.w/4)===a.w/4-1))&&v>0)edge++;}
records.push({id:family+'/'+a.id+'-v1',file,width:a.w,height:a.h,role:construction?'object':'decal',pivot:{x:a.frames?a.w/8:a.w/2,y:a.h-(a.frames?4:6)},frameSize:a.frames?{width:a.w/4,height:a.h,count:4}:null,generationRecords:[{prompt:a.prompt,references:a.references||[],rawFile,originalWidth:meta.width,originalHeight:meta.height,tool:'builtin imagegen',modelVersion:'not supplied',seed:'not supplied'}],processing:a.frames?'Split source into four equal cells; alpha bounds threshold3; common scale across frames; single resize from source; bottom-center registration; transparent RGBA composite.':'Alpha bounds threshold3; aspect-preserving single resize from source; lower-center transparent canvas. Dimensions chosen because construction brief has no numeric canvas size.',qa:{status:'candidate',zeroAlphaPixels:zero,partialAlphaPixels:semi,nontransparentBoundaryPixels:edge,representativeScale:0.3,runtimeIntegration:false,animation:a.frames?'Four distinct drawn phases; frame4-to1 aesthetic continuity requires runtime timing validation.':null}});
}
fs.writeFileSync(__dirname+'/effects.json',JSON.stringify(records,null,2));
const layers=[];for(let i=0;i<records.length;i++){const r=records[i];layers.push({input:await sharp(base+'/'+r.file).resize(Math.round(r.width*.3),Math.round(r.height*.3)).toBuffer(),left:20+(i%3)*130,top:20+Math.floor(i/3)*100});}await sharp({create:{width:410,height:320,channels:4,background:'#69744e'}}).composite(layers).png().toFile(__dirname+'/effects-all-03.png');
console.log(records.map(r=>[r.id,r.width,r.height,r.qa.nontransparentBoundaryPixels]));
})();
