const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {createCanvas,loadImage}=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const {PNG}=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/pngjs');
const work=__dirname,root='/tmp/astra-wave39-candidates-20260930/assets';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function bbox(p,x0=0,y0=0,w=p.width,h=p.height){let l=x0+w,t=y0+h,r=-1,b=-1;for(let y=y0;y<y0+h;y++)for(let x=x0;x<x0+w;x++){if(p.data[(y*p.width+x)*4+3]>8){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}}return [l,t,r-l+1,b-t+1]}
(async()=>{let out=[];for(const s of JSON.parse(fs.readFileSync(path.join(work,'native.json')))){
let p=PNG.sync.read(fs.readFileSync(s.sourcePath)),im=await loadImage(s.sourcePath),c=createCanvas(s.width,s.height),ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';let frames=s.width===384?6:1;let crops=[];
if(frames===6){for(let k=0;k<6;k++){let x=Math.floor(k%3*p.width/3),y=Math.floor(Math.floor(k/3)*p.height/2),w=Math.floor((k%3+1)*p.width/3)-x,h=Math.floor((Math.floor(k/3)+1)*p.height/2)-y; crops.push([x,y,w,h]);ctx.drawImage(im,x,y,w,h,k*64+(s.folder==='debris'?14:2),s.folder==='debris'?5:2,s.folder==='debris'?36:60,s.folder==='debris'?22:28)}}else {let box=bbox(p);crops.push(box);let tw=s.width-4,th=s.height-4;if(s.id==='roof_leaves-v1'){tw=28;th=18}if(s.id.startsWith('snowflake')){tw=th=s.width===8?2:s.width===12?3:5}let scale=Math.min(tw/box[2],th/box[3]),w=box[2]*scale,h=box[3]*scale;ctx.drawImage(im,...box,(s.width-w)/2,(s.height-h)/2,w,h)}
const outputPath=path.join(root,s.folder,s.id+'.png');fs.writeFileSync(outputPath,c.toBuffer('image/png'));let final=PNG.sync.read(fs.readFileSync(outputPath)),alphaPixels=0;for(let j=3;j<final.data.length;j+=4)if(final.data[j])alphaPixels++;
let moving=frames===6||s.id.startsWith('snowflake');let refs=(s.references||[]).map(p=>({path:p,sha256:sha(p)}));out.push({...s,assetId:s.folder+'/'+s.id,outputPath,sourceSha256:sha(s.sourcePath),sha256:sha(outputPath),tool:'image_gen.imagegen',model:'not displayed',generatedDate:'2026-09-30',references:refs,width:s.width,height:s.height,frames,frameWidth:frames===6?64:s.width,frameHeight:s.height,pivot:[frames===6?32:s.width/2,s.height/2],recommendedAlpha:s.folder==='snow'?0.7:0.85,recommendedSpeed:moving?(s.id.startsWith('snowflake')?12:24):0,speedUnit:'world pixels/second; tile128x64 at zoom1',windTilt:moving?20:0,windTiltUnit:'degrees from vertical; renderer controls sign',lifetime:moving?(s.id.startsWith('snowflake')?4:1.2):0,lifetimeUnit:'seconds; 0 means static persistent decal',status:'candidate',candidateCount:s.priorAttempts?2:1,selectionReason:'Distinct silhouette and transparent particle/decal coverage at intended scale.',manualEdits:'Native generated RGBA alpha retained; alpha bounds crop for static assets, aspect-preserving resize centered; animation3x2 equal-cell crop and horizontal six-frame packing; leaf groups36x22 centered in64x32 and snow groups60x28; roof leaf cluster28x18 centered; snow grain alone resized to2/3/5px. No procedural artwork.',crops,alphaPixels,alphaCoverage:alphaPixels/(s.width*s.height)});
}fs.writeFileSync(path.join(work,'manifest.json'),JSON.stringify(out,null,2));const board=createCanvas(1000,Math.ceil(out.length/2)*130),bc=board.getContext('2d');bc.fillStyle='#7b8066';bc.fillRect(0,0,board.width,board.height);bc.font='15px sans-serif';for(let i=0;i<out.length;i++){let x=i%2*500,y=Math.floor(i/2)*130;bc.fillStyle='#fff';bc.fillText(out[i].id,x+8,y+20);let im=await loadImage(out[i].outputPath);bc.drawImage(im,x+8,y+35);if(out[i].width<128){bc.imageSmoothingEnabled=false;bc.drawImage(im,x+180,y+35,out[i].width*3,out[i].height*3);bc.imageSmoothingEnabled=true}}fs.writeFileSync(path.join(work,'contact.png'),board.toBuffer('image/png'));console.log(JSON.stringify({count:out.length,files:out.map(s=>({id:s.id,alpha:s.alphaCoverage}))}));})();
