export const BALANCE = {
  TICKS_PER_SECOND: 20,
  CARTER_SPEED: 0.08,
  CARTER_CAPACITY: 8,
  DISTRIBUTOR_SPEED: 0.06,
  DISTRIBUTOR_CAPACITY: 12,
  DISTRIBUTOR_INTERVAL: 120,
  DISTRIBUTOR_RANGE: 40,
  BREAD_HUNGER_WINDOW: 200,
  DEVOLUTION_GRACE: 400,
  GROWTH_INTERVAL: 50,
  STARVATION_WINDOW: 300,
  WORKERS_PER_RESIDENT: 0.5,
  STARTING_TIMBER: 205,
} as const;

export const BALANCE_CONFIG = BALANCE;
