export const BALANCE = {
  TICKS_PER_SECOND: 20,
  CARTER_SPEED: 0.14,
  CARTER_CAPACITY: 8,
  DISTRIBUTOR_SPEED: 0.11,
  DISTRIBUTOR_CAPACITY: 12,
  DISTRIBUTOR_INTERVAL: 120,
  DISTRIBUTOR_RANGE: 40,
  BREAD_HUNGER_WINDOW: 200,
  DEVOLUTION_GRACE: 400,
  GROWTH_INTERVAL: 150,
  FOOD_PRODUCTION_MARGIN_FACTOR: 1.05,
  STARVATION_WINDOW: 300,
  WORKERS_PER_RESIDENT: 0.5,
  CONSTRUCTION_MIN_WORKER_SHARE: 0.2,
  STARTING_TIMBER: 120,
  /** Provisional (B2): one calendar year per minute at 1x; four 300-tick seasons. Tune after player timing. */
  TICKS_PER_YEAR: 1200,
} as const;

export const BALANCE_CONFIG = BALANCE;
