const fs=require('fs'),path=require('path'),crypto=require('crypto'),sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..');
const margins={treaty_frame:[128,160,128,112],clause_row:[48,18,48,18],clause_row_changed:[48,18,48,18],clause_row_rejected:[48,18,48,18],reason_chip_plus:[44,14,24,14],reason_chip_minus:[44,14,24,14],ledger_book:[72,72,72,72],litigation_track:[72,20,72,20],receipt_frame:[40,190,40,110]};
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
async function main(){const files=walk(path.join(root,'assets')).filter(f=>f.endsWith('.png')).sort(),rows=[],layers=[];let html='<meta charset="utf-8"><title>Wave35 후보 갤러리</title><style>body{background:#d8c9a7;color:#392e22;font:16px sans-serif}section{display:inline-block;vertical-align:top;width:280px;margin:12px}img{max-width:270px;max-height:180px;object-fit:contain}small{display:block}</style><h1>Wave35 영주 모드 후보</h1><p>게임 미설치 · 이미지를 누르면 원본 PNG · 프레임 중앙선/장부 접힘은 별도 고정폭 레이어</p>';
for(let i=0;i<files.length;i++){const f=files[i],rel=path.relative(root,f),id=path.basename(f,'.png'),m=await sharp(f).metadata(),data=await sharp(f).ensureAlpha().raw().toBuffer();let transparent=0,badRGB=0,partial=0;
for(let p=0;p<data.length;p+=4){if(data[p+3]===0){transparent++;if(data[p]||data[p+1]||data[p+2])badRGB++;}else if(data[p+3]<255)partial++;}
rows.push({id,file:rel,width:m.width,height:m.height,status:'candidate',nine_slice_ltrb:margins[id]?.join('|')||'',usage:id==='treaty_divider'?'협상 중앙 고정폭 오버레이':id==='ledger_spine'?'장부 중앙 고정폭 오버레이':rel.split('/')[1],transparent_pixels:transparent,partial_alpha_pixels:partial,hidden_rgb_pixels:badRGB,sha256:crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')});
const thumb=await sharp(f).resize(240,146,{fit:'inside'}).png().toBuffer(),tm=await sharp(thumb).metadata();layers.push({input:thumb,left:(i%5)*256+8,top:Math.floor(i/5)*180+8});
const svg='<svg width="252" height="24"><text x="3" y="17" font-family="sans-serif" font-size="11" fill="#312518">'+id+'</text></svg>';layers.push({input:Buffer.from(svg),left:(i%5)*256,top:Math.floor(i/5)*180+153});
html+='<section><a href="'+rel+'"><img src="'+rel+'"></a><small>'+id+' · '+m.width+'×'+m.height+'</small></section>';}
fs.writeFileSync(path.join(root,'index.html'),html);const keys=Object.keys(rows[0]);fs.writeFileSync(path.join(root,'assets.csv'),'\uFEFF'+[keys.join(','),...rows.map(r=>keys.map(k=>'"'+String(r[k]).replaceAll('"','""')+'"').join(','))].join('\n')+'\n');
fs.writeFileSync(path.join(root,'qa/pixel-audit.json'),JSON.stringify(rows,null,2));
fs.writeFileSync(path.join(root,'records/nine-slice.json'),JSON.stringify({order:'left,top,right,bottom',margins,assembly:{treaty_frame:'treaty_divider centered, fixed16px width; stretch only its vertical middle',ledger_book:'ledger_spine centered, fixed24px width',receipt_frame:'portrait aperture top protected by190px; bottom separator protected by110px; minimumHeight301px'}},null,2));
await sharp({create:{width:1280,height:Math.ceil(files.length/5)*180,channels:3,background:'#dbcfb1'}}).composite(layers).jpeg({quality:90}).toFile(path.join(root,'qa/assets-contact.jpg'));console.log(JSON.stringify({count:files.length,alphaChannels:rows.length,hiddenRGB:rows.reduce((s,r)=>s+r.hidden_rgb_pixels,0)}));}
main().catch(e=>{console.error(e);process.exit(1)});
