// LM-R3 phase 2a: the words of the lord slice's opening page and its end — "이 도시가 내 결정의 결과인가" (docs/design/
// lord-slice.md LS-1, LS-5; game principles A4·A5: the page lays the evidence side by side, the player answers). Words
// follow docs/design/glossary.md; the ledger's own sentences are quoted as the ledger writes them.

export const SLICE_COPY = {
  start: {
    kicker: "영주의 스무 해 · 첫 장",
    title: (house: string) => `${house} 가문이 장원을 맡습니다`,
    house: (house: string) => `당신은 ${house} 가문의 영주입니다.`,
    armsLabel: (house: string) => `${house} 가문의 문장`,
    home: (name: string, value: string) => `${name} — 한 해 수입 ${value}`,
    town: "지금의 마을",
    townLine: (population: number, houses: number, treasury: string) => `사람 ${population}명 · 집 ${houses}채 · 금고 ${treasury}`,
    neighbours: "이웃 영지",
    neighbour: (name: string, manors: string, value: string) => `${name} — ${manors} · 한 해 ${value}`,
    neighbourDebt: (debt: string) => `빚 ${debt}`,
    neighbourLord: (age: number) => `영주 ${age}세`,
    daughtersOnly: "아들 없이 딸만 있음",
    /** The first two neighbours' lords lead the neighbour factions (ES-8). */
    asFaction: "이웃 영주 세력으로도 만납니다",
    factions: "만나게 될 세력",
    faction: (name: string, kind: string | null, band: string) => kind === null ? `${name} — 지금 ${band}` : `${name}(${kind}) — 지금 ${band}`,
    slice: "이 판은",
    years: (years: number, from: number, to: number) => `${years}년(${from}~${to}년) 동안 다스립니다.`,
    second: (years: number) => `두 번째 영지를 쥐면, 그로부터 ${years}년 뒤에 끝납니다.`,
    goal: (min: number, max: number) => `${min}~${max}년이 지나면 묻습니다: 이 도시가 내 결정의 결과인가.`,
    begin: "다스리기 시작",
  },
  end: {
    kicker: "영주의 스무 해 · 마지막 장",
    title: "이 도시가 내 결정의 결과인가",
    why: "왜 끝났나",
    /** The user's ruling (2026-10-09): the last year at the top, in its year card's place. */
    lastYear: (year: number) => `마지막 해 ${year}`,
    lastHouse: "가문의 일",
    lastDecisions: "영주가 정한 일",
    lastChanged: "결정 뒤에 일어난 일",
    lastNoDecision: "이 해에는 영주가 내린 큰 결정이 없었습니다.",
    withOutcome: (line: string, outcome: string) => `${line} (${outcome})`,
    lastMore: (count: number) => `그 밖에 ${count}가지 — 그 해의 카드에 모두 있습니다`,
    yearCard: (year: number) => `${year}년 카드 보기`,
    seasonCard: "이 철의 장부 보기",
    years: (years: number, date: string) => `다스린 지 ${years}년이 되었습니다 — ${date}.`,
    second: (years: number, secondYear: number, date: string) => `${secondYear}년에 두 번째 영지를 쥐고 ${years}년이 지났습니다 — ${date}.`,
    thenNow: "그때와 지금",
    then: "처음",
    now: (date: string) => `지금(${date})`,
    /** The chronicle's first season line (the start's houses and treasury are not kept). */
    thenPopulation: (date: string, population: number) => `${date} 장부: 사람 ${population}명`,
    nowPopulation: (population: number, houses: number, treasury: string) => `사람 ${population}명 · 집 ${houses}채 · 금고 ${treasury}`,
    estates: (names: string) => `쥔 영지: ${names}`,
    list: (names: readonly string[]) => names.join(" · "),
    secondYear: (year: number) => `두 번째 영지를 쥔 해: ${year}년`,
    projects: (all: number, byLord: number) => `마을의 사업 ${all}건 — 그 가운데 영주의 결정이 움직인 것 ${byLord}건`,
    promises: (kept: number, broken: number, open: number) => `영주의 약속: 지킴 ${kept} · 어김 ${broken} · 열림 ${open}`,
    noPromises: "영주가 한 약속은 없었습니다.",
    marriage: (stage: string) => `혼인: ${stage}`,
    noMarriage: "혼인은 맺어지지 않았습니다.",
    shaped: "도시를 만든 결정들",
    shapedLead: "뒤따른 일이 많은 결정부터. 청지기의 처리와 답하지 않은 일은 그렇게 적혀 있습니다.",
    followed: (count: number) => `뒤따른 일 ${count}건`,
    noShaped: "결정 뒤에 따라온 일이 기록되지 않았습니다.",
    toRecord: "연대기에서 이 결정 보기",
    remembers: "누가 기억하나",
    remembersLine: (faction: string, feels: string, because: string) => `${faction}: ${feels} — ${because}`,
    noRemembers: "결정을 기억하는 세력이 없습니다.",
    years20: "해마다 한 줄",
    yearLine: (year: number, parts: readonly string[]) => `${year}년 — ${parts.join(" · ")}`,
    yearHouse: (line: string) => `가문: ${line}`,
    /** The year's decision lines in the ledger, by who decided (DC-D14). */
    yearDecisions: (lord: number, steward: number, lapsed: number) =>
      [`영주의 결정 ${lord}건`, ...(steward === 0 ? [] : [`청지기의 처리 ${steward}건`]), ...(lapsed === 0 ? [] : [`답하지 않은 일 ${lapsed}건`])].join(", "),
    yearFollowed: (count: number) => `뒤따른 일 ${count}건`,
    yearQuiet: "결정이 없던 해",
    yearPopulation: (population: number) => `연말 사람 ${population}명`,
    question: "판정은 내리지 않습니다. 위의 기록을 나란히 보고, 이 도시가 당신의 결정의 결과인지 답해 보세요.",
    chronicle: "연대기에서 보기",
    continue: "계속 다스리기",
    reopen: "영주의 스무 해 돌아보기",
  },
} as const;
