// UX-1 first-session tutorial copy (research E "첫 세션 대본 0~15분"; the five concepts: direct building, road links,
// prediction / refusal, production -> storage, zones). Card titles are one line (18 px), reasons at most two lines,
// the steward's lines 70-110 characters.

export const TUTORIAL_COPY = {
  stewardName: "청지기",
  cards: {
    greet: { title: "영지를 둘러보세요", why: "먼저 사람들이 살아갈 물과 길부터 챙깁니다.", cta: "시작하기" },
    well: { title: "집 가까이에 우물 설치", why: "우물은 반경 6칸 안의 집에 물을 댑니다. 밝게 표시된 집이 물을 받습니다.", cta: "우물 놓기", place: "표시한 자리에 우물 놓기" },
    wellDone: { title: "결과를 먼저 보고 놓기", why: "배치 전에 예측을 보고, 빨간 이유가 뜨면 그 이유를 먼저 보십시오. 잘못 놓았으면 되돌리기로 무를 수 있습니다.", cta: "계속" },
    road: { title: "길 한 칸 내기", why: "길은 사람과 물자의 통로입니다. 집과 일터는 길가에만 지을 수 있습니다.", cta: "길 놓기", place: "표시한 칸에 길 놓기" },
    house: { title: "새 길가에 집 짓기", why: "집은 목재 없이 짓습니다. 물과 빵이 닿으면 사람들이 들어와 인구가 늡니다.", cta: "집 놓기", place: "표시한 자리에 집 놓기" },
    arable: { title: "식량 기반: 경작지", why: "밀은 경작지 띠에서 자랍니다. 길가 빈 땅을 경작지로 칠하세요.", cta: "경작지 칠하기", place: "표시한 땅을 경작지로 칠하기" },
    arableLimits: { title: "칠할 수 없는 땅 알아보기", why: "붉은 곳에는 경작할 수 없습니다. 빗금 칸은 길이 닿지 않아 거둔 밀을 옮기지 못합니다.", cta: "알겠습니다" },
    foodChain: { title: "헛간과 방앗간 짓기", why: "헛간이 경작지를 갈고 거두고, 방앗간이 밀을 빵으로 만듭니다. 둘 다 길에 이어야 합니다.", ctaFarmstead: "헛간 놓기", ctaMill: "방앗간 놓기", placeFarmstead: "표시한 자리에 헛간 놓기", placeMill: "표시한 자리에 방앗간 놓기" },
    granary: { title: "새 곡창 짓기", why: "올해 먹을 것만으로는 부족합니다. 수확이 나쁜 해를 버티려면 곡식을 저장해야 합니다.", cta: "곡창 놓기", place: "표시한 자리에 곡창 놓기" },
    zoneUnlock: { title: "땅의 용도 정하기", why: "이제 건물 하나씩이 아니라 땅의 용도를 정할 수 있습니다.", cta: "구역 열기" },
    burgage: { title: "첫 필지 구역 칠하기", why: "필지 구역 안에서는 사람들이 스스로 집을 짓습니다. 길에 닿는 땅이 필지가 됩니다.", cta: "필지 칠하기", place: "표시한 땅을 필지로 칠하기" },
    burgageDone: { title: "사람들이 채우는 땅", why: "직접 둔 건물은 그대로 보호됩니다. 구역 안의 집은 사람들이 짓습니다.", cta: "알겠습니다" },
    wrapUp: { title: "다음: 시장과 예배당", why: "마을이 자라면 시장과 예배당을 갖추어 시장 도시로 키우십시오.", cta: "안내 마치기" },
  },
  advisor: {
    greet: "이곳을 시장 도시로 키우십시오. 먼저 사람들이 살아갈 물과 길부터 챙기지요. 목표 카드의 단추를 누르시면 됩니다.",
    well: "밝게 표시된 집이 물을 받습니다. 놓기 전에 예상 공급을 보시고, 표시한 자리에 우물을 두십시오.",
    wellDone: "좋습니다. 배치 전에 결과를 보고, 빨간 이유가 뜨면 그 이유를 먼저 보십시오. 잘못 두셨다면 되돌리기로 무르면 됩니다.",
    house: "집은 목재가 들지 않습니다. 물과 빵이 닿는 집에는 사람들이 들어와 살고, 그렇게 인구가 늘어납니다.",
    arable: "밀은 경작지 띠에서 자랍니다. 붉은 곳에는 경작할 수 없으니, 길가의 빈 땅을 골라 칠하십시오.",
    granary: "올해 먹을 것만 있으면 충분하지 않습니다. 수확이 나쁜 해에 대비해 곡식을 저장하십시오.",
    zoneUnlock: "이제 건물 하나씩이 아니라 땅의 용도를 정할 수도 있습니다. 아래 왼쪽의 구역 단추가 열렸습니다.",
    burgageDone: "이제 이 안의 성장은 사람들이 맡습니다. 직접 둔 건물은 그대로 보호됩니다. 길만 잘 이어 주십시오.",
    wrapUp: "안내는 여기까지입니다. 다음으로 시장과 예배당을 갖추어 마을을 시장 도시로 키우십시오.",
  },
  mapLabels: {
    well: "여기에 우물", house: "여기에 집", road: "여기에 길", arable: "이 땅을 경작지로", food_chain: "여기에 짓기",
    granary: "여기에 곡창", burgage: "이 땅을 필지로",
  } as Record<string, string>,
  advisorButton: "알겠습니다",
  help: "도움말",
  unlocked: (name: string) => `새로 열림: ${name}`,
  zoneBanner: "이제 땅의 용도를 정할 수 있습니다",
  locked: "잠김",
  lockedCategory: {
    trade: "식량 기반 목표에서 열립니다",
    storage: "곡창 목표에서 열립니다",
    public: "첫 안내를 마치면 열립니다",
    defense: "목책 단계에서 열립니다",
  },
  lockedTool: "첫 안내를 마치면 열립니다",
  lockedLayer: { zone: "첫 생산 뒤에 열립니다", direction: "첫 청원 뒤에 열립니다" },
  layers: { direct: "직접", zone: "구역", direction: "방향" },
  layerGroup: "조작 층위",
  progress: (current: number, target: number) => `${current}/${target}`,
  alreadyDone: "이미 갖춰짐",
  done: "완료",
  drawer: "목표 기록",
  drawerEmpty: "아직 마친 목표가 없습니다",
  cardsLabel: "목표 카드",
  lookHere: "위치 보기",
  paused: "일시정지 중 · Space",
  tutorialToggle: "튜토리얼",
  tutorialOn: "켬",
  tutorialOff: "끔",
  tutorialOffNote: "끄면 모든 건설과 구역이 바로 열립니다",
  wellSupply: (supplied: number, total: number) => `예상 공급 ${supplied}/${total}`,
  plotsExpected: (low: number, high: number) => `예상 ${low}~${high}필지`,
  modeLines: {
    campaign_market_town: "목표를 따라 마을을 시장 도시로 키웁니다. 처음이라면 이 모드로 시작하세요.",
    sandbox: "목표와 실패 없이 자유롭게 짓습니다.",
  },
  pickTool: "도구를 고르세요",
  generalCard: { title: (name: string) => name, cta: "조건 보기", arm: (name: string) => `${name} 놓기`, place: (name: string) => `표시한 자리에 ${name} 놓기` },
  buildingNames: { market: "시장", chapel: "예배당" },
  categories: { living: "생활", paths: "길", trade: "생업", storage: "저장·유통", public: "공공·신앙", defense: "방어" },
} as const;
