// Generated by scripts/build-identity.mjs; regenerate after model source edits.
// Local reproducibility identity, not an authentication signature.
export const BUILD_IDENTITY = {
  "format": 1,
  "sourceHash": "ef5f2dfdd1d29d6b307f0f463e43fce332270337045917accf71bf244caf8007",
  "rulesHash": "46703da6f64d12b00dcbe1912f595aba62069a80bae7134d32c138e9d845c52a",
  "contentHash": "7431a139e7d72f6eb5d07052aa8cafb0ff5c94bcbaa07ae46e1c90ec8f9fd60f"
} as const;
export const BUILD_SOURCES = [
  {
    "path": "battle.ts",
    "sha256": "1910ac80e7e61934eae4c5beec5bb160ec141e37a3f6a7a3605cc14da6f12931"
  },
  {
    "path": "battle.types.ts",
    "sha256": "ae1297c09305c981e92fe55cb6697a03f63e190217a12e0c49cbea4f8c92ebd9"
  },
  {
    "path": "contracts.ts",
    "sha256": "743f5b5df7748f8758c537025cf1c64673030c4bad9193cad344749ac57a56f3"
  },
  {
    "path": "contracts.types.ts",
    "sha256": "b85d8f12b4c024424024ab3931cb806eb7f67610b7851504d7df52f181076e4e"
  },
  {
    "path": "economy.ts",
    "sha256": "79096e05daacd8fbbcdca5445725b491d129b57c6e72ee1172642bc782bcb204"
  },
  {
    "path": "index.ts",
    "sha256": "6fb832c155b25a8eb4db52d14c9fc4801ecfbca7d79a3bdef25a25e8beba8a7b"
  },
  {
    "path": "pathfinding.ts",
    "sha256": "208e92edb059b0a13ee3d8d7b76fdd7896a3b5535de736e2180ed74fcce05162"
  },
  {
    "path": "random.ts",
    "sha256": "f47c97f0c7e9fd221a5167c7b04e383a157ae18e76e645465fc5ed05c69fc879"
  },
  {
    "path": "rules.ts",
    "sha256": "55acc4426c12548d236c8b170a5a73fe3019b448812f9cda8a1828ba87a4f085"
  },
  {
    "path": "terrain.ts",
    "sha256": "5242a4cb72f91200c62631b1899fb97095355dfaf2a0959b01281903ec2346c5"
  },
  {
    "path": "types.ts",
    "sha256": "15d44f156eaa6d3a334832ca854abfa1c40efd6108b42dbd16ebecd42d6356f0"
  }
] as const;
