// Alpha bounds of the finished-building sprites that are drawn fitted to their footprint (render fix R0-2,
// src/render/buildingSpriteFit.ts): the anchor sprites whose authored registration put a one-tile painting on its far
// tile (well, logging camp, storehouse, barn = granary) and the farmstead (painted in the storehouse frame). Bounds of
// alpha >= 128 in the meta's pixel units (the base image; variants share its frame).
//   tsx scripts/buildBuildingSpriteFit.ts
import { writeFileSync } from "node:fs";

import { BUILDING_VARIANT_POOLS } from "../src/render/buildingVariantManifest";
import { spriteMeta } from "../src/render/worldAssets";
import { readPng } from "./processBuildingSprite";

function alphaBounds(url: string, width: number, height: number) {
  const { dimensions, rgba } = readPng(`public/${url.replace(/^\//, "")}`);
  let left = dimensions.width, top = dimensions.height, right = -1, bottom = -1;
  for (let y = 0; y < dimensions.height; y += 1) for (let x = 0; x < dimensions.width; x += 1) {
    if (rgba[(y * dimensions.width + x) * 4 + 3]! < 128) continue;
    left = Math.min(left, x); right = Math.max(right, x); top = Math.min(top, y); bottom = Math.max(bottom, y);
  }
  const kx = width / dimensions.width, ky = height / dimensions.height;
  return { x: left * kx, y: top * ky, width: (right + 1 - left) * kx, height: (bottom + 1 - top) * ky };
}

const entries: Record<string, { url: string; width: number; height: number; alpha: ReturnType<typeof alphaBounds> }> = {};
for (const key of ["well", "logging_camp", "storehouse", "barn"]) {
  const meta = spriteMeta(key);
  if (meta === null) throw new Error(`no sprite meta for ${key}`);
  entries[key] = { url: meta.url, width: meta.width, height: meta.height, alpha: alphaBounds(meta.url, meta.width, meta.height) };
}
const farmstead = BUILDING_VARIANT_POOLS.find(pool => pool.kind === "farmstead")?.variants.find(variant => variant.id === "a");
if (farmstead === undefined || farmstead.url === null || !("width" in farmstead)) throw new Error("no farmstead a");
entries.farmstead = { url: farmstead.url, width: farmstead.width, height: farmstead.height, alpha: alphaBounds(farmstead.url, farmstead.width, farmstead.height) };
const round = (value: number) => Math.round(value * 100) / 100;
const body = Object.entries(entries).map(([key, entry]) => `  ${key}: { width: ${entry.width}, height: ${entry.height}, alpha: { x: ${round(entry.alpha.x)}, y: ${round(entry.alpha.y)}, width: ${round(entry.alpha.width)}, height: ${round(entry.alpha.height)} } }, // ${entry.url}`).join("\n");
writeFileSync("src/render/buildingSpriteFit.generated.ts", `// Generated by scripts/buildBuildingSpriteFit.ts — alpha (>= 128) bounds of the fitted building sprites, meta px.
export const BUILDING_SPRITE_ALPHA = {
${body}
} as const;
`);
console.log(Object.keys(entries).join(" "));
