// LM-E9b (spec docs/design/registry.md ER-13): the content canon v4 with its deltas (v4.1; scripts/registryCanon.ts) as the
// registry's data — the executable part of registry-v4.json (bindings, conditions, choices and their commands, frequency,
// recurrence, dedup) without its prose, and events-v4.json's words (title, body, each choice's label, ledger and
// chronicle lines). An entry the canon blocks for an unsupported filter (an authored context or a new effect the engine
// lacks, R5) keeps only its id, class and the filters' ids, so the bundle carries no spec that cannot run.
//   tsx scripts/buildRegistryV4.ts   (writes src/content/registry/v4Entries.generated.ts and v4Copy.generated.ts)
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { readCanon } from "./registryCanon";

const ROOT = resolve(import.meta.dirname, "..");
const V4 = resolve(ROOT, "docs/design/content-drafts-20261002/v4");
const HANGUL = /[가-힣]/;
// Prose and provenance the runtime does not read (the canon keeps them; the registry spec ER-13).
const DROP = new Set(["sourceConditions", "sourcePreconditions", "windowRationale", "authoredYears", "contentRef", "sourceRevision", "enabledInEngine",
  "sourceEffectIndex", "expectedEffectsOwner", "conditionBinding", "bindingStatus", "effectSupport", "capabilityRefs", "currentEnabledConsequentialChoices",
  "bindingRequirements", "automaticObservations", "rangeInputPolicy", "unsupportedSelectors"]);

function strip(value: unknown, key?: string): unknown {
  if (Array.isArray(value)) return value.map(item => strip(item));
  if (typeof value === "object" && value !== null) {
    const out: Record<string, unknown> = {};
    for (const [name, inner] of Object.entries(value)) {
      if (DROP.has(name)) continue;
      if (typeof inner === "string" && HANGUL.test(inner) && name !== "literal") continue;
      out[name] = strip(inner, name);
    }
    return out;
  }
  void key;
  return value;
}

interface CanonEntry { readonly id: string; readonly contentClass: string; readonly unsupportedFilters: readonly { readonly id: string }[] }
interface CanonEvent { readonly id: string; readonly title: string; readonly body: string; readonly sender?: { readonly faction?: string; readonly role?: string };
  readonly category?: string; readonly choices: readonly { readonly id: string; readonly label: string; readonly ledger?: string; readonly chronicle?: string; readonly tradeoff?: string }[] }

// v4 with its delta releases merged by id (v4.1: 011 replaced, 201–215 added — events and registry together).
const canon = readCanon<CanonEvent, CanonEntry>();
const registry = canon.registry;
const events = canon.events;

const live = registry.entries.filter(entry => entry.unsupportedFilters.length === 0).map(entry => strip(entry));
const blocked = registry.entries.filter(entry => entry.unsupportedFilters.length > 0)
  .map(entry => ({ id: entry.id, contentClass: entry.contentClass, blockedBy: entry.unsupportedFilters.map(filter => filter.id) }));
const readModel = strip(JSON.parse(readFileSync(resolve(V4, "READ_MODEL.json"), "utf8")).derived);

const header = (what: string) => `// Generated by scripts/buildRegistryV4.ts from docs/design/content-drafts-20261002/v4, v4.1, v4.2 and v4.1-senders (${what}). Do not edit by hand.\n`;
writeFileSync(resolve(ROOT, "src/content/registry/v4Entries.generated.ts"), `${header("registry-v4.json, READ_MODEL.json derived")}
/** ER-13: the entries the canon leaves runnable (their executable spec), in the canon's order. */
export const V4_LIVE_ENTRIES: unknown = ${JSON.stringify(live)};
/** ER-13: the entries the canon blocks for an unsupported filter, with the filters (R5). */
export const V4_BLOCKED_ENTRIES: readonly { readonly id: string; readonly contentClass: string; readonly blockedBy: readonly string[] }[] = ${JSON.stringify(blocked)};
/** ER-13: the canon's policy (budgets, the least choices). */
export const V4_POLICY: unknown = ${JSON.stringify(registry.policy)};
/** ER-14: READ_MODEL's derived values (parameters and expression). */
export const V4_DERIVED: unknown = ${JSON.stringify(readModel)};
`);

const copy = Object.fromEntries(events.map(event => [event.id, { title: event.title, body: event.body, sender: event.sender?.role ?? event.sender?.faction ?? "", senderFaction: event.sender?.faction ?? "",
  choices: Object.fromEntries(event.choices.map(choice => [choice.id, { label: choice.label, ...(choice.tradeoff === undefined ? {} : { tradeoff: choice.tradeoff }),
    ...(choice.ledger === undefined ? {} : { ledger: choice.ledger }), ...(choice.chronicle === undefined ? {} : { chronicle: choice.chronicle }) }])) }]));
writeFileSync(resolve(ROOT, "src/content/registry/v4Copy.generated.ts"), `${header("events-v4.json")}
export interface V4ChoiceCopy { readonly label: string; readonly tradeoff?: string; readonly ledger?: string; readonly chronicle?: string }
export interface V4EventCopy { readonly title: string; readonly body: string; readonly sender: string; readonly senderFaction: string; readonly choices: Readonly<Record<string, V4ChoiceCopy>> }
/** ER-13: each v4 event's words (the canon's events-v4.json). */
export const V4_COPY: Readonly<Record<string, V4EventCopy>> = ${JSON.stringify(copy)};
`);
// DEC-TRACE (the user's decision 2026-10-06): the v4.2 audit's 38 recommended holds, each with its reason (the data keeps
// why, so an event comes back on when a real effect exists).
const holds = JSON.parse(readFileSync(resolve(ROOT, "docs/design/content-drafts-20261002/v4.2/HOLD_RECOMMENDATIONS.json"), "utf8")) as { entries: { id: string; reason: string; effectClass: string }[] };
writeFileSync(resolve(ROOT, "src/content/registry/v4Holds.generated.ts"), `${header("v4.2/HOLD_RECOMMENDATIONS.json")}
/** DEC-TRACE: the events held off after the v4.2 audit — not drawn — with the audit's effect class and reason. */
export const V4_HELD_ENTRIES: readonly { readonly id: string; readonly effectClass: string; readonly reason: string }[] = ${JSON.stringify(holds.entries.map(entry => ({ id: entry.id, effectClass: entry.effectClass, reason: entry.reason })))};
`);
process.stdout.write(`${JSON.stringify({ live: live.length, blocked: blocked.length, events: events.length })}\n`);
