import { readFile, writeFile } from 'node:fs/promises';
const records = JSON.parse(await readFile('public/assets/phase16-landscape/manifest.json', 'utf8'));
const metadata = records.map(({ id, url, width, height, displayWidth, groundAnchor }) => ({ id, url, width, height, displayWidth, groundAnchor }));
await writeFile('src/render/townLandscapeManifest.generated.ts', '// Generated by scripts/generateTownLandscapeManifest.mjs.\nexport const townLandscapeManifest = ' + JSON.stringify(metadata, null, 2) + ' as const;\n');
