"""UI-9: install the Wave 12 guildhall body and active overlay
(confirmed in assets-inbox/INBOX_LEDGER.csv: wave12/candidates-20260926 body and
wave12/rework-20260926 active overlay, both confirmed 2026-09-26) into
public/assets/wave12/bld/. The engine has no guildhall building kind; this art is
used as a chapter-4 world prop (reorgWorldProps.ts) when guildOf(state) is not null.

Creates:
  public/assets/wave12/bld/guildhall-v1.png        (body, 352×300, pivot 107,291)
  public/assets/wave12/bld/guildhall-active-v1.png (active overlay, 352×300)
  src/render/wave12GuildhallManifest.generated.ts
  docs/provenance/assets.csv rows (replaces any earlier row for these runtime paths)
  docs/provenance/prompts/guildhall-wave12-body.txt
  docs/provenance/prompts/guildhall-wave12-active.txt

Run: python3 scripts/installWave12Guildhall.py
"""
import csv
import hashlib
import shutil
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INBOX = ROOT / "assets-inbox"
CANDIDATES = INBOX / "wave12" / "candidates-20260926"
REWORK = INBOX / "wave12" / "rework-20260926"
RUNTIME = ROOT / "public" / "assets" / "wave12" / "bld"
LEDGER = ROOT / "docs" / "provenance" / "assets.csv"
INBOX_LEDGER = INBOX / "INBOX_LEDGER.csv"
MANIFEST = ROOT / "src" / "render" / "wave12GuildhallManifest.generated.ts"
PROMPTS = ROOT / "docs" / "provenance" / "prompts"
INSTALLED_BY = "UI-9"

BODY_INBOX_REL = "wave12/candidates-20260926/assets/bld/guildhall-v1.png"
ACTIVE_INBOX_REL = "wave12/rework-20260926/assets/active/guildhall-active-v1.png"
BODY_SHA = "ec19064c1cb777ef0e9edf11806b23d1e65e6fbf5fb66b16c452670a06de6c94"
ACTIVE_SHA = "5b0dcd48a3bfffd51c060191e9a441d46a2187a08c19a37d5da2b30198c0392e"

csv.field_size_limit(sys.maxsize)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def png_wh(data: bytes) -> tuple[int, int]:
    assert data[:8] == b"\x89PNG\r\n\x1a\n", "not PNG"
    w, h = struct.unpack(">II", data[16:24])
    return w, h


def inbox_rows() -> dict[str, dict]:
    return {row["file"]: row for row in csv.DictReader(open(INBOX_LEDGER, encoding="utf-8"))}


def candidate_records() -> dict[str, dict]:
    return {row["file"]: row for row in csv.DictReader(
        open(CANDIDATES / "records" / "assets.csv", encoding="utf-8-sig"))}


def rework_records() -> dict[str, dict]:
    return {row["file"]: row for row in csv.DictReader(
        open(REWORK / "records" / "assets.csv", encoding="utf-8-sig"))}


def main() -> None:
    inbox = inbox_rows()
    candidates = candidate_records()
    reworks = rework_records()

    # Verify inbox status and sha256 for both assets.
    body_inbox = inbox[BODY_INBOX_REL]
    assert body_inbox["status"] == "confirmed", f"body not confirmed: {body_inbox['status']}"
    assert body_inbox["sha256"] == BODY_SHA, "body sha256 mismatch"

    active_inbox = inbox[ACTIVE_INBOX_REL]
    assert active_inbox["status"] == "confirmed", f"active not confirmed: {active_inbox['status']}"
    assert active_inbox["sha256"] == ACTIVE_SHA, "active sha256 mismatch"

    body_src = CANDIDATES / "assets" / "bld" / "guildhall-v1.png"
    active_src = REWORK / "assets" / "active" / "guildhall-active-v1.png"
    assert sha(body_src) == BODY_SHA, "body file sha mismatch"
    assert sha(active_src) == ACTIVE_SHA, "active file sha mismatch"

    body_data = body_src.read_bytes()
    active_data = active_src.read_bytes()
    bw, bh = png_wh(body_data)
    aw, ah = png_wh(active_data)
    assert (bw, bh) == (352, 300), f"body size: {bw}x{bh}"
    assert (aw, ah) == (352, 300), f"active size: {aw}x{ah}"

    # Copy to runtime.
    RUNTIME.mkdir(parents=True, exist_ok=True)
    body_dst = RUNTIME / "guildhall-v1.png"
    active_dst = RUNTIME / "guildhall-active-v1.png"
    shutil.copyfile(body_src, body_dst)
    shutil.copyfile(active_src, active_dst)
    assert sha(body_dst) == BODY_SHA
    assert sha(active_dst) == ACTIVE_SHA

    # Candidate record for body (to extract prompt).
    body_rec = candidates.get("assets/bld/guildhall-v1.png") or candidates.get("guildhall")
    active_rec = reworks.get("assets/active/guildhall-active-v1.png") or reworks.get("guildhall_active")

    # Write prompts.
    PROMPTS.mkdir(parents=True, exist_ok=True)
    body_prompt_path = PROMPTS / "guildhall-wave12-body.txt"
    active_prompt_path = PROMPTS / "guildhall-wave12-active.txt"
    body_prompt = (body_rec.get("full_prompt") if body_rec else "") or "(no prompt recorded)"
    active_prompt = (active_rec.get("full_prompt") if active_rec else "") or "(no prompt recorded)"
    body_prompt_path.write_text(body_prompt.strip() + "\n")
    active_prompt_path.write_text(active_prompt.strip() + "\n")

    # Generate manifest.
    MANIFEST.write_text(
        "// Generated by scripts/installWave12Guildhall.py — Wave 12 guildhall world prop (UI-9):\n"
        "// body painting and active overlay; chapter 4 (chapterArt.ts CHAPTER_ART).\n"
        "// pivot: Astra's ground registration (SW front-left corner of the 3×2 building).\n"
        f"export const WAVE12_GUILDHALL_IMAGES = {{\n"
        f"  guildhall_body: {{\"url\": \"assets/wave12/bld/guildhall-v1.png\", "
        f"\"width\": {bw}, \"height\": {bh}, "
        f"\"pivot\": {{\"x\": 107, \"y\": 291}}}},\n"
        f"  guildhall_active: {{\"url\": \"assets/wave12/bld/guildhall-active-v1.png\", "
        f"\"width\": {aw}, \"height\": {ah}, "
        f"\"pivot\": {{\"x\": 107, \"y\": 291}}}},\n"
        f"}} as const;\n"
    )

    # Update docs/provenance/assets.csv.
    ledger_header = next(csv.reader(open(LEDGER, encoding="utf-8")))
    our_paths = {str(body_dst.relative_to(ROOT)), str(active_dst.relative_to(ROOT))}
    kept = [row for row in csv.DictReader(open(LEDGER, encoding="utf-8")) if row.get("runtimePath") not in our_paths]
    new_rows = [
        {
            "assetId": "wave12/guildhall", "version": "v1",
            "runtimePath": str(body_dst.relative_to(ROOT)),
            "runtimeSha256": BODY_SHA,
            "sourcePath": str(body_src.relative_to(ROOT)),
            "sourceSha256": BODY_SHA,
            "tool": "Astra (orca codex)", "model": "unknown",
            "generatedAt": "2026-09-26",
            "prompt": str(body_prompt_path.relative_to(ROOT)),
            "referenceInputs": "wave12/candidates-20260926",
            "seed": "", "candidates": "wave12/candidates-20260926",
            "manualEdits": "none", "artBible": "AB_2026-09-26_wave12",
            "historicalProfile": "S_England_1300_1450_v1",
            "owner": "project owner",
            "usedIn": "src/render/wave12GuildhallManifest.generated.ts (UI-9: guildhall world prop)",
            "status": "runtime",
            "notes": f"Wave 12 guildhall body (confirmed INBOX_LEDGER.csv) installed by {INSTALLED_BY} on 2026-09-29; byte-for-byte copy.",
        },
        {
            "assetId": "wave12/guildhall_active", "version": "v1",
            "runtimePath": str(active_dst.relative_to(ROOT)),
            "runtimeSha256": ACTIVE_SHA,
            "sourcePath": str(active_src.relative_to(ROOT)),
            "sourceSha256": ACTIVE_SHA,
            "tool": "Astra (orca codex)", "model": "unknown",
            "generatedAt": "2026-09-26",
            "prompt": str(active_prompt_path.relative_to(ROOT)),
            "referenceInputs": "wave12/rework-20260926",
            "seed": "", "candidates": "wave12/rework-20260926",
            "manualEdits": "none", "artBible": "AB_2026-09-26_wave12",
            "historicalProfile": "S_England_1300_1450_v1",
            "owner": "project owner",
            "usedIn": "src/render/wave12GuildhallManifest.generated.ts (UI-9: guildhall active overlay)",
            "status": "runtime",
            "notes": f"Wave 12 guildhall active overlay rework (confirmed INBOX_LEDGER.csv) installed by {INSTALLED_BY} on 2026-09-29; byte-for-byte copy.",
        },
    ]
    with open(LEDGER, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=ledger_header)
        writer.writeheader()
        writer.writerows(kept)
        writer.writerows(new_rows)

    print(f"Installed: {body_dst.relative_to(ROOT)}")
    print(f"Installed: {active_dst.relative_to(ROOT)}")
    print(f"Generated: {MANIFEST.relative_to(ROOT)}")
    print("Updated: docs/provenance/assets.csv")


if __name__ == "__main__":
    main()
