// PERSON-0 (spec docs/design/persons.md PS-5): builds `src/content/portraitPool.ts` from the portrait pool CSVs
// (pilot P01–P36, pool 1 and pool 2 I037–I100, docs/design/portraits/). Only the attributes the matcher reads are kept.
//   tsx scripts/portraitPoolImport.ts
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const FILES = ["portrait_pilot.csv", "portrait_pool1.csv", "portrait_pool2.csv"] as const;

/** RFC 4180 rows (quoted fields, doubled quotes, commas and newlines inside quotes). */
function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let quoted = false;
  for (let index = 0; index < text.length; index += 1) {
    const char = text[index]!;
    if (quoted) {
      if (char === '"' && text[index + 1] === '"') { field += '"'; index += 1; }
      else if (char === '"') quoted = false;
      else field += char;
    } else if (char === '"') quoted = true;
    else if (char === ",") { row.push(field); field = ""; }
    else if (char === "\n" || char === "\r") {
      if (char === "\r" && text[index + 1] === "\n") index += 1;
      row.push(field); field = "";
      if (row.some(value => value !== "")) rows.push(row);
      row = [];
    } else field += char;
  }
  if (field !== "" || row.length > 0) { row.push(field); rows.push(row); }
  return rows;
}

const entries: string[] = [];
const sources: string[] = [];
for (const file of FILES) {
  const raw = readFileSync(`docs/design/portraits/${file}`);
  sources.push(`${file} ${createHash("sha256").update(raw).digest("hex")}`);
  const [header, ...rows] = parseCsv(raw.toString("utf8").replace(/^﻿/, ""));
  const col = (row: string[], name: string) => row[header!.indexOf(name)] ?? "";
  for (const row of rows) {
    const stage = col(row, "stage");
    const band = stage === "pool" ? col(row, "age_group") : stage;
    const body = col(row, "body");
    entries.push(JSON.stringify({
      id: col(row, "id"), identityId: col(row, "identity_id"), stage, band, file: col(row, "file"),
      sex: col(row, "sex") === "f" ? "female" : "male", age: Number(col(row, "age")), classBand: col(row, "class"),
      occupation: col(row, "occupation"), role: col(row, "role"), build: body === "fat" || body === "heavy" ? "heavy" : body,
    }));
  }
}
writeFileSync("src/content/portraitPool.ts", `// Generated by scripts/portraitPoolImport.ts from docs/design/portraits/*.csv — do not edit by hand.
// Sources (sha256): ${sources.join("; ")}
export interface PortraitEntry {
  readonly id: string;
  readonly identityId: string;
  /** "pool" (pilot, one picture) or an aging stage: child · young · mature · old. */
  readonly stage: string;
  /** Age band the picture shows: child · young · mature · old. */
  readonly band: "child" | "young" | "mature" | "old";
  readonly file: string;
  readonly sex: "female" | "male";
  readonly age: number;
  readonly classBand: string;
  readonly occupation: string;
  readonly role: string;
  readonly build: "thin" | "average" | "heavy";
}

export const PORTRAIT_POOL: readonly PortraitEntry[] = [
${entries.map(entry => `  ${entry},`).join("\n")}
];
`);
process.stdout.write(`${entries.length} portraits\n`);
