/**
 * Best-effort, hash- and manifest-verified source/tool/prompt evidence lookup
 * for runtime assets. Every field this module fills in is backed by a file
 * already committed to the repository; nothing here is invented. Anything
 * this module cannot find evidence for is left as "unknown" (or "none" for
 * list-shaped fields with no entries), per docs/provenance/ASSET_PROVENANCE.md
 * rule 3.
 */
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { REPO_ROOT } from "./provenanceLedgerAssets";

function readJson<T>(relative: string): T {
  return JSON.parse(readFileSync(path.join(REPO_ROOT, relative), "utf8")) as T;
}

export const UNKNOWN = "unknown";
export const NONE = "none";

export interface AssetEvidence {
  sourcePath: string;
  sourceSha256: string;
  tool: string;
  model: string;
  generatedAt: string;
  /** Either literal prompt text (short) or a docs/provenance/prompts/... path reference note. */
  promptFile: string | null;
  promptInline: string;
  referenceInputs: string;
  seed: string;
  candidates: string;
  manualEdits: string;
  artBible: string;
  historicalProfile: string;
  notes: string;
}

function blankEvidence(notes: string): AssetEvidence {
  return {
    sourcePath: UNKNOWN,
    sourceSha256: UNKNOWN,
    tool: UNKNOWN,
    model: UNKNOWN,
    generatedAt: UNKNOWN,
    promptFile: null,
    promptInline: UNKNOWN,
    referenceInputs: UNKNOWN,
    seed: "",
    candidates: "",
    manualEdits: UNKNOWN,
    artBible: UNKNOWN,
    historicalProfile: UNKNOWN,
    notes,
  };
}

// --- 1) docs/asset-evidence/runtime-sources/derivatives.json ---------------
// Generated by scripts/downscaleRuntimeAssets.py. Covers historical-houses,
// historical-facilities-v1, historical-farm, historical-gate, historical-wall,
// runtime-mill-v1, complete-art-v1, runtime-actors-v1 and runtime-construction-v1.
interface DerivativeAsset {
  url: string; // "assets/..."
  source: string; // "docs/asset-evidence/runtime-sources/..."
  originalSha256: string;
  sha256: string; // runtime file hash after downscale
}
interface DerivativesManifest {
  assets: DerivativeAsset[];
}
let derivativesCache: Map<string, DerivativeAsset> | null = null;
function derivativesByUrl(): Map<string, DerivativeAsset> {
  if (derivativesCache) return derivativesCache;
  const manifest = readJson<DerivativesManifest>("docs/asset-evidence/runtime-sources/derivatives.json");
  derivativesCache = new Map(manifest.assets.map(a => [a.url, a]));
  return derivativesCache;
}

// --- 2) public/assets/world_asset_manifest.json -----------------------------
interface WorldAssetManifestAcceptedSource {
  kind: "accepted-art";
  path: string;
  sha256: string;
}
interface WorldAssetManifestSeedSource {
  seed: number;
  candidate: number;
}
type WorldAssetManifestSource = WorldAssetManifestAcceptedSource | WorldAssetManifestSeedSource;
interface WorldAssetManifestAsset {
  key: string;
  path: string;
  source?: WorldAssetManifestSource;
}
interface WorldAssetManifest {
  assets: WorldAssetManifestAsset[];
}
let worldManifestCache: Map<string, WorldAssetManifestAsset> | null = null;
function worldManifestByPath(): Map<string, WorldAssetManifestAsset> {
  if (worldManifestCache) return worldManifestCache;
  const manifest = readJson<WorldAssetManifest>("public/assets/world_asset_manifest.json");
  worldManifestCache = new Map(manifest.assets.map(a => [a.path, a]));
  return worldManifestCache;
}

// --- 3) docs/asset-evidence/phase16-sources/generation.json ----------------
interface Phase16GenerationRecord {
  asset_id: string;
  prompt_exact: string;
  tool: string;
  model_name: string | null;
  model_version: string | null;
  seed: number | null;
  generation_date: string;
  historical_profile: string;
  art_bible_version: string;
  reference_images: string[];
  source_sha256?: string;
}
interface Phase16Generation {
  records: Phase16GenerationRecord[];
}
let phase16GenCache: Map<string, Phase16GenerationRecord> | null = null;
function phase16GenerationByAssetId(): Map<string, Phase16GenerationRecord> {
  if (phase16GenCache) return phase16GenCache;
  const gen = readJson<Phase16Generation>("docs/asset-evidence/phase16-sources/generation.json");
  phase16GenCache = new Map(gen.records.map(r => [r.asset_id, r]));
  return phase16GenCache;
}

// --- 4) public/assets/phase16-landscape/manifest.json -----------------------
interface Phase16LandscapeAsset {
  id: string;
  url: string;
  source: string; // e.g. "garden-vegetables-v1.png"
  sourceSha256: string;
  runtimeSha256: string;
}
let phase16LandscapeCache: Map<string, Phase16LandscapeAsset> | null = null;
function phase16LandscapeByPublicPath(): Map<string, Phase16LandscapeAsset> {
  if (phase16LandscapeCache) return phase16LandscapeCache;
  const arr = readJson<Phase16LandscapeAsset[]>("public/assets/phase16-landscape/manifest.json");
  phase16LandscapeCache = new Map(arr.map(a => [`public${a.url}`, a]));
  return phase16LandscapeCache;
}

// --- 5) public/assets/phase16-house-condition/registration.json ------------
interface HouseConditionEntry {
  assetId: string;
  condition: string;
  url: string;
  bodySource: string;
  bodySha256: string;
  originalSha256: string;
  runtimeSha256: string;
}
let houseConditionCache: Map<string, HouseConditionEntry> | null = null;
function houseConditionByPublicPath(): Map<string, HouseConditionEntry> {
  if (houseConditionCache) return houseConditionCache;
  const arr = readJson<HouseConditionEntry[]>("public/assets/phase16-house-condition/registration.json");
  houseConditionCache = new Map(arr.map(a => [`public${a.url}`, a]));
  return houseConditionCache;
}

function relativeUrlFor(runtimePath: string): string {
  // "public/assets/x.png" -> "assets/x.png" (matches the derivatives.json "url" key format).
  return runtimePath.replace(/^public\//, "");
}

/**
 * Resolves whatever committed evidence exists for a runtime asset. Purely
 * lookup-based: never fabricates values. Callers get "unknown"/"none" when
 * no matching record exists.
 */
export function resolveEvidence(runtimePath: string): AssetEvidence {
  const url = relativeUrlFor(runtimePath);

  // Rule A: downscale derivatives archive (historical-*, runtime-actors-v1,
  // runtime-construction-v1, runtime-mill-v1, complete-art-v1).
  const derivative = derivativesByUrl().get(url);
  if (derivative) {
    const e = blankEvidence(
      "Source archived pre-downscale original; scripts/downscaleRuntimeAssets.py records both hashes. " +
        "No prompt/tool record with a matching hash was found in the repository for this family.",
    );
    e.sourcePath = derivative.source;
    e.sourceSha256 = derivative.originalSha256;
    e.referenceInputs = UNKNOWN;
    e.manualEdits = "scripted downscale source→runtime (scripts/downscaleRuntimeAssets.py); earlier hand edits unknown";
    return e;
  }

  // Rule B/C: public/assets/world_asset_manifest.json top-level building/foliage/terrain sprites.
  const worldAsset = worldManifestByPath().get(runtimePath);
  if (worldAsset) {
    const source = worldAsset.source;
    if (source && "kind" in source && source.kind === "accepted-art") {
      const e = blankEvidence(
        "docs/asset-evidence/accepted-art/README.md: sourced from the sibling feudal-lord-simulator/output " +
          "directory via scripts/installAcceptedArt.mjs; no prompt/seed retained for accepted-art sources.",
      );
      e.sourcePath = source.path;
      e.sourceSha256 = source.sha256;
      e.tool = "scripts/installAcceptedArt.mjs (accepted-art pipeline)";
      e.referenceInputs = UNKNOWN;
      return e;
    }
    if (source && "seed" in source) {
      const e = blankEvidence(
        `README/world_asset_manifest.json record only a seed/candidate index (seed ${source.seed}, candidate ${source.candidate}); ` +
          "no archived original bytes or prompt text for this exact candidate were found in the repository.",
      );
      e.tool = "scripts/generateBuildingCandidates.py (seed/candidate selection, no archived original)";
      e.seed = String(source.seed);
      e.candidates = `candidate ${source.candidate} selected (see docs/asset-evidence/phase13WorldRelease.json)`;
      e.referenceInputs = UNKNOWN;
      return e;
    }
  }

  // Rule D: phase16 landscape overlays (garden props) — full generation record.
  const landscape = phase16LandscapeByPublicPath().get(runtimePath);
  if (landscape) {
    const rec = phase16GenerationByAssetId().get(landscape.source.replace(/\.png$/, ""));
    const e = blankEvidence("Matched via public/assets/phase16-landscape/manifest.json + docs/asset-evidence/phase16-sources/generation.json (hash-verified).");
    e.sourcePath = existsSync(path.join(REPO_ROOT, "docs/asset-evidence/phase16-sources/generated", landscape.source))
      ? `docs/asset-evidence/phase16-sources/generated/${landscape.source}`
      : `docs/asset-evidence/phase16-sources/registered/${landscape.source}`;
    e.sourceSha256 = landscape.sourceSha256;
    if (rec) {
      e.tool = rec.tool;
      e.model = rec.model_name ?? UNKNOWN;
      e.generatedAt = rec.generation_date;
      e.promptInline = rec.prompt_exact;
      e.referenceInputs = rec.reference_images.length > 0 ? rec.reference_images.join("; ") : NONE;
      e.artBible = rec.art_bible_version;
      e.historicalProfile = rec.historical_profile;
      e.seed = rec.seed === null ? "" : String(rec.seed);
    }
    return e;
  }

  // Rule E: phase16 house-condition composites (existing house body + generated overlay).
  const houseCondition = houseConditionByPublicPath().get(runtimePath);
  if (houseCondition) {
    const wearRec = phase16GenerationByAssetId().get("condition-wear-v1");
    const e = blankEvidence(
      `Composite of existing house body (${houseCondition.bodySource}, already listed as its own runtime asset row) ` +
        "plus a generated condition overlay, built by scripts/phase16Art.py. " +
        "No archived file holds the intermediate composite, so sourcePath/sourceSha256 stay unknown rather than " +
        "point at a file whose bytes would not match. The pre-downscale composite hash " +
        `${houseCondition.originalSha256} is recorded in public/assets/phase16-house-condition/registration.json ` +
        "(see also runtimePath above) for reference.",
    );
    e.tool = "scripts/phase16Art.py (house body + generated condition-overlay composite)";
    e.manualEdits = "scripted composite + downscale (scripts/phase16Art.py); earlier hand edits unknown";
    e.referenceInputs = `${houseCondition.bodySource} (project-own, runtime asset)`;
    if (wearRec) {
      e.artBible = wearRec.art_bible_version;
      e.historicalProfile = wearRec.historical_profile;
      e.generatedAt = wearRec.generation_date;
      e.model = wearRec.model_name ?? UNKNOWN;
    }
    return e;
  }

  return blankEvidence("No matching evidence record found by any resolution rule; treat as unknown until archived source material is located.");
}
