"""F0-V roof smoke anchors (visibility design 1절: the houses have no chimney, so smoke leaves the ridge / thatch).
For every house art the game draws (the historical houses and pairs, and their Wave 2 variants, which are painted in
their base's frame), the anchor is the ridge: the middle of the opaque pixels (alpha >= 128) in the first four opaque
rows of the art's alpha bounds (scaled to a variant's size), as a fraction of those bounds (x from the left, y from
the top). Writes src/render/roofSmokeAnchors.generated.ts. Run: python3 scripts/roofSmokeAnchors.py
"""
import json
import re
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent


def manifest(path):
    text = (ROOT / path).read_text()
    body = text[text.index("["):]
    return json.JSONDecoder().raw_decode(re.sub(r",(\s*[\]}])", r"\1", body))[0]


def anchor(url, width, height, bounds):
    image = Image.open(ROOT / "public" / url).convert("RGBA")
    sx, sy = image.width / width, image.height / height
    x0, y0 = round(bounds["x"] * sx), round(bounds["y"] * sy)
    x1, y1 = round((bounds["x"] + bounds["width"]) * sx), round((bounds["y"] + bounds["height"]) * sy)
    alpha = np.array(image)[y0:y1, x0:x1, 3] >= 128
    rows = np.nonzero(alpha.any(axis=1))[0]
    top = int(rows.min())
    xs = np.nonzero(alpha[top:top + 4].any(axis=0))[0]
    return {"fx": round(float((xs.min() + xs.max()) / 2 / alpha.shape[1]), 4), "fy": round(top / alpha.shape[0], 4)}


anchors = {}
singles = {entry["level"]: entry for entry in manifest("src/render/historicalHouseAssetManifest.generated.ts")}
for entry in singles.values():
    anchors[entry["url"]] = anchor(entry["url"], entry["width"], entry["height"], entry["alphaBounds"])
pairs = manifest("src/render/houseCompoundAssetManifest.generated.ts")
for entry in pairs:
    anchors[entry["url"]] = anchor(entry["url"], entry["width"], entry["height"], entry["alphaBounds"])
pools = manifest("src/render/buildingVariantManifest.ts")
for pool in pools:
    if pool.get("kind") != "house":
        continue
    base = singles.get(pool["level"]) if pool.get("lot") == "single" else next(
        (entry for entry in pairs if entry["level"] == pool["level"] and entry["axis"] == pool.get("lot")), None)
    if base is None:
        continue
    for variant in pool["variants"]:
        if variant.get("url"):
            anchors[variant["url"]] = anchor(variant["url"], base["width"], base["height"], base["alphaBounds"])
body = json.dumps(anchors, indent=1, sort_keys=True)
(ROOT / "src/render/roofSmokeAnchors.generated.ts").write_text(
    "// Generated by scripts/roofSmokeAnchors.py (rule in its header). Do not edit by hand.\n"
    "// Ridge point of each house art as a fraction of its alpha bounds (fx from the left, fy from the top).\n"
    f"export const ROOF_SMOKE_ANCHORS: Readonly<Record<string, {{ readonly fx: number; readonly fy: number }}>> = {body};\n")
print(len(anchors), "anchors")
