const fs=require('node:fs');const path=require('node:path');const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..');
async function main(){const records=JSON.parse(fs.readFileSync(path.join(root,'records/metadata-misc.json'))); const tiles=[];
for(const r of records){const raw=path.join(root,r.generationRecords[0].rawFile);let im=sharp(raw).ensureAlpha();let {data,info}=await im.raw().toBuffer({resolveWithObject:true});let x0=info.width,y0=info.height,x1=0,y1=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){if(data[(y*info.width+x)*4+3]>8){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y)}}const box={left:x0,top:y0,width:x1-x0+1,height:y1-y0+1};r.rawSize=[info.width,info.height];r.alphaBounds=box;
if(r.id==='pulse_ring'){const frames=[];for(let i=0;i<3;i++){const side=[48,66,84][i];const opacity=[0.8,0.55,0.28][i];let b=await sharp(raw).extract(box).resize(side,side,{fit:'contain',background:'#00000000'}).ensureAlpha().raw().toBuffer();for(let j=3;j<b.length;j+=4)b[j]=Math.round(b[j]*opacity);frames.push({input:await sharp(b,{raw:{width:side,height:side,channels:4}}).png().toBuffer(),left:i*96+Math.floor((96-side)/2),top:Math.floor((96-side)/2)});}await sharp({create:{width:288,height:96,channels:4,background:'#00000000'}}).composite(frames).png().toFile(path.join(root,r.file));}
else{let b=await sharp(raw).extract(box).resize(80,80,{fit:'inside'}).png().toBuffer();let m=await sharp(b).metadata();await sharp({create:{width:96,height:96,channels:4,background:'#00000000'}}).composite([{input:b,left:Math.floor((96-m.width)/2),top:Math.floor((96-m.height)/2)}]).png().toFile(path.join(root,r.file));}
for(let j=0;j<3;j++){let size=[24,32,48][j];let src=sharp(path.join(root,r.file));if(r.id==='pulse_ring')src=src.extract({left:96,top:0,width:96,height:96});tiles.push({input:await src.resize(size,size).png().toBuffer(),left:20+j*80,top:20+records.indexOf(r)*70});} r.qa={status:'candidate',alpha:'preserved original generated alpha',smallSizeReview:[24,32,48],text:'none',forbiddenMotifs:'none',runtimeInstalled:false};}
await sharp({create:{width:260,height:370,channels:4,background:'#d9c9a7'}}).composite(tiles).png().toFile(path.join(root,'records/misc-size-check.png'));fs.writeFileSync(path.join(root,'records/metadata-misc.json'),JSON.stringify(records,null,2)+'\n');console.log(records.map(r=>({id:r.id,dimensions:[r.width,r.height],rawSize:r.rawSize})));}
main().catch(e=>{console.error(e);process.exitCode=1});
