const fs=require('fs'),crypto=require('crypto');
const {createCanvas,loadImage}=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const {PNG}=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/pngjs');
const work='/tmp/astra-wave39-work-20260930/rain',dest='/tmp/astra-wave39-candidates-20260930/assets/rain';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function bbox(p,x0=0,x1=p.width){let xMin=x1,yMin=p.height,xMax=-1,yMax=-1;for(let y=0;y<p.height;y++)for(let x=x0;x<x1;x++)if(p.data[(y*p.width+x)*4+3]>8){xMin=Math.min(xMin,x);xMax=Math.max(xMax,x);yMin=Math.min(yMin,y);yMax=Math.max(yMax,y)}return{x:xMin,y:yMin,w:xMax-xMin+1,h:yMax-yMin+1}}
(async()=>{let rows=[];for(const it of JSON.parse(fs.readFileSync(work+'/sources.json'))){let src=PNG.sync.read(fs.readFileSync(it.sourcePath));let img=await loadImage(it.sourcePath);let w,h,frames=1,fw,fh,c,ctx;const edits=[];
if(it.kind==='streak'){w=16;h=24;c=createCanvas(w,h);ctx=c.getContext('2d');const b=bbox(src);const bh=it.len,bw=Math.max(it.width,Math.ceil(it.len*Math.sin(it.angle*Math.PI/180))+it.width);ctx.drawImage(img,b.x,b.y,b.w,b.h,Math.floor((w-bw)/2),Math.floor((h-bh)/2),bw,bh);edits.push('Alpha bounding-box crop; fit to prescribed short streak envelope; center in16x24; alpha peak and neutral grey RGB normalized; integer-aligned crop avoids expanding particle envelope.');}
else if(it.kind==='splash'){frames=4;fw=it.size==='small'?16:24;fh=it.size==='small'?12:16;w=fw*4;h=fh;c=createCanvas(w,h);ctx=c.getContext('2d');let bs=[];for(let f=0;f<4;f++)bs.push(bbox(src,Math.floor(f*src.width/4),Math.floor((f+1)*src.width/4)));const maxw=Math.max(...bs.map(b=>b.w)),maxh=Math.max(...bs.map(b=>b.h));const scale=Math.min((it.size==='small'?9:14)/maxw,(it.size==='small'?6:9)/maxh);for(let f=0;f<4;f++){const b=bs[f];const dw=b.w*scale,dh=b.h*scale;ctx.drawImage(img,b.x,b.y,b.w,b.h,f*fw+(fw-dw)/2,fh-3-dh,dw,dh)}edits.push('Four equal source cells alpha-cropped; one common scale across temporal frames; shared contact baseline h-3; no painted pixels added.');}
else {w=it.kind==='shadow'?512:128;h=it.kind==='shadow'?256:64;c=createCanvas(w,h);ctx=c.getContext('2d');if(it.kind==='shadow')ctx.filter='blur(9px)';ctx.drawImage(img,0,0,w,h);ctx.filter='none';edits.push('Mechanical canvas resize; shadow alpha-edge feather9px; wet native luminance extracted to low-contrast alpha; neutral dark tint RGB and low peak alpha normalization.');}
let p=PNG.sync.read(c.toBuffer('image/png'));if(it.kind==='wet'){for(let i=0;i<p.data.length;i+=4){const lum=(p.data[i]+p.data[i+1]+p.data[i+2])/3;p.data[i+3]=Math.round(180+(255-lum)*0.25);}}let maxA=0;for(let i=3;i<p.data.length;i+=4)maxA=Math.max(maxA,p.data[i]);const peak=it.kind==='streak'?(it.strength==='faint'?95:175):it.kind==='shadow'?35:it.kind==='wet'?28:170;for(let i=0;i<p.data.length;i+=4){p.data[i+3]=Math.round(p.data[i+3]*peak/Math.max(1,maxA));if(it.kind==='streak'){p.data[i]=185;p.data[i+1]=196;p.data[i+2]=199;}if(it.kind==='shadow'||it.kind==='wet'){p.data[i]=41;p.data[i+1]=47;p.data[i+2]=46;}}
if(it.kind==='wet'){for(let y=0;y<h;y++){const a=(y*w)*4+3,b=(y*w+w-1)*4+3;const avg=Math.round((p.data[a]+p.data[b])/2);p.data[a]=p.data[b]=avg;}for(let x=0;x<w;x++){const a=x*4+3,b=((h-1)*w+x)*4+3;const avg=Math.round((p.data[a]+p.data[b])/2);p.data[a]=p.data[b]=avg;}edits.push('Opposite edge alpha pairs averaged to enforce exact XY seam continuity.');}
const out=dest+'/'+it.id+'.png';fs.writeFileSync(out,PNG.sync.write(p));rows.push({...it,outputPath:out,width:w,height:h,frames,frameWidth:fw||w,frameHeight:fh||h,pivot:it.kind==='splash'?[fw/2,fh-3]:[w/2,h/2],status:'candidate',tool:'image_gen.imagegen',model:'not displayed',date:'2026-09-30',sourceSha256:sha(it.sourcePath),sha256:sha(out),recommendedAlpha:1,encodedPeakAlpha:peak,recommendedSpeed:it.kind==='streak'?'120–220 px/s':it.kind==='shadow'?'4–12 px/s':it.kind==='splash'?'4 frames / 160–240 ms':'static; interpolate wetness 1–4 s',windAngle:it.angle||0,lifecycle:it.kind==='streak'?'world-space falling; occlude behind roofs; kill on ground contact':it.kind==='splash'?'one shot at ground/roof contact':it.kind==='shadow'?'non-tileable world-space soft shadow':'XY tileable material wetness overlay',manualEdits:edits.join(' '),candidateCount:1,selectionReason:'Single native candidate, normalized to actual world-particle scale.'});}
fs.writeFileSync(work+'/manifest.json',JSON.stringify(rows,null,2));console.log('normalized',rows.length);})();
