import{W,D,R,fs,path,sha,csv,pixels,bounds}from'./lib.mjs';
const prior='/tmp/astra-wave20-work-20260926',old=JSON.parse(await fs.readFile(prior+'/registered.json')),geometry=JSON.parse(await fs.readFile(prior+'/records/geometry-contract.json')),reg=JSON.parse(await fs.readFile(W+'/records/registration.json'));
const data=[];await fs.mkdir(D+'/provenance/generated',{recursive:true});await fs.mkdir(D+'/provenance/records',{recursive:true});
for(let level=0;level<5;level++)for(const era of[1350,1400])for(const variant of['a','b']){const unchanged=level<2,id=`house_l${level}_${era}_${variant}-v${unchanged?1:2}`,file=`assets/houses/${id}.png`,g=geometry.houses[level],r=unchanged?old.find(r=>r.id===id):reg.find(r=>r.id===id);if(!r)throw Error('Missing registration '+id);const record=unchanged?r.record:JSON.parse(await fs.readFile(W+`/records/${era}/${id}.json`)),image=await pixels(D+'/'+file),chimney=era===1400&&(level===4||(level===3&&variant==='b'));
let raw='';if(!unchanged){raw=`provenance/generated/${id}-raw.png`;await fs.copyFile(r.source,D+'/'+raw);await fs.writeFile(D+`/provenance/records/${id}.json`,JSON.stringify({generation:record,registration:r,source_in_archive:raw,source_sha256:await sha(r.source)},null,2));}
const overlayBoarded=level<2?`references/overlays/boarded_l${level}-v2.png`:`assets/overlays/boarded_l${level}_${era}-v3.png`,overlaySnow=level<2?`references/overlays/roof_snow_l${level}-v2.png`:`assets/overlays/roof_snow_l${level}_shared-v3.png`;
data.push({asset_id:id,base_grade_id:`house_l${level}`,file,status:unchanged?'accepted_unchanged':'candidate_rework',era,level,variant,version:unchanged?1:2,canvas_width:image.w,canvas_height:image.h,pivot_x:g.runtimeDerivedNativeAnchor[0],pivot_y:g.runtimeDerivedNativeAnchor[1],pivot_units:'native PNG px; top-left origin',footprint_tiles_x:1,footprint_tiles_y:1,native_to_world_scale:g.nativeToWorldScale,render_contract:'full canvas at existing scale and pivot; do not reuse old upper alpha crop',alpha_bbox:bounds(image,8),chimney,chimney_count:chimney?1:0,chimney_material:chimney?'red brick shaft; open top; no chimney pot':'none',smoke_origin_x:r.smokeOrigin?.[0]??'',smoke_origin_y:r.smokeOrigin?.[1]??'',smoke_baked_in:false,jetty_overhang_native_px:r.jettyOverhangNativePx??'',jetty_basis:!unchanged&&era===1350?'manual approximate upper-vs-ground wall setback, not logical tile size':'',ground_source_points:r.sourceGround??'',ground_target_points:r.targetGround??'',ground_mapping_residual_px:!unchanged?Math.max(...r.groundResiduals.flat().map(Math.abs)):'',ground_landmark_tolerance_px:unchanged?0:2,boarded_overlay:overlayBoarded,snow_overlay:overlaySnow,overlay_offset_x:0,overlay_offset_y:0,overlay_scale:1,candidate_sha256:await sha(D+'/'+file),previous_approved_sha256:unchanged?await sha(prior+'/delivery/'+file):'',reference_house:`references/houses/${path.basename(originalFile(level))}`,reference_sha256:g.referenceSha256,generation_method:unchanged?'byte-identical approved reuse':'built-in image_gen edit',generated_master:raw,full_actual_prompt:record.prompt,postprocessing:unchanged?'No changes; byte-identical copy':'Native ground-landmark affine registration; upper-only vertical scale to grade original top; original roof/upper silhouette/window masks NOT restored; no recolor-only shortcut. See registration.json.',era_signal:unchanged?'Previously accepted low-grade treatment':era===1350?'strong projecting upper storey, deep underside, joist ends/brackets, broad dark horizontal unglazed windows, regular box frame':'dense close studding, broad diamond-leaded glazing, rough stone lower wall, red canopy; permitted large brick chimney',scope:'local candidate package only; not installed'});}
function originalFile(l){return R+`/house_l${l}-v${l?2:3}.png`;}
await fs.writeFile(D+'/assets.csv',csv(data));
for(const name of['registration.json','ground-contract.json'])await fs.copyFile(W+'/records/'+name,D+'/provenance/records/'+name);
await fs.copyFile(prior+'/delivery/facility_chimney_notes.csv',D+'/facility_chimney_notes.csv');
for(const name of['lib.mjs','proofs.mjs','blind.mjs','catalog.mjs'])await fs.copyFile(W+'/'+name,D+'/provenance/'+name);
await fs.writeFile(D+'/provenance/README.md','# 재작업 기록\n\n신규 본체 원화12개와 전체 실제 프롬프트·정합 행렬을 보존합니다. L0/L1 승인8장은 새로 생성하지 않았습니다. 등록점은 보이는 기초 모서리의 수동 측정점이며, 좌표계의 수치적 잔차0과 원래 기초 픽셀 전체 일치는 다른 주장입니다. 상층·창·지붕 실루엣 변화는 이번 재작업의 의도입니다.\n\n스크립트는 실제 실행 기록입니다. 작업 당시 /tmp 경로와 설치된 sharp 경로를 포함하므로 다른 위치에서 재실행할 때 lib.mjs 경로를 조정해야 합니다.\n');console.log('house CSV',data.length,'rework',data.filter(r=>r.status==='candidate_rework').length,'unchanged',data.filter(r=>r.status==='accepted_unchanged').length);
