import{W,D,fs,path,sharp,pixels,bounds,sha,csv}from'./lib.mjs';
const prior='/tmp/astra-wave20-work-20260926',reg=JSON.parse(await fs.readFile(W+'/records/registration.json')),g=JSON.parse(await fs.readFile(prior+'/records/geometry-contract.json')),checks=[],metrics=[];
const assert=(name,pass,detail)=>checks.push({name,pass:!!pass,detail});
function parse(text){const result=[],row=[];let val='',quote=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){val+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(val);val='';}else if(c==='\n'&&!quote){row.push(val.replace(/\r$/,''));result.push(row.splice(0));val='';}else val+=c;}if(quote)throw Error('CSV unclosed quote');return result;}
const table=parse((await fs.readFile(D+'/assets.csv','utf8')).replace(/^\ufeff/,'')),keys=table[0],rows=table.slice(1).map(row=>Object.fromEntries(keys.map((k,i)=>[k,row[i]])));
assert('20 house rows',rows.length===20,rows.length);assert('12 reworks',rows.filter(r=>r.status==='candidate_rework').length===12,reg.length);assert('8 approved preserved',rows.filter(r=>r.status==='accepted_unchanged').length===8,8);assert('3 required chimneys',rows.filter(r=>r.chimney==='true').length===3,3);
for(const r of rows){const p=await pixels(D+'/'+r.file),l=Number(r.level),geo=g.houses[l],record=reg.find(t=>t.id===r.asset_id),name=r.asset_id+': ';assert(name+'canvas',p.w===geo.canvas[0]&&p.h===geo.canvas[1],[p.w,p.h]);assert(name+'pivot',Number(r.pivot_x)===geo.runtimeDerivedNativeAnchor[0]&&Number(r.pivot_y)===geo.runtimeDerivedNativeAnchor[1],[r.pivot_x,r.pivot_y]);assert(name+'scale',Number(r.native_to_world_scale)===geo.nativeToWorldScale,r.native_to_world_scale);assert(name+'1x1 footprint',r.footprint_tiles_x==='1'&&r.footprint_tiles_y==='1','1x1');assert(name+'CSV hash',await sha(D+'/'+r.file)===r.candidate_sha256,r.candidate_sha256);
let edges=0;for(let y=0;y<p.h;y++)for(let x=0;x<p.w;x++)if((x===0||y===0||x===p.w-1||y===p.h-1)&&p.data[(y*p.w+x)*4+3]>0)edges++;assert(name+'transparent border',edges===0,edges);
let residual='';if(l<2){assert(name+'byte identical accepted',await sha(D+'/'+r.file)===await sha(prior+'/delivery/'+r.file),r.file);}else{residual=Math.max(...record.groundResiduals.flat().map(Math.abs));assert(name+'ground landmark mapping',residual<1e-8,residual);assert(name+'raw generation prompt roundtrip',r.full_actual_prompt===JSON.parse(await fs.readFile(W+`/records/${r.era}/${r.asset_id}.json`)).prompt,'full exact prompt');assert(name+'upper silhouette changed',await sha(D+'/'+r.file)!==await sha(prior+'/delivery/assets/houses/'+r.asset_id.replace('-v2','-v1')+'.png'),'different image');if(r.era==='1350')assert(name+'pronounced jetty measurement',record.jettyOverhangNativePx>=10,record.jettyOverhangNativePx);}
const chimney=r.era==='1400'&&(l===4||(l===3&&r.variant==='b'));assert(name+'chimney rule',(r.chimney==='true')===chimney,chimney);if(chimney){const x=Math.round(Number(r.smoke_origin_x)),y=Math.round(Number(r.smoke_origin_y));assert(name+'smoke origin in visible sprite',x>=0&&x<p.w&&y>=0&&y<p.h&&p.data[(y*p.w+x)*4+3]>128,[x,y]);}else assert(name+'no smoke coords',r.smoke_origin_x===''&&r.smoke_origin_y==='',[r.smoke_origin_x,r.smoke_origin_y]);
for(const type of['boarded_overlay','snow_overlay']){const o=await pixels(D+'/'+r[type]);assert(name+type+' canvas',o.w===p.w&&o.h===p.h,r[type]);assert(name+type+' identity placement',r.overlay_offset_x==='0'&&r.overlay_offset_y==='0'&&r.overlay_scale==='1','0,0; scale1');if(l>=2&&type==='boarded_overlay'){let off=0;for(let i=3;i<o.data.length;i+=4)if(o.data[i]>0&&p.data[i]===0)off++;assert(name+'no floating boards',off===0,off);}}
metrics.push({asset_id:r.asset_id,status:r.status,canvas:`${p.w}x${p.h}`,pivot_x:r.pivot_x,pivot_y:r.pivot_y,footprint:'1x1',ground_landmark_transform_residual_px:residual,manual_ground_landmark_tolerance_px:l<2?0:2,jetty_overhang_native_px:record?.jettyOverhangNativePx??'',border_nontransparent_pixels:edges,lower_edge_warp:record?.lowerEdgeWarp??'',sha256:r.candidate_sha256});}
const overlays=(await fs.readdir(D+'/assets/overlays')).filter(f=>f.endsWith('.png'));assert('9 replacement overlays within original max10',overlays.length===9,overlays.length);const proofs=(await fs.readdir(D+'/proofs')).filter(f=>f.endsWith('.png'));assert('2 required layout proofs',proofs.length===2,proofs);for(const p of proofs){const m=await sharp(D+'/proofs/'+p).metadata();assert(p+' size',m.width===640&&m.height===665,[m.width,m.height]);}
const v=JSON.parse(await fs.readFile(D+'/qa/visual-verdict.json'));assert('independent visual >=90 pass',v.score>=90&&v.verdict==='pass',v.score);
const report={assertions:checks.length,passed:checks.filter(c=>c.pass).length,failed:checks.filter(c=>!c.pass),checks,scope:'Offline registered PNG/CSV/proof verification, not game runtime. Manual ground landmarks have +/-2px visual tolerance; matrix residual is a different numeric measure.'};await fs.writeFile(D+'/qa/pixel_metrics.csv',csv(metrics));await fs.writeFile(D+'/qa/validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify({assertions:report.assertions,passed:report.passed,failed:report.failed},null,2));if(report.failed.length)process.exitCode=1;
