require 'json';require 'digest'
r=__dir__;repo='/Users/rexxa/fls-astra-steward';round=File.expand_path('../..',r);write=lambda{|f,v|File.write(r+'/'+f,JSON.pretty_generate(v)+"\n")};head='5fb1aebfe735592c1424c947e88388d4ffe21742'
def obj(props);{type:'object',required:props.keys,additionalProperties:false,properties:props};end
specs=[
 ['lord.wardship_ended','endingGuardianKind',{'named_guardian'=>'후견인이 기록되어 있던 영주의 후견이 성년과 함께 끝났다.','overlord'=>'상위 영주의 후견 아래 있던 영주가 성년이 되어 후견을 벗어났다.'},'src/engine/lordship.ts:56-72,170-181; src/engine/history.ts:586-600','At successful ending, bind SAME ward lord ID before and after; verify event-year minus birthYear is finite safe integer >=21. Snapshot before.lordship.wardship.guardianId: nonempty string -> named_guardian; null -> overlord by engine convention; missing/invalid unknown. Do not infer mother/kin from role or current state.'],
 ['faction.leader_succeeded','successorHouseholdAtEvent',{'same_household'=>'세상을 떠난 수장과 같은 가구의 사람이 무리를 이었다.','different_household'=>'세상을 떠난 수장과 다른 가구의 사람이 무리를 이었다.'},'src/engine/history.ts:285-294; src/engine/factions.ts:117-149,290-305','Match params predecessorId and leaderId to exact event identities. Require predecessor explicitly dead and successor explicitly alive. Snapshot predecessor householdId from before persons people/past and successor householdId after; both nonempty valid IDs. Equal -> same_household else different_household. No inference of blood kin, hereditary right, rivalry, or motive.'],
 ['stewardship.steward_died','oversightModeAtSuccession',{'direct'=>'영주가 직접 보는 영지에서 장부를 맡던 사람이 세상을 떠나 후임이 장부를 맡았다.','steward'=>'청지기에게 맡긴 영지에서 담당자가 세상을 떠나 후임 청지기가 뒤를 이었다.'},'src/engine/stewardship.ts:137-158; src/engine/history.ts:924-940','Capture in per-estate oversight loop, retaining estate ID even though current history record lacks it. Require prior/current steward IDs equal record params, deceased explicitly dead, successor exists and alive=true in estates.people, prior.mode==after.mode. direct/steward only. Multiple estate matches without capture identity -> unknown. No current-state backfill or promises of loyal/competent successor.'],
 ['stewardship.began','offMapPortfolioAtStart',{'sole_estate'=>'관리하는 지도 밖 영지가 한 곳인 가운데, 영주가 직접 보고 청지기가 장부를 맡기 시작했다.','multiple_estates'=>'여러 지도 밖 영지를 관리하는 가운데, 이 영지도 영주가 직접 보고 청지기가 장부를 맡기 시작했다.'},'src/engine/stewardship.ts:51-54,117-134; src/engine/history.ts:924-935','At new oversight require after mode=direct, estate offMap=true and titleHolder=possessor=lord, appointed person exists alive=true. Count distinct after oversight estate IDs whose after estates are offMap and held in BOTH title/possession by lord, including this estate. One -> sole_estate, greater than one -> multiple_estates; zero/duplicate/invalid -> unknown. This describes concurrent oversight portfolio only, not lifetime first acquisition. Multiple additions share after snapshot; never invent ordering.']
]
fields=specs.map{|t,f,lines,source,rule|{id:f,templates:[t],values:lines.keys,capture:source,captureRule:rule,provenance:'emission_snapshot',currentRecordStorage:'absent: proposed event-time context',reconstruction:'Unknown for old records without this verified event-time snapshot. Never fill from current persons, estates or office holders.'}}
adds=specs.flat_map{|t,f,lines,_,_|lines.map{|value,line|{template:t,variant:{id:t+'.r06office.'+value,priority:20,when:[{field:'context.'+f,op:'eq',value:value}],headline:line,requiredSlots:[],retainFactLine:true}}}}
proposal={formatVersion:'office-context-v1',status:'AUTHOR_DRAFT_UNINSTALLED',sourceHead:head,fields:fields,additions:adds,fallback:'Unknown, malformed or record/campaign mismatched context -> existing baseline; no inferred past facts',runtimeImplemented:false};write.call('PROPOSAL.json',proposal);write.call('FIELD_CONTRACTS.json',fields)
# Exact authoring scopes: typed proposal with fixed field contracts, bounded rows, template-specific variant branches.
variants=specs.map{|t,f,lines,_,_|obj({template:{const:t},variant:obj({id:{type:'string',pattern:'^'+Regexp.escape(t)+'\\.r06office\\.[a-z_]+$'},priority:{const:20},when:{type:'array',minItems:1,maxItems:1,items:obj({field:{const:'context.'+f},op:{const:'eq'},value:{enum:lines.keys}})},headline:{type:'string',minLength:1},requiredSlots:{const:[]},retainFactLine:{const:true}})})}
ps=obj({formatVersion:{const:'office-context-v1'},status:{const:'AUTHOR_DRAFT_UNINSTALLED'},sourceHead:{const:head},fields:{const:fields},additions:{type:'array',minItems:8,maxItems:8,uniqueItems:true,items:{anyOf:variants}},fallback:{const:proposal[:fallback]},runtimeImplemented:{const:false}});write.call('PROPOSAL.schema.json',ps)
common={recordId:{type:'string',minLength:1},recordTick:{type:'integer',minimum:0,maximum:9007199254740991},campaignId:{type:'string',minLength:1},sourceHead:{const:head},captureKind:{const:'emission_snapshot'}}
branches=specs.flat_map{|t,f,lines,_,_|[obj(common.merge({template:{const:t},status:{const:'known'},referenceVerified:{const:true},fields:obj({f=>{enum:lines.keys}})})),obj(common.merge({template:{const:t},status:{const:'unknown'},referenceVerified:{const:false},fields:{const:{}}}))]};write.call('CONTEXT.schema.json',{'$schema'=>'https://json-schema.org/draft/2020-12/schema',anyOf:branches})
fixtures=[]
adds.each_with_index do |a,i|
 t=a[:template];q=a[:variant][:when][0];identity={recordId:'office-h-'+i.to_s,recordTick:1234+i,campaignId:'seed1-fixture',template:t,sourceHead:head};context=identity.merge({captureKind:'emission_snapshot',status:'known',referenceVerified:true,fields:{q[:field].sub('context.','')=>q[:value]}})
 fixtures<<{id:a[:variant][:id]+'.known',identity:identity,context:context,expected:a[:variant][:id]}
 {'missing_field'=>lambda{|x|x[:fields]={}},'unknown_enum'=>lambda{|x|x[:fields].transform_values!{'invented'}},'wrong_record'=>lambda{|x|x[:recordId]='other'},'wrong_tick'=>lambda{|x|x[:recordTick]+=1},'wrong_campaign'=>lambda{|x|x[:campaignId]='other'},'wrong_source'=>lambda{|x|x[:sourceHead]='0'*40},'negative_tick'=>lambda{|x|x[:recordTick]=-1},'unsafe_tick'=>lambda{|x|x[:recordTick]=9007199254740992},'unverified'=>lambda{|x|x[:referenceVerified]=false},'extra_name'=>lambda{|x|x[:name]='한때 이름'},'wrong_provenance'=>lambda{|x|x[:captureKind]='current_person_lookup'},'unknown_empty'=>lambda{|x|x[:status]='unknown';x[:referenceVerified]=false;x[:fields]={}}}.each{|name,mutate|c=Marshal.load(Marshal.dump(context));mutate.call(c);fixtures<<{id:a[:variant][:id]+'.'+name,identity:identity,context:c,expected:nil}}
end
write.call('FIXTURES.json',fixtures)
sources={'src/engine/history.ts'=>[[285,294],[586,600],[924,940]],'src/engine/lordship.ts'=>[[31,32],[56,72],[170,181]],'src/engine/stewardship.ts'=>[[51,54],[117,158]],'src/engine/factions.ts'=>[[117,149],[290,305]],'src/engine/persons.types.ts'=>[[48,81]],'src/content/historyCopy.ko.ts'=>[[189,191],[217,225]],'src/engine/historyNames.ts'=>[[15,20],[43,54]],'docs/design/glossary.md'=>[[19,23],[88,98],[189,192]]}.map{|path,spans|body=File.read(repo+'/'+path);{path:path,sha256:Digest::SHA256.hexdigest(body),spans:spans.map{|a,b|{start:a,end:b,text:body.lines[(a-1)...b].join}}}};write.call('SOURCE_EVIDENCE.json',sources)
write.call('ADOPTION_LIMITS.json',{allVariantsRequireVerifiedCapture:true,compositionHolds:adds.select{|a|a[:template]=='stewardship.began'}.map{|a|{variantId:a[:variant][:id],reason:'Baseline says estate just entered lord hands, but emitter checks new oversight, not fresh transfer. Must review composed line; proposed neutral baseline: 영주가 이 영지를 직접 보고 청지기가 장부를 맡기 시작했다.',engineModified:false}},inheritedRisk:'Dead or missing successor must produce unknown context; this proposal does not fix existing dead-steward runtime bugs or baseline claims.',runtimeInstalled:false})
write.call('BASELINE_REF.json',{path:'../../chronicle/variants.ko.json',sha256:Digest::SHA256.file(round+'/chronicle/variants.ko.json').hexdigest,modified:false})
