require 'json';require 'digest';require 'csv';require 'rexml/document'
ROOT='/tmp/astra-steward-r08-20261004';OUT=__dir__;GRAPH=ROOT+'/graphs/fen-comparison-r08'; REPO='/Users/rexxa/fls-astra-steward'
def j(p);JSON.parse(File.read(p));end
def jl(p);File.readlines(p).reject{|l|l.strip.empty?}.map{|l|JSON.parse(l)};end
def sha(p);Digest::SHA256.file(p).hexdigest;end
def save(n,x);File.write(OUT+'/'+n,JSON.pretty_generate(x)+"\n");end
paths={'open'=>ROOT+'/inherited/R07/long-run/seed3-open-fixed-growth','fen'=>ROOT+'/long-run/seed3-fen-fixed-growth'};runs={};checks={};inputs=[]
paths.each do |name,p|
 rows=jl(p+'/years.jsonl');cmd=jl(p+'/commands.jsonl');meta=j(p+'/metadata.json');sum=j(p+'/summary.json');start=j(p+'/start.fls.json')['state'];final=j(p+'/final.fls.json')['state'];ctl=j(p+'/controls.json')['frozen'];raise 'control' unless ctl=={'policy'=>'growth','dues'=>1000,'subsidies'=>[]};raise 'complete' unless sum['completedTarget']&&sum['stoppedFor']=='target_year'&&sum['final']['tick']==600000&&sum['targetYear']==1450
 raise 'grid' unless rows.map{|r|r['periodYear']}==(1300...1450).to_a && rows.all?{|r|r['tick']==4000*(r['year']-1300)&&r['year']==r['periodYear']+1}
 raise 'config' unless meta['config'].values_at('seed','years','mode','policy')==[3,150,'fixed','growth']&&meta['head']=='5fb1aebfe735592c1424c947e88388d4ffe21742'
 raise 'annual controls' unless rows.all?{|r|r['policy']==ctl['policy']&&r['dues']==ctl['dues']&&r['subsidies']==ctl['subsidies']}&&cmd.all?{|c|c['controlsBefore']==ctl&&c['controlsAfter']==ctl}
 raise 'commands' unless rows.sum{|r|r['attemptedCommands']}==cmd.size&&rows.sum{|r|r['changedStateCommands']}==cmd.count{|c|c['stateReferenceChanged']}&&rows.all?{|r|r['asked']+r['own']==r['changedStateCommands']&&r['decisionsByKind'].values.sum==r['changedStateCommands']}
 buckets=cmd.group_by{|c|1300+c['tick']/4000};raise 'command bucket' unless rows.all?{|r|a=buckets.fetch(r['periodYear'],[]);a.size==r['attemptedCommands']&&a.count{|c|c['stateReferenceChanged']}==r['changedStateCommands']}
 prev=(start.dig('persons','past')||[]).select{|x|!x['alive']}.group_by{|x|x['deathCause']||'unspecified'}.transform_values(&:size)
 rows.each{|r|v=r['retainedDeathsByCause'];r['deathNetChange']=(prev.keys|v.keys).to_h{|k|[k,v.fetch(k,0)-prev.fetch(k,0)]};r['deathNetTotal']=r['deathNetChange'].values.sum;prev=v}
 dead=(final.dig('persons','past')||[]).select{|x|!x['alive']};raise 'duplicate death ids' unless dead.map{|x|x['id']}.uniq.size==dead.size
 death_by_year=dead.group_by{|x|x['deathYear']};death_match=rows.all?{|r|actual=dead.select{|x|x['deathYear']&&x['deathYear']<r['year']}.group_by{|x|x['deathCause']||'unspecified'}.transform_values(&:size);actual==r['retainedDeathsByCause']}
 raise 'death cohort reconcile' unless death_match
 manifest=File.readlines(p+'/SHA256SUMS').reject{|l|l.strip.empty?}.map{|l|s,f=l.strip.split(/\s+/,2);f=f.sub(/^\*/,'');if File.file?(p+'/'+f);raise "hash #{name} #{f}" unless sha(p+'/'+f)==s;{path:f,status:"verified"};else;raise "fen missing #{f}" if name=="fen";{path:f,status:"not_in_lightweight_inheritance"};end}
 codec=jl(p+'/save-checks.jsonl');raise 'codec log' unless codec.size==38&&codec.all?{|c|c['exactJsonRoundTrip']}
 %w[years.jsonl commands.jsonl metadata.json summary.json controls.json start.fls.json final.fls.json save-checks.jsonl SHA256SUMS].each{|f|inputs<<{path:p+'/'+f,sha256:sha(p+'/'+f)}}
 kinds=cmd.group_by{|c|c['kind']}.transform_values{|a|{attempted:a.size,changed:a.count{|c|c['stateReferenceChanged']}}}
 stats={end:rows.last.select{|k,v|%w[population treasury timber foodReserveTicks houseRecords inhabited livingTownPeople retainedDeathsByCause claimStates suitStates promises registry].include?(k)},commands:{attempted:cmd.size,changed:cmd.count{|c|c['stateReferenceChanged']},asked:rows.sum{|r|r['asked']},own:rows.sum{|r|r['own']},noChange:cmd.count{|c|!c['stateReferenceChanged']},zeroAttemptYears:rows.count{|r|r['attemptedCommands']==0},zeroChangedYears:rows.count{|r|r['changedStateCommands']==0},zeroAskedYears:rows.count{|r|r['asked']==0},thresholds:[3,5,10].to_h{|n|[n,{attemptedYears:rows.count{|r|r['attemptedCommands']>=n},changedYears:rows.count{|r|r['changedStateCommands']>=n}}]},kinds:kinds,pauseTicks:rows.sum{|r|r['pauseTicks']}},deaths:{retained:dead.size,byCause:rows.last['retainedDeathsByCause'],personDiedHistory:rows.sum{|r|r['historyTemplates'].fetch('person.died',0)},negativeAnnualCounterDiffs:rows.select{|r|r['deathNetChange'].values.any?{|v|v<0}}.map{|r|r['periodYear']}},houses:final['houses'].group_by{|h|h['level']}.transform_values{|a|{houses:a.size,residents:a.sum{|h|h['residents']}}},seconds:sum['seconds']}
 runs[name]={rows:rows,metadata:meta,summary:stats};checks[name]={annualRows:rows.size,manifest:manifest,codecRecords:codec.size,commandsReconciled:true,controlsPreserved:true,finalDeathYearAgainstBoundaries:death_match,uniqueDeathIds:dead.size,completedTarget:true,sourceHashes:meta.dig('verifiedSource','sourceSha256'),findings:sum['findings'],partialYearCounters:sum['partialYearCounters']}
end
raise 'source pair' unless checks['open'][:sourceHashes]==checks['fen'][:sourceHashes]
inputs+=j(ROOT+'/records/fen-comparison-design/INPUT_SHA256.json').select{|x|x['path'].start_with?(REPO)}.map{|x|raise 'probe source drift' unless sha(x['path'])==x['sha256'];x}
checks[:probeVersionLimit]='Same protocol and locally pinned probe source verified; metadata embeds engine source hashes, not full remote probe SHA. Remote harness byte identity depends on parent source transfer provenance.'
fields=%w[population treasury timber foodReserveTicks houseRecords inhabited attemptedCommands changedStateCommands asked own pauseTicks deathNetTotal];causes=runs.values.flat_map{|x|x[:rows].last['retainedDeathsByCause'].keys}.uniq.sort
annual=(0...150).map{|i|o=runs['open'][:rows][i];f=runs['fen'][:rows][i];r={'periodYear'=>o['periodYear'],'snapshotYear'=>o['year'],'tick'=>o['tick']};fields.each{|k|r['open_'+k]=o[k];r['fen_'+k]=f[k];r['delta_'+k]=f[k]-o[k]};causes.each{|k|r['open_death_'+k]=o['deathNetChange'].fetch(k,0);r['fen_death_'+k]=f['deathNetChange'].fetch(k,0)};r}
blocks=annual.each_slice(25).map{|a|r={'periodFrom'=>a.first['periodYear'],'periodTo'=>a.last['periodYear'],'snapshotYear'=>a.last['snapshotYear']};%w[open fen].each{|n|%w[population treasury timber foodReserveTicks houseRecords inhabited].each{|k|r[n+'_end_'+k]=a.last[n+'_'+k]};%w[attemptedCommands changedStateCommands asked own pauseTicks deathNetTotal].each{|k|r[n+'_sum_'+k]=a.sum{|z|z[n+'_'+k]}};causes.each{|k|r[n+'_death_'+k]=a.sum{|z|z[n+'_death_'+k]}}};r}
[ ['ANNUAL',annual],['BLOCKS25',blocks] ].each{|n,a|save(n+'.json',a);CSV.open(OUT+'/'+n+'.csv','w'){|c|c<<a.first.keys;a.each{|r|c<<r.values}}}
surfaces={};runs.each{|name,run|rs=run[:rows];surfaces[name]={estates:rs.flat_map{|r|r['estates'].map{|x|x['id']}}.uniq.map{|id|v=rs.map{|r|r['estates'].find{|x|x['id']==id}}.compact;{id:id,observed:v.size,first:v.first,last:v.last,titlePossessorStates:v.map{|x|[x['title'],x['possessor']]}.uniq}},factions:rs.flat_map{|r|r['factions'].map{|x|x['id']}}.uniq.map{|id|v=rs.map{|r|r['factions'].find{|x|x['id']==id}};p=v.compact;{id:id,observed:p.size,min:p.map{|x|x['relation']}.min,max:p.map{|x|x['relation']}.max,final:p.last['relation'],distinctLeaders:p.map{|x|x['leader']}.uniq.size,adjacentChanges:v.each_cons(2).count{|a,b|a&&b&&a['leader']!=b['leader']}}},trades:rs.flat_map{|r|r['trades'].keys}.uniq.map{|id|v=rs.map{|r|r['trades'].fetch(id,0)};{id:id,firstBoundary:rs[v.index{|n|n>0}]['year'],min:v.min,max:v.max,final:v.last}}}}
save('SURFACES.json',surfaces);save('SUMMARY.json',runs.transform_values{|x|x[:summary]});save('CHECKS.json',checks);save('INPUT_SHA256.json',inputs)
# Static SVG only: each panel owns a labelled scale; no dual axes.
def esc(s);s.to_s.gsub('&','&amp;').gsub('<','&lt;').gsub('>','&gt;');end
def chart(file,title,subtitle,panels)
 w=1200;h=1200;svg=[%Q{<svg xmlns="http://www.w3.org/2000/svg" width="#{w}" height="#{h}" viewBox="0 0 #{w} #{h}"><rect width="100%" height="100%" fill="#fffdf8"/><g font-family="Arial, sans-serif" fill="#252b31"><text x="65" y="36" font-size="23">#{esc(title)}</text><text x="65" y="63" font-size="14">#{esc(subtitle)}</text><text x="800" y="36" fill="#23628c">Open field</text><text x="960" y="36" fill="#ba4b31">Fen</text>}]
 panels.each_with_index do |p,i|
  y0=130+i*500;left=100;right=1150;bottom=y0+340;all=p[:series].flat_map{|s|s[:values]};lo=[0,all.min].min;hi=[all.max,1].max;span=hi-lo
  svg<<%Q{<text x="65" y="#{y0-15}" font-size="16">#{esc(p[:title])}</text>}
  5.times{|k|v=lo+span*k/4.0;y=bottom-340*k/4.0;svg<<%Q{<line x1="#{left}" x2="#{right}" y1="#{y}" y2="#{y}" stroke="#d9dde0"/><text x="90" y="#{y+5}" text-anchor="end" font-size="12">#{v.round(1)}</text>}}
  [0,24,49,74,99,124,149].each{|n|x=left+(right-left)*n/149.0;svg<<%Q{<text x="#{x}" y="#{bottom+22}" text-anchor="middle" font-size="12">#{p[:start]+n}</text>}}
  p[:series].each{|s|pts=s[:values].each_with_index.map{|v,n|"#{(left+(right-left)*n/149.0).round(2)},#{(bottom-340*(v-lo)/span).round(2)}"}.join(' ');svg<<%Q{<polyline points="#{pts}" fill="none" stroke="#{s[:color]}" stroke-width="2.3"/>}}
  svg<<%Q{<text x="620" y="#{bottom+46}" text-anchor="middle" font-size="12">#{esc(p[:axis])}</text>}
 end
 svg<<%Q{<text x="65" y="#{h-20}" font-size="12">Single seed 3; descriptive paths only. Same fixed growth / dues 1000 / no subsidy.</text></g></svg>};txt=svg.join("\n");REXML::Document.new(txt);File.write(GRAPH+'/'+file,txt)
end
panel=lambda{|key,title,start,axis|{title:title,start:start,axis:axis,series:%w[open fen].each_with_index.map{|n,i|{values:runs[n][:rows].map{|r|r[key]},color:i==0 ? '#23628c' : '#ba4b31'}}}}
chart('01-population-housing.svg','Population and housing at year-end boundaries','Counts at the following-year boundary; not average residents across the year.',[panel.call('population','Population (residents)',1301,'Snapshot boundary year'),panel.call('inhabited','Inhabited house records (count)',1301,'Snapshot boundary year')])
chart('02-economy.svg','Treasury and food reserve snapshots','Treasury balance is not annual income. Food reserve is the engine estimate in ticks.',[panel.call('treasury','Treasury balance (pence)',1301,'Snapshot boundary year'),panel.call('foodReserveTicks','Food reserve (ticks)',1301,'Snapshot boundary year')])
chart('03-deaths.svg','Retained death records: annual net additions','Counters reconcile to final deathYear cohorts for these two runs; not mortality rates.',[panel.call('deathNetTotal','All retained death causes (persons / period)',1300,'Period year [start tick, next-year tick)'),{title:'Food-related codes famine + famine_year (persons / period)',start:1300,axis:'Period year [start tick, next-year tick)',series:%w[open fen].each_with_index.map{|n,i|{values:runs[n][:rows].map{|r|r['deathNetChange'].fetch('famine',0)+r['deathNetChange'].fetch('famine_year',0)},color:i==0 ? '#23628c' : '#ba4b31'}}}])
chart('04-command-density.svg','Bot command density per year','Attempts and reducer reference changes shown separately; neither is fun or human workload.',[panel.call('attemptedCommands','Attempted commands (count / period)',1300,'Period year [start tick, next-year tick)'),panel.call('changedStateCommands','State-reference-changed commands (count / period)',1300,'Period year [start tick, next-year tick)')])
puts JSON.pretty_generate(runs.transform_values{|x|x[:summary]})
