require 'json';require 'digest';require 'fileutils'
r=__dir__;round=File.expand_path('../..',r);repo='/Users/rexxa/fls-astra-steward';canonical=round+'/chronicle/variants.ko.json'
write=lambda{|f,v|File.write(r+'/'+f,JSON.pretty_generate(v)+"\n")};sha=Digest::SHA256.file(canonical).hexdigest;raise 'baseline drift' unless sha=='7314050459321e78ea19257fd4376ff80ab803586b0adfdaf2dd8ee159666dbf'
rows=[['plague.new_graves','dead','one','eq',1,'역병으로 숨진 한 사람이 기록되었다.'],['plague.new_graves','dead','several','gt',1,'역병으로 숨진 여러 사람이 기록되었다.'],['plague.empty_streets','houses','one','eq',1,'역병 기록에 빈집 한 채가 올랐다.'],['plague.empty_streets','houses','several','gt',1,'역병 기록에 여러 채의 빈집이 올랐다.'],['legacy.mayor_demand','candidateId','unidentified','eq','','시장 후보를 특정하지 않은 선출권 요구가 기록되었다.'],['legacy.mayor_demand','candidateId','identified','neq','','시장 후보가 함께 적힌 선출권 요구가 기록되었다.']]
additions=rows.group_by(&:first).map{|template,entries|{template:template,variants:entries.map{|_,field,id,op,value,line|{id:template+'.r06raw.'+id,priority:20,when:[{field:'params.'+field,op:op,value:value}],headline:line,requiredSlots:[],retainFactLine:true}}}}
patch={schemaVersion:1,status:'AUTHOR_CANDIDATE_REQUIRES_GUARD_AND_OPERATOR_REVIEW',sourceHead:'5fb1aebfe735592c1424c947e88388d4ffe21742',baselineSha256:sha,canonicalModified:false,additions:additions};write.call('ADDITIONS.json',patch)
FileUtils.cp(canonical,r+'/baseline650.ko.json')
schema=JSON.parse(File.read(round+'/chronicle/variants.schema.json'));FileUtils.cp(round+'/chronicle/variants.schema.json',r+'/CURRENT_VARIANTS.schema.json');schema['$defs']['condition']['properties']['op']['enum']<<'neq';schema['$id']='urn:astra:current-param-proposed-variants:r06';write.call('PROPOSED_VARIANTS.schema.json',schema)
contracts={status:'PROPOSED_NOT_IMPLEMENTED',preconditions:[{templates:['plague.new_graves'],field:'params.dead',type:'finite_safe_integer',minimum:1,maximum:9007199254740991},{templates:['plague.empty_streets'],field:'params.houses',type:'finite_safe_integer',minimum:1,maximum:9007199254740991},{templates:['legacy.mayor_demand'],field:'params.candidateId',type:'string',normalization:'none: exact empty vs any nonempty string; do not trim or resolve the ID to select'}],conditionExtension:{op:'neq',semantics:'Typed string inequality only after the declared string guard; missing/null/number/object/array must fallback, never coerce'},fallback:'Any failed type/domain precondition selects original baseline; never compare malformed values',nameContract:'No personal names in added headlines. Retain raw candidateId and baseline history.summary(record,state), whose historyParams resolves names at reading. Empty ID means no identified candidate in this record, not death, vacancy, or no possible candidate anywhere.',runtimeImplemented:false};write.call('GUARD_CONTRACT.json',contracts)
blocks=additions.flat_map{|a|a[:variants].map{|v|{variantId:v[:id],status:'BLOCK_UNTIL_DECLARED_SELECTOR_GUARD_VERIFIED',reason:v[:id].start_with?('plague.') ? 'Existing condition schema does not ensure positive finite safe integer input; gt/eq alone is not this guard.' : 'Typed candidateId string guard required; nonempty branch also needs proposed neq operator. Never infer death from empty ID.',requiresNewOperator:v[:when][0][:op]=='neq',runtimeInstalled:false}}};write.call('INSTALL_BLOCKS.json',{status:'ALL_SIX_UNINSTALLED',blocks:blocks})
fixtures=[]
rows.group_by(&:first).each do |template,entries|
 field=entries[0][1];values=field=='candidateId' ? ['', 'p17','missing-person-id',' ',nil,0,1,false,[],{},['p17']] : [1,2,9007199254740991,0,-1,1.5,9007199254740992,'1',nil,false,[],{},1.0]
 values.each_with_index do |value,i|
  suffix=if field=='candidateId';value.is_a?(String) ? (value.empty? ? 'unidentified':'identified') : nil;else;value.is_a?(Numeric)&&value.finite?&&value==value.to_i&&value>=1&&value<=9007199254740991 ? (value==1 ? 'one':'several') : nil;end
  fixtures<<{id:template+".value#{i}",template:template,params:{field=>value},expectedVariant:suffix && template+'.r06raw.'+suffix}
 end
 [nil,{},[]].each_with_index{|value,i|fixtures<<{id:template+".missing#{i}",template:template,params:value,expectedVariant:nil}}
end
write.call('FIXTURES.json',fixtures)
sources={'src/engine/history.ts'=>[[655,661],[727,737]],'src/engine/plague.ts'=>[[227,233]],'src/engine/legacy.ts'=>[[93,98],[466,469]],'src/content/historyCopy.ko.ts'=>[[40,43],[159,163],[183,185]],'src/engine/historyNames.ts'=>[[15,20],[43,54]],'docs/design/glossary.md'=>[[64,69],[189,192]]}.map{|path,spans|text=File.read(repo+'/'+path);{path:path,sha256:Digest::SHA256.hexdigest(text),spans:spans.map{|first,last|{start:first,end:last,text:text.lines[(first-1)...last].join}}}};write.call('SOURCE_EVIDENCE.json',sources)
puts 'created six candidates; no canonical changes'
