const fs=require('fs'),path=require('path'),crypto=require('crypto');
const{loadImage}=require('/tmp/astra-wave4b-work-20260925/node_modules/@napi-rs/canvas');
const root=path.resolve(__dirname,'..'),prior=path.resolve(root,'../astra-ui-p0-candidates-v1');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{const entries=['frames','icons','portraits'].flatMap(f=>JSON.parse(fs.readFileSync(path.join(__dirname,f+'.json'))));const names=new Set(entries.map(a=>path.basename(a.file))),rows=[],preserved=[];
 for(const a of entries){const p=path.join(root,a.file),im=await loadImage(p);if(im.width!==a.width||im.height!==a.height)throw Error('dimensions:'+a.id);rows.push({asset_id:a.id,status:'candidate',file:a.file,width:im.width,height:im.height,role:a.role,sha256:sha(p),generation_records:JSON.stringify(a.generationRecords),processing:JSON.stringify(a.processing??{}),slice_or_cells:JSON.stringify(a.nineSlice??{cellSize:a.cellSize,cellOrder:a.cellOrder}),unchanged_from_prior:sha(p)===sha(path.join(prior,'assets/ui',path.basename(a.file))),qa:JSON.stringify(a.qa??{})});}
 fs.mkdirSync(path.join(root,'retained/ui'),{recursive:true});
 for(const name of fs.readdirSync(path.join(prior,'assets/ui')).filter(n=>n.endsWith('.png'))){const source=path.join(prior,'assets/ui',name),target=path.join(root,names.has(name)?'assets/ui':'retained/ui',name);if(!names.has(name))fs.copyFileSync(source,target);preserved.push({file:path.relative(root,target),baselineSha256:sha(source),sha256:sha(target),unchanged:sha(source)===sha(target)});}
 fs.copyFileSync(path.join(prior,'assets.csv'),path.join(__dirname,'previous-assets.csv'));
 fs.writeFileSync(path.join(__dirname,'asset-rows.json'),JSON.stringify(rows,null,2));fs.writeFileSync(path.join(__dirname,'preservation.json'),JSON.stringify({total:preserved.length,delivery:entries.length,outsideDelivery:preserved.length-entries.length,changed:preserved.filter(x=>!x.unchanged).length,unchanged:preserved.filter(x=>x.unchanged).length,files:preserved},null,2));
 let html='<!doctype html><meta charset="utf-8"><title>UI P0 rework</title><style>body{background:#e1d1ae;color:#332d25;font:16px sans-serif;margin:24px}section{display:flex;flex-wrap:wrap;gap:16px}figure{width:340px;margin:0;padding:14px;background:#bfb49e}img{max-width:100%;max-height:200px;object-fit:contain}small{display:block}a{color:#332d25}</style><h1>UI P0 재작업 후보</h1><p>게임 미설치 · 지정 파일 외 원본 유지</p><p><a href="README.md">설명</a> · <a href="assets.csv">재작업 납품 CSV</a></p><section>';
 for(const a of rows)html+=`<figure><a href="${a.file}"><img src="${a.file}"><small>${a.asset_id}</small></a><small>${a.width}×${a.height}${a.unchanged_from_prior?' · 유지':''}</small></figure>`;
 fs.writeFileSync(path.join(root,'index.html'),html+'</section>');console.log(JSON.stringify({rows:rows.length,preserved:preserved.filter(x=>x.unchanged).length,total:preserved.length}));})();
