const fs=require('fs'),crypto=require('crypto'),sharp=require('/Users/rexxa/.npm/_npx/8b377f6eec906bc4/node_modules/sharp/lib/index.js');const W=__dirname, w=512,h=32;
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const raw=async p=>sharp(p).ensureAlpha().raw().toBuffer({resolveWithObject:true});
const png=async(b,p,width=w,height=h)=>sharp(b,{raw:{width,height,channels:4}}).png().toFile(p);
const mod=(x,n)=>(x%n+n)%n;
(async()=>{let {data:ref}=await raw('/tmp/astra-wave29-work/reference/astra-wave29-reference-files/shoreline_a-v1.png');let profile=[];for(let x=0;x<w;x++){let edge=42;for(let y=26;y<65;y++){let i=(y*w+x)*4;if(ref[i+2]>ref[i]+3){edge=y;break}}profile.push(edge)}
// Existing coast average baseline 43, rendered overlay top-left y=27.
profile=profile.map((v,x)=>{let a=0;for(let d=-2;d<=2;d++)a+=profile[mod(x+d,w)];return a/5});for(let x=0;x<10;x++){let t=x/10;let avg=(profile[x]+profile[511-x])/2;profile[x]=avg*(1-t)+profile[x]*t;profile[511-x]=avg*(1-t)+profile[511-x]*t;}profile[511]=profile[0];
fs.writeFileSync(W+'/provenance/coastline-registration.json',JSON.stringify({reference:'shoreline_a-v1.png',reference_size:[512,96],overlay_top_left:[0,27],anchor:[0,16],baseline_in_reference:43,coastline_y:profile,method:'First blue-greater-than-red transition after row 26; 5px horizontal smoothing; periodic 10px edge feather.'},null,2));
let index=[],qa=[];
for(const [name,id,n,fps] of [['foam','shore_foam_sheet',6,4],['ice','ice_edge',1,0]]){let {data,info}=await raw(W+'/provenance/'+name+'-raw.png'), sw=info.width;let clean=Buffer.alloc(data.length);for(let y=420;y<590;y++)for(let x=0;x<sw;x++){let i=(y*sw+x)*4,v=(data[i]+data[i+1]+data[i+2])/3,a=data[i+3];let factor=Math.max(0,Math.min(1,(v-(name==='foam'?145:110))/50));a=Math.round(a*factor);if(a<8)continue;clean.set([data[i],data[i+1],data[i+2],a],i)}
let cent=[];for(let x=0;x<sw;x++){let sum=0,ys=0;for(let y=420;y<590;y++){let a=clean[(y*sw+x)*4+3]**2;sum+=a;ys+=a*y}cent[x]=sum?ys/sum:506;}
let base=Buffer.alloc(w*40*4);for(let y=0;y<40;y++)for(let x=0;x<w;x++){let sx=Math.round(x*(sw-1)/(w-1)),sy=Math.round(cent[sx]+(y-20)*3),si=(sy*sw+sx)*4,di=(y*w+x)*4;if(sy>=0&&sy<1024)clean.copy(base,di,si,si+4)}
// Bilinear sample the coherent painted base, wrapped X, without new artwork.
function sample(x,y){x=mod(x,w-1);let x0=Math.floor(x),x1=(x0+1)%(w-1),y0=Math.floor(y),fy=y-y0,fx=x-x0;let out=[0,0,0,0];for(let dy=0;dy<2;dy++)for(let dx=0;dx<2;dx++){let yy=y0+dy;if(yy<0||yy>=40)continue;let xx=dx?x1:x0,i=(yy*w+xx)*4,wt=(dx?fx:1-fx)*(dy?fy:1-fy);for(let c=0;c<4;c++)out[c]+=base[i+c]*wt}return out;}
function frame(t){let b=Buffer.alloc(w*h*4),phase=2*Math.PI*t,shift=name==='foam'?3*Math.sin(phase):0,pulse=name==='foam'?.71+.22*Math.cos(phase):.74;for(let x=0;x<w;x++)for(let y=1;y<h-1;y++){let line=profile[x]-27+(name==='foam'?1.1*Math.sin(phase):0),p=sample(x-shift,20+(y-line)*(name==='foam'?2:1.7)),a=Math.round(p[3]*pulse);if(a<3)continue;let i=(y*w+x)*4;b.set([Math.round(p[0]),Math.round(p[1]),Math.round(p[2]),a],i)}for(let y=0;y<h;y++){let i=y*w*4,j=(y*w+w-1)*4;for(let c=0;c<4;c++){let a=Math.round((b[i+c]+b[j+c])/2);b[i+c]=b[j+c]=a;}}return b}
let frames=[];for(let k=0;k<n;k++){let b=frame(k/n);frames.push(b);await png(b,W+'/frames/'+id+'_'+k+'.png')}
let sheet=await sharp({create:{width:w*n,height:h,channels:4,background:'#00000000'}}).composite(frames.map((b,k)=>({input:b,raw:{width:w,height:h,channels:4},left:w*k,top:0}))).png().toBuffer();let file=W+'/assets/'+id+'-v1.png';fs.writeFileSync(file,sheet);let dif=(a,b)=>{let s=0;for(let i=0;i<a.length;i+=4){for(let c=0;c<3;c++)s+=Math.abs(a[i+c]*a[i+3]/255-b[i+c]*b[i+3]/255);s+=Math.abs(a[i+3]-b[i+3])}return s/a.length};let steps=frames.map((a,k)=>dif(a,frames[(k+1)%n]));qa.push({id,edge_max:0,alpha_top_bottom_zero:true,temporal_steps:steps,closure_exact:frame(0).equals(frame(1)),loop_seam_pass:n===1||steps[n-1]<=Math.max(...steps.slice(0,-1))*1.15+.05});let gen=JSON.parse(fs.readFileSync(W+'/provenance/'+name+'-generation.json'));index.push({id,file:'assets/'+id+'-v1.png',sha256:hash(file),frame_width:w,frame_height:h,frame_count:n,sheet_width:w*n,sheet_height:h,layout:'horizontal',fps,loop:true,repeat_x:true,repeat_y:false,alpha_baked_max:Math.max(...frames[0].filter((_,i)=>i%4===3)),recommended_alpha:name==='foam'?.65:.8,blend:'source-over',anchor_x:0,anchor_y:16,placement_offset_x:0,placement_offset_y:27,preview_frame:0,notes:'shoreline_a 512x96 reference top-left plus (0,27), baseline reference y43. Register shoreline orientation before use. X-repeat only.',prompt:gen.prompt,generation_source:W+'/provenance/'+name+'-raw.png',source_sha256:hash(W+'/provenance/'+name+'-raw.png'),processing:'Extract bright painted pixels and preserve source alpha; normalize per-column line center; map to measured existing shoreline; periodic subpixel lateral/vertical sine and opacity foam only; exact X RGBA edges; hidden RGB zero.'});let comp=await sharp('/tmp/astra-wave29-work/reference/astra-wave29-reference-files/shoreline_a-v1.png').composite([{input:frames[0],raw:{width:w,height:h,channels:4},top:27,left:0}]).png().toBuffer();fs.writeFileSync(W+'/qa/'+id+'-composite.png',comp);
}
fs.writeFileSync(W+'/index.json',JSON.stringify(index,null,2));fs.writeFileSync(W+'/qa/metrics.json',JSON.stringify(qa,null,2));console.log(qa);
})();
