import{W,D,R,fs,path,sharp,pixels,original,sha,csv}from'./lib.mjs';
const rows=JSON.parse(await fs.readFile(W+'/registered.json')),g=JSON.parse(await fs.readFile(W+'/records/geometry-contract.json'));
if(rows.length!==20)throw Error('Expected twenty completed candidates');
const assets=[];
await fs.mkdir(D+'/provenance/generated',{recursive:true});await fs.mkdir(D+'/provenance/records',{recursive:true});
for(const r of rows){const sourceRel=`provenance/generated/${r.id}-raw.png`;await fs.copyFile(r.source,D+'/'+sourceRel);await fs.writeFile(D+`/provenance/records/${r.id}.json`,JSON.stringify({...r,source_archive_path:sourceRel,source_sha256:await sha(r.source),candidate_sha256:await sha(D+'/'+r.file)},null,2));assets.push({asset_id:r.id,file:r.file,status:'candidate',era:r.era,level:r.level,variant:r.variant,canvas_width:r.canvas[0],canvas_height:r.canvas[1],pivot_x:r.pivot[0],pivot_y:r.pivot[1],pivot_units:'native PNG pixels; origin top-left',pivot_basis:'runtime historicalHouseAssets.ts alpha-crop bottomcenter mapped from1254 source; identical to reference',footprint_tiles_x:1,footprint_tiles_y:1,native_to_world_scale:r.scale,chimney:r.chimney,chimney_count:r.chimney?1:0,chimney_material:r.chimney?'plain stone / muted brick; no pot':'none',smoke_origin_x:r.smokeOrigin?.[0]??'',smoke_origin_y:r.smokeOrigin?.[1]??'',smoke_origin_units:r.chimney?'native PNG pixels, dark open top':'not applicable',smoke_baked_into_png:false,roof_smoke_note:r.chimney?'use chimney origin':'existing open-hearth roof smoke behavior; chimney absent',boarded_overlay:`references/overlays/boarded_l${r.level}-v2.png`,snow_overlay:`references/overlays/roof_snow_l${r.level}-v2.png`,overlay_offset_x:0,overlay_offset_y:0,overlay_scale:1,original_house:`references/houses/${path.basename(original(r.level))}`,reference_sha256:g.houses[r.level].referenceSha256,candidate_sha256:await sha(D+'/'+r.file),generation_tool:'built-in image_gen edit',generated_master:sourceRel,generated_master_sha256:await sha(r.source),generated_count:1,selected_count:1,full_actual_prompt:r.record.prompt,manual_processing:'Generated architecture crop registered once to original native body box; original alpha silhouette except explicit chimney polygon; original Wave7 roof polygons retained; per-column lowest4 original-alpha pixels retained for ground contact; original pivot/canvas/world scale copied. See registration source and polygon records.',selection_reason:'Same grade, same original roof and footprint, era facade joins and chimney rule; overlay identity composition verified',era_legibility:r.level<2?'restrained low-grade joinery/shutter change; not an independent date label at zoom0.6':'box-frame/jetty bands;1400uppergrades add limited glazing/canopy; permitted chimney',scope_note:'candidate only; not installed'});}
await fs.writeFile(D+'/assets.csv',csv(assets));
const facilities=[['malt_kiln','말트 가마','existing_work_furnace_flue','변경 없음'],['smithy','대장간','existing_work_furnace_flue','변경 없음'],['lime_kiln','석회 가마','existing_work_furnace_flue','변경 없음'],['pottery_kiln','도기 가마','existing_work_furnace_flue','변경 없음'],['inn','여관','possible_1400_variant','굴뚝 변형 검토 가능; 이번 범위 밖'],['manor','영주관','possible_1400_variant','굴뚝 변형 검토 가능; 이번 범위 밖'],['guildhall','길드홀','possible_1400_variant','굴뚝 변형 검토 가능; 이번 범위 밖']].map(([id,name,rule,note])=>({id,name,era:1400,rule,new_png_count:0,note}));await fs.writeFile(D+'/facility_chimney_notes.csv',csv(facilities));
for(const name of ['geometry-contract.json','roof-polygons.json','chimney-regions.json'])await fs.copyFile(W+'/records/'+name,D+'/provenance/records/'+name);
for(const name of ['lib.mjs','register.mjs','proofs.mjs','catalog.mjs'])await fs.copyFile(W+'/'+name,D+'/provenance/'+name);
await fs.writeFile(D+'/provenance/README.md','# 제작 기록\n\n20개의 개별 built-in image_gen 편집 출력과 전체 실제 프롬프트를 보존했습니다. 원화는 최종 게임 크기와 다르며, 설치 대상으로 쓰지 않습니다. assets/houses만 신규 후보입니다. references는 검수 기준, generated는 생성 증빙입니다.\n\n후처리 스크립트는 실제 실행 기록으로 보존한 것이며 당시 로컬 경로와 기존 sharp 설치 경로를 포함합니다. 이 ZIP을 다른 경로에서 재실행하려면 lib.mjs의 W/D/R 및 sharp 경로를 조정해야 합니다. 원본 이미지/정합 다각형/캔버스/피벗/후처리 내역은 함께 제공됩니다.\n');
console.log('catalog',assets.length,'facilities',facilities.length);
