import{W,D,fs,sharp,pixels,original,svg,label,xml}from'./lib.mjs';
const rows=JSON.parse(await fs.readFile(W+'/registered.json')),geometry=JSON.parse(await fs.readFile(W+'/records/geometry-contract.json'));
const lookup=(era,l,v)=>era===1300?{file:original(l),pivot:geometry.houses[l].runtimeDerivedNativeAnchor,level:l,era,variant:v}:rows.find(r=>r.era===era&&r.level===l&&r.variant===v);
const fileOf=r=>r.era===1300?r.file:D+'/'+r.file;
async function draw(rowsToDraw,width,height,background,decorations,filename){const comps=[{input:svg(width,height,decorations),left:0,top:0}];for(const r of rowsToDraw){const meta=await sharp(r.file).metadata();const input=await sharp(r.file).resize(Math.round(meta.width*r.scale),Math.round(meta.height*r.scale)).png().toBuffer();comps.push({input,left:Math.round(r.x),top:Math.round(r.y)});}await sharp({create:{width,height,channels:4,background}}).composite(comps).png().toFile(filename);}
// Proof 1: native pixels, stable canvas pivots, identical street geometry.
{const width=1050,height=1325,items=[];let deco=label(28,35,'WAVE 20 | Same street, three eras | Native PNG scale 1.0',22)+label(28,61,'A and B are separate variants. Every grade keeps the existing 1 x 1 footprint and fractional pivot.',14);
for(let vr=0;vr<2;vr++)for(let e=0;e<3;e++){const v=vr?'b':'a',era=[1300,1350,1400][e],y=110+(vr*3+e)*199,ground=y+162;deco+=`<rect x="125" y="${ground-17}" width="895" height="32" fill="#b1a387"/><path d="M125 ${ground+15}H1020" stroke="#a9997f"/>`+label(20,y+88,String(era),23)+label(21,y+109,era===1300?'reference':`variant ${v}`,13);
for(let l=0;l<5;l++){const r=lookup(era,l,v);if(!r)continue;const p=await pixels(fileOf(r)),cx=225+l*178;items.push({file:fileOf(r),scale:1,x:cx-r.pivot[0],y:ground-r.pivot[1]});deco+=label(cx-12,ground+39,`L${l}`,14);}}
await draw(items,width,height,'#c3bdab',deco,D+'/proofs/01_same_street_three_eras.png');}
// Proof 2: all forty identity-offset overlays plus three smoke origins.
{const width=2650,height=1460,comps=[];let deco=label(24,36,'WAVE 20 | Smoke origins + 40 overlay compatibility composites',26)+label(24,63,'Native canvas, native pixels. No overlay translation, resize or re-centering. Old Wave 7 v2 overlays reused.',17);
const chimneyRows=rows.filter(r=>r.chimney);for(let i=0;i<chimneyRows.length;i++){const r=chimneyRows[i],x=30+i*870,origin=r.smokeOrigin??[0,0];const scale=1.5;comps.push({input:await sharp(fileOf(r)).resize(Math.round(r.canvas[0]*scale),Math.round(r.canvas[1]*scale)).png().toBuffer(),left:x,top:90});deco+=label(x+275,121,r.id,20)+label(x+275,151,`smoke origin native px: (${origin[0]}, ${origin[1]})`,17)+label(x+275,181,'One masonry stack. No chimney pot. Smoke is not baked in.',15);
if(origin[0]){const cx=x+origin[0]*scale,cy=90+origin[1]*scale;comps.push({input:svg(width,height,`<circle cx="${cx}" cy="${cy}" r="5" fill="none" stroke="#e62d31" stroke-width="2"/><path d="M${cx-9} ${cy}h18 M${cx} ${cy-9}v18" stroke="#e62d31"/>`),left:0,top:0});}}
for(let row=0;row<4;row++){const era=row<2?1350:1400,v=row%2?'b':'a',y=435+row*250;for(let l=0;l<5;l++){const r=lookup(era,l,v);if(!r)continue;const x=l*530;deco+=label(x+14,y,`${era} / L${l} / ${v}`,20);for(let k=0;k<3;k++){const type=k===1?'roof_snow':'boarded',base=sharp(fileOf(r)),input=k?await base.composite([{input:D+`/references/overlays/${type}_l${l}-v2.png`,left:0,top:0}]).png().toBuffer():await base.png().toBuffer();comps.push({input,left:x+10+k*173,top:y+20});deco+=label(x+17+k*173,y+204,k===0?'BASE':k===1?'SNOW +0,+0':'BOARDED +0,+0',13);}}}
await sharp({create:{width,height,channels:4,background:'#c5bcaa'}}).composite([{input:svg(width,height,deco),left:0,top:0},...comps]).png().toFile(D+'/proofs/02_smoke_origins_overlay_fit.png');}
// Proof 3: source approx 0.3, exact runtime per-grade scale times game zoom 0.6.
{const width=860,height=590,items=[];let deco=label(25,34,'WAVE 20 | Game zoom 0.6',23)+label(25,59,'Actual asset size: native-to-world scale x 0.6 (about 30% of source PNG).',14)+label(25,81,'View this PNG at 100%. Low-grade changes are intentionally restrained.',14);
for(let vr=0;vr<2;vr++){const v=vr?'b':'a',start=25+vr*425;deco+=label(start+40,117,`VARIANT ${v.toUpperCase()}`,17);for(let e=0;e<3;e++){const era=[1300,1350,1400][e],ground=218+e*140;deco+=label(start,ground-67,String(era),17)+`<rect x="${start+35}" y="${ground-5}" width="355" height="13" fill="#b1a387"/>`;for(let l=0;l<5;l++){const r=lookup(era,l,v);if(!r)continue;const scale=geometry.houses[l].nativeToWorldScale*.6,cx=start+63+l*70;items.push({file:fileOf(r),scale,x:cx-r.pivot[0]*scale,y:ground-r.pivot[1]*scale});deco+=label(cx-8,ground+30,`L${l}`,12);}}}await draw(items,width,height,'#c3bdab',deco,D+'/proofs/03_zoom_06_three_eras.png');}
console.log('3 proof sheets rendered; houses',rows.length);
