import{W,D,fs,path,sharp,pixels,original,sha,csv}from'./lib.mjs';
const rows=JSON.parse(await fs.readFile(W+'/registered.json')),geometry=JSON.parse(await fs.readFile(W+'/records/geometry-contract.json')),roofPolygons=JSON.parse(await fs.readFile(W+'/records/roof-polygons.json'));
function inside(x,y,poly){let result=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){if((poly[i][1]>y)!==(poly[j][1]>y)&&x<(poly[j][0]-poly[i][0])*(y-poly[i][1])/(poly[j][1]-poly[i][1])+poly[i][0])result=!result;}return result;}
const checks=[],metrics=[];function assert(name,ok,detail){checks.push({name,pass:!!ok,detail});}
assert('candidate count',rows.length===20,rows.length);assert('unique IDs',new Set(rows.map(r=>r.id)).size===20,'20 unique');assert('chimney count',rows.filter(r=>r.chimney).length===3,rows.filter(r=>r.chimney).map(r=>r.id));
for(const r of rows){const p=await pixels(D+'/'+r.file),ref=await pixels(original(r.level));const chim=r.era===1400&&(r.level===4||(r.level===3&&r.variant==='b'));let alphaDiff=0,groundDiff=0,roofDiff=0,chimneyAlpha=0,visible=0;const bottom=new Int16Array(p.w).fill(-1);for(let y=0;y<p.h;y++)for(let x=0;x<p.w;x++)if(ref.data[(y*p.w+x)*4+3]>0)bottom[x]=y;
for(let y=0;y<p.h;y++)for(let x=0;x<p.w;x++){const i=(y*p.w+x)*4,inChim=r.chimneyPolygon&&inside(x+.5,y+.5,r.chimneyPolygon);if(p.data[i+3]>0)visible++;if(!inChim&&p.data[i+3]!==ref.data[i+3])alphaDiff++;if(inChim&&p.data[i+3]>128&&ref.data[i+3]<32)chimneyAlpha++;
if(ref.data[i+3]&&y>=bottom[x]-3&&p.data.subarray(i,i+4).compare(ref.data.subarray(i,i+4)))groundDiff++;
if(!inChim&&roofPolygons[r.level].some(poly=>inside(x+.5,y+.5,poly))&&p.data.subarray(i,i+4).compare(ref.data.subarray(i,i+4)))roofDiff++;}
const prefix=r.id+': ';assert(prefix+'canvas',p.w===r.canvas[0]&&p.h===r.canvas[1],[p.w,p.h]);assert(prefix+'pivot unchanged',r.pivot.every((v,i)=>v===geometry.houses[r.level].runtimeDerivedNativeAnchor[i]),r.pivot);assert(prefix+'footprint',r.footprint[0]===1&&r.footprint[1]===1,'1x1');assert(prefix+'alpha outside chimney unchanged',alphaDiff===0,alphaDiff);assert(prefix+'ground RGBA unchanged',groundDiff===0,groundDiff);assert(prefix+'roof RGBA outside chimney unchanged',roofDiff===0,roofDiff);assert(prefix+'chimney rule',r.chimney===chim,chim);assert(prefix+'not empty',visible>1000,visible);assert(prefix+'distinct from original',await sha(D+'/'+r.file)!==await sha(original(r.level)),r.file);
if(chim){assert(prefix+'smoke origin in visible chimney',r.smokeOrigin&&inside(...r.smokeOrigin,r.chimneyPolygon)&&p.data[(r.smokeOrigin[1]*p.w+r.smokeOrigin[0])*4+3]>128,r.smokeOrigin);assert(prefix+'visible stack added',chimneyAlpha>40,chimneyAlpha);}else assert(prefix+'no smoke coordinate',r.smokeOrigin===null,r.smokeOrigin);
for(const kind of['boarded','roof_snow']){const file=D+`/references/overlays/${kind}_l${r.level}-v2.png`,o=await pixels(file),contract=geometry.overlays.find(o=>o.version===2&&o.member.endsWith(`${kind}_l${r.level}-v2.png`));assert(prefix+kind+' same canvas',o.w===p.w&&o.h===p.h,[o.w,o.h]);assert(prefix+kind+' exact reused hash',await sha(file)===contract.sha256,contract.sha256);}
metrics.push({id:r.id,canvas:`${p.w}x${p.h}`,alpha_drift_outside_chimney_px:alphaDiff,protected_ground_rgba_drift_px:groundDiff,protected_roof_rgba_drift_px:roofDiff,added_chimney_opaque_pixels:chimneyAlpha,smoke_origin:r.smokeOrigin??'',status:'candidate'});}
for(let l=0;l<5;l++)for(const era of[1350,1400]){const a=rows.find(r=>r.level===l&&r.era===era&&r.variant==='a'),b=rows.find(r=>r.level===l&&r.era===era&&r.variant==='b');assert(`L${l} ${era} independent variants`,await sha(D+'/'+a.file)!==await sha(D+'/'+b.file),'different final hashes');}
function parseCSV(text){const rows=[],row=[];let s='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){s+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(s);s='';}else if(c==='\n'&&!quote){row.push(s.replace(/\r$/,''));rows.push(row.splice(0));s='';}else s+=c;}if(quote)throw Error('Unclosed CSV quote');return rows;}
const csvRows=parseCSV((await fs.readFile(D+'/assets.csv','utf8')).replace(/^\ufeff/,''));assert('CSV20 rows',csvRows.length===21,csvRows.length-1);const promptIndex=csvRows[0].indexOf('full_actual_prompt');assert('CSV full prompt roundtrip',rows.every((r,i)=>csvRows[i+1][promptIndex]===r.record.prompt),'exact prompts including newlines/quotes');
const proofFiles=(await fs.readdir(D+'/proofs')).filter(x=>x.endsWith('.png'));assert('3 proof PNGs',proofFiles.length===3,proofFiles);for(const file of proofFiles){const meta=await sharp(D+'/proofs/'+file).metadata();assert(file+' decoded',meta.width>0&&meta.height>0,[meta.width,meta.height]);}
await fs.mkdir(D+'/qa',{recursive:true});await fs.writeFile(D+'/qa/pixel_metrics.csv',csv(metrics));const report={assertions:checks.length,passed:checks.filter(c=>c.pass).length,failed:checks.filter(c=>!c.pass),checks,scope:'Offline candidate PNG/canvas/anchor/overlay-reference/proof/provenance checks. No in-game runtime installation, cache or collision tests.'};await fs.writeFile(D+'/qa/validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify({assertions:report.assertions,passed:report.passed,failed:report.failed},null,2));if(report.failed.length)process.exitCode=1;
