require 'json'
require 'digest'
require 'time'
B='/tmp/astra-steward-r08-20261004'
O=File.join(B,'records/requirement-audit')
def read(p); JSON.parse(File.read(File.join(B,p))); end
def valid(path,sha); File.file?(path) && Digest::SHA256.file(path).hexdigest==sha; end
content=read('content/events.json'); reg=read('content/registry.json'); c=read('chronicle/variants.ko.json'); cat=read('chronicle/CONTEXT_DRAFTS.catalog.json'); age=read('records/age-context-copy-proposal/ADDITIONS.json')
top=read('records/top10-evidence-plan/EVIDENCE_FILES.json'); fp=read('records/firstplay-current/TRACKING.json')
checks={events:content.size,uniqueEventIds:content.map{|e|e['id']}.uniq.size,choices:content.sum{|e|e['choices'].size},registryEntries:reg['entries'].size,registryRuntimeStatus:reg['status'],missingEventFields:content.map{|e| {id:e['id'],missing:%w[id years conditions sender title body choices recurrence illustration history].reject{|k|e.key?(k)}}}.reject{|r|r[:missing].empty?},missingChoiceFields:content.flat_map{|e|e['choices'].map{|ch|{id:e['id']+'.'+ch['id'],missing:%w[tradeoff costAxes ledger chronicle].reject{|k|ch.key?(k)}}}}.reject{|r|r[:missing].empty?},historyTypes:c['historyTemplates'].size,ledgerTypes:c['ledgerCategories'].size,canonicalVariants:(c['historyTemplates']+c['ledgerCategories']).sum{|e|e['variants'].size},separateContext:cat['entries'].size,ageGroups:age['additions'].size,ageVariants:age['additions'].sum{|e|e['variants'].size},astraAnswers:read('content/ASTRA_ANSWERS_R05.json')['answers'].size,top10EvidenceRows:top.size,top10MissingOrHashMismatch:top.reject{|r|[r['destination'],*r['existingR08Paths']].compact.any?{|p|valid(File.join(B,p),r['sha256'])}}.map{|r|r['source']},firstplayRows:fp['rows'].size,firstplayEvidenceRows:fp['handoff_recommendations'].size,firstplayMissingOrHashMismatch:fp['handoff_recommendations'].reject{|r|valid(r['destination'],r['sha256'])}.map{|r|r['destination']},rootManifestPresent:File.file?(File.join(B,'SHA256SUMS')),zipPresent:File.file?(B+'.zip'),oldAssetStrategyRelativeLinkPresent:File.file?(File.join(B,'records/storage-background-art-audit-r07/REPORT.md'))}
File.write(File.join(O,'CHECKS.json'),JSON.pretty_generate({at:Time.now.iso8601,method:'Light Ruby JSON, direct counts and SHA; no engine/browser/remote. Field presence is not historical/semantic correctness.',checks:checks})+"\n")
paths=%w[REPORT.md ROUND_PLAN.md SYSTEM_MAP.md ASSET_STRATEGY.md HANDOFF_CURRENT.md records/ROUND_START.json records/status-midround/STATUS.md records/status-midround/findings.json records/top10-evidence-plan/REPORT.md records/top10-evidence-plan/EVIDENCE_FILES.json records/TOP10_EVIDENCE_PARENT_ADOPTION.json records/firstplay-current/TRACKING.md records/firstplay-current/TRACKING.json records/FIRSTPLAY_PARENT_ADOPTION.json records/assets-current/REPORT.md records/de-coverage-current/RESULT.json records/de-coverage-current/REVIEW.md records/long-run-inheritance/REPORT.md content/events.json content/registry.json content/ASTRA_ANSWERS_R05.json chronicle/variants.ko.json chronicle/CONTEXT_DRAFTS.catalog.json chronicle/BIOGRAPHY_CONTRACT.json records/age-context-copy-proposal/ADDITIONS.json records/fen-run-lifecycle/LIVE_PROGRESS_1049.txt FIRST_PLAY_STATUS_R08.md records/ASSET_REPORT_LINK_ADOPTION.json records/storage-background-art-audit-r07/REPORT.md]
pins=paths.map{|p|{path:p,bytes:File.size(File.join(B,p)),sha256:Digest::SHA256.file(File.join(B,p)).hexdigest}}
goal='/Users/rexxa/Library/Application Support/orca/codex-accounts/54be5844-95fd-4c46-925c-75327ccd186a/home/attachments/f24f76ab-2fb8-4c0e-9ff6-2a061b9ebe64/pasted-text-1.txt'
pins.unshift({path:goal,bytes:File.size(goal),sha256:Digest::SHA256.file(goal).hexdigest})
File.write(File.join(O,'INPUT_PINS.json'),JSON.pretty_generate({at:Time.now.iso8601,scope:'Read-time snapshot; parent-owned live files may change after this audit.',files:pins})+"\n")
puts JSON.pretty_generate(checks)
