const fs=require('fs'),path=require('path'),sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const {createCanvas}=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const root=path.resolve(__dirname,'..'),W=209,H=167;
const polys={c:[[145,380],[330,32],[725,204],[1140,415],[1264,493],[1280,537],[1150,419],[1015,732],[864,456],[607,586],[406,293],[196,432]],d:[[125,360],[300,22],[1147,410],[1271,515],[1246,539],[1155,421],[1016,720],[833,337],[606,573],[430,227],[196,410]],e:[[126,370],[306,24],[716,210],[1140,411],[1254,515],[1237,539],[1144,427],[1012,724],[870,436],[612,578],[420,223],[189,409]]};
const spec={c:{roof:'thatch',shape:'unequal intersecting double gables',wall:'warm ochre limewash, diagonal oak'},d:{roof:'flat_clay_tile',shape:'narrow twin gables, petite jetty',wall:'pale pink limewash, upright framing'},e:{roof:'stone_slab',shape:'broad left and lower offset right gable, side doorway',wall:'ivory limewash, diagonal braces'}};
async function raw(p){return sharp(p).ensureAlpha().resize(W,H,{fit:'fill'}).raw().toBuffer()}
async function png(b,p){await sharp(b,{raw:{width:W,height:H,channels:4}}).png().toFile(p)}
(async()=>{fs.mkdirSync(root+'/records/masks',{recursive:true});const assets=[];const source=await raw(root+'/references/house_pair_l3_horizontal-v2.png');const contact=await raw(root+'/records/masks/l3h-contact.png');
for(const v of ['c','d','e']){const native=root+'/native/l3h/',base=await raw(native+v+'-base.png');const roofCanvas=createCanvas(W,H),ctx=roofCanvas.getContext('2d');ctx.fillStyle='white';ctx.beginPath();polys[v].forEach(([x,y],i)=>{const q=[x/1392*W,y/1136*H];i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.closePath();ctx.fill();const rm=Buffer.from(ctx.getImageData(0,0,W,H).data);for(let i=0;i<rm.length;i+=4){const on=rm[i+3]>=128&&base[i+3]>=128;rm[i]=rm[i+1]=rm[i+2]=255;rm[i+3]=on?255:0;}await png(rm,root+'/records/masks/l3h-'+v+'-roof.png');
for(const state of ['base','weathered','fresh','snow','boarded']){const id='house_pair_l3_horizontal_'+v+(state==='base'?'':'_'+state)+'-v1',file='assets/'+id+'.png',data=state==='base'?Buffer.from(base):await raw(native+v+'-'+state+'.png');let snowPixels=0,roofPixels=0;const sm=Buffer.alloc(W*H*4);for(let i=0;i<data.length;i+=4){if(state==='snow'){const min=Math.min(data[i],data[i+1],data[i+2]),max=Math.max(data[i],data[i+1],data[i+2]);if(min<150||max-min>48)data[i+3]=0;if(rm[i+3]){roofPixels++;if(data[i+3]>=128){snowPixels++;sm[i]=sm[i+1]=sm[i+2]=sm[i+3]=255;}}}else if(state==='fresh'||state==='weathered'){let d=Math.max(Math.abs(data[i]-base[i]),Math.abs(data[i+1]-base[i+1]),Math.abs(data[i+2]-base[i+2]));data[i+3]=Math.round(data[i+3]*Math.max(0,Math.min(1,(d-14)/30)));}if(state!=='base'){data[i+3]=Math.min(data[i+3],base[i+3]);if(contact[i+3])data[i+3]=0;}else if(contact[i+3])for(let c=0;c<4;c++)data[i+c]=source[i+c];if(!data[i+3])data[i]=data[i+1]=data[i+2]=0;}await png(data,root+'/'+file);const row={id,file,level:3,direction:'horizontal',variant:v,state,width:W,height:H,...spec[v],pivotcontract:'records/source-contract.json l3h; fixed full canvas, source footplate RGBA restored, no recenter',reference:state==='base'?'references/house_pair_l3_horizontal-v2.png':'native/l3h/'+v+'-base.png',ref:state==='base'?'references/house_pair_l3_horizontal-v2.png':'native/l3h/'+v+'-base.png',nativeOutput:'native/l3h/'+v+'-'+state+'.png',prompt:fs.readFileSync(native+v+'-'+state+'-prompt.txt','utf8'),model:null,seed:null,transforms:'Whole canvas resize 209x167. Footplate source restored for base; overlays alpha clipped to base and zeroed at contact. Fresh/weathered changed-pixel extraction RGB maxdiff ramp14–44. Snow white-pigment extraction minRGB150 chroma<=48, roof denominator independently annotated on base.'};if(state==='snow'){row.roofMask='records/masks/l3h-'+v+'-roof.png';row.snowMask='records/masks/l3h-'+v+'-snow.png';row.roofPixels=roofPixels;row.snowPixels=snowPixels;row.coveragePercent=100*snowPixels/roofPixels;await png(sm,root+'/'+row.snowMask);console.log(v,row.coveragePercent);}assets.push(row);}
}fs.writeFileSync(root+'/records/l3h.json',JSON.stringify({assets,roofPolygons:polys,roofCoordinateBasis:[1392,1136],qa:'Visually viewed bases and states; roof masks annotated from base before snow extraction; coverage measured alpha>=128.'},null,2));})();
