const fs=require('fs'),path=require('path'),sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const{createCanvas,loadImage}=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const R=path.resolve(__dirname,'..'),contracts=JSON.parse(fs.readFileSync(R+'/records/source-contract.json')).assets;
function board(w,h){const c=createCanvas(w,h),g=c.getContext('2d');g.fillStyle='#697261';g.fillRect(0,0,w,h);return[c,g]}
function txt(g,s,x,y,size=18){g.fillStyle='#fff5df';g.font=`${size}px sans-serif`;g.fillText(s,x,y)}
async function saveJpeg(c,p){await sharp(c.toBuffer('image/png')).jpeg({quality:88,mozjpeg:true}).toFile(p)}
(async()=>{
const layout=JSON.parse(fs.readFileSync(R+'/records/city-layout.json')),scenes=[];
for(const s of layout.scenes){const[c,g]=board(s.width,s.height),original=await loadImage(R+'/'+s.source),clean=await loadImage(await sharp(R+'/'+s.clean).resize(s.width,s.height,{fit:'fill'}).png().toBuffer());g.drawImage(original,0,0);const mask=createCanvas(s.width,s.height),mg=mask.getContext('2d');mg.fillStyle='white';for(const site of s.sites){mg.beginPath();site.polygon.forEach(([x,y],i)=>i?mg.lineTo(x,y):mg.moveTo(x,y));mg.closePath();mg.fill();}const raw=g.getImageData(0,0,s.width,s.height),cc=createCanvas(s.width,s.height),cg=cc.getContext('2d');cg.drawImage(clean,0,0);const cr=cg.getImageData(0,0,s.width,s.height).data,m=mg.getImageData(0,0,s.width,s.height).data;for(let i=0;i<s.width*s.height;i++)if(m[i*4+3])for(let k=0;k<3;k++)raw.data[i*4+k]=Math.round(raw.data[i*4+k]*(1-m[i*4+3]/255)+cr[i*4+k]*m[i*4+3]/255);g.putImageData(raw,0,0);
for(const site of s.sites){const ct=contracts.find(c=>c.family===site.family),crop=ct.normalized_crop,im=await loadImage(`${R}/assets/house_pair_l${ct.level}_${ct.direction}_${site.variant}-v1.png`),scale=site.width/crop.width,dx=site.pivot[0]-site.width/2,dy=site.pivot[1]-crop.height*scale;g.drawImage(im,crop.x,crop.y,crop.width,crop.height,dx,dy,site.width,crop.height*scale);site.drawRect={x:dx,y:dy,width:site.width,height:crop.height*scale};}
await sharp(mask.toBuffer('image/png')).png().toFile(R+'/records/masks/city-'+s.width+'-replacement.png');scenes.push({s,original,c});}
let[c,g]=board(2440,1510);txt(g,'Wave 30 · 합필 집 후보 / 첨부 화면의 주거지에 놓은 오프라인 합성',25,35,27);txt(g,'실제 건물 ID·합필 여부는 저장 상태가 없어 미확인. 붉은 지붕·흰 받침 곡창은 교체하지 않음.',25,66,21);
let y=108;for(const{ s,original,c:town}of scenes){const x1=20+(1200-s.width)/2,x2=1240+(1200-s.width)/2;txt(g,s.label+' · 첨부 원본',x1,y-12,20);txt(g,s.label+' · 초가 / 기와 / 돌판 후보 배치',x2,y-12,20);g.drawImage(original,x1,y);g.drawImage(town,x2,y);y+=s.height+48;}
txt(g,'판정: 배치한 주택의 지붕 재료·벽색 반복은 줄었음. 가장 큰 곡창의 반복은 그대로 남음(별도 대상).',25,1490,21);await saveJpeg(c,R+'/proofs/01-city-repetition.jpg');
fs.writeFileSync(R+'/records/city-composite-qa.json',JSON.stringify({kind:'offline screenshot reconstruction, NOT installed or runtime capture',scenes:layout.scenes,unverified:'Original building IDs, actual compound lot locations and zoom factors; attachment labels retained.',preserved:'Original pixels outside tight three-site house masks and new sprite silhouettes. Granaries unchanged.'},null,2));
[c,g]=board(1230,3540);txt(g,'Wave 30 · 기본 + 상태 오버레이 / 원본과 같은 캔버스·피벗',20,31,23);['기본','낡음','새것','눈','빈집 판자'].forEach((t,i)=>txt(g,t,140+i*216,66,18));let row=0;
for(const ct of contracts)for(const v of ['c','d','e']){const y=88+row*190,stem=`house_pair_l${ct.level}_${ct.direction}_${v}`,base=await loadImage(R+'/assets/'+stem+'-v1.png');txt(g,ct.family+' '+v,12,y+94,17);const scale=Math.min(196/ct.width,171/ct.height);for(let col=0;col<5;col++){const x=118+col*216+(196-ct.width*scale)/2,dy=y+174-ct.height*scale;g.drawImage(base,x,dy,ct.width*scale,ct.height*scale);if(col){const state=['','weathered','fresh','snow','boarded'][col],over=await loadImage(R+'/assets/'+stem+'_'+state+'-v1.png');g.drawImage(over,x,dy,ct.width*scale,ct.height*scale);}}row++;}
await saveJpeg(c,R+'/proofs/02-variants-states.jpg');console.log('proofs2 written');
})().catch(e=>{console.error(e);process.exit(1)});
