const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('/Users/rexxa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const R=path.resolve(__dirname,'..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const raw=async p=>await sharp(p).ensureAlpha().raw().toBuffer({resolveWithObject:true});
(async()=>{const contracts=JSON.parse(fs.readFileSync(R+'/records/source-contract.json')).assets,assets=[],failures=[];
for(const c of contracts){const rec=JSON.parse(fs.readFileSync(R+'/records/'+c.family+'.json')),rows=Array.isArray(rec)?rec:(rec.assets||rec.rows),src=await raw(R+'/'+c.reference),contact=await raw(R+'/'+c.contact_mask);
if(rows.length!==15)throw Error(c.family+' rows !=15');
for(const r of rows){const filename=path.basename(r.file),file='assets/'+filename,p=R+'/'+file,m=await sharp(p).metadata(),a=await raw(p),variant=r.variant||filename.match(/_([cde])(?:_|-v1)/)[1],state=r.state||'base',stem=`house_pair_l${c.level}_${c.direction}_${variant}`,base=await raw(R+'/assets/'+stem+'-v1.png');let transparent=0,partial=0,visible=0,contactMismatch=0,outsideBase=0;
for(let i=0;i<c.width*c.height;i++){let alpha=a.data[i*4+3];transparent+=alpha===0;partial+=alpha>0&&alpha<255;visible+=alpha>0;if(contact.data[i*4+3]>0){if(state==='base')for(let k=0;k<4;k++)contactMismatch+=a.data[i*4+k]!==src.data[i*4+k];else contactMismatch+=alpha>0;}if(state!=='base'&&base.data[i*4+3]===0&&alpha>0)outsideBase++;}
if(m.width!==c.width||m.height!==c.height||m.channels!==4||!transparent||!visible||contactMismatch||outsideBase)failures.push({file,m,contactMismatch,outsideBase});
let coverage=null;if(state==='snow'){const roofMask=r.roofMask||r.coverage?.roof_mask,snowMask=r.snowMask||r.coverage?.snow_mask;if(!roofMask||!snowMask)throw Error('missing masks '+file);const roof=await raw(R+'/'+roofMask),snow=await raw(R+'/'+snowMask);let denominator=0,numerator=0,removedAfterMask=0;for(let i=0;i<c.width*c.height;i++)if(roof.data[i*4+3]>=128){denominator++;if(snow.data[i*4+3]>=128){if(a.data[i*4+3]>=128)numerator++;else removedAfterMask++;}}const percent=numerator/denominator*100;if(percent<60||percent>80)failures.push({file,percent});coverage={roofMask,snowMask,roofPixels:denominator,snowPixels:numerator,coveragePercent:percent,removedAfterMask,method:'Independent authored roof mask alpha>=128; saved classified snow mask alpha>=128 intersect final overlay alpha>=128. Family record holds color thresholds.'};}
assets.push({id:filename.replace('.png',''),file,status:'candidate',family:c.family,level:c.level,direction:c.direction,variant,state,width:c.width,height:c.height,roof:r.roof,shape:r.shape,wall:r.wall,pivot:c.pivot,crop:c.normalized_crop,reference:c.reference,provenance:'records/'+c.family+'.json',coverage,alpha:{transparent,partial,visible},contactMismatch,outsideBase,sha256:sha(fs.readFileSync(p))});}
}
const files=fs.readdirSync(R+'/assets').filter(x=>x.endsWith('.png'));if(files.length!==90||assets.length!==90||new Set(assets.map(x=>x.file)).size!==90)failures.push({counts:[files.length,assets.length]});
assets.sort((a,b)=>a.file.localeCompare(b.file));fs.writeFileSync(R+'/records/manifest.json',JSON.stringify({status:failures.length?'FAIL':'PASS',count:assets.length,failures,assets},null,2));console.log(JSON.stringify({assets:assets.length,snow:assets.filter(x=>x.coverage).map(x=>({id:x.id,percent:x.coverage.coveragePercent})),failures},null,2));if(failures.length)process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
